### ISSUE TITLE
Additional sentence to be added to the end of [PAINREL2], etc. questions

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#10]
For the medications section for the questions that say, “During the time(s) that you were taking _____, about how many days per week OR days per month did you take it?”  There was additional language added to the end of the question that should state, “Please choose whichever makes the most sense for you” 

[PAINREL2], [CHOLHTN2], [METFOR2A], [INSULIN2A], [ACIDSUP2]

**Comment by boyd-mj** [comment]
@cusackjm Per the comments above, the language is currently what's shown in the second example. Do you want us to update the markup to match what is in the questionnaire as shown in the first example? There are some comments between Alaina and Deanna in the document, but it looks like a resolution wasn't reached. Thanks.

**Comment by freedmanne** [comment]
hi, I reviewed the documents. I think the concern would be that participants might think they would have to fill out both days per week and days per month. So how about this, "Please fill out either days per week or days per month."

**Comment by boyd-mj** [comment]
@freedmanne thanks. Should we then take out the line that says "Or, if it is easier to remember..."? So it would look like this:

D2.	 [PAINREL2] During the time(s) that you were taking [MED FROM PAINREL1], about how many days per week OR per month did you take it? Please fill out either days per week or days per month.
|__|__| #Days PER Week
Or:
|__|__| #Days PER Month

**Comment by freedmanne** [comment]
sure!

**Comment by boyd-mj** [comment]
@freedmanne these changes have been made in the mark-up. The questions now look like this:

![image](https://user-images.githubusercontent.com/80920570/147272357-eab25058-5c69-44bf-915f-517b4d5a8997.png)

@cusackjm can you please update the questionnaire on Box to reflect this when you are back in the office? Thanks.

**Comment by cusackjm** [comment]
Changes have been made to Box documents
