### ISSUE TITLE
Module 1 in stage- QAQC errors

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [episphere/questionnaire#102]
TEST 1 (taratdrp@gmail.com, 2252696519, 5/6 stage testing)
-QAQC crossvalid1 less than with explanation: (may be an error with QAQC code) claims that D_403258164(Ever worked for pay) was answered as 978204320 (Grade school grades 1-8). D_403258164 was never asked of the participant as they are currently working, and D_367803647 (Education level) was the question answered with 978204320 

QAQC problem in M1_valid_with_explination
o One Total Family Income D_759004335==530094502 (not an option) this same issue with the same answer selected showed in Stage testing as well

**Comment by zly2021** [comment]
Variables added

**Comment by KELSEYDOWLING7** [comment]
@zly2021  Thank you! Only a few more

**Comment by KELSEYDOWLING7** [comment]
@FrogGirl1123 do we want to look at this QAQC code while we're updating the others? I think this is just an error in the coding that allowed this to slip through
