### ISSUE TITLE
[PREG8] Breastfeeding informational text - available for some and not others

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#104]
I entered that I have had 3 pregnancies.

Pregnancy loop 1
[PREG5] = 0=Live birth: single infant
[PREG6] = skipped (correct logic)
[PREG7]  = 1=Vaginal
[PREG8] = 'breastfeeding' in blue with the informational text modal

![Screen Shot 2022-05-13 at 12 08 56 PM](https://user-images.githubusercontent.com/83971268/168327115-de1f6490-0861-4b09-ab46-6e2b867959c1.png)

Pregnancy loop 2 - 
[PREG5] = 3=Live birth and stillbirth (loss of one or more of multiples)
[PREG6] = 0=Two (twins)
[PREG7] 0=Cesarean
[PREG8] = 'breastfeeding' was plain black text

![Screen Shot 2022-05-13 at 12 09 17 PM](https://user-images.githubusercontent.com/83971268/168327061-a660472f-2731-46fb-a84f-040b274d3aff.png)

Pregnancy loop 3 - 
[PREG5] = 1=Live birth: twins, triplets, or higher multiples
[PREG6] = 1=Three (triplets)
[PREG7] = 0=Cesarean
[PREG8] = 'breastfeeding' was blue with the informational text modal

![Screen Shot 2022-05-13 at 12 08 56 PM](https://user-images.githubusercontent.com/83971268/168327115-de1f6490-0861-4b09-ab46-6e2b867959c1.png)

**Comment by huip-ims** [comment]
@cusackjm @woodruffr @joshid-ims Hi Julie, I've updated PREG8, and it's currently going through internal testing. Could you please confirm if "breastfeed" in PREG9 should also have information text? If so, we'll update this as well.

**Comment by cusackjm** [comment]
@huip-ims yes

![image](https://user-images.githubusercontent.com/85582895/169300409-4630efbc-eacc-4968-a3e8-54d0bbb9b062.png)

**Comment by cusackjm** [comment]
@huip-ims what is the status on this?

**Comment by huip-ims** [comment]
@cusackjm @boyd-mj Hi Julie - this has passed IMS internal testing. Jen will be including this fix in the next delivery.

**Comment by cusackjm** [comment]
@boyd-mj this wasnt in the deliverables sheet, but just wanted to check in to see if it was in the latest delivery because of the above comment

**Comment by boyd-mj** [comment]
@cusackjm it was, I just added it to the deliverables log

**Comment by cusackjm** [comment]
fixed in testing 6/30
