### ISSUE TITLE
"RESET ANSWER" & "NEXT" buttons overlap when screen is made smaller

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#105]
![image](https://user-images.githubusercontent.com/85582895/168826962-30f98c0e-a310-4b91-8a6f-848aba25db2c.png)

only happens when screen is a certain size, once made small enough the buttons eventually stack on top of each other

(happens in all modules)

**Comment by cusackjm** [comment]
confirmed fix in 5/17/22 testing

**Comment by cusackjm** [comment]
Seeing issue in biospecimen testing on 5/20 
![image](https://user-images.githubusercontent.com/85582895/169570817-0ee45589-5153-4ce6-9ea8-f9d6833ba406.png)

**Comment by cunnaneaq** [comment]
Mine is working fine - using regular Chrome on a Mac

![Screen Shot 2022-05-20 at 12 27 44 PM](https://user-images.githubusercontent.com/83971268/169571673-8eac41e1-26b8-40bc-9f9b-ae9b2e450855.png)

![Screen Shot 2022-05-20 at 12 27 55 PM](https://user-images.githubusercontent.com/83971268/169571709-1eaaaadc-6da1-4e88-8129-22b5becc0186.png)

**Comment by cusackjm** [comment]
@naiyume This is only happening to me in the Grid questions

**Comment by cusackjm** [comment]
appears fixed in COV24 grid
