### ISSUE TITLE
Open-ended response Text is not saved when going back in PWA

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#106]
The response selection is saved (see picture of blue highlighted response), but the text box entry is not saved. I noticed this when going back into a partially complete module 2, but am not sure if this happens in other modules.

![image](https://user-images.githubusercontent.com/85582895/168828115-91e5416b-56c4-4e8f-8719-9c3bd0b5dcfe.png)

**Comment by naiyume** [comment]
@cusackjm This should be resolved now. Please try it out when you have time

**Comment by cusackjm** [comment]
confirmed fix in 5/17 testing
