### ISSUE TITLE
The date widget is allowing invalid dates.

### ISSUE THREAD

**Issue by naiyume** [episphere/questionnaire#107]
The date widget is allowing invalid dates. 

![image](https://user-images.githubusercontent.com/64986739/168877255-f0dadcce-ca2c-4d04-9899-b723e1c19e42.png)

_Originally posted by @joshid-ims in https://github.com/episphere/questionnaire/issues/85#issuecomment-1129148035_

**Comment by naiyume** [comment]
@joshid-ims

**Comment by woodruffr** [comment]
@danielruss Our tester Gwen got that error testing the Menstrual Cycle Survey using a Chrome browser.

**Comment by naiyume** [comment]
@woodruffr 
```
[SRVBLU_MENS2_V1R0!] Please provide the first day that your next menstrual period started. This information helps researchers figure out where your body was in the menstrual cycle on the day you donated samples. If you do not remember the exact day, please make your best guess: 
 
|date|
 
[END,end] Thank you. We will check back in with you soon. 
```
This is the markup. There is no indication of min or max. Are you expecting that the max that you can set is current day?

**Comment by woodruffr** [comment]
I believe that is what our tester was expecting. With these types of questions we were not expecting future dates.

**Comment by naiyume** [comment]
@danielruss is this an option that we have in the markup? If not, I think it might be worth our time to add this in. Current date maxes as an option sounds pretty standard.

**Comment by danielruss** [comment]
add you want to add the equivalent of  "min=5-19-2022 max=6-19-2022". This might be addressable as today and today+30.  Let me test...

**Comment by danielruss** [comment]
ok, there is no today variable.  creating one #today

**Comment by danielruss** [comment]
new issue https://github.com/episphere/quest/issues/405

**Comment by danielruss** [comment]
Try this:
```
[SRVBLU_MENS2_V1R0!] Please provide the first day that your next menstrual period started. This information helps researchers figure out where your body was in the menstrual cycle on the day you donated samples. If you do not remember the exact day, please make your best guess: 
 
|date|min=#today-45 max=today+45|
 
[END,end] Thank you. We will check back in with you soon. 
```

You can adjust the number of days.  If you don't need the future, use #today or #today-1 if you want yesterday.

**Comment by danielruss** [comment]
@naiyume 

> @danielruss is this an option that we have in the markup? If not, I think it might be worth our time to add this in. Current date maxes as an option sounds pretty standard. Another solution (could be a quick fix) would be to add current date in as a parameter from the PWA and set that as the max.

I think this needs to be a quest feature.  Of course, you have the ability to whatever you want in the PWA.  I would never see it.

**Comment by boyd-mj** [comment]
@joshid-ims or @huip-ims please test Daniel's solution

**Comment by joshid-ims** [comment]
What should be the limits for date? Do we need to update the Word document for this? 

For now, we are testing with |date|min=#today-30 max=#today|

**Comment by joshid-ims** [comment]
Tagged Julie. Could not tag Neal.

**Comment by cusackjm** [comment]
Shoulf be 60 (instead of 30) because this question is for participants who have had a menstrual period in the last 60 days
|date|min=#today-**60** max=#today|

**Comment by boyd-mj** [comment]
Hi Julie, this is the only issue for this survey so we can redeliver anytime.

**Comment by cusackjm** [comment]
@boyd-mj please wait and deliver them together
