### ISSUE TITLE
[COVSUMMARY] not all symptoms selected are present

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#109]
[COV8]

![Screen Shot 2022-05-20 at 11 57 31 AM](https://user-images.githubusercontent.com/83971268/169567006-c2bbef79-1936-4ba5-8cf8-5b808721d254.png)

[COVSUMMARY]

![Screen Shot 2022-05-20 at 11 59 32 AM](https://user-images.githubusercontent.com/83971268/169567062-e0983383-43f5-4c8d-a112-3e2155aa71e9.png)

160627865 "Weakness or fatigue (tiredness)" missing from the symptom list

Not sure if this is a mark-up, Quest, or PWA issue.

**Comment by cunnaneaq** [comment]
To provide more information, in another scenario I selected 8= Sore throat, 9 = Cough, and 15= Vomiting (throwing up) at [COV8] and none of my selections appeared in [COVSUMMARY]
![Screen Shot 2022-05-20 at 2 05 18 PM](https://user-images.githubusercontent.com/83971268/169587259-fc5617ae-0df4-4930-888c-1473bff1a48d.png)

**Comment by huip-ims** [comment]
@cusackjm @cunnaneaq @joshid-ims @boyd-mj Hi Aileen, IMS had initially coded the markup to show all selected symptoms in COVSUMMARY. However, from the display changes addressed in issue #100, COVSUMMARY was recently updated to only show selected symptoms COV8A (Fever), COV8B (Body chills), and COV8C (Body or muscle aches). If you would like to display additional selected symptoms in the summary, please update the Word doc so we can make the necessary changes to the markup.


![image](https://user-images.githubusercontent.com/82978291/170131852-eeffc321-3726-4b35-9c28-38d734efd76d.png)

**Comment by cusackjm** [comment]
@huip-ims the box questionnaire document has been updated so that the symptoms are responses from COV8

**Comment by boyd-mj** [comment]
This issue has been fixed and will be included in the next delivery

**Comment by cunnaneaq** [comment]
Agree with Kelsey - 1. seeing all of the symptoms selected in COV8 in COVSUMMARY and 2. not seeing questions in the summary that weren't asked (i.e. hospitalization)
![Screen Shot 2022-06-08 at 2 13 25 PM](https://user-images.githubusercontent.com/83971268/172687682-02bf8297-0c14-4d4b-8a91-75c2225eeb5d.png)

![Screen Shot 2022-06-08 at 2 08 01 PM](https://user-images.githubusercontent.com/83971268/172686812-d0c03516-70fd-422f-b860-eede33079729.png)
