### ISSUE TITLE
[COV26] word after text box is "times" should be "shot(s)"

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#110]
![Screen Shot 2022-05-20 at 12 20 21 PM](https://user-images.githubusercontent.com/83971268/169570565-d0f80e52-c7e8-4a22-9470-3cb31884dc2b.png)

**Comment by boyd-mj** [comment]
This issue has been fixed and will be included in the next delivery

**Comment by cunnaneaq** [comment]
fixed in 6/8 stage testing

![Screen Shot 2022-06-08 at 2 40 11 PM](https://user-images.githubusercontent.com/83971268/172692258-0095066b-3e75-4005-bd2e-2d219f70976b.png)
