### ISSUE TITLE
Incorrect skip logic following COVSUMMARY

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#111]
I entered the following info: 

COV1= 1
COV2= 1
COV3= 6/2022
COV4= 0
COV5= 0
COV6=0
COVSUMMARY (displayed correct information) --> COV19

**correctly did not see COV19, but instead of going to COV23, I went to COV27**
![image](https://user-images.githubusercontent.com/85582895/169583188-04f111a1-de3c-4135-8f44-96ccf075d4e3.png)

**Should have seen COV23 based on display logic and responses I entered at COV5 and COV6**
![image](https://user-images.githubusercontent.com/85582895/169583348-75fa83b1-39dd-4fe7-bb4f-87eeaaa472b6.png)

**Comment by joshid-ims** [comment]
Issue https://github.com/episphere/quest/issues/407 is created for this.
