### ISSUE TITLE
Incorrect skip logic following COV1

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#112]
Entered the following responses:
COV1= 0 --> COV23

**Should have gone to COV23, but instead went to COV27**
![image](https://user-images.githubusercontent.com/85582895/169593845-f57f800f-c5c8-4805-a1bd-07fbbfb41851.png)

**Comment by cusackjm** [comment]
same thing happens when COV1= non-response

**Comment by joshid-ims** [comment]
Issue https://github.com/episphere/quest/issues/407 is created for this.

**Comment by huip-ims** [comment]
@cusackjm @joshid-ims @boyd-mj Hi Julie, Should COV23 be asked if COV1 = non-response, and if so, could you please update the Word doc?  Currently, it has to display if COV1 = 1, 77.

**Comment by cusackjm** [comment]
@huip-ims yes it should. I am updating the word documents now

**Comment by cunnaneaq** [comment]
Fixed for COV1= 0 and NR; brought directly to COV23 (scenarios 6 & NR in testing spreadsheet)
