### ISSUE TITLE
[MWUSE] response "Flouride" should be "Fluoride"

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#114]
In [MWUSE], response 3 should read "Fluoride mouthwash (such as ACT)"
Spelling in question for [MWFLOURIDE] is correct.

![Screen Shot 2022-05-20 at 3 08 06 PM](https://user-images.githubusercontent.com/83971268/169595713-21c0b09d-df77-4df6-a029-793a78f05546.png)

**Comment by woodruffr** [comment]
@cusackjm The Questionnaire for this has the spelling as Flouride. If you want the American "Floride" please update the Questionnaire and put a comment here. Thanks

**Comment by cusackjm** [comment]
@woodruffr Spelling is changed to "fluoride" in the qx documents. 

Should I also change the spelling of the variable name?

**Comment by KELSEYDOWLING7** [comment]
Spelling is correct on 6/8 testing

**Comment by cusackjm** [comment]
madhuri also confirmed fix on 6/8
