### ISSUE TITLE
ECIGLIFE/CIGARLIFE/CHEWLIFE/HOOKAHLIFE/PIPELIFE/SECSMLF/SMMARLIFE/ALCLIFE: Incorrect age ranges displayed

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [episphere/questionnaire#115]
Module 3 DEV testing   (5/23 testing, connect ID 4164883179)
(For reference I put that I started smoking cigarettes on a regular basis at 21- seems to have caused all other grids to start at 21 whether the smoking started for that product then or not)

ECIGLIFE: For e-cigarettes I marked age first used at 40, and on a regular basis at age 45. I'm seeing: 
"On days that you used e-cigarettes or other vaping devices for nicotine or tobacco when you were age [X] to age [Y ], what is the total amount of time you used them per day? " for ages 21-24, 25-29, 30-39

CIGARLIFE: Marked first used at age 35, regular basis at 36 and seeing:
"On days that you smoked when you were age [X] to age [Y ], about how many cigars, cigarillos, or little filtered cigars did you smoke per day?" for ages 21-24 and 25-29

CHEWLIFE: Marked age at first use 45, regular basis at 45. Seeing:
"On days that you used chewing tobacco, snus, snuff, or dip when you were age [X] to age [Y ], what is the total amount of time you used them per day? "  for ages 21-24, 25-29, 30-39

HOOKAHLIFE:  Marked age at first use 50, regular basis at 50. Seeing:
"On days that you smoked a hookah or water pipe when you were age [X] to age [Y ], what is the total amount of time you used them per day?  for ages 21-24, 25-29, 30-39, 40-49. Age range of 50-59 was also not displayed 

PIPELIFE: Marked age at first use 50, regular basis at 50. Seeing:
"On days that you smoked when you were age  [X] to age [Y ], about how many pipe fills of tobacco did you smoke per day?" for ages 21-24, 25-29, 30-39, 40-49. Age range of 50-59 was also not displayed 

For test scenario 2 Connect ID 1246342159 
(For reference Cigarettes were 10 or less- seems to have caused no other grids to be produced)
ECIGLIFE:  E-cigarettes were 100+ a day starting regularly at age 35, current age 52: NO ECIGLIFE SECTION was displayed
SECSMLF: Age range 50-52 not displayed 
SMMARLIFE: Entire section missing, 100+ times smoked, every day

**Comment by naiyume** [comment]
This might require some data dictionary changes.
Currently, the concept id 408696162 is being harmonized for every question that asks how old people are when they began using some substance.
This is causing issues because the questions are text box answers (which need to be unique for the sake of quest iirc)

**Comment by cunnaneaq** [comment]
Unharmonized ages in LIFE questions is fixed.  I had the same issue as Kelsey in her comment about AGECOR/AGE and entered a new issue to track it https://github.com/episphere/questionnaire/issues/128
