### ISSUE TITLE
[EYECOLORINTRO] click "next" twice to move on

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#117]
To move from [EYECOLORINTRO] to [EYECOLOR] I had to click the "Next" button twice.  Similarly, if clicking back, I had to click the "back" button twice.  This happened consistently in testing two different scenarios.  Once I clicked "Next" twice, I was able to move on to the next question without an issue.

Not sure if this is a mark up, quest, or PWA issue - assigned IMS and NCI.  I imagine this is low priority.

**Comment by cusackjm** [comment]
fixed in testing on 7/25
