### ISSUE TITLE
Able to enter an age of doing something that is less than the age the person started doing something

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#120]
Min for PIPE9D (age stopped smoking everyday) should be PIPE2 (age first smoked a pipe) response.

Was able to enter PIPED9D= 17, when I reported PIPE2= 33

**This is a low priority issue.**

**Comment by joshid-ims** [comment]
None of the stop using product age questions are based on that min. They all have min =0. Should all be changed?

**Comment by boyd-mj** [comment]
Per discussion on call on 6/15, minimum age should be changed for all products to when they started using the product

**Comment by cusackjm** [comment]
@joshid-ims what is the status on this?

**Comment by joshid-ims** [comment]
Actually, our tester asked about why we are using CIG3 age as I have coded as min=valueOrDefault("CIG3_AGE","CIG2",0), like use age in 3 or in 2 or 0 (in that order). Is this ok or just age in 2 should be used?

**Comment by cusackjm** [comment]
Please leave as is @joshid-ims

**Comment by cusackjm** [comment]
@joshid-ims what is the status on this

**Comment by cusackjm** [comment]
tested 7/25: entered the following
CIG2: 35
CIG3: was able to enter 37 without an error message

**Comment by cusackjm** [comment]
fixed in testing on 7/25
