### ISSUE TITLE
did not see CHILDADD3

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#125]
I left the STREET NUMBER AND STREET NAME BLANK IN CHILDADD1 BUT COMPLETED THE CITY and STATE FIELDS IN CHILDADD2 and was not shown CHILDADD3

Is this a markup issue or quest/data pulling issue? @naiyume @boyd-mj

**Comment by boyd-mj** [comment]
This has been fixed and will be included in the next delivery

**Comment by cusackjm** [comment]
tested and fixed on 6/3/22
