### ISSUE TITLE
Mod3 DEV testing-  Test scenario not saving in Connect

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [episphere/questionnaire#126]
Note: All participants info from test scenarios have been saving in Connect.participants for all environments. Query for Connect.participants ran smoothly as scheduled this morning and during all Module 3 DEV testing

TEST SCENARIO 1 (taratdrp@gmail.com / Connect_ID= 2314222519):
-None of the responses for Test Scenario 1 saved to the Connect.participants table
-Some answers are in recruitment.participants but many are incorrect

**Comment by naiyume** [comment]
Checked ALCLIFE2C and ALCLIFE2E for scenario 2 and both were found in firestore under D_633553324 along with D_164707243 and D_818310825. ELMAR10 also seems to have 437269318 stored in firestore.

**Comment by KELSEYDOWLING7** [comment]
With this problem not presenting in 6/2 stage testing and recent pushes, will be closing this issue for now
