### ISSUE TITLE
AGECOR/AGE from Mod 1 not correct in LIFE questions in Mod 3

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#128]
Stage re-test of mod 3 scenario 3 on 6/3, Connect ID: 9857825959

Original age from user profile = 47
Mod 1
AGECOR = NO
AGE = 48

In the LIFE grids for mod 3, the max age I am seeing is 47.  

Not sure if a PWA, Quest, or mark up issue

**Comment by danielruss** [comment]
@cunnaneaq, when I run this setting "AGE" to 48 and "age" to 47,  I get the expect result.

![image](https://user-images.githubusercontent.com/3767675/172225573-5c43cb6d-97c0-474a-9ab2-df0cb15afdda.png)

This is exact what is expected from the code in module 2.  `Age 40 to age {$e:min(49,valueOrDefault("AGE","age",100)) };`.  The `{$e:...}` is replaced by the minimum of 49 OR the value of "AGE".  If "AGE" is not defined, it uses the value of "age".  Finally if neither "AGE" or "age" is defined, it defaults to 100.  Of course 100 is greater than 49, so you never see that.

Quest is working as expected.

**Comment by cunnaneaq** [comment]
Thank you @danielruss.  Consulted with the team and this is a low priority issue

**Comment by huip-ims** [comment]
@danielruss Daniel- Since the code and Quest are working as expected, is this a PWA issue then?

**Comment by danielruss** [comment]
Not sure @huip-ims .  I would think this would be the same in the PWA as in quest.  @naiyume If the PWA is not getting the value of AGE from firestore, it would fall back to age.  Can you check that it is passed into the module.

**Comment by boyd-mj** [comment]
@naiyume believes a change made 9 days ago addressed this. Per @FrogGirl1123 please re-test
