### ISSUE TITLE
Not seeing school commuting section (CURSCH*) & STUDENT=1

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#129]
**this is a high priority issue**

selected STUDENT=1 in mod 1 and was not displayed the school commuting section in module 4

@woodruffr @naiyume is this a markup, PWA, or quest issue?

**Comment by FrogGirl1123** [comment]
@naiyume  Hi Brian, could you please check this issue and confirm it's a render issue and if so the timeline for fixing?

**Comment by naiyume** [comment]
This is fixed in dev and @cunnaneaq is testing it in stage.
