### ISSUE TITLE
incorrect skip logic for CURWORKT11-13

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#133]
CURWORK10F: 1 - "16 to 30 minutes"
CURWORK10G: 2 - "31-59 minutes"

Should see CURWORKT11 - CURWORKT13, but am skipping to CURWORKT14

I think there's an issue with the instructions in the specs doc: 
![Screen Shot 2022-06-10 at 10 32 25 AM](https://user-images.githubusercontent.com/83971268/173088312-14136b38-c294-482b-9742-b8f138918050.png)

should say, "ASK CURWORKT11 - CURWORKT13 IF ANY CURWORK**T10** = 1, 2, 3, OR 4"

**Comment by boyd-mj** [comment]
@cusackjm could you confirm/update the questionnaire document if a change is needed?

@huip-ims please keep an eye on this issue, thanks.

**Comment by cusackjm** [comment]
@huip-ims @boyd-mj questionnaire document is updated

**Comment by boyd-mj** [comment]
This issue has been fixed and will be included in the next delivery

**Comment by cusackjm** [comment]
fixed during testing 6/13
