### ISSUE TITLE
Concept IDs displaying in question text

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#134]
If I log out and log back into the PWA and then click back, the concept IDs display in the question text instead of the address entered.  If I click back to the question where the address is entered, my responses are saved and then it works correctly going forward.

This is happening for all questions that are meant to display an address (e.g., CURWORK1 and CHILDADD)

See below screenshots:

![Screen Shot 2022-06-10 at 11 00 03 AM](https://user-images.githubusercontent.com/83971268/173093810-66a527cc-b1fe-49e4-a9c0-65498e8afeeb.png)
![Screen Shot 2022-06-10 at 11 00 26 AM](https://user-images.githubusercontent.com/83971268/173093887-e6f4a43f-5015-4c32-bace-6d62b59db2a1.png)

**Comment by danielruss** [comment]
@naiyume I think the PWA is not getting the values from firestore.  I'll try to run this in quest.

**Comment by cunnaneaq** [comment]
Checked this for HOMEADD, SEASADD, and CHILDADD and did not see concept IDs when click back for any of them.  Spoke with @naiyume about my comment above, this is the intended function of the PWA/Quest
