### ISSUE TITLE
Responded to MENS1&2 - not getting correct end message

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#137]
MENS1 - YES
MENS2 - 06/07/2022

Message should say "Thank you for completing the survey." and should be able to submit

Instead, the screen says "Thank you.  We will check back in with you soon."

![Screen Shot 2022-06-17 at 10 38 10 AM](https://user-images.githubusercontent.com/83971268/174320035-8730835a-5ee7-4db5-b49a-72e0eec501f4.png)

On the dashboard, the survey is still available and in the "to do" list.

Potentially related outstanding issue:
Code and database storage misalignment of the type of variable.  Code is expecting an integer, but the CID is in string form so not recognizing as eligible because of the D_ that prefaces the variable on the backend.

**Comment by cunnaneaq** [comment]
@anthonypetersen fixed in dev - able to submit the survey when MENS1 = YES

**Comment by anthonypetersen** [comment]
I think this still needs to go to IMS

**Comment by cunnaneaq** [comment]
I created a new issue to keep prevent confusion - https://github.com/episphere/questionnaire/issues/144
