### ISSUE TITLE
MENSINTRO - not pulling date from MENSTART in Biospecimen Survey

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#138]
2nd paragraph of MENSINTRO in specs document says:
![Screen Shot 2022-06-17 at 10 45 52 AM](https://user-images.githubusercontent.com/83971268/174321351-3e18da1f-b596-4994-92ff-2c57a9834035.png)

In the biospecimen survey, I entered "5/20/2022" at MENSTART, and MENSINTRO looked like this (see green box):

![Screen Shot 2022-06-17 at 10 47 11 AM](https://user-images.githubusercontent.com/83971268/174321800-4dc6e341-37e1-4076-ab35-2add56da3b0c.png)

Not sure if this is a markup, quest, or PWA issue

**Comment by boyd-mj** [comment]
@joshid-ims @huip-ims

**Comment by naiyume** [comment]
This is most likely a PWA issue

**Comment by cusackjm** [comment]
fixed in testing on 7/15
