### ISSUE TITLE
Max # value is incorrect, looks like 1 is added to the value max should be

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#143]
![image](https://user-images.githubusercontent.com/85582895/175132784-00690dec-0133-4318-b6bf-d5d485447d2f.png)
Participant is 45, but the error message is 46 and console looks like 1 is being added to it

**Comment by naiyume** [comment]
@boyd-mj 
Please assign to IMS. This ended up being a markup issue.
<img width="364" alt="image" src="https://user-images.githubusercontent.com/27040828/175141285-6f3517f9-e3c5-4960-a8d5-b79a334d25b8.png">
Unsure what the reason for this +1 is for, but this is causing the max age to be one larger than the age they give you. Picture above is just an example of this showing up from another question.

**Comment by boyd-mj** [comment]
@cusackjm this has come up before. My understanding is that this was done to allow for the participant to have had a birthday in between providing an age and completing later modules. @FrogGirl1123 may be able to confirm?

**Comment by cusackjm** [comment]
@FrogGirl1123 can you confirm this?
