### ISSUE TITLE
End message when MENS1=YES is incorrect

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#144]
MENS1 = YES
MES2 = 06/07/2022

![Screen Shot 2022-06-23 at 4 21 23 PM](https://user-images.githubusercontent.com/83971268/175393796-197797f7-e40c-450f-b2fc-b1c62ed48536.png)

When MENS1 = YES, message should say, "Thank you for completing the survey."

**Comment by boyd-mj** [comment]
This has been fixed and will be included in the next delivery

**Comment by cusackjm** [comment]
confirmed fixed in dev testing on 8/8
