### ISSUE TITLE
TOBACCO and ECIG Brand Language

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#145]
This small language change for TOBACCO and ECIG1 adds “some if the most popular brands” so that the trademark symbols are not required. This change does not involve any data dictionary changes.

From: Cusack, Julie (NIH/NCI) [C] <julie.cusack@nih.gov> 
Sent: Thursday, June 23, 2022 11:08 AM
To: Woodruff, Rose (IMS) <WoodruffR@imsweb.com>
Cc: Freedman, Neal (NIH/NCI) [E] <freedmanne@mail.nih.gov>; Boyd-Morin, Jennifer (IMS) <Boyd-MorinJ@imsweb.com>; Gerlanc, Nicole (NIH/NCI) [E] <nicole.gerlanc@nih.gov>
Subject: RE: M3 Small Omission TOBACCO

Hi Rose,

I’ve updated the questionnaire documents to include the “some if the most popular brands” language when the E-cig brands are mentioned.

Best,
Julie

Julie Cusack [C] • Operational Development Coordinator
Division of Cancer Epidemiology and Genetics
National Cancer Institute, National Institutes of Health
9609 Medical Center Drive, Rockville, MD 20850
[C] N4 Solutions, LLC
E: [julie.cusack@nih.gov](mailto:julie.cusack@nih.gov)
P: 240-276-5861

From: Freedman, Neal (NIH/NCI) [E] <[freedmanne@mail.nih.gov](mailto:freedmanne@mail.nih.gov)> 
Sent: Wednesday, June 22, 2022 10:16 PM
To: Cusack, Julie (NIH/NCI) [C] <[julie.cusack@nih.gov](mailto:julie.cusack@nih.gov)>
Subject: RE: M3 Small Omission TOBACCO

Hi Julie, if possible, I like the “some of the most popular brands” language.
Best,
Neal

From: Cusack, Julie (NIH/NCI) [C] <[julie.cusack@nih.gov](mailto:julie.cusack@nih.gov)> 
Sent: Wednesday, June 22, 2022 3:24 PM
To: Freedman, Neal (NIH/NCI) [E] <[freedmanne@mail.nih.gov](mailto:freedmanne@mail.nih.gov)>
Subject: FW: M3 Small Omission TOBACCO

Hi Neal,

Do you have a preference for whether we add the brand statement (highlighted in yellow) or just put the trademarks in next to the product names?

 

Best,
Julie

Julie Cusack [C] • Operational Development Coordinator
Division of Cancer Epidemiology and Genetics
National Cancer Institute, National Institutes of Health
9609 Medical Center Drive, Rockville, MD 20850
[C] N4 Solutions, LLC
E: [julie.cusack@nih.gov](mailto:julie.cusack@nih.gov)
P: 240-276-5861

From: Woodruff, Rose (IMS) <[WoodruffR@imsweb.com](mailto:WoodruffR@imsweb.com)> 
Sent: Wednesday, June 22, 2022 7:45 AM
To: Cusack, Julie (NIH/NCI) [C] <[julie.cusack@nih.gov](mailto:julie.cusack@nih.gov)>
Cc: Boyd-Morin, Jennifer (IMS) <[Boyd-MorinJ@imsweb.com](mailto:Boyd-MorinJ@imsweb.com)>; Gerlanc, Nicole (NIH/NCI) [E] <[nicole.gerlanc@nih.gov](mailto:nicole.gerlanc@nih.gov)>
Subject: [EXTERNAL] M3 Small Omission TOBACCO

Hi Julie,

At this point I don’t know if you all will want this corrected now or later, but I noticed that in the M3 TOBACCO question, responses 2 and 3 use the language with “brands” so the trademarks aren’t needed; however, response 1 lacks that language, so should have the trademark symbols or have the language changed to match the other two.

Regards,
Rose

**Comment by cusackjm** [comment]
@joshid-ims what is the status on the markup change?

**Comment by cusackjm** [comment]
@joshid-ims partially fixed:

![image](https://user-images.githubusercontent.com/85582895/180820853-a6a2af87-8d4f-47f5-8436-f3a6b5189473.png)
The comma should be a semi colon. Please update markup

**Comment by joshid-ims** [comment]
It is in internal testing.

**Comment by cusackjm** [comment]
issue fixed in dev testing on 8/5
