### ISSUE TITLE
Remove some of question text in SLEEP1D, SLEEP1I, SLEEP1M, SLEEP2D, SLEEP2I, SLEEP2N

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#146]
for SLEEP1D, SLEEP1I, SLEEP1M, SLEEP2D, SLEEP2I, SLEEP2N, there is question text that does not make sense with the response type.

Please remove "Select the number of minutes and/or hours using the drop-down options below." from SLEEP1D, SLEEP1I, SLEEP1M, SLEEP2D, SLEEP2I, SLEEP2N.

For example: 
![image](https://user-images.githubusercontent.com/85582895/176923174-63ff166f-4771-4a30-ac5e-51f75c265da8.png)

**Comment by huip-ims** [comment]
@cusackjm Hi Julie - I'll be making these changes in the markup. Could you please also remove this text from the Quex Word doc? Thanks!

**Comment by cusackjm** [comment]
@huip-ims hi! qx documents are updated

**Comment by cusackjm** [comment]
confirmed fixed during testing on 8/2
