### ISSUE TITLE
Functionality of textboxes in "optional multiple choice with textbox" question types

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#149]
*sanford feedback*
"With the questions about water consumption (Module 4, DRINKSWTR2F), there are a couple where it asks how many times a day with a free text field. When you click on the actual text field it doesn’t do anything. It seems like you have to first select the answer row and then it allows you to type. This is not very intuitive and was a little frustrating."

@danielruss @naiyume Is it possible to click on a text box and have the participant simultaneously select the response and be able to type a response in? Right now, participants have to first select the multiple choice response, and then click on the text box to enter text. This is for "Optional Multiple Choice with textbox (text in text box)" question types (ex: Mod1 SEXORIENT) and "Optional Multiple Choice with textbox (numeric textbox)" question types (ex: Mod 4 DRINKSWTR2A)

This is **low** priority issue

**Comment by danielruss** [comment]
> Is it possible to click on a text box and have the participant simultaneously select the response and be able to type a response in? Right now, participants have to first select the multiple choice response, and then click on the text box to enter text.
@cusackjm   That was the original functionality.  Somewhere along the line, that was changed.

**Comment by cusackjm** [comment]
@danielruss Is it possible to change it back? (If not, I don't see it to be a huge deal for a participant to click twice.)

**Comment by cusackjm** [comment]
@danielruss @Davinkjohnson Can I close this if we don't intend on changing this?

**Comment by danielruss** [comment]
@cusackjm  ok by me.  If I have some time, I'll change it back. But I cannot make any promise when it will be completed.  I'll let you know when it is finished.  Otherwise, let close it.
