### ISSUE TITLE
Adding response to PREWORK1

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#150]
We would like to change the question type for PREWORK1, so a participant can avoid re-typing an address in, if it is the same address a participant entered at CURWORK.

For PREWORK1, we would like a response to say "My current job is the longest job I have had in the past 20 years". The response should be displayed where the yellow highlight is: 
![image](https://user-images.githubusercontent.com/85582895/178334432-73a86299-2a96-441e-baeb-acd9dc4aa215.png)

This is similar to HOMEMOVEOUT:
![image](https://user-images.githubusercontent.com/85582895/178334467-82f0a10f-0fa5-4109-8c1b-d774077f4c9c.png)

@woodruffr to my understanding PREWORK1 will now be the "Text Box Plus Special Missing Other Than 77/88/99" question type. Is this correct?

Adding this response also involved skip logic updates for PREWORK2, PREWORKCONFIRM, and PREWORKYR1. The questionnaire documents are updated in tracked changes.

**Comment by woodruffr** [comment]
@cusackjm As this was a Multiple Text Box question, at a minimum it would be a Multiple Text Boxes Plus Check Box question, which is a little more complicated that the simple Text Box Plus Check Box format. However, this question also uses DisplayIf, Exists/Does Not Exist, and piping. I would need to discuss with @joshid-ims if the overall format with all of these conditions is supported in Quest.

**Comment by cusackjm** [comment]
@woodruffr Sounds good. 

If this is not a function in Quest, would it be possible to separate the responses in to 2 questions. I.e., (1) Is your current job the longest job you have had in the past 20 years? (Yes/No)
If No --> participant goes to next question (2) PREWORK1 (to enter address)
If Yes --> participant skips to PREWORKCONFIRM

**Comment by cusackjm** [comment]
@joshid-ims Neal also prefers splitting PREWORK1 into 2 questions (PREWORK1A & PREWORK1B). The questionnaire documents are updated. 

@woodruffr this change does not require us to change the question type of PREWORK1, but does require changing PREWORK1 to PREWORK1B in the DD and adding PREWORK1A to the DD and question type document. Is it ok for me to make those changes now?

**Comment by woodruffr** [comment]
@cusackjm, Nicole has set up a process/SOP that involves checks/balances. She would be the person to ask. I will look at this now so I understand what needs to be added/changed.

**Comment by cusackjm** [comment]
fixed in dev testing on 8/5, but is it possible to get rid of space between responses? 
![image](https://user-images.githubusercontent.com/85582895/183133988-1077ad9f-c6e1-47f1-8b51-c6b9d1b778e7.png)
@joshid-ims @danielruss

**Comment by danielruss** [comment]
@joshid-ims  remove the empty line in module 4

```
[PREWORK1A?] Is your current job the longest job you have had in the past 20 years? 

(1) Yes -> INTROCURSCH 

(0) No, I worked longer at another job that I had within the past 20 years 

```
to 
```
[PREWORK1A?] Is your current job the longest job you have had in the past 20 years? 
(1) Yes -> INTROCURSCH 
(0) No, I worked longer at another job that I had within the past 20 years 
```

**Comment by cusackjm** [comment]
fixed in stage testing on 8/11
