### ISSUE TITLE
"ever" should be removed from question text for product8C questions

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#153]
This was an edit addressed in tracked changes (for all products) for issue #127 - but is still in PWA. 
(making a new issue to make it easier to track)

![image](https://user-images.githubusercontent.com/85582895/180823295-177bba79-f76a-47f4-82ad-ad7d81454c2f.png)

**Comment by cusackjm** [comment]
Also saw this for HOOKAH, but this was not case for every product. 
 "ever" was not present in CHEW, SMMAR, TOMAR, and ELMAR

**Comment by joshid-ims** [comment]
@cusackjm which questions this should be removed from?

**Comment by cusackjm** [comment]
CIG8C and HOOKAH8C

**Comment by joshid-ims** [comment]
This is at internal testing.

**Comment by woodruffr** [comment]
I note that all of the tobacco and smoking products 8c questions have ever in the data dictionary. We will highlight what should be changed and email it to you.

**Comment by cusackjm** [comment]
fixed in dev testing on 8/5
