### ISSUE TITLE
CIGLIFEEE was not supposed to be shown, but was shown and was missing piped age

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#154]
(part of issue #127 - making new issue to improve tracking)

testing on 7/25, I entered the following:
CIG1= 3 (100 OR MORE)
CIG2= 35
CIG3= 37
CIG4= 0 (NO NOT AT ALL)
CIG5= 2 (MORE THAN 1 YEAR AGO)
CIG8= 40
CIG8C= 1 (YES)
CIG9A= 22
CIG10= 0 (5 MIN OR LESS)
CIG11= 0 (ALMOST ALL THE TIME)
Correctly skipped CIGLIFEA-C
CIGLIFED= 12 (37 to 39) 
****CIGLIFEE= 3 (40 to )** Based on skip logic, Y should = CIG8_AGE, which is 40, so I don't think CIGLIFEE, should have been shown. This is in the questionnaire doc, as:** 
![image](https://user-images.githubusercontent.com/85582895/180828551-70cfa39e-a2c8-4947-9d0a-e48c048eb05d.png)

![image](https://user-images.githubusercontent.com/85582895/180824518-e79d214c-f669-4d3d-b7fa-e335c4c21b20.png)

**Comment by cusackjm** [comment]
(unsure if this is helpful), but this worked for ECIG when I entered the following:
ECIG1= 3 (100 OR MORE)
ECIG2= 3
ECIG3= 7
ECIG4= 3 (YES, EVERYDAY)
ECIG9A= 2
ECIG10= JUUL
ECIGLIFEA= 0 (7 to 17)
ECIGLIFEB= 1
ECIGLIFEC= 2
ECIGLIFED= 3
**ECIGLIFEE= 4 (40 to 42)** (the max (AGE) worked as intended here)

**Comment by cusackjm** [comment]
Incorrectly saw THMARLIFEE (as 40 to 40) when it should not have been shown.
THMAR8_AGE= 40

**Comment by guinevere83** [comment]
Our current documentation for whether the range of a LIFE question is appropriate to be displayed seems like it's based on age or AGE.

![image](https://user-images.githubusercontent.com/75336502/181515499-e1550668-83aa-4a57-a97f-a5371de813da.png)

As per that, the test cases you listed would be correct, so I think we're going to have to update the wording. If I understand correctly, we're trying to avoid displaying LIFE questions which have too narrow a year range? Is our goal to not display LIFE questions that have a range of two years or less, or is there a better way to note what behavior we're looking to produce here?

**Comment by joshid-ims** [comment]
So in other words, for e.g., for range 40 - 49, do you want to add a condition like display CIGLIFEE only if
CIG3_AGE >= 42 and CIG8 <= 47 (if CIG8C = 1)

**Comment by cusackjm** [comment]
No. That wouldn't work because we want to show CIGLIFEE if CIG3_AGE= 40 and CIG8C_AGE is 43

**Comment by joshid-ims** [comment]
@cusackjm what is the decision about this? Are you going to update document in Box?

**Comment by danielruss** [comment]
@cusackjm What is cig8c_age?  cig8c is  During that time, did you smoke cigarettes every day?

**Comment by cusackjm** [comment]
Neal and I are ok with the participant being shown the narrow age range given the complexity of the skip logic. It is also likely that very few participants in connect will have smoked everyday for only 2 years or less. That being said, I am going to delete this section of the logic for every product section “[CIGLIFE AGE RANGE: IF RESPONDENT'S CURRENT AGE IS 2 YEARS OR LESS FROM THE BOTTOM OF THE SPECIFIED AGE RANGE, THEY SHOULD NOT BE GIVEN THE QUESTION AND INSTEAD ROUTED TOECIG1.” and we can leave the programming as is.

**Comment by cusackjm** [comment]
@joshid-ims qx documents are updated

**Comment by cusackjm** [comment]
confirmed fixed during dev testing 8/5
