### ISSUE TITLE
Participant enters SIB=9 and gets stuck in more than 9 loops

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#157]
tested on 7/27 with hippaconsent@yahoo.com to replicate a real participant issue.

![image](https://user-images.githubusercontent.com/85582895/181306926-254dade2-fbf6-4d2e-ab99-790f239cc769.png)

**Comment by danielruss** [comment]
@cusackjm  Please Test

**Comment by cusackjm** [comment]
tested under juliecusack13@gmail.com and still not fixed

**Comment by danielruss** [comment]
@cusackjm  we did not push the fix to stage. do you test in dev?

**Comment by cusackjm** [comment]
@danielruss I can test in dev now

**Comment by cusackjm** [comment]
@danielruss confirmed fixed in dev

**Comment by danielruss** [comment]
@cusackjm waiting for the CDN to refresh...  @naiyume  any ideas?  maybe change from latest to 1?

**Comment by cusackjm** [comment]
@danielruss do you want this tested again in stage? or can this be pushed  to prod

**Comment by danielruss** [comment]
@cusackjm   Just saw your note.  I looked on the CDN and it appears that the stage/prod version of question was updated at some point.  I guess you tested and it worked.  Thank you for closing.
