### ISSUE TITLE
Incorrect skip pattern for WORKACT 

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#16]
WORK=1 and was not taken to WORKACT section. Instead, was incorrectly skipped to INTROSITTING

**Comment by boyd-mj** [comment]
@Davinkjohnson as reported on 7/28 IMS was not able to replicate this error

**Comment by cunnaneaq** [comment]
3/11 tested WORK=1 and saw WORKACT grid questions

![Screen Shot 2022-03-11 at 2 39 45 PM](https://user-images.githubusercontent.com/83971268/157946008-8b1e1037-2085-41c9-884f-b2d1f12c8f87.png)
