### ISSUE TITLE
CHILDADD5, CHILDADD6, CHILDWTR2 should not have "current address" piped in with address

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#161]
![image](https://user-images.githubusercontent.com/85582895/183132689-b3ce3620-3306-4b6d-a10f-704b2f24517d.png)

**Comment by guinevere83** [comment]
Currently, I'm still seeing this in CHILDADD4 and CHILDWTR1:

![image](https://user-images.githubusercontent.com/75336502/183148371-ba8ba201-ac83-4f53-88b9-9058c9574d8b.png)

Also, what did we want to display when the address selected is NR? It's showing up as blank now:

![image](https://user-images.githubusercontent.com/75336502/183148456-676fbdde-78da-4690-8493-9906d4ba7223.png)

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/183430784-40dac844-82cf-4939-a41c-8313175c68cc.png)
 the highlighted text should not be there

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/183431218-80dddbeb-8b77-4b12-8430-371cf4e55383.png)
If theres an address, data from CHILDADD1-CHILDADD3 should be piped.
If its no response, "your childhood home" should be piped

**Comment by joshid-ims** [comment]
@cusackjm, here is how it is working currently or how we are making changes:

If CHILDADD = 0 (Lived at previously entered addresses) and that address is NR or no details provided, we are displaying words "Current Address", "2nd Address", etc. 

If CHILDADD = 1 (entering new address for childhood home) and it is NR or no details provided in CHILDADD2 and 3, we are displaying words "Your childhood home" 

Is that what is expected?

**Comment by cusackjm** [comment]
@joshid-ims no, "current address" should not be displayed. It should be the address provided in CHILDADD1, CHILDADD2, CHILDADD3

**Comment by joshid-ims** [comment]
But user selected 0 at CHILDADD. That means previously entered address. Not new address entered in CHILD1,2 and 3. That is when CHILDADD is 1.

**Comment by cusackjm** [comment]
If the participant selected 0 at CHILDADD, can you pipe in the previous address that they selected in CHILDADD?

**Comment by joshid-ims** [comment]
Yes, but we are talking about when it is NR. If it is present, we are already showing that.

**Comment by cusackjm** [comment]
@joshid-ims if CHILDADD1-3 are NR?

**Comment by joshid-ims** [comment]
It all depends on this question:

[CHILDADD?] What was the street address of your childhood home (where you lived when you were about 13 years old)?

(0) I lived at a previous address already entered  -> CHILDTEST

(1) Not listed here -> CHILDADD1
< #NR -> CHILDADD1>

CHILDADD1-3 are asked only if CHILDADD = 1. 
If it is NR for CHILDADD1-3, we are displaying 'your childhood home'

If CHILDADD = 1, one of the previous addresses are shown but if it was NR for those addresses, we show Current Address (for 1st Address) or '2nd Address', '3rd address', etc.

**Comment by cusackjm** [comment]
@joshid-ims It should just be data entered at CHILDADD1-3, and if no data is provided for CHILADD1-3, then it should be "your childhood home". Those are the only piping options we want. "current address" is not in the directions for this section.

**Comment by guinevere83** [comment]
Alright, this has passed internal testing and we should be able to deliver soon.

**Comment by cusackjm** [comment]
Qc documents have been updated. Please see skip logic changes to CHILDTEST

**Comment by cusackjm** [comment]
@joshid-ims @guinevere83 hi just wanted to check in on the status of this

**Comment by joshid-ims** [comment]
@danielruss, is valueIsNotOneOf a valid function? Or I will have to use or along with doesNotEqual?

**Comment by joshid-ims** [comment]
I want to use them for 0,1,2,...,10 which are options to a question. The question has 10 radio buttons. So if the response to that question is NR, it should work, right?

**Comment by danielruss** [comment]
That makes sense `not valueIsOneOf("lala","0","1","2","3","4","5","6","7","8","9","10")` should work. you might also want to try `not valueIsBetween("0",10","lala")`

**Comment by joshid-ims** [comment]
Thanks!

**Comment by danielruss** [comment]
@joshid-ims  did it work as expected?

**Comment by joshid-ims** [comment]
No, getting this error:
![image](https://user-images.githubusercontent.com/64986739/184964700-2ed260fe-eebc-4a77-82a7-6cd698a6f280.png)

**Comment by joshid-ims** [comment]
But may not be related. Looking into it.

**Comment by danielruss** [comment]
it looks like you are mixing old + new functions

**Comment by guinevere83** [comment]
Alright, we've finished internal testing.

**Comment by cusackjm** [comment]
@guinevere83 @boyd-mj you can wait to deliver. We are working on finalizing an edit to the "thank you" text at the end of the survey.

**Comment by cusackjm** [comment]
fixed in testing on 8/29
