### ISSUE TITLE
Error message not shown when entering invalid response WEIGHTTHIS & MHGROUP(s) age/year of dx/surgery

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#162]
Entered the following at WEIGHTTHIS:
18 YEARS: 2070
25 YEARS: 200
35 YEARS: 190
45 YEARS: 167
55 YEARS: 170

Did not see the red text error message and the "next" button did not work. This is what I saw in the Console:
![image](https://user-images.githubusercontent.com/85582895/183979268-24c1e16b-a598-444d-84ba-7ff4b8f5e101.png)

I was able to move forward once I entered 207 at 18 YEARS. Tested in taratdrp1@yahoo.com in Stage. Shared my screen with Tony and he said to reach out to you to see if this was a PWA/QUEST issue

@danielruss

**Comment by danielruss** [comment]
@cusackjm   I was able to reproduce the error.  I think I know the cause.

**Comment by danielruss** [comment]
@cusackjm ready for testing on DEV.

**Comment by danielruss** [comment]
will take some time for the fix to propagate to stage/prod

**Comment by cusackjm** [comment]
fixed in dev testing on 9/8
