### ISSUE TITLE
Added response to PERMTTHLOST, updated TEETHLOSTD skip logic, & added new question TEETHLOSTOTH

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#167]
Added response to PERMTTHLOST, updated TEETHLOSTD skip logic, & added new question TEETHLOSTOTH. 
Edits are denoted in tracked changes.

**Comment by cusackjm** [comment]
@joshid-ims @boyd-mj what is the status on this?

**Comment by joshid-ims** [comment]
This was marked fixed on the August 24th comment and the related issue (468) was delivered August 29th. Unless there is anything in the Github after that, this is fixed.
Gene sent the JSON, which required one error fix to the '77' response for SRVMW_TEETHLOSTD_V1R0. Updated JSON with that fixed was received and run through the transformer without issue.

**Comment by cusackjm** [comment]
The last update I had via email was this:

From: Boyd-Morin, Jennifer (IMS) <[Boyd-MorinJ@imsweb.com](mailto:Boyd-MorinJ@imsweb.com)> 
Sent: Monday, September 12, 2022 11:17 AM
To: Cusack, Julie (NIH/NCI) [C] <[julie.cusack@nih.gov](mailto:julie.cusack@nih.gov)>
Cc: Gerlanc, Nicole (NIH/NCI) [E] <[nicole.gerlanc@nih.gov](mailto:nicole.gerlanc@nih.gov)>; Johnson, Davin (NIH/NCI) [C] <[davin.johnson@nih.gov](mailto:davin.johnson@nih.gov)>
Subject: [EXTERNAL] RE: Module 4 & Biospecimens ETA

Hi Julie,

Daniel and Deepti are still working on Github issue #95. There is one other outstanding issue that is awaiting delivery (Github #167). Which of these are you expecting will address the problem you’re running into?
If it’s the latter, we can deliver an updated version while work continues on #95.

Thanks,
Jen

@joshid-ims i do see it in the deliverables log, but I don't have a delivery email for it so I am confused

**Comment by cusackjm** [comment]
Based on this folder (https://nih.app.box.com/folder/170499018689) I dont think it was delivered? Im also free to hop on a call if teams would be easier to figure out this

**Comment by woodruffr** [comment]
You are correct. It was not delivered. I must check our internal procedures and will discuss delivery with Jen.

**Comment by boyd-mj** [comment]
@cusackjm per our calls on 9/7 and 9/14 this issue has been fixed and awaiting delivery pending resolution of issue #95 . Per your recent emails, we will investigate issue #152 and then redeliver rather than waiting on issue 95.

**Comment by cusackjm** [comment]
@boyd-mj Yes, thank you

**Comment by cusackjm** [comment]
Fixed in 9/30 stage testing
