### ISSUE TITLE
No unit listed for response boxes in [WEIGHTTHIS] 

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#169]
At [WEIGHTTHIS] "The next questions ask about how much you weighed at different times in your life. If you don’t remember your exact weight, please make your best guess. If you were pregnant at any of these times, how much did you weigh before your pregnancy? How much did you weigh when you were..." there is no unit listed like the previous pages - i.e., #Pounds (lbs)

**Comment by cusackjm** [comment]
Partially fixed in testing on 9/8:

@boyd-mj @joshid-ims 
My participant is 46 years old (so they correctly don't see WEIGHTTHIS5, but the units are still shown

![image](https://user-images.githubusercontent.com/85582895/189146475-02ae5d69-fb82-4b09-a0b6-94c95f154cb9.png)

**Comment by cusackjm** [comment]
@boyd-mj @joshid-ims @danielruss 
Please see comment above. Is this markup, PWA, or Quest issue?

**Comment by danielruss** [comment]
@cusackjm   What is the error that you see?  In quest, ALWAYS see that text box, which is wrong.  But you see only the label an no text box? 

I am using:
https://episphere.github.io/quest/

with this module:
https://raw.githubusercontent.com/cyrjeant/privatequest/master/module1.txt

**Comment by danielruss** [comment]
This is from [module 1](https://github.com/cyrjeant/privatequest/blob/master/module1.txt#L1020-L1035)
 
notice that the #Pounds (lbs) is not in a displayif.    This is a module coding issue.

```
|displayif=greaterThanOrEqual(isDefined(AGE,age),18)|a. 18 years old|
|__|__|__|id=WEIGHTHIS1 displayif=greaterThanOrEqual(isDefined(AGE,age),18) min=0 max=999 softedit=true modalif=value<70 modalvalue='Is the weight correct?'|#Pounds (lbs)
```

There is also a quest issue that I addressed and will push in the next update that I accidentally stumbled across while trying to reproduce this error.

**Comment by cusackjm** [comment]
@joshid-ims see above comment

**Comment by cusackjm** [comment]
@danielruss I will go through a test and screenshot the console for the missing text box if the participant age is >55

**Comment by danielruss** [comment]
@cusackjm please wait for @joshid-ims to update the module.

**Comment by joshid-ims** [comment]
In internal testing.

**Comment by guinevere83** [comment]
This has passed internal testing.

**Comment by cusackjm** [comment]
fixed in stage testing on 10/7
