### ISSUE TITLE
Skip pattern missed [INTROWH] and went directly to menstrual health history section [MENSHIS].

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#17]
Skip pattern missed [INTROWH] and went directly to menstrual health history section [MENSHIS].

Was correct in being taken to MENSHIS (participant SEX/GENDER= 00 FEMALE), but should have seen the INTROWH heading/intro screen first

**Comment by cunnaneaq** [comment]
Saw [INTROWH] as Sex/gender=0 participant

![Screen Shot 2022-03-11 at 2 05 45 PM](https://user-images.githubusercontent.com/83971268/157934976-94d8c335-5ab1-40e2-8d89-f99c9c13c95f.png)
