### ISSUE TITLE
Blank page between [ACNEMED3] and [FAMHISTINTRO]

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#170]
![Screen Shot 2022-04-08 at 10 05 16 AM](https://user-images.githubusercontent.com/83971268/162452135-2991ba81-a511-475d-ae83-f0e074d3938c.png)

![Screen Shot 2022-04-08 at 10 05 26 AM](https://user-images.githubusercontent.com/83971268/162452171-54856c2d-8213-40bf-80a7-c735c4dca514.png)

![Screen Shot 2022-04-08 at 10 05 41 AM](https://user-images.githubusercontent.com/83971268/162452221-09dc24d1-c026-4cca-b8c2-321139882e40.png)

**Comment by anthonypetersen** [comment]
moved from PWA board..

**Comment by cusackjm** [comment]
@boyd-mj

**Comment by cusackjm** [comment]
fixed in stage testing on 9/8
