### ISSUE TITLE
Can enter 0 at PPLEHOUSE. Min response should be 1

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#172]
PPLHOUSE: How many people currently live in your household? **Please include yourself in the total number.** (Include students living away at school, deployed military, etc.), but participant is able to enter 0. Min should be set to 1

**Comment by anthonypetersen** [comment]
moved from PWA board

**Comment by cusackjm** [comment]
@boyd-mj PPLEHOUSE min should be 1, not 0

**Comment by cusackjm** [comment]
testing in stage:

When I enter 0, the next button won't work and i see this error
![image](https://user-images.githubusercontent.com/85582895/189154652-f4826f24-e87f-4a17-bb56-7b147ebd20a7.png)

**Comment by joshid-ims** [comment]
This also may not be a code error? @danielruss?

**Comment by danielruss** [comment]
One sec.  I think I see the problem.

**Comment by danielruss** [comment]
pushing fix.

**Comment by danielruss** [comment]
@cusackjm please test

**Comment by cusackjm** [comment]
fixed in dev testing on 9/8
