### ISSUE TITLE
Conditions/surgeries are not bolded in age of diagnoses questions for BREASTSUR0-9, BREASTDIS3, & BREASTDIS4

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#173]
![image](https://user-images.githubusercontent.com/85582895/137491048-c75f0ccd-d525-460b-9daf-b8bf40e3bfc2.png)

**Comment by cusackjm** [comment]
@boyd-mj

**Comment by joshid-ims** [comment]
@cusackjm Should names of siblings and children be in bold for all questions?

**Comment by cusackjm** [comment]
@joshid-ims no, deleting that comment

**Comment by joshid-ims** [comment]
@danielruss, the bolding tags are not working in a code like this:

[BREASTSUR9?,displayif=and(equals(MHGROUP9,5),(equals(BREASTSUR,55)] How old were you when you had |displayif=exists("BREASTSUR_TB")|<b>{$BREASTSUR_TB}</b>||displayif=equals(BREASTSUR_TB,"")|<b>another type of breast surgery</b>|?<br/>

Is it because of the displayif statement?

**Comment by danielruss** [comment]
[line 839 of module1 in GitHub](https://github.com/cyrjeant/privatequest/blob/master/module1.txt#L839)  There is an extra opening parenthesis before equals(BREASTSUR,55)

```
displayif=and(equals(MHGROUP9,5),(equals(BREASTSUR,55)]
                                 ^
```

**Comment by joshid-ims** [comment]
It is not there in the code. Sometimes when we copy paste code it gets inserted. 

![image](https://user-images.githubusercontent.com/64986739/187217640-dcc18524-f053-45f2-8ca3-d15089f42ee1.png)

**Comment by danielruss** [comment]
I see it in the code you copied.  The "(" before the equals.

**Comment by joshid-ims** [comment]
Oh sorry, I misread! Trying that now.

**Comment by joshid-ims** [comment]
Bolding still not working.

**Comment by danielruss** [comment]
When I set the previous results to:
{
 "age":67,
 "BREASTSUR_TB":"painful surgery",
"MHGROUP9":5,
"BREASTSUR":55 
}

use this example 
```
[Q1] Hi

[BREASTSUR9?,displayif=and(equals(MHGROUP9,5),equals(BREASTSUR,55))] How old were you when you had |displayif=exists("BREASTSUR_TB")|<b>{$BREASTSUR_TB}</b>||displayif=equals(BREASTSUR_TB,"")|<b>another type of breast surgery</b>|?<br/>

|__|__|xor=BREASTSUR9 id=BREASTOTH_AGE min=0 max=isDefined(AGE,age)| Age at surgery

Or, if it is easier to remember the year, enter that here:<br/>
|__|__|__|__|xor=BREASTSUR9 id=BREASTOTH_YEAR minval=difference(difference(#currentYear,isDefined(AGE,age)),1) max=#currentYear| Year of surgery

[END] done
```
Painful surgery is bold.

**Comment by joshid-ims** [comment]
It is in bold when "BREASTSUR_TB" has a value. Not when it is left blank. When it is left blank, we need to show a different text " another type of breast surgery" as:

[BREASTSUR9?,displayif=and(equals(MHGROUP9,5),(equals(BREASTSUR,55)] How old were you when you had |displayif=exists("BREASTSUR_TB")|{$BREASTSUR_TB}||displayif=equals(BREASTSUR_TB,"")|another type of breast surgery|?

**Comment by danielruss** [comment]
Change the second displayif to:
`|displayif=doesNotExist("BREASTSUR_TB")|`
