### ISSUE TITLE
"to" should not be included between "including" and "the" in [SEX]

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#174]
Typo ("to" should not be between "including" and "the") in [SEX] "Later questions in this survey will ask about surgeries and medical procedures, including to the sex organs you were born with. We want to ask questions that will make sense for you."

**Comment by woodruffr** [comment]
Hi Julie,

This correction is not yet in the Questionnaire document on Box.

![image](https://github.com/episphere/questionnaire/assets/81166095/f7576810-8c84-4c06-8b33-593ed8e29bbb)

**Comment by cusackjm** [comment]
questionnaire documents are updated

**Comment by guinevere83** [comment]
This has passed internal testing and will be delivered soon.

**Comment by cusackjm** [comment]
confirmed fix in dev testing on 11/15/2023
