### ISSUE TITLE
Heading for [PREG] should not be on same line as supporting sentence 

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#18]
![image](https://user-images.githubusercontent.com/85582895/127027438-55a4f539-7133-4675-a3da-8cdf947b6144.png)

**Comment by cunnaneaq** [comment]
Still present during testing on 3/11

**Comment by naiyume** [comment]
@cunnaneaq  Does this issue still show up?

**Comment by cusackjm** [comment]
@naiyume Yes

**Comment by cusackjm** [comment]
The heading and intro text are also on different pages for the follow variables:

Module 1:
[SECTION 1] and [AGECOR]

**Comment by cusackjm** [comment]
@boyd-mj markup issue

**Comment by cunnaneaq** [comment]
Heading and [PREG] intro text look good!  Going to leave this open until we check [SECTION1] and [AGECOR] in mod 1.  I'll change the label from mod 2 --> mod 1

![Screen Shot 2022-05-13 at 11 51 39 AM](https://user-images.githubusercontent.com/83971268/168320880-a50d0a3d-2524-4d0e-ba48-e2ea81469311.png)

**Comment by boyd-mj** [comment]
These have been updated and will be included in the next deliveries

**Comment by cunnaneaq** [comment]
Looks good in stage testing 6/30:

[SECTION1] and [AGECOR]:
![Screen Shot 2022-06-30 at 12 27 24 PM](https://user-images.githubusercontent.com/83971268/176729395-1fc46f9d-9c35-4cce-883f-dc873cd7d6a4.png)

"Height and Weight" heading and [WEIGHT]:
![Screen Shot 2022-06-30 at 1 05 39 PM](https://user-images.githubusercontent.com/83971268/176736328-2f0a42df-637b-48e3-8430-9a5685fc7bb8.png)
