### ISSUE TITLE
Stuck in sibling loop

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#180]
I tried the following and am stuck in the sibling loop:
1. SIB1= 0 
2. SIBCONFIRM correctly showed 0
3. *should have skipped the sibling loop, but instead started the sibling loop*
4. Went back to SIB1; changed response to SIB1=1
5. SIBCONFIRM is still showing 0 (should be 1 now)
6. still was stuck in sibling loop; went through the loop 14 times and got stuck on SIB3 in the 14th iteration and saw this 

![image](https://user-images.githubusercontent.com/85582895/189150564-331f9031-a833-4cbd-bc9a-e2b1e71ff8eb.png)
7. I clicked back button, changed SIB2 answer and got "unstuck"
8. continued to go through the sibling loops for the full 25 iterations

**HIGH priority**

**Comment by cusackjm** [comment]
The same thing is happening for the children loop

**Comment by danielruss** [comment]
@anthonypetersen   This is a PWA issue.  Let's talk about storing the data in indexedDB and upload the data at various points.

**Comment by cusackjm** [comment]
fixed in dev testing on 9/8
