### ISSUE TITLE
Stuck on page when reporting ALCOHOL= 0

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#181]
1. Stuck on ALCOHOL when trying to ALCOHOL=0 "no"
2. Able to move to ALCOHOL2 if ALCOHOL=1
3. On ALCOHOL2 screen, I tried to click "back"  and was sent to a blank screen. Console showed this: 
![image](https://user-images.githubusercontent.com/85582895/189165201-5ca977e8-c6d7-4602-94ed-b4fd345b805f.png)

4. Had to click on  "messages" tab to get off blank screen. 
5. Re-opened module 3 in "dashboard" tab and was taken to ALCOHOL2
6. Can't move forward in ALCOHOL2 if trying to submit ALCOHOL2= 0, 1
7. Able to move forward if ALCOHOL2= 3, 4 (seems like i have to go through the loop to not get stuck)

@boyd-mj @danielruss is this a PWA/QUEST or IMS issue?

**Comment by danielruss** [comment]
@anthonypetersen  is going to get tired of me throwing the PWA under the bus.  This is a PWA problem.

Here is the most simple logic surrounding ALCOHOL1 and 2.  No issue with Quest.  However if the api call fails..  PWA problem.


```
[ALCOHOL1?] Have you ever had an <b>alcoholic beverage</b> (beer, wine, wine cooler, liquor, cocktail, or a mixed drink) in your life?
(1) Yes -> ALCOHOL2
(0) No -> SECTION4
< #NR -> SECTION4>


[ALCOHOL2?] How many alcoholic beverages have you had in your <b>entire life</b>?
(0) 10 or less -> SECTION4
(1) 11 to 49 -> SECTION4
(2) 50 to 99 -> ALCOHOL3
(3) 100 or more -> ALCOHOL3
< #NR -> SECTION4>



[ALCOHOL3] This is alcohol3...
< -> END >

[SECTION4] This is section4...


[END] All Done..
```

**Comment by cusackjm** [comment]
@anthonypetersen do you have a status update on this

**Comment by anthonypetersen** [comment]
@cusackjm this isn't on my radar at the moment, if it's something that needs done sooner than later reach out to Davin and we can get this prioritized against the other items I'm working on at the moment
