### ISSUE TITLE
BLDTRANS4 Range Check not working

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#182]
(Participant is 47 years old) - I entered the following:

1. BLDTRANS3= 40 (Max range check works - error for 47 (age))
2. Tried BLDTRANS4= 48 (Max range check works - error for 47 (age))
3. Tried BLDTRANS4= 30 (Error for range check incorrect - seeing "value must be **greater** than or equal to 47"; should see a range check as "value must be greater than or equal to 40" (based on BLDTRANS3, the age of 1st blood transfusion)
4. Tried BLDTRANS4= 41 (Error for range check incorrect - seeing "value must be **greater** than or equal to 47"; shouldn't see an error message at all
5. only response I don't see an error for is BLDTRANS4= 47 (this is wrong)

Is this a PWA/QUest or ims issue? @danielruss @boyd-mj 
![image](https://user-images.githubusercontent.com/85582895/189679713-a7023ae8-02c8-4f93-a042-fec05ea10fad.png)

**Comment by danielruss** [comment]
@cusackjm   I think the problems is the max= isDefined(...).  Please ask IMS to change:

in question BLDTRANS3:
input AGE:
max=valueOrDefault("AGE","age",100)

input year:
min=#currentYear-valueOrDefault("AGE","age",100)-1 

note: 100 should never come into play, just for safety...

Same for the next question...  See below:

```
[BLDTRANS2?] How many blood transfusions have you had in total?
|__|__| min=1| # of transfusions
<#NR -> BLDTRANS3 >

[BLDTRANS3?,displayif=greaterThanOrEqual(BLDTRANS2,1)] How old were you when you had your <b>first</b> blood transfusion?
|__|__|xor=BLDTRANS3 id=BLDTRANS3_AGE min=0 max=valueOrDefault("AGE","age",100)| Age at first transfusion

Or, if it is easier to remember the year, enter that here:<br/>
|__|__|__|__|xor=BLDTRANS3 id=BLDTRANS3_YEAR min=#currentYear-valueOrDefault("AGE","age",100)-1 max=#currentYear| Year at first transfusion
<#NR -> BLDTRANS4 >

[BLDTRANS4?,displayif=greaterThan(BLDTRANS2,1)] How old were you when you had your <b>last</b> blood transfusion?
|__|__|xor=BLDTRANS4 id=BLDTRANS4_AGE min=valueOrDefault("BLDTRANS3_AGE",0) max=isDefined(AGE,age)| Age at last transfusion

Or, if it is easier to remember the year, enter that here:<br/>
|__|__|__|__|xor=BLDTRANS4 id=BLDTRANS4_YEAR min=valueOrDefault("BLDTRANS3_YEAR",#currentYear-valueOrDefault("AGE","age",100)-1 ) max=#currentYear| Year at last transfusion
```

There is one minor flaw in the logic.  If the user was born in 2000, had there first blood transfusion in 2005.  Then in BLDTRANS4 you can say they were 3 when they had the last transfusion.

**Comment by danielruss** [comment]
just updated the code, I left an "isDefined(...)" in the example

**Comment by cusackjm** [comment]
fixed in stage testing on 9/26
