### ISSUE TITLE
Participant stuck at COV19

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#183]
The participant was unable to advance the survey upon answering the question asking if they continue to have ongoing symptoms after having COVID (COV19). The participant logged out and back in, refreshed, and reset the answer and continued to be "stuck" at this point in the survey.

**Comment by Davinkjohnson** [comment]
@cusackjm Do you have any updates for this issue? (Also, does this apply to the "Whole" blood/urine/mouthwash survey?)

**Comment by danielruss** [comment]
@cusackjm  I just just took the BUM survey said I had covid 2x.  Answered all the symptom question.  Had to wait while the survey skipped the other ~23 questions.  Is this why the error occurred?

**Comment by danielruss** [comment]
@cusackjm no, it took about 5 sec to run through all the "hidden questions"

**Comment by danielruss** [comment]
@cusackjm   There are a few problems that I see with the biospecimen module that I have in the past discussed with @joshid-ims 

When I followed the path set by the participant, I got stuck at question  `[D_959877599?] How long did it take you to recover to your usual state of health from the date you first realized you had COVID-19? `  

Problem 1: You must have `required=TRUE` NOT `required` in question [D_980800222] month and year
 
Problem 2:  Question. value `D_366972678_1` and `D_173502329_1` should be  `D_366972678_1_1` and `D_173502329_1_1`


Also the question [D_273371161?] Following your COVID-19 infection in ...  Should have _1_1 or _2_2 

These errors are what caused the participant to get stuck.

**Comment by cusackjm** [comment]
@danielruss I used participant table data but was unsuccessful in replicating this issue (everything worked fine). Was this issue resolved?

**Comment by danielruss** [comment]
I think IMS resolved the issue. This was the problem where I changed the code to use ID_1_1, ID_2_2 ... and IMS was not expecting the change.  I believe they fixed it.  @joshid-ims  does this sound right?

**Comment by boyd-mj** [comment]
Deepti is out for the next 3 weeks but this is what I recall as well.
