### ISSUE TITLE
Unnecessary range check in COV22

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#187]
Seeing a range check for COV22 (which I don't know where the 2 came from, and i didnt see this in a different test)
![image](https://user-images.githubusercontent.com/85582895/193311030-f470dd74-65b1-4541-b6ed-7e67be445d5a.png)

**Comment by joshid-ims** [comment]
@cusackjm Can you please post here the exact test case, values you entered to reach here?

**Comment by cusackjm** [comment]
SEX= 1
SYMPTDAY= NONE OF THESE
EATDRINKBEFORE= THE SAME DAY
EATDRINKTIME= 8:45
SLEEPTIME= 1:30
WAKETIME=7:00
TYLENOL= 1
NSAIDS= 0
ACID= 0
COV1= 1
COV2= 1
COV3= 7 MONTH, 2022 YEAR
COV4= 1
COV6= 1
COV7= 1
COV8= WEAKNESS OR FATIGUE; OTHER (no text entered)
COV9= 0
COV10= 0
COV11= 0
COV12= 0
COV19A1= 0
COV19A2= 0
COV19A3= 2
COV19A4= 0
COV19A5= 0
COV19A6= 0
COV19B1= 0
COV19B2= 2
COV19B3= 0
COV19B4= 2
COV19B5= 0
COV19C1= 0
COV19C2= 0
COV19C3= 0
COV19C4= 0
COV19C5= 0
COV19C6A= 1 "I felt a bit “off” before the cough started. Not grounded in my body, but not light-headed."
COV19C6B= 0
COV20A2= 0
COV20A10= 0
COV20A12= 0
COV20A17= 1
COV21= 1
COV22= 2 months (I couldn't enter 6 without getting an error)

**Comment by huip-ims** [comment]
@cusackjm @joshid-ims Hi Julie, I discussed this with you a few months back, and you agreed to add this check. This range check is to ensure the entered # of months for recovery (COV22) did not exceed the difference in # months from today's date and the 1st (earliest) reported COVID infection. In your example, the 1st COVID infection was 7/2022 with 9/2022 as current month/year. Therefore, there are only 2 months lapse in time. However, in your code testing, you're trying to enter 6 months of recovery time. Did you want the range check to be removed and allow a participant to enter any value for # of recovery months?

**Comment by cusackjm** [comment]
@huip-ims sorry did not realize that in the test. Closing the issue
