### ISSUE TITLE
Have to scroll up to read intro/first question in mod 2

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#188]
Module 2 in stage is starting at the bottom of the screen.  Have to scroll up to read the first question

@anthonypetersen  @danielruss - not sure if this is a Quest or PWA issue 

![Screen Shot 2022-10-05 at 12 10 53 PM](https://user-images.githubusercontent.com/83971268/194110084-5f581048-e570-4362-9102-a13e5c2f0aac.png)

**Comment by anthonypetersen** [comment]
@cunnaneaq have you tried starting any other modules in stage?

**Comment by danielruss** [comment]
@cunnaneaq I dont see it when I [run module 2 through quest](https://episphere.github.io/quest/?url=https://raw.githubusercontent.com/episphere/questionnaire/main/module2Stage.txt&run&style=Style1.css).
