### ISSUE TITLE
Module 2 stage "age" showing as a conceptId

### ISSUE THREAD

**Issue by danielruss** [episphere/questionnaire#189]
While looking at #188 I came across a potential problem.  The id _age_ is not getting converted to a concept Id.

```
[D_113681507?] About how many years did you take baby or low-dose aspirin (81 mg or less)?

#Years |__|__|min=1 max=sum(isDefined(D_150344905,age),1)|
< -> D_177526169 >
```

I'm not sure if this is a bug or a feature, _age_ comes from the user profile so it may be correct.

**Comment by cusackjm** [comment]
This is still in the markdown, is this still an issue?
