### ISSUE TITLE
ELSE statement for Quest ID SrvMw_MWUSE_v1r0

### ISSUE THREAD

**Issue by huip-ims** [episphere/questionnaire#190]
@cusackjm Hi Julie - For Quest ID SrvMw_MWUSE_v1r0, I noticed the following Displayif condition:

[DISPLAY SrvMw_MWUSE_v1r0 IF (SrvMw_HYGEINE_v1r0= 5)
ELSE, GO TO SrvMw_BRUSH2_v1r0]

Is the ELSE statement necessary, and if so, should it go to SrvMw_BRUSH2_v1r0?  FYI - this occurs in both Word docs on Box: "Research Appointment (blood urine mouthwash) 20220127.docx" and "At Home Mouthwash (mouthwash) 20220127.docx"

**Comment by cusackjm** [comment]
@huip-ims just to confirm, can I close this

**Comment by huip-ims** [comment]
@cusackjm Hi Julie - Yes, this issue is resolved and can be closed.
