### ISSUE TITLE
Skip logic for SrvBlU_COV25_v1r0

### ISSUE THREAD

**Issue by huip-ims** [episphere/questionnaire#191]
@cusackjm Hi Julie - In the stand-alone Blood & Urine survey, the documentation Word file "Clinical Collection (blood urine) 20220127.docx" on Box has the following skip logic for COV25:

> 57.	[SrvBlU_COV25_v1r0] Did you get vaccinated against a COVID-19 vaccination?
1	Yes
0	No -> GO TO SrvMw_ORALHLTH_v1r0
77	Don’t know -> GO TO SrvMw_ORALHLTH_v1r0
NO RESPONSE -> GO TO SrvMw_ORALHLTH_v1r0

Could you please replace "GO TO **SrvMw_ORALHLTH_v1r0**" with "GO TO **END**"? Thanks!

**Comment by cusackjm** [comment]
@huip-ims Hi Pete. Qx documents are updated

**Comment by cusackjm** [comment]
@huip-ims just to confirm, can I close this

**Comment by huip-ims** [comment]
@cusackjm Yes, this can be closed. Thanks!
