### ISSUE TITLE
Apartment # and Year Last Spent Time in Module 4

### ISSUE THREAD

**Issue by huip-ims** [episphere/questionnaire#195]
@boyd-mj @cusackjm Hi Julie - In recent testing at IMS, we noticed that the Apartment # box for Home Address only allows numeric responses, whereas the Seasonal Home Address Apartment # box allows alphanumeric. Should we update the the Home Address Apartment # to also allow alphanumeric?

Also, for "Year Last Spent Time At This Address", a participant can currently enter a value less than "Year First Spent Time ...". Should we go ahead to add a check to make sure "Year Last Spent Time" is ≥ "Year First Spent Time" for both Home and Seasonal Addresses?

**Comment by cusackjm** [comment]
@huip-ims Hi, yes to both.

@woodruffr would the first edit require just an update to the data dictionary?

**Comment by woodruffr** [comment]
@cusackjm The Apt variables are listed as Char in the data dictionary. It only needs to be changed in the Mark-up.

**Comment by huip-ims** [comment]
@danielruss @cusackjm Hi Julie - Daniel provided the code to check and make sure "Year Last Spent Time" is ≥ "Year First Spent Time" for both Home and Seasonal Addresses, and it has worked pretty well. However, there are a few small quirks.
- "Last Year Spent Time" has to be ≥1 year after "Year First Spent Time". The check code currently doesn't allow last year and first year to be the same value.
- For a reported home, if the "Year First Spent Time" is equal to the current calendar year, a participant can't enter the current year as the "Year Last Spent Time" because the check code won't allow it. And, a participant can't enter ≥1 year after "Year First Spent Time" because it would be after the current calendar year (i.e., in the future). Therefore, the only option for the participant is to click the checkbox for "I still live here".

Are these 2 issues acceptable to NCI or what tweaks to the check code would you like us to make?
For more context, please see the Github quest issue: https://github.com/episphere/quest/issues/415

**Comment by cusackjm** [comment]
@huip-ims that is fine. For both home and seasonal addresses, the question text *should* prevent them from putting in the same year anyways ("addresses where you have lived for at least two years in the last 20 years" and "homes where you have spent at least 24 months in the past 20 years")

**Comment by danielruss** [comment]
```
[AGE!] How old are you? |__|__|min=30 max=100|
// note: the max for the Year first spent time is last year
// because you had to spend at least 1 year there.
// you could set it to the current year, but then you 
// would need a displayif on the LYST
[YFST]  Year first spent time |__|__|min=#currentYear-_value("AGE") max=#currentYear-1|


// note: If you filled out question YFST, the min is YFST+1.  If not, the 
// min is the year of your birth. 
[LYST] Last year spent time |__|__| min=valueOrDefault("YFST",#currentYear-_value("AGE")-1)+1 max=#currentYear|



[YFST2] Next place Year first spent time |__|__| min=valueOrDefault("LYST","YFST",#currentYear-_value("AGE")-1)+1 max=#currentYear-1|

// the logic is a little more complicated.  either YFST2+1 or LYST+2 or YFST+2 or year of birth +1
// the more locations you have, the more complicated the logic.  You should require these values or else risk the 
// tower of valuesOrDefaults. valueOrDefault(X,valueOrDefault(Y,valueOrDefault,Z))
[LYST2] Next place Last year spent time |__|__| min=valueOrDefault("YFST2",valueOrDefault("LYST","YFST",#currentYear-_value("AGE")-1)+1)+1 max=#currentYear|

[END] end

```

**Comment by danielruss** [comment]
you should be able to handle even these more complicated cases.

**Comment by cusackjm** [comment]
@huip-ims we think the first check is fine. Addresses can also overlap for HOMEADD and SEASADD

**Comment by huip-ims** [comment]
@cusackjm Thanks Julie. IMS will do some internal testing using Daniel's first check and also implement the changes you just addressed in issue 198. We'll send you an unconverted markup for testing and feedback soon.

**Comment by cusackjm** [comment]
@huip-ims We discussed the implications of a range check error for participants entering the same year for HOMEMOVEIN and HOMEMOVEOUT and would like to remove the range check, so that participants can enter the same year. This applies to both home and seasonal address sections

**Comment by huip-ims** [comment]
@cusackjm Thanks Julie for the feedback. IMS will proceed with these changes and send you updated markup once it passes our internal testing.

**Comment by cusackjm** [comment]
@huip-ims Yes, same thing for childadd
