### ISSUE TITLE
Concatenated Age Mostly NA

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [episphere/questionnaire#196]
PROD ENVIORNMENT
Warren created the variable d_117249500 that calculates derived age from DOB in Firestore (at time of user profile completion) and loads it into the participants table. However, this is missing for a large majority of participants. Can you review the code for this variable? I need the age of participants for filtering purposes.

**Comment by anthonypetersen** [comment]
This code only would've applied to participants that submitted their User Profile after the code went live in production
