### ISSUE TITLE
Markup responses inconsistent with questionnaire document 

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#198]
responses are "these are all my addresses" and "I have another address", but should be 
![image](https://user-images.githubusercontent.com/85582895/199311989-e21e62db-d141-4bb5-a6ee-6a76b6b55ea8.png)
 As listed in the Qx document.

This edit needs to be made for 
HOMEADDSUM_1, HOMEADDSUM_2, HOMEADDSUM_3, HOMEADDSUM_4, HOMEADDSUM_5, HOMEADDSUM_6, HOMEADDSUM_7, HOMEADDSUM_8, HOMEADDSUM_9, HOMEADDSUM_10
and
SEASADDSUM_1, SEASADDSUM_2, SEASADDSUM_3, SEASADDSUM_4, SEASADDSUM_5, SEASADDSUM_6, SEASADDSUM_7, SEASADDSUM_8, SEASADDSUM_9

These edits are already in the DD.

**Comment by huip-ims** [comment]
@cusackjm Hi Julie - could you please confirm which version of text I should use for SEASADDSUM_1-SEASADDSUM_9?

In the DD and Word doc, the text is:
1 = Yes, this is correct
0 = No, I want to add a seasonal or vacation home address

from your comment above, the text is:
1 = Yes, this list is complete
0 = No, I want to add **another** seasonal or vacation home address

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/199326373-5d4b91f8-242e-4114-bf6f-4773beb8efb1.png)

Please follow the qx document. In the DD version I have, the response text is the same as the qx document.

**Comment by okisahia** [comment]
> @cusackjm Hi Julie - could you please confirm which version of text I should use for SEASADDSUM_1-SEASADDSUM_9?
> 
> In the DD and Word doc, the text is: 1 = Yes, this is correct 0 = No, I want to add a seasonal or vacation home address
> 
> from your comment above, the text is: 1 = Yes, this list is complete 0 = No, I want to add **another** seasonal or vacation home address

@huip-ims Hi Pete,

The first set of options you've quoted is for SEASADDSUM1 which is different from SEASADDSUM_1-SEASADDSUM_9

**Comment by cusackjm** [comment]
Hi - changes are in GitHub DD

**Comment by woodruffr** [comment]
Hi Julie,

One small item: Excel line 5071 Question Text- v1 needs a space between "more" and "at". It seems we both missed that.

Also, of minimal concern is that the Formula for Index has #REF! errors from 4794 to the end, and the Index is missing from 5071 which then makes it incorrect for subsequent rows. I don't know if the index impacts any functionality.

Thanks,
Rose

**Comment by cusackjm** [comment]
changes are in GitHub

**Comment by woodruffr** [comment]
At Julie's request, met with Julie and Gene to discuss changing the HOMEADDSUM_1 variable to HOMEADDSUM (instead of deprecating HOMEADDSUM (just revise it). HOMEADDSUM_2 through HOMEADDSUM_11 will stay as they are. Julie has made this update on the Box Questionnaire document.

**Comment by cusackjm** [comment]
For HOMEADDSUMs we are keeping the response values as 0- "Yes, this list is complete" and 1- "No, I want to add another address" to be in sync with what is currently in prod

**Comment by cusackjm** [comment]
fixed in dev testing on 11/22
