### ISSUE TITLE
55 Other text boxes don't fit inside response bar

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#199]
![image](https://user-images.githubusercontent.com/85582895/199576772-01b8e656-aebe-4ccb-a8d9-201a4ac0f5ad.png)

![image](https://user-images.githubusercontent.com/85582895/199576852-8f09925c-7cb1-4802-a95a-09046ae23d0d.png)

Is this a markup, PWA, or Quest issue? @boyd-mj @danielruss

**Comment by anthonypetersen** [comment]
@cusackjm is it always on this question? how easily are you able to reproduce this?

**Comment by cusackjm** [comment]
@anthonypetersen in the past it was much smaller, I will see if I can find a screenshot. @cunnaneaq also saw it on her iPad

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/199739640-650a575c-6958-43ac-b6d1-8dc107d8aa37.png)

**Comment by cusackjm** [comment]
Not sure if anyone worked on this, but the text boxes look normal in stage:
![image](https://user-images.githubusercontent.com/85582895/199974876-d1e60fa6-2e55-4100-b397-33936faa5d7b.png)
