### ISSUE TITLE
[PREG8] and [SHIFTWORK] text formatting looks weird

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#20]
![image](https://user-images.githubusercontent.com/85582895/126841469-72c0e207-da0e-475d-8f9e-cec9a1296913.png)

**Comment by boyd-mj** [comment]
@Davinkjohnson it looks like this issue can be closed?

**Comment by Davinkjohnson** [comment]
The comment on this issue is saying that Aileen was expecting to see "breastfeed" in blue but didn't.

Also, we believe Julie posted the issue to point out the misalignment of "breastfeed" and "shift work." 

Unless we can verify that this is closed we should leave it open for now.

**Comment by Davinkjohnson** [comment]
In Today's meeting with IMS Jen shared that their testing of this in the renderer it looked to be functioning, but it might be that the small misalignment of text is within the PWA. She will assign this back to Brian for further investigation.

**Comment by boyd-mj** [comment]
Here's how it appears in the renderer when we test. The user needs to click on the button in order to see the explanatory text, which is expected. 

![shiftwork](https://user-images.githubusercontent.com/80920570/147154321-ee5c9594-9223-4a78-9407-c8f15e6ed4e3.png)

**Comment by Davinkjohnson** [comment]
Julie and I reviewed this and agreed that it looks good in the renderer and is ready for another round of testing. We'll close if it works through this round.

**Comment by cunnaneaq** [comment]
The informational text for breastfeeding worked well (and more recently added eclampsia/pre-eclampsia).  The alignment looks the same as above.  Potentially, a quest issue?

**Comment by boyd-mj** [comment]
@Davinkjohnson is someone looking into this on the Quest end? It doesn't sound like testing on our end is needed, but let me know if I'm mistaken.

**Comment by KELSEYDOWLING7** [comment]
Still seeing in 6/2 testing. 
taratdrp@gmail.com connect id: 6537895747

**Comment by danielruss** [comment]
@cusackjm   works for me

![Screen Shot 2022-06-29 at 3 16 22 PM](https://user-images.githubusercontent.com/3767675/176518008-a0adb041-f5e0-47f3-adf0-66b89b328e08.png)

**Comment by danielruss** [comment]
@naiyume i can turn off the Quest.css styling, and it looks similar to the original image.  @cusackjm Was this on the PWA?

**Comment by danielruss** [comment]
![Screen Shot 2022-06-29 at 3 21 32 PM](https://user-images.githubusercontent.com/3767675/176518856-3c6db2e9-acce-46f8-a7c2-a4a26d202b80.png)

**Comment by cusackjm** [comment]
@danielruss yes on the pwa

If you cant make the text aligned with the other text, we'd prefer it be left as the blue font rather than the yellow box
