### ISSUE TITLE
Edits to GEN responses

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#201]
making note of proposed edit. Waiting for IRB approval (Amendment 13)

**Comment by cusackjm** [comment]
New response also requires an edit to the Module 2 INTRONONCISWOM skip logic
![image](https://user-images.githubusercontent.com/85582895/205376575-0a1cc997-6d40-4ce2-862f-8a0c62dc6383.png)

**Comment by cusackjm** [comment]
@huip-ims correction is in document

**Comment by guinevere83** [comment]
This has passed internal testing, but we'll need a new JSON to deliver and test converted files.

**Comment by guinevere83** [comment]
Converted file is good now too.

**Comment by cusackjm** [comment]
module 1 looks good in dev testing on 1/4/23. Removing Module 1 tag

**Comment by cusackjm** [comment]
fixed in dev testing on 1/5/23
