### ISSUE TITLE
Question text added to INTRORH, HOMEADDSUM_11, INTROSH, and SEASADDSUM_10

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#202]
additional text is denoted in tracked changes

@woodruffr just want to confirm, but HOMEADDSUM_11 and SEASADDSUM_10 are the only variables that require DD edits?

**Comment by boyd-mj** [comment]
On hold pending IRB review

**Comment by cusackjm** [comment]
this was approved
