### ISSUE TITLE
Edits to INTROSTD text and heading

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#203]
awaiting IRB approval

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/205374049-e69972c6-9ec3-4fb7-8fe9-0cc185862f08.png)
edits are in tracked changes

**Comment by guinevere83** [comment]
This has passed internal testing, but we can't deliver until we have a new JSON.

**Comment by cusackjm** [comment]
fixed in dev testing on 1/4/23
