### ISSUE TITLE
Question text revisions for every product8C and product9B question

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#204]
waiting for IRB amendment 13 approval

**Comment by cusackjm** [comment]
Edited question text for CIG8C, CIG9B, ECIG8C, ECIG9B, CIGAR8C, CIGAR9B, CHEW8C, CHEW9B, HOOKAH8C, HOOKAH9B, PIPE8C, 
PIPE9B, SMMAR8C, SMMAR9B, TOMAR8C, TOMAR9B, ELMAR8C, ELMAR9B, EAMAR8C, EAMAR9B, THMAR8C, THMAR9B 
(in tracked changes)

**Comment by huip-ims** [comment]
@cusackjm Hi Julie - could you please confirm if these changes have been approved by IRB?

**Comment by cusackjm** [comment]
@huip-ims Hi yes

**Comment by guinevere83** [comment]
This has passed internal testing.

**Comment by cusackjm** [comment]
fixed in dev testing on 1/4/23 https://nih.box.com/s/nsqfnupkgsr5m7j8f8l2rl9975gr3ff3
