### ISSUE TITLE
_V2 variables not saving data (clinical collection survey)

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#207]
1. The following participant issue was reported on 12/2:
"CID: 7593575667 entered a response to the question “When did you get vaccinated with your 1st shot?” and clicked next. A pop-up message appeared “There is 1 question unanswered on this page. Would like you like to continue?” with the options to “Continue without answering” or “Answer the question.” I’ve attached the screenshot that they provided. They already submitted the survey, though we wanted to make you all aware of the error before additional participants donate samples."

2. I tried replicating the issue using the participant table responses, but realized this was not possible, as the question of concern (COV27) populated as null.
 
3. I think this has to do with the _V2 versioning as none of the _V2 variables saved any data (all were null):
EATDRINKTIME 191057574
SLEEPTIME 299417266
WAKETIME 689861450
COV25 890156588
COV26 877074400
COV27 715581797

**Comment by KELSEYDOWLING7** [comment]
COV27 is showing as null in the flattened table FlatConnect.clinicalBioSurvey_v1_JP and in the source table Connect.clinicalBioSurvey_v1 for this participant

**Comment by FrogGirl1123** [comment]
@cusackjm and @KELSEYDOWLING7 I assume this was not an issue in the testing of the v2 version in Dev and Stage?

**Comment by KELSEYDOWLING7** [comment]
@FrogGirl1123 this issue wasn't showing in the backend in Dev and Stage, no

**Comment by FrogGirl1123** [comment]
Good to know, even if it doesn't help give us a solution.

**Comment by anthonypetersen** [comment]
I can see data that was saved for V2 versions of the following:

EATDRINKTIME 191057574
SLEEPTIME 299417266
WAKETIME 689861450

**Comment by KELSEYDOWLING7** [comment]
EATDRINKTIME , SLEEPTIME , WAKETIME , COV25 , COV26 have the answers for this participant in the source table Connect.clinicalBioSurvey_v1 but populate as null in the flattened table FlatConnect.clinicalBioSurvey_v1_JP. So those variables would just be a flattening issue.

**Comment by jacobmpeters** [comment]
I will look into the flattening issue for these for these variables and report back.

EATDRINKTIME 191057574
SLEEPTIME 299417266
WAKETIME 689861450
COV25 890156588
COV26 877074400

**Comment by jacobmpeters** [comment]
I generated a new query with any new variables present in the Connect.clinicalBioSurvey_v1 schema in prod. 

The FlatConnect.clinicalBioSurvey_v1_JP table now has these variables under the v2 concept_IDs.

> SELECT
>     D_191057574_V2, D_191057574,
>     D_299417266_V2, D_299417266,
>     D_689861450_V2, D_689861450,
>     D_890156588_V2, D_890156588,
>     D_877074400_V2, D_877074400
> FROM
>   `nih-nci-dceg-connect-prod-6d04.FlatConnect.clinicalBioSurvey_v1_JP`
> WHERE
>   Connect_ID='7593575667'

**Comment by FrogGirl1123** [comment]
@cusackjm I think now we have the data to try recreating the issue the participant was having.

**Comment by jacobmpeters** [comment]
Hmm.. @KELSEYDOWLING7 I'm not seeing the same issue. When I query that variable I see only time data in XX:XX format.. Let me know if you are still not seeing this on your end and we can discuss further.

SELECT D_191057574_V2 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.clinicalBioSurvey_v1_JP`

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters Huh, that's so odd. It was showing 0 yesterday afternoon but I do see a time now. 

@cusackjm Well that's one issue down

**Comment by cusackjm** [comment]
@KELSEYDOWLING7 What is the time?

**Comment by KELSEYDOWLING7** [comment]
@cusackjm  07:55

**Comment by cusackjm** [comment]
Unable to replicate this issue in Stage Testing under nciccctesting7@gmail.com. 

Discrepancies to note:
1. The participant table had COV25 (890156588)= 0 No, which doesn't make sense. If they selected 0 NO, they never would have gotten to COV27 to report their issue.
2. Given that, in testing, I entered COV25 (890156588)= 0 Yes, so I could get to COV26 (877074400), enter 4, and get to COV27. I had no issue entering dates at COV27
