### ISSUE TITLE
Generic text for blank text boxes

### ISSUE THREAD

**Issue by joshid-ims** [episphere/questionnaire#209]
If user does not enter any text in SrvPES_PHONE2_v1r0, SrvPES_TABLET2_v1r0, SrvPES_COMP2_v1r0, it appears as blank 

![image](https://user-images.githubusercontent.com/64986739/208685497-17801314-52c3-49dc-97d1-ecd52159ab19.png)

We need to have some generic test there to display if text does not exist.

**Comment by cusackjm** [comment]
Is this similar to how MHGROUP8 looks in Module 1?

**Comment by cusackjm** [comment]
https://github.com/episphere/questionnaire/issues/86

**Comment by joshid-ims** [comment]
It is more like if address details are not present we display Current Address or something in Module 4. 

Something to display if the piped in value is blank from the text box.

**Comment by cusackjm** [comment]
I have added pipe text directions for if someone selects the "other" option but does not enter anything in the textbox.
