### ISSUE TITLE
[METFOR4] was able to submit “0” years in text box 

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#21]

**Comment by cusackjm** [comment]
issue still open 3/11 testing

**Comment by joshid-ims** [comment]
Should min value be changed to 1?

**Comment by joshid-ims** [comment]
@cusackjm @boyd-mj What do I do here? Change min value to 1 instead of 0?

**Comment by cusackjm** [comment]
@joshid-ims hi yes the min should be 1

**Comment by joshid-ims** [comment]
Made change. Testing at our end.

**Comment by cusackjm** [comment]
issue still present in testing 4/29/22
account: 609-576-3460
Connect ID: 9393372061

**Comment by boyd-mj** [comment]
Hi Julie, we haven't redelivered Module 2 yet so the issue will still occur during testing on the PWA

**Comment by boyd-mj** [comment]
This change has been completed on our end and will be included in the next delivery
