### ISSUE TITLE
CIG4=0 Response text is missing 

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#210]
![image](https://user-images.githubusercontent.com/85582895/210633136-3ae9d4f9-65ab-4204-8f59-800e75b9397e.png)
0 should be "No, not at all"

![image](https://user-images.githubusercontent.com/85582895/210633239-5eabcd83-b6f2-4770-9295-21fb3c708fd1.png)

**Comment by cusackjm** [comment]
Record: https://nih.box.com/s/nsqfnupkgsr5m7j8f8l2rl9975gr3ff3

**Comment by cusackjm** [comment]
=0 "No**, not at all"** 

the bolded response text is missing for CIG4, ECIG4, CIGAR4, CHEW4, HOOKAH4, PIPE4, SMMAR4, TOMAR4, ELMAR4, EAMAR4, THMAR4

**Comment by huip-ims** [comment]
@cusackjm Hi Julie - These changes have been made in the markup and have passed IMS internal testing. Jen or Rose should deliver the updated file shortly.

**Comment by cusackjm** [comment]
fixed in dev testing on 1/12/23 https://nih.box.com/s/8iqjuljhs5jaxpz8o9xtn6r4znb8zn4m
