### ISSUE TITLE
Selecting multiple choice responses with text boxes

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#211]
To select a multiple-choice response with the textbox, the participant has to click outside of the text box (the highlighted part)
![image](https://user-images.githubusercontent.com/85582895/210840369-d0129949-eed1-4f29-aa75-4675d1e47cc9.png)

The response is not selected if the participant clicks inside the text box.

Functionality to allow the response to be selected by clicking anywhere on the response

**Comment by danielruss** [comment]
@cusackjm @anthonypetersen @Davinkjohnson --  Quest is updated.  If the user types in the box, the button is select.  If the user deletes what they typed, the button is unselected.  The user can select the button and leave the box empty.    If the user types something in the box, unselects the box, and reselects the box,  the text will re-appear.

**Comment by cusackjm** [comment]
confirmed fixed in stage
