### ISSUE TITLE
updates to BSNSSTYP1 and BSNSSTYP2 responses

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#212]
changing SOCcer categories

**Comment by cusackjm** [comment]
DCEG and IMS documents have changes denoted in tracked changes. DD in GitHub also is updated.
![image](https://user-images.githubusercontent.com/85582895/218546881-d72de0ed-1793-4def-adb5-a86c1eee5d4b.png)

**Comment by boyd-mj** [comment]
@cusackjm we delivered these changes on 2/14.

**Comment by cusackjm** [comment]
confirmed fixed in dev testing on 5/24/23: https://nih.app.box.com/file/1221349527219
