### ISSUE TITLE
selectionCount should not count 77 as response

### ISSUE THREAD

**Issue by joshid-ims** [episphere/questionnaire#213]
Currently, if user selects 77(don't know) as a response, it is counted by sectionCount function. As per requirement of Cancer Prevention Experience survey, it should not be counted. The requirement stated in the document is:

[DISPLAY SrvPES_MOSTUSE_v1r0 IF MORE THAN 1 RESPONSE IS SELECTED FROM SrvPES_PHONE2_v1r0, SrvPES_TABLET2_v1r0, SrvPES_COMP2_v1r0,  

IF ONLY 1 RESPONSE SELECTED OR ([SrvPES_PHONE2_v1r0= 77 OR NR] AND [SrvPES_TABLET2_v1r0= 77 OR NR] AND [SrvPES_COMP2_v1r0= 77 OR NR]) GO TO SrvPES_OWNER_v1r0]

**Comment by joshid-ims** [comment]
@danielruss any update on this?

**Comment by danielruss** [comment]
on it.

**Comment by joshid-ims** [comment]
Thanks!

**Comment by danielruss** [comment]
Bug fix in.  Please test with episphere.github.io/quest before I make a release.

**Comment by joshid-ims** [comment]
The question is being shown even when I selected one option and 2 Don't Knows(77). The count should be just 1 and not >1. 

![image](https://user-images.githubusercontent.com/64986739/216097082-605ce0f6-95ea-49a1-89cf-35322e9ef959.png)

**Comment by danielruss** [comment]
where is the questionnaire

**Comment by joshid-ims** [comment]
This is the question  

[SRVPES_PESINTRO_V1R0] <b>Connect for Cancer Prevention Experience Survey</b>

The following questions are designed to help us understand your experience as a participant in the Connect for Cancer Prevention Study. We will use the information you share to improve the study. 

We value the information you share with us and will always protect your privacy. We remove information that can be used to identify you, like your name, from your survey answers before we share them with researchers. You may skip any question you do not feel comfortable answering.

[SRVPES_DEVICE_V1R0?] <b>MyConnect</b>

Which types of devices do you use for MyConnect? Select all that apply.
[0] Phone
[1] Tablet
[2] Laptop or desktop computer
<#NR -> SRVPES_OWNER_V1R0> 

[SRVPES_PHONE2_V1R0?,displayif=equals(SRVPES_DEVICE_V1R0,0)] Which type of <b>phone</b> do you use? Select all that apply.
[0] iPhone (Apple)
[1] Android 
[55] Other phone, please describe |__|id=SRVPES_PHONE2OTH_V1R0|
[77*] Don’t know

[SRVPES_TABLET2_V1R0?,displayif=equals(SRVPES_DEVICE_V1R0,1)] Which type of <b>tablet</b> do you use? Select all that apply.
[0] iPad (Apple)
[1] Microsoft® Surface
[2] Amazon Fire Tablet
[3] Google Pixel
[4] Samsung Galaxy
[5] Lenovo Tab
[55] Other tablet, please describe |__|id=SRVPES_TABLET2OTH_V1R0| 
[77*] Don’t know

[SRVPES_COMP2_V1R0?,displayif=equals(SRVPES_DEVICE_V1R0,2)] Which type of <b>laptop or desktop compute</b>r do you use? Select all that apply.
[0] Mac (Apple)
[1] PC (Windows)
[2] Chromebook
[55] Other computer, please describe |__|id=SRVPES_COMP2OTH_V1R0|
[77*] Don’t know


[SRVPES_MOSTUSE_V1R0?,displayif=selectionCount("SRVPES_PHONE2_V1R0") + selectionCount("SRVPES_TABLET2_V1R0") + selectionCount("SRVPES_COMP2_V1R0")>1]Which device do you use to access MyConnect most of the time? 
(0,displayif=equals(SRVPES_PHONE2_V1R0,0)) iPhone (Apple) 
(1,displayif=equals(SRVPES_PHONE2_V1R0,1)) Android 
(2,displayif=equals(SRVPES_PHONE2_V1R0,55)) {$SRVPES_PHONE2OTH_V1R0} |displayif=doesNotExist("SRVPES_PHONE2OTH_V1R0")|Other phone|
(3,displayif=equals(SRVPES_TABLET2_V1R0,0)) iPad (Apple)
(4,displayif=equals(SRVPES_TABLET2_V1R0,1)) Microsoft® Surface 
(5,displayif=equals(SRVPES_TABLET2_V1R0,2)) Amazon Fire Tablet 
(6,displayif=equals(SRVPES_TABLET2_V1R0,3)) Google Pixel 
(7,displayif=equals(SRVPES_TABLET2_V1R0,4)) Samsung Galaxy 
(8,displayif=equals(SRVPES_TABLET2_V1R0,5)) Lenovo Tab 
(9,displayif=equals(SRVPES_TABLET2_V1R0,55)) {$SRVPES_TABLET2OTH_V1R0} |displayif=doesNotExist("SRVPES_TABLET2OTH_V1R0")|Other tablet| 
(10,displayif=equals(SRVPES_COMP2_V1R0,0)) Mac (Apple) 
(11,displayif=equals(SRVPES_COMP2_V1R0,1)) PC (Windows) 
(12,displayif=equals(SRVPES_COMP2_V1R0,2)) Chromebook 
(13,displayif=equals(SRVPES_COMP2_V1R0,55)) {$SRVPES_COMP2OTH_V1R0} |displayif=doesNotExist("SRVPES_COMP2OTH_V1R0")|Other computer|

[END] end

**Comment by danielruss** [comment]
ok,  I did not handle the case where you had Other: <textbox> 

You can use `|__|` (1-line input `<input type="text">`) but not `|___|`  (multiline input `<textarea>`)

on episphere.github.io/quest

**Comment by danielruss** [comment]
This is a test questionnaire.

```
[Q1] lala
[1] one
[2] two
[3] three |__|
[4*] NONE OF THE ABOVE

[Q2] |displayif=selectionCount('Q1')>0 |<p>You chose Something!!! </p><hr>| Hi
```

**Comment by cusackjm** [comment]
is this still an issue?

**Comment by cunnaneaq** [comment]
Not sure who's best to confirm that this issue is resolved, @danielruss do you know?

**Comment by danielruss** [comment]
I can test with the original question.  One sec.

**Comment by danielruss** [comment]
I modified the module to remove some of the unneeded displayifs, but the logic is the same.

In Q1: The user selects 0 or more from Phone, tablet, computer
If the user selects phone ==> which type of phone
if the user selects tablet  ==> which type of tablet
if the user selects computer  ==> which type of computer

If the user made any selection, a list of those selections are listed for the user to select. If the user selected nothing or just one item, the user skips this question.

END...

The module works as expected.  Please close.

```
[SRVPES_PESINTRO_V1R0] Connect for Cancer Prevention Experience Survey

The following questions are designed to help us understand your experience as a participant in the Connect for Cancer Prevention Study. We will use the information you share to improve the study.

We value the information you share with us and will always protect your privacy. We remove information that can be used to identify you, like your name, from your survey answers before we share them with researchers. You may skip any question you do not feel comfortable answering.

[SRVPES_DEVICE_V1R0?] MyConnect

Which types of devices do you use for MyConnect? Select all that apply.
[0] Phone -> SRVPES_PHONE2_V1R0
[1] Tablet -> SRVPES_TABLET2_V1R0
[2] Laptop or desktop computer -> SRVPES_COMP2_V1R0
< -> SRVPES_MOSTUSE_V1R0>

[SRVPES_PHONE2_V1R0?] Which type of phone do you use? Select all that apply.
[0] iPhone (Apple)
[1] Android
[55] Other phone, please describe |__|id=SRVPES_PHONE2OTH_V1R0|
[77*] Don’t know

[SRVPES_TABLET2_V1R0?,displayif=equals(SRVPES_DEVICE_V1R0,1)] Which type of tablet do you use? Select all that apply.
[0] iPad (Apple)
[1] Microsoft® Surface
[2] Amazon Fire Tablet
[3] Google Pixel
[4] Samsung Galaxy
[5] Lenovo Tab
[55] Other tablet, please describe |__|id=SRVPES_TABLET2OTH_V1R0|
[77*] Don’t know

[SRVPES_COMP2_V1R0?,displayif=equals(SRVPES_DEVICE_V1R0,2)] Which type of laptop or desktop computer do you use? Select all that apply.
[0] Mac (Apple)
[1] PC (Windows)
[2] Chromebook
[55] Other computer, please describe |__|id=SRVPES_COMP2OTH_V1R0|
[77*] Don’t know

[SRVPES_MOSTUSE_V1R0?,displayif=selectionCount("SRVPES_PHONE2_V1R0") + selectionCount("SRVPES_TABLET2_V1R0") + selectionCount("SRVPES_COMP2_V1R0")>1]Which device do you use to access MyConnect most of the time?
(0,displayif=equals(SRVPES_PHONE2_V1R0,0)) iPhone (Apple)
(1,displayif=equals(SRVPES_PHONE2_V1R0,1)) Android
(2,displayif=equals(SRVPES_PHONE2_V1R0,55)) {$SRVPES_PHONE2OTH_V1R0} |displayif=doesNotExist("SRVPES_PHONE2OTH_V1R0")|Other phone|
(3,displayif=equals(SRVPES_TABLET2_V1R0,0)) iPad (Apple)
(4,displayif=equals(SRVPES_TABLET2_V1R0,1)) Microsoft® Surface
(5,displayif=equals(SRVPES_TABLET2_V1R0,2)) Amazon Fire Tablet
(6,displayif=equals(SRVPES_TABLET2_V1R0,3)) Google Pixel
(7,displayif=equals(SRVPES_TABLET2_V1R0,4)) Samsung Galaxy
(8,displayif=equals(SRVPES_TABLET2_V1R0,5)) Lenovo Tab
(9,displayif=equals(SRVPES_TABLET2_V1R0,55)) {$SRVPES_TABLET2OTH_V1R0} |displayif=doesNotExist("SRVPES_TABLET2OTH_V1R0")|Other tablet|
(10,displayif=equals(SRVPES_COMP2_V1R0,0)) Mac (Apple)
(11,displayif=equals(SRVPES_COMP2_V1R0,1)) PC (Windows)
(12,displayif=equals(SRVPES_COMP2_V1R0,2)) Chromebook
(13,displayif=equals(SRVPES_COMP2_V1R0,55)) {$SRVPES_COMP2OTH_V1R0} |displayif=doesNotExist("SRVPES_COMP2OTH_V1R0")|Other computer|

[END] end
```

**Comment by woodruffr** [comment]
What about the 77 counting as one of the three? Also, this issue should stay open until Dev testing has confirmed it is fixed.

**Comment by woodruffr** [comment]
Dev and Stage testing has been completed for this Survey.
