### ISSUE TITLE
Mock Survey for CID_V2 testing

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#215]
_V2 issue identified on 2/6/23: If a participant stops taking a survey before submitting, and the question that the participant leaves off on has its CID versioned (_V2), when the participant tries to re-enter the survey they get stuck on a blank page.

The mock surveys were created to replicate this issue, as well as investigate other scenarios that could also lead to a blank page.

**Comment by cusackjm** [comment]
IMS Mock Surveys: https://nih.app.box.com/folder/194837457808
DCEG Mock Surveys and Test Scenarios: https://nih.app.box.com/folder/194654830110

**Comment by boyd-mj** [comment]
Hi @cusackjm ,

Do you need us to code/test both versions 1 & 2? 

Thanks,
Jen

**Comment by cusackjm** [comment]
@boyd-mj yes. The testing involves starting version 1 of the Mock survey, stopping somewhere in the survey (where we stop depends on what scenario we are testing), pushing version 2 of the mock survey (COV27's CID will be versioned to 715581797_V2), and then going back in the survey to see what happens on the PWA display and what the backend data looks like

**Comment by boyd-mj** [comment]
Gotcha, that makes sense! I missed a little of the explanation of how you would be testing this on the call. Thanks!
