### ISSUE TITLE
Adding sentence to DRINKSWTR1, DRINKSWTR2A-F question text

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#216]
Question text updated for DRINKSWTR1, DRINKSWTR2A-F

DCEG qx doc: https://nih.app.box.com/file/1123103520312
IMS qx doc: https://nih.app.box.com/file/1123099028107

DD is updated

**Comment by boyd-mj** [comment]
This update has been made. We are waiting for the new JSON to do a final check before delivery.

**Comment by cusackjm** [comment]
CONFIRMED FIXED IN DEV TESTING ON 5/24/23: https://nih.app.box.com/file/1221349527219
