### ISSUE TITLE
Remove COVID-19 questions from Blood/Urine Survey (Clinical Collection Survey)

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#218]
Edits involved:
1. COVID-19 section questions removed from survey
2. Edited skip logic for [SrvBlU_REPROINTRO_v1r0] and [SrvBlU_CONTRACEPT_v1r0]

DCEG document (edits in tracked changes): https://nih.app.box.com/file/1147389108199
IMS document (edits in tracked changes): https://nih.app.box.com/file/1147389895619

@FrogGirl1123 @woodruffr, just want to confirm DD edits before I make them, the COVID-19 variables should be denoted as deprecated?

**Comment by cusackjm** [comment]
Questions deprecated from DD on 2/23/2023

**Comment by cusackjm** [comment]
@boyd-mj @joshid-ims  what is the status of this

**Comment by woodruffr** [comment]
It is waiting for the new JSON to be reviewed so that we can test it with a transformed mark-up.

**Comment by cusackjm** [comment]
confirmed fix in dev testing on 5/24/23: https://nih.app.box.com/file/1221352677758
