### ISSUE TITLE
New Survey Ready for Programming - Cancer Screening History

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#223]
IRB Approved Survey ready for programming

DCEG Qx Doc: https://nih.app.box.com/file/1117993558597
IMS Qx Doc: https://nih.app.box.com/file/1189006521721 

This is NOT in the DD or question types document. I will update this issue once those documents are updated

**Comment by woodruffr** [comment]
Hi Julie,

I believe we changed out procedures to include a review with a coder (Deepti), and a documentation person (me) before work is begun. Would you like to do this with a meeting or via email?

**Comment by cusackjm** [comment]
@woodruffr Lets set up a call. I will email you my availability

**Comment by cusackjm** [comment]
Survey is in question types document

**Comment by woodruffr** [comment]
As Deepti's comment came across my desk, I saw a grammatical error. In SrvScr_SKIN_v1r0 "wore" should be "worn" because the configuration is "**may have** removed your clothing and **worn**.

**Comment by joshid-ims** [comment]
Is this a typo? Should it go to END?


97.	[SrvScr_MULTISCREEN_v1r0] Multi-Cancer Screening Tests
Have you ever had any of these tests to check for multiple-types of cancers? Select all that 	apply.
[NOTE TO PROGRAMMERS: IF 88 IS SELECTED, DE-SELECT ALL OTHER RESPONSES]
0	[SrvScr_MCED_v1r0] Multi-cancer early detection (MCED) Test
Also known as a liquid biopsy. MCED tests (for example, GRAIL’s Galleri ™ 	test) are blood tests that measure biological signals in body fluids that may be 	shed by cancer cells.
1	[SrvScr_FBODMRI_v1r0] Full body MRI or CT
An MRI (Magnetic Resonance Imaging) or CT (CAT scan) of your body. Detailed pictures of the inside of your body were taken while you were laying down in an MRI or CT machine.  
88	[SrvScr_NOMULTISCREEN_v1r0] I have not had any of these screening tests -	**-> GO TO SrvScr_MULTISCREEN_v1r0**
NO RESPONSE --> GO TO END

**Comment by cusackjm** [comment]
@joshid-ims yes, i will update the documents

**Comment by joshid-ims** [comment]
The document needs to be updated for all names in all options for Select All that Apply type of questions to be same for 88* to work.

**Comment by cusackjm** [comment]
@joshid-ims like harmonizing the 88 variable names to [SrvScr_NOSCREEN_v1r0] ?

**Comment by woodruffr** [comment]
This is a straight forward Select All that Applies. Although the Mark-up uses the Source Question and the responses connect from the Data Dictionary to the Mark-up by the numbers, each question needs a Variable Name in the Data Dictionary. @joshid-ims please look at the Blood, Urine, and Mouthwash mark-up SRVBIO_SYMPTDAY_V1R0. On the mark-up, the Variable Names do not get included in the responses, only the Question gets a Variable Name.

**Comment by woodruffr** [comment]
The 88* will harmonize if you remove the Variable Names from the responses.

**Comment by joshid-ims** [comment]
I meant they all need to be same as question variable. Currently they are like:

[SRVSCR_COLSCREEN_V1R0?] <b>Colon and Rectal Cancer Screening</b>
Have you <b>ever</b> had any of these tests or procedures for colorectal cancer or other medical conditions? Select all that apply. 

[0:SRVSCR_COL_V1R0] <b>Colonoscopy</b>
Before the procedure, it is likely that a medicine was given through a needle in your arm to make you sleepy. A healthcare provider used a long tube-like instrument to examine your colon and check for cancer or other problems. Someone else needed to drive you home. 
[1:SRVSCR_CTCOL_V1R0] <b>CT Colonoscopy</b>
Also known as a “virtual” colonoscopy or CT colonography, a special CAT scan of the lower part of your colon that made detailed pictures of your colon to see if there were colon polyps or cancer. Your body passed through a large tunnel-shaped X-ray machine.
[2:SRVSCR_SIG_V1R0]<b> Sigmoidoscopy </b>
Also known as flexible sigmoidoscopy. You were awake and not given medicine to make you sleepy. A healthcare provider used a short tube-like instrument to examine the lower part of your colon and check for cancer or other problems. You were probably able to drive yourself home.
[3:SRVSCR_PROCT_V1R0] <b>Proctoscopy</b>
Also known as a rigid sigmoidoscopy. You were awake and not given medicine to make you sleepy. A healthcare provider used a thin, tube-like instrument with a light and a lens to examine the inside of your rectum and check for cancer or other problems. You were probably able to drive yourself home. This test is rarely used now and was more commonly used in the past.
[4:SRVSCR_STOOL_V1R0] <b>Stool (fecal) test </b>
A test for blood or abnormal DNA in your stool. This test is sometimes called a fecal occult blood test (a FOBT), or a fecal immunochemical test (FIT), a Stool DNA Test (Cologuard®). These tests should be done at home and the sample is mailed in.
[88*:SRVSCR_NOCOLSCREEN_V1R0] I have <b>not</b> had any of these screening tests -> SRVSCR_ANALSCREEN_V1R0
<#NR -> SRVSCR_ANALSCREEN_V1R0>

**Comment by woodruffr** [comment]
Please remove all Variable Names from the responses. It should be formatted like this:
[SRVBIO_SYMPTDAY_V1R0?] Did you have any of the following symptoms in the 24 hours before you donated your samples? Select all that apply.
[0] Cough
[1] Diarrhea
[2] Stuffy nose (also known as nasal congestion)
[3] Feeling sick to your stomach or throwing up
[4] Fever
[88*] No, I had none of these symptoms

**Comment by cusackjm** [comment]
will they have variable names in the DD? I am confused by this DD formatting.

We have not had questions with long descriptions, but we do have ones with partial bolding. The only new aspect of these responses is that we would like the responses to be on a new line, rather than being on the same line

**Comment by joshid-ims** [comment]
I think that can be done in code by adding a new line character.

**Comment by woodruffr** [comment]
Standard Select All That Apply questions in the Mark-up have the Source Question Name as the D_ (Question Name) and the responses just have numbers. In the Mark-up, the Question uses the CID/Variable Name of the Source Question (which is the same for all responses). The Mark-up's response text is the CID/Question text in the data dictionary.  Our transformation software uses the DD "Connect Value for Select all that apply questions - Surveys only" value to link the Mark-up number to the correct response CID. The response Variable Names don't get used in the Mark-up, but are the Variable Names that go with the Question Text field in the DD.

**Comment by cusackjm** [comment]
ok so to clairfy, I am just deleting the yellow-highlighted text in the questionnaire documents? 
![image](https://github.com/episphere/questionnaire/assets/85582895/444bff08-0f43-4e85-b084-b3a66997f30a)

**Comment by woodruffr** [comment]
Hi Julie,

Thanks. Aminat is reviewing the JSON to compare the changes to those we were expecting. Since it has been three months, it will probably take a while. I'm out this afternoon. So we will not start reviewing the data dictionary until tomorrow or Thursday. 

In Biospecimens, the Variable Names were left in the questionnaire document. In previous Modules, the Quest IDs were not included in Select All That Apply responses. There is benefit to having them in the questionnaire, but originally the questionnaire was to be as close to the mark-up as possible. Let's discuss whether the questionnaire should have Variable Names in Select All That Apply responses on tomorrow's call.

**Comment by cusackjm** [comment]
@woodruffr the variables are removed from the select all that apply responses

**Comment by woodruffr** [comment]
I believe all updates have been made and the only outstanding issue is the AGE and SEX not getting accessed appropriately in the transformed mark-up.  https://github.com/episphere/quest/issues/422

**Comment by guinevere83** [comment]
Alright this has passed internal review and should be delivered soon.

**Comment by woodruffr** [comment]
This has been delivered.

**Comment by cunnaneaq** [comment]
These updates were delivered 7/19/2023 - 2024 CSH survey changes be tracked elsewhere
