### ISSUE TITLE
Couple of issues in Cancer screening history survey

### ISSUE THREAD

**Issue by joshid-ims** [episphere/questionnaire#231]
1. For Question:

 [SrvScr_SKIN1_v1r0] When you had a visual skin examination, how much of your body was
screened for skin cancer? Select all that apply.
0 I have had a specific spot on my body screened for skin cancer --> GO TO
SrvScr_UPENDO_v1r0
1 I have had part of my body screened for skin cancer --> GO TO
SrvScr_UPENDO_v1r0
2 I have had a full body skin examination to screen for skin cancer --> GO TO
SrvScr_SKIN2_v1r0
77 Don’t know --> GO TO SrvScr_UPENDO_v1r0

I am not sure if it is supposed to be a select all question. If it is, then we need to correct the go to logic for all options. It is not working correctly if multiple options are selected. 

2. For question:
 
[SrvScr_ANALSCREEN_v1r0] Anal Cancer Screening
Have you ever had an anal screening test to look for anal cancer or other medical conditions?
During an anal screening test, you were lying on your side or bending over an exam table. A
healthcare provider inserted a swab (which looks like a long Q-tip) into your anus to collect a
small amount of cells. The cells were checked for the type of HPV that can lead to anal cancer.

Should "ever" be bolded like all other questions?

**Comment by cusackjm** [comment]
SKIN1 is meant to be a select all that apply question. If SKIN1= 2 is selected, they go to SKIN2. If SKIN1= 2 is not selected, they go to UPENDO.

yes, ever should be bolded

**Comment by joshid-ims** [comment]
@cusackjm, For SRVSCR_CERVSCREEN_V1R0, the 77 in the code should be a 2. Can you please make that change? I am going to go ahead and change it in the markup.

**Comment by cusackjm** [comment]
updated to 2 in the questionnaire documents
