### ISSUE TITLE
NovaVax (COV28 = 4) not listed in Summary (COV29)

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#232]
COV29 (Vaccine summary) did not display COV28 = 4 NovaVax in the summary. The new response was correctly shown in COV28. Please add this new response to the summary.

**Comment by cusackjm** [comment]
@joshid-ims  what is the status of this?

**Comment by boyd-mj** [comment]
@cusackjm this is fixed and awaiting redelivery once the other issues are resolved

**Comment by cusackjm** [comment]
confirmed fix in dev testing on 6/29/23
