### ISSUE TITLE
"Other" textbox Response piped into COV29 summary has extra spaces

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#235]
Please remove the extra space around the textbox response piped in COV29

![image](https://github.com/episphere/questionnaire/assets/85582895/1b668b47-4316-430e-9871-875db3d81011)

**Comment by joshid-ims** [comment]
There are no spaces to remove here:

[SRVCOV_COV29_V1R0,displayif=greaterThanOrEqual(SRVCOV_COV26_V1R0,#loop)] Here's a summary of the information you shared about your COVID-19 vaccinations. If any of the information is incorrect, please select the "Back" button to update your responses. If all the information is correct, please select the "Next" button to move forward.

Vaccination number: #loop
Vaccination date: {$SRVCOV_COV27_MY_V2R0}
COVID-19 vaccine shot: |displayif=equals(SRVCOV_COV28_V1R0,0)| Moderna||displayif=equals(SRVCOV_COV28_V1R0,1)| Pfizer||displayif=equals(SRVCOV_COV28_V1R0,2)| Johnson & Johnson||displayif=equals(SRVCOV_COV28_V1R0,3)| AstraZeneca||displayif=equals(SRVCOV_COV28_V1R0,4)| Novavax||displayif=equals(SRVCOV_COV28_V1R0,55)| Other (**{$SRVCOV_COV28DESC_V1R0})**||displayif=equals(SRVCOV_COV28_V1R0,77)| Don't know|

**Comment by joshid-ims** [comment]
@danielruss - could this be renderer issue?

**Comment by cusackjm** [comment]
@danielruss please see Deepti's comment/what is the status of this?

**Comment by danielruss** [comment]
@cusackjm what is the problem? the space between the parenthesis and the "E" of essential oils?

**Comment by cusackjm** [comment]
Yes, can it be displayed as (essential oils) instead of ( essential oils )

**Comment by danielruss** [comment]
[Stage definitely has spaces that can be removed](https://github.com/episphere/questionnaire/blob/b7d963bb8cd64d9c465f1690f31ea4d1e4c38d33/moduleCOVID19Stage.txt#L377C279-L377C303)

and so does [prod](https://github.com/episphere/questionnaire/blob/b7d963bb8cd64d9c465f1690f31ea4d1e4c38d33/prod/moduleCOVID19.txt#L377C279-L377C303)

**Comment by joshid-ims** [comment]
Vaccination date: {$SRVCOV_COV27_MY_V2R0}
COVID-19 vaccine shot: |displayif=equals(SRVCOV_COV28_V1R0,0)| Moderna||displayif=equals(SRVCOV_COV28_V1R0,1)| Pfizer||displayif=equals(SRVCOV_COV28_V1R0,2)| Johnson & Johnson||displayif=equals(SRVCOV_COV28_V1R0,3)| AstraZeneca||displayif=equals(SRVCOV_COV28_V1R0,4)| Novavax||displayif=equals(SRVCOV_COV28_V1R0,55)| **Other ({$SRVCOV_COV28DESC_V1R0})|**|displayif=equals(SRVCOV_COV28_V1R0,77)| Don't know|

Not sure where the spaces are.

**Comment by cusackjm** [comment]
confirmed fix in dev testing
