### ISSUE TITLE
"Other" textbox Response NOT piped into COVSUMMARY

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#236]
I entered "hair loss" in the 55 Other textbox for COV8_3 (third time in COVID infection loop) and only "Other" was piped into COVSUMMARY. 

Please add the textbox response saved in SrvCov_COV8S_OTH_v1r0 to the summary. 
Should be: Other (hair loss)

**Comment by joshid-ims** [comment]
@danielruss Can text box value be piped into displaylist? For e.g.:

|displayList(valueIsOneOf("SRVCOV_COV8_V1R0",0),"Fever",valueIsOneOf("SRVCOV_COV8_V1R0",1),"Body chills (feeling cold, shivering)",valueIsOneOf("SRVCOV_COV8_V1R0",55),"Other",sep="; ")

**Comment by danielruss** [comment]
😒 Not designed to do that....  If this a requirement you absolutely need, let me know.

**Comment by cusackjm** [comment]
@danielruss yes please :)

Also related to this: https://github.com/episphere/questionnaire/issues/235

**Comment by danielruss** [comment]
🎆 🎆 🎆 🎆 🎆  Woot Woot... I was wrong...  It can do it.... 🎆 🎆 🎆 🎆 🎆 

```
[N3] Name: |__|id="name"|

[Q4] 
Do you have loss of taste or smell
(0:lts) No 
(1:lts) Yes

Do you have appetite changes
(0:ac) No 
(1:ac) Yes 

Are you feeling generally more tired than you used to feel
(0:tired) No 
(1:tired) Yes 

[Q5] summary:

Symptoms: |displayList(exists("N3"),"name: ",exists("N3"),"N3",valueEquals("Q4.lts",1),"loss of taste or smell",valueEquals('Q4.ac',1),"appetite change",valueEquals('Q4.tired',1),"generally more tired than you used to feel",sep="; ")|
[END] bye
```
<img width="431" alt="image" src="https://github.com/episphere/questionnaire/assets/3767675/bdbaec2b-8f17-4241-9a18-35081f2786a2">

**Comment by joshid-ims** [comment]
But how to pipe for such text box:

(55) Other |__|id=SRVCOV_COV28DESC_V1R0|

**Comment by joshid-ims** [comment]
Now with value for Other it is displaying like this because of ; separator:

![image](https://github.com/episphere/questionnaire/assets/64986739/9aa57550-c385-42e2-bc4c-bbd4457481d3)

and if there is no value for Other it is:

![image](https://github.com/episphere/questionnaire/assets/64986739/c2c3a7ae-5a58-4ee5-9d33-db9470d495e8)

@cusackjm  is this acceptable?

**Comment by cusackjm** [comment]
@joshid-ims No, Can it be presented as:

"Symptoms: Other" if the textbox is null 

"Symptoms: hair loss" if "hair loss" is entered in the textbox? If not, "Symptoms: Other: hair loss" is ok too

**Comment by guinevere83** [comment]
We've made those updates and the issue has passed internal testing. We should deliver soon.

**Comment by cusackjm** [comment]
confirmed fix in dev testing on 6/29/23
