### ISSUE TITLE
Edit COVIDINTRO text

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#237]
Delete first sentence in COVIDINTRO text. Denoted in tracked changes:
![image](https://github.com/episphere/questionnaire/assets/85582895/a2995544-ba40-4cf2-95f4-c0df749540fc)

IMS and DCEG documents have been updated. 
DD and Question Types Document updates not required (Change involves introduction text)

**Comment by cusackjm** [comment]
@joshid-ims what is the status of this?

**Comment by boyd-mj** [comment]
@cusackjm this issue is fixed and awaiting redelivery

**Comment by cusackjm** [comment]
confirmed fix in dev testing 6/29/23
