### ISSUE TITLE
Stuck on Page (trying to NR)

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#238]
@danielruss 
Testing in Stage using Chrome on PC laptop. Stuck on HYGIENE and seeing this console error:
![image](https://github.com/episphere/questionnaire/assets/85582895/46418a6e-230f-4f58-9fb5-a674d730a6b3)
![image](https://github.com/episphere/questionnaire/assets/85582895/a2a18813-b1fb-4027-801f-4c69ac4d1d0f)

Entered the following:
![image](https://github.com/episphere/questionnaire/assets/85582895/9f3fd1d2-d4d8-45dc-a445-256b27c24a57)

Issue was not identified in Dev, but I did test this scenario using the Edge Browser (unsure if this makes a difference)

**Comment by danielruss** [comment]
This was labeled COVID-19 Survey, but it appears to be biospecimen.

**Comment by cusackjm** [comment]
sorry wrong tag

**Comment by danielruss** [comment]
Ran using local quest on my mac and https://github.com/episphere/questionnaire/blob/main/moduleBiospecimenStage.txt 
worked fine....
Will Try with Edge ... in about an hour.

**Comment by danielruss** [comment]
@joshid-ims. I think the problem is caused [by line 153 of the module](https://github.com/episphere/questionnaire/blob/main/moduleBiospecimenStage.txt#L153).

```
[D_479143504?] Next, we have a few questions about your oral health and routine that will help us better understand your mouthwash (saliva) sample.

In the last <b>month</b>, which of these oral hygiene products have you used? Select all that apply.

[203919683]	Toothbrush -> D_498984275
[807884576]	Floss -> D_205713835
[165596977]	Water-based flosser or pick/jet -> D_353467497
[578402172]	Tongue Cleaner or Scraper -> D_429994023
[184513726]	Teeth-whiteners (strips, etc.) -> D_499977481
[390351864]	Mouthwash -> D_406270109
<-> D_899251483_V2>
```

I don't believe there is a question `D_899251483_V2`. Can you check that we are not suppose to jump to question `D_899251483_2` 

`<-> D_899251483_2>`

**Comment by cusackjm** [comment]
@danielruss @joshid-ims D_899251483_V2 is SrvMtW_PERMTTHLOST_v2r0

**Comment by danielruss** [comment]
@cusackjm That question does not exist in the module I think you are referring to [the following question:](https://github.com/episphere/questionnaire/blob/main/moduleBiospecimenStage.txt#L279C1-L284C18)

```
[D_899251483_2?] Have you lost any of your permanent adult teeth, not including tooth crowns or your wisdom teeth? Select all that apply. 
[812107266]	Yes, from accident or injury -> D_724589244
[452438775]	Yes, from tooth decay or disease -> D_957305523
[886864375] Yes, for some other reason -> D_360678252
[551489317*]  No
 ```

Maybe the "V" in "_V2" is missing?

**Comment by cusackjm** [comment]
@danielruss yes, I just updated the markdown and will see if that fixed it

**Comment by cusackjm** [comment]
![image](https://github.com/episphere/questionnaire/assets/85582895/4cca2f52-4580-432f-93d6-48e54e998135)
Still saw this trying to skip the question. I was able to move to the next question by selecting "toothbrush" but after clicking back I got stuck on a blank screen. Upon refreshing the page, it took e back to the dashboard and I was able to get back to the survey then

**Comment by cusackjm** [comment]
I tested this scenario in a new account and it passed

**Comment by danielruss** [comment]
🎆
