### ISSUE TITLE
Issue with text box responses & skip logic

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#240]
*tested in chrome, on PC laptop*

If I click inside the textbox for a 55 Other |_|_| response and enter text, the follow up question does not appear.
This occurred for COV19C6A (I entered hair loss) and I did not see COV19C6B. I went back and clicked the multiple choice response and then clicked the textbox, entered hair loss and correctly saw COV19C6B.

The same thing happened at COV28, except the issue pertained to the response not piping into COV29 (the covid vax summary).

@danielruss Is this a QUEST issue?

**Comment by cusackjm** [comment]
In Module 2, if a participant selects the textbox in the 55 “other” response (without clicking the 55 multiple choice response) and does not select any other responses in that question, they will not see the follow-up questions. 
•	If text entered at ESTROHOR= 55 textbox, participant does not see ESTROHOR2, ESTROHOR3, ESTROHOR4, ESTROHOR5
•	If text entered at PROGHOR= 55 textbox, participant does not see PROGHOR2, PROGHOR3, PROGHOR4, PROGHOR5, PREGHOR6_2
•	If text entered at COMBHOR= 55 textbox, participant does not see COMBHOR2, COMBHOR3, COMBHOR4, COMBHOR5, SEPHOR2

The issue does not pertain to textboxes that have information piped in questions that have other questions before them. For example, I haven’t observed an issue with COV8S’s textbox entry being piped into COVSUMMARY (as there are other questions between the COV8 grid and COVSUMMARY). 

This appears to only be an issue for textboxes in 55 other responses (Multiple Choice and Select All That Apply question types). Text Box only questions that pipe text into the next question are working (e.g., name entered in SIBNAME is correctly piping into SIB2, which is the question right after SIBNAME).

**Comment by danielruss** [comment]
@cusackjm   What questions are you talking about?  I see a PROGHOR5_1 in module2, but there is no textbox same with estrohor.

**Comment by danielruss** [comment]
@cusackjm  I assume you are referring to question D_668834883.  

This is not a quest bug, but a coding bug.  It took awhile to figure it out.  There is a lot of module here...

```
[D_668834883?] Have you ever taken any of these types of <b>estrogen-only (unopposed estrogen) prescription hormones</b>? Select all that apply.
[246843973|oralEst] Oral estrogen-only medication (such as Cenestin®, Estrace®, Femtrace®, Menest®, Ogen®, or Premarin®)
[854184254|patchEst] Patch estrogen-only medication (such as Estraderm®, Alora®, or Climara®)
[515434780|ring] Vaginal ring (Femring®), vaginal cream (Estrace®), or vaginal tablet (Vagifem®) estrogen-only medication
[674148137|estSkin] Estrogen-only skin gel, cream, or spray-on medication (such as Divigel®, Elestrin®, or EstroGel®)
[807835037|other] Any other type of estrogen-only medication: Please describe |__|id=D_640559281|
[535003378*] None of the above
< #NR -> D_800943768 >
```

Assuming you answer this question WITH ONLY "an other" the coder wants the next question to be:

```
[D_872509317?,displayif=equals(D_668834883,807835037)]
How old were you when you first used |displayif=doesNotEqual(D_640559281,"")|<b>{$D_640559281}</b>||displayif=equals(D_640559281,"")|the other type of estrogen-only medication|?

Age |__|__|min=0 max=sum(isDefined(D_150344905,age),1)|
```

**This does not work!**  As I have mentioned before displayif's are dangerous toys and should be avoided if not needed.  I HIGHLY recommend the following notation:

```
[D_668834883?] Have you ever taken any of these types of <b>estrogen-only (unopposed estrogen) prescription hormones</b>? Select all that apply.  
[246843973|oralEst] Oral estrogen-only medication (such as Cenestin®, Estrace®, Femtrace®, Menest®, Ogen®, or Premarin®) -> D_856627601 
[854184254|patchEst] Patch estrogen-only medication (such as Estraderm®, Alora®, or Climara®) -> D_800943768
[515434780|ring] Vaginal ring (Femring®), vaginal cream (Estrace®), or vaginal tablet (Vagifem®) estrogen-only medication -> D_263785082
[674148137|estSkin] Estrogen-only skin gel, cream, or spray-on medication (such as Divigel®, Elestrin®, or EstroGel®)
[807835037|other] Any other type of estrogen-only medication: Please describe |__|id=D_640559281| ->D_XXXXX
[535003378*] None of the above
<  -> D_800943768 >
```

you will need to change the follow up question also.  I can help the module coder.

Since I highly doubt they will change it.  The quick fix is to change to

```
[D_872509317?,displayif=valueIsOneOf("D_668834883",807835037) or valueLength("D_640559281")>0]
How old were you when you first used |displayif=valueLength("D_640559281")>0|<b>{$D_640559281}</b>||displayif=valueLength("D_640559281")==0|the other type of estrogen-only medication|?

Age |__|__|min=0 max=valueOrDefault("D_150344905","age",1)|
```

Explanation:
There are 2 conditions that must be handled.

1. The user select other, but does not type in the box.  -- In this case, the valueIsOneOf detects that the other button was selected *BUT NO "OTHER" was typed*.
2. the user types in the box (and other is autoselected) in this case there is a value in "other"

The data is stored differently in these cases.  NOTE: every followup question also needs to change.  Please re-assign IMS and take QUEST ISSUE and me off

**Comment by cusackjm** [comment]
@boyd-mj @joshid-ims @huip-ims please review the above, @danielruss is going to go over this and issue #233 on the call today

**Comment by cusackjm** [comment]
@joshid-ims what is the status of this?

**Comment by guinevere83** [comment]
This passed internal testing and will be ready for delivery soon.

**Comment by woodruffr** [comment]
The updated Module 2 file has been delivered to https://app.box.com/folder/216811897791.

**Comment by cusackjm** [comment]
Thanks! what is the status of this for the COVID survey?

**Comment by woodruffr** [comment]
Deepti needed to change the Variable Name Versions so this is still in process.

**Comment by cusackjm** [comment]
@boyd-mj confirmed fix in Module 2 dev testing on 7/19/23

**Comment by cusackjm** [comment]
confirmed fixed in dev testing 7/24/2023
