### ISSUE TITLE
Remove extra space between PREG title and intro text

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#245]
*low priority later problem, can be address the next time module 2 markup is updated for a medium/high priority issue*

![image](https://github.com/episphere/questionnaire/assets/85582895/be37ecbb-e9e2-4a50-a9f4-db0cb81e277b)

**Comment by cusackjm** [comment]
(It appears to have 2 lines in between the title and intro text)

For example, FERT has 1 line and looks better 
![image](https://github.com/episphere/questionnaire/assets/85582895/2de5cfc1-de0c-485c-8286-3d3149a69b7b)

**Comment by guinevere83** [comment]
This has passed internal testing and will be delivered soon.

**Comment by cusackjm** [comment]
confirmed fix in dev testing on 11/3/2023
