### ISSUE TITLE
remove programming note from WORK4

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#248]
Remove programming note "[JOB FROM WORK3]" in WORK4
![image](https://github.com/episphere/questionnaire/assets/85582895/0394921e-e002-4bda-b52c-1ae482b6d9aa)
(I can remove the note in the qx document from inside the question text if needed)
![image](https://github.com/episphere/questionnaire/assets/85582895/06f5e1e4-3d60-4cd3-a7b0-4af77045d93c)

WORK4 should look like WORK8
![image](https://github.com/episphere/questionnaire/assets/85582895/ec4c38a1-32e4-4b47-8c13-4fbc5bb90675)

**Comment by guinevere83** [comment]
This has passed internal testing and is ready to deliver.

**Comment by cusackjm** [comment]
confirmed fix in dev testing on 11/15/2023
