### ISSUE TITLE
Formatting issue for [SITTING], [SLHABIT1], and [HOUSE1] in various browser sizes

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#25]
[SITTING] question and responses are on different pages, shouldn’t these be on same page?  

[SITTING] responses also have weird format if screen is smaller. With small screen, I am getting a soft error for missing a response, but I have put all the responses in. The formatting in the larger screen also looks weird, with text squished. 

Issue also occurs for [HOUSE1] and [SLHABIT1] 

Example smaller screen: 
![image](https://user-images.githubusercontent.com/85582895/126840295-2e684aca-81bd-4989-9037-a454340be1d2.png)
Example with larger screen:
![image](https://user-images.githubusercontent.com/85582895/126840369-ac9c8479-e8c5-40c4-957e-1f297b40bde0.png)

**Comment by boyd-mj** [comment]
@Davinkjohnson & @naiyume this may be a Quest issue?

**Comment by Davinkjohnson** [comment]
This will require further testing and updates from Brian, Daniel, and the Quest collaborators.

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/157914069-6a8d0ec6-689b-439e-98b8-8878ea2a6e47.png)
3/11 screen when making the screen smaller.

**Comment by danielruss** [comment]
@Davinkjohnson Can you give me a minimal module that contains this (i.e. A simple question before, the grid, end)?  Also, please surround the text with 3 back ticks (key to the left of 1, 3 before and 3 after, not on the same line). This is tells the chat that code, not markdown follows.

```

**Comment by naiyume** [comment]
@cunnaneaq @cusackjm This should be addressed on the PWA now.
