### ISSUE TITLE
Put LAWN heading on same screen as LAWN1

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#251]
![image](https://github.com/episphere/questionnaire/assets/85582895/d19a306c-b3be-4f0a-a61f-b09e491e68fa)
![image](https://github.com/episphere/questionnaire/assets/85582895/993f28fc-6156-44c1-bc10-6c3dad7921b0)

**Comment by guinevere83** [comment]
This has passed internal testing and will be delivered soon.

**Comment by cusackjm** [comment]
@guinevere83 please do not deliver anything until all issues have been delivered for the next prod push. As mentioned on the IMS call yesterday, the next prod push is Jan. 2024. The deadline for DCEG to submit issues for that prod push is Oct 1., issues will be programmed and delivered in one delivery, to reduce the number of deliveries/testing sessions for both IMS and DCEG.
@boyd-mj @woodruffr

**Comment by cusackjm** [comment]
Confirmed fix in dev testing on 11/1/2023
