### ISSUE TITLE
Remove extra space between WEIGHT question text and response

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#253]
Remove extra space between WEIGHT question text and response
![image](https://github.com/episphere/questionnaire/assets/85582895/984117f9-59be-42ec-8071-04ce385eb8ca)

format should look like HEIGHTFEET:
![image](https://github.com/episphere/questionnaire/assets/85582895/11952d32-6457-44eb-8786-b1efae23caf1)

**Comment by huip-ims** [comment]
@cusackjm Julie - Currently, for WEIGHT, there's a line break added in the markdown code between the question text and text box. This displays correctly if the participant is a male (SEX=1).
![image](https://github.com/episphere/questionnaire/assets/82978291/b583bf44-b12c-47ae-8e70-903c4f02917e)

However, if participant is female or intersex (SEX=0 or 2), then this results in the extra lines between the question text and text box, as you have shown above. We can't control this spacing issue when there may be additional text to display depending on the sex of participant. It will display correctly for 1 sex but not for others. This is similar to WEIGHT3Y that you addressed in Github #254.

One option to try is to remove the current line break in place, but the results may not be ideal for all sexes. See below.
SEX=1:
![image](https://github.com/episphere/questionnaire/assets/82978291/b6ff4156-1ea5-4872-8ee0-c4445a203328)

SEX=0 or 2:
![image](https://github.com/episphere/questionnaire/assets/82978291/f05566d4-2fb0-47a1-bbe0-aa9a3c3ef377)

Do you prefer the option with line break (currently in use) or the 2nd option without line break?

**Comment by cusackjm** [comment]
Hi! The 2nd option we currently have is preferred, thanks!

**Comment by huip-ims** [comment]
@cusackjm Julie - We currently have the 1st option in place (i.e., with line break). Did you want to instead use the 2nd option, without line break? Please confirm if you prefer with or without line break.

**Comment by cusackjm** [comment]
Sorry  I read that wrong. The current 1st option (no change), with the line break
