### ISSUE TITLE
Put ALCLIFE2 on same screen as ALCLIFE2A-H GRID

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#256]
![image](https://github.com/episphere/questionnaire/assets/85582895/8f688e76-025f-4899-876c-4540cb7dbc86)
![image](https://github.com/episphere/questionnaire/assets/85582895/aabc29ce-75f5-498b-b1f5-f329942e01af)

**Comment by joshid-ims** [comment]
Issues in grid are because of the roll back as per Daniel

**Comment by cusackjm** [comment]
@joshid-ims will it be possible to address by the Jan prod push?

**Comment by joshid-ims** [comment]
We are waiting for updates on quest to be put on Production where we test. All grid issues were caused by the roll back as per Daniel.

**Comment by cusackjm** [comment]
@joshid-ims could you coordinate with @danielruss to determine what needs to be updated in quest so you can work on this edit?

**Comment by joshid-ims** [comment]
ALCLIFE4 grid just does not display. So not sure what needs to be changed. Similarly. House2 grid in Module 2 also does not display.

**Comment by danielruss** [comment]
@joshid-ims I'll look at it today.

**Comment by cusackjm** [comment]
confirmed fixed in dev testing on 1/31/2024
