### ISSUE TITLE
Headings and intro descriptions on separate screens

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#26]
“Medications” header and INTROMED are on separate pages and should be on same one 
Same error for “Physical Activity” header and [INTROPA] 
Same error for “Sleep” and [SLEEPINTRO]

**Comment by Davinkjohnson** [comment]
@boyd-mj 

To resolve this, see the as-is/to-be for markup:

<b>As-is</b>
[SECTION3]\<b\>Physical Activity\<\/b\>

[INTROPA]
Next, we will ask you about different types of physical activities. We are interested in activities that you do during a usual day, including at work or around the house. We are also interested in activities that you do specifically for exercise or for fun.

Many of the questions in this section ask you to share the amount of time you spend doing specific activities. If you are not sure of the exact amount of time, please make your best guess.

<b>To-be</b>
[SECTION3]\<b\>Physical Activity\<\/b\>

Next, we will ask you about different types of physical activities. We are interested in activities that you do during a usual day, including at work or around the house. We are also interested in activities that you do specifically for exercise or for fun.

Many of the questions in this section ask you to share the amount of time you spend doing specific activities. If you are not sure of the exact amount of time, please make your best guess.

**Comment by joshid-ims** [comment]
This change is not reflected in the Word document on Box. We will need to remove Quest IDs INTROMED, INTROPA and SLEEPINTRO from the document.

**Comment by freedmanne** [comment]
hi, yes I agree with this change.
best,
Neal

**Comment by boyd-mj** [comment]
@joshid-ims to make these changes. Assigning back to IMS.

**Comment by boyd-mj** [comment]
These changes have been made and will be included in the next delivery

**Comment by cusackjm** [comment]
changes made to box documents
