### ISSUE TITLE
Put COV19 intro text on same screen as COV19A1-6

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#274]
COV19 and COV19A grid
COV23 and COV23A grid 
Put Grid ID/Source question on same screen as questions/responses 
![image](https://github.com/episphere/questionnaire/assets/85582895/e58b4223-ca5e-4941-a7fb-9c3439a66831)
![image](https://github.com/episphere/questionnaire/assets/85582895/e629630b-3ee8-408c-ab44-b3706b60ff23)

**Comment by cusackjm** [comment]
Made the following edits to the questionnaire document so the question is not there twice.
![image](https://github.com/episphere/questionnaire/assets/85582895/12cac745-2fc2-42a1-86b0-e91ff609f2e2)
![image](https://github.com/episphere/questionnaire/assets/85582895/772ca9d3-629a-428a-aafa-42ea6704b36c)

**Comment by jeannewu** [comment]
@cusackjm may you tell me what I should check in the data? What data should I check, dev, prod, stage?

**Comment by cusackjm** [comment]
confirmed fix in dev testing on 11/1/2023

**Comment by cusackjm** [comment]
confirmed fix in stage testing on 11/1/2023
