### ISSUE TITLE
Changing min range check for CIGLIFEA-H, CIGARLIFEA-H, PIPELIFEA-H, TOMARLIFEA-H, EAMARLIFEA-H, THMARLIFEA-H

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#277]
currently min= 1, change to min= 0

**Comment by cusackjm** [comment]
Added to range checks document: https://nih.app.box.com/file/869524081027?s=hznm7f2wjvenx7cguh7tu1l4iy00onip

waiting for nicole's feedback to see if this should be documented in the questionnaire documents and/or the DD

**Comment by cusackjm** [comment]
CS0010598

**Comment by cusackjm** [comment]
DCEG Questionnaire Document is updated.

Will add note to DD once IMS questionnaire document is updated/issue is submitted to IMS for programming

**Comment by cusackjm** [comment]
do you have an eta for this? 

(I will be OOO 12/4-12/15 and Aileen is taking over testing)

**Comment by joshid-ims** [comment]
Ready to be delivered with other issues.

**Comment by cusackjm** [comment]
Passed dev testing using Chrome, PC on 12/28/2023 
Template: https://nih.app.box.com/file/1401074464603

(Keeping open until it passes backend Stage testing)
