### ISSUE TITLE
add new response to ECIGLIFEA-H, CHEWLIFEA-H, HOOKAHLIFEA-H, SMMARLIFEA-H, ELMARLIFEA-H

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#278]
o	Didn’t use e-cigarettes or other vaping devices for nicotine or tobacco during this time
o	Didn’t use chewing tobacco, snus, snuff, or dip during this time
o	Didn’t smoke a hookah or water pipe during this time
o	Didn’t smoke marijuana during this time
o	Didn’t use electronic marijuana delivery devices during this time

**Comment by cusackjm** [comment]
CS0010598

**Comment by cusackjm** [comment]
do you have an eta for this? 

(I will be OOO 12/4-12/15 and Aileen is taking over testing)

**Comment by joshid-ims** [comment]
Ready to be delivered with other issues.

**Comment by cusackjm** [comment]
Passed dev testing using Chrome, PC on 12/28/2023 
Template: https://nih.app.box.com/file/1401074464603

(Keeping open until it passes backend Stage testing)
