### ISSUE TITLE
Mod 1 SOCcer updates

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#279]
**for January prod push**
Added new questions WORK3B and WORK7B (task questions that contribute to SOCcer calculation of OCCUPTN1 and OCCUPTN2 responses).
By adding WORK3B and WORK7B, the skip logic following WORK3 and WORK7 is updated.

Also changed OCCUPTN1 and OCCUPTN2 so that 6 responses are populated instead of 4.

this requires both QUEST SOCcer edits (@danielruss) and markdown edits for skip logic and question (@boyd-mj )

**Comment by danielruss** [comment]
@cusackjm what is text for the questions [WORK3B] and [WORK7B].

**Comment by cusackjm** [comment]
Module 1: https://nih.app.box.com/file/1110365640829?s=tx97ibzzl02wyd90vhbq6i2lquk6j03u

"What are your main tasks and activities in this job? Please be descriptive. For example, constructed residential homes, drove patients from home to medical visits, provided assistance to elementary school students with special needs."

**Comment by cusackjm** [comment]
DCEG: https://nih.app.box.com/file/1110365640829?s=tx97ibzzl02wyd90vhbq6i2lquk6j03u
IMS: https://nih.app.box.com/file/923659410218?s=aw8cjazz6dnoh2kdbkno0rcyso3fije2
DD: updates made

**Comment by woodruffr** [comment]
The data dictionary updates were reviewed and are as expected.

**Comment by cusackjm** [comment]
confirmed WORK3B and WORK7B were added in dev testing on 11/15/2023

@danielruss only 4 responses are being piped into OCCUPTN1 and OCCUPTN2 (should be 6 responses), can you update this?

**Comment by cusackjm** [comment]
@danielruss if I skip WORK3/WORK7 and enter info at WORK3B/WORK7B, OCCUPTN1/2 does not provide a relevant occupation category. Instead it provides the categories that I believe were default for when we did not have WORK3B/WORK7B and WORK3/WORK7 was skipped: 
![image](https://github.com/episphere/questionnaire/assets/85582895/e6cf4554-e074-4e0e-ba9b-36c026f2fdbb)

**Comment by danielruss** [comment]
@cusackjm   This needs to be fixed in the PWA.  I am happy to make the changes, but we need to bring @anthonypetersen  in on this.

**Comment by anthonypetersen** [comment]
PWA Development Work needed:

* update event listener to listen for submission of WORK3B / WORK7B
* grab information from WORK3 / WORK7 within event listener functionality
* pass all information to SOCcer, along with parameter for `n` which we want to be 6

**Comment by anthonypetersen** [comment]
@cusackjm Do we have the markdown for these updates yet? I won't be able to test PWA changes until the markdown is in the Questionnaire repo.

**Comment by cusackjm** [comment]
@anthonypetersen yes its in dev/stage

**Comment by anthonypetersen** [comment]
PWA updates have been pushed to dev

**Comment by cusackjm** [comment]
confirmed fix in dev testing on 1/11/2024 on chrome laptop
