### ISSUE TITLE
Concept ID for SIBNAME/SIB2

### ISSUE THREAD

**Issue by boyd-mj** [episphere/questionnaire#28]
Please see question concerning concept ID decision for SIBNAME and SIB2 in Module 1

From: "Boyd-Morin, Jennifer (IMS)" <Boyd-MorinJ@imsweb.com>
Date: Tuesday, December 14, 2021 at 4:45 PM
To: "Natarajan, Madhuri (NIH/NCI) [C]" <madhuri.natarajan@nih.gov>, "Gerlanc, Nicole (NIH/NCI) [E]" <nicole.gerlanc@nih.gov>, "Shen, Brian (NIH/NCI) [C]" <brian.shen@nih.gov>, "Johnson, Davin (NIH/NCI) [C]" <davin.johnson@nih.gov>
Cc: "Snyder, Kirk (IMS)" <SnyderK@imsweb.com>, "Cusack, Julie (NIH/NCI) [C]" <julie.cusack@nih.gov>
Subject: [EXTERNAL] New 'Deliverables' folder on Box/M2 DD Change for SIB2

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

Hi everyone,

I’ve created the new ‘Deliverables’ folder on Box: https://app.box.com/folder/152164822116
The folder contains a change log, a readme file with some documentation of the decisions we made, an example folder that demonstrates the naming conventions we decided upon, and an archive folder. The latter currently contains the old ‘Concept ID Docs’ folder and can be used for future archivals as well.

Please let me know if you have any feedback or would like me to make any changes. In particular @Johnson, Davin (NIH/NCI) [C] could you make sure the naming conventions match what Nicole outlined in our meeting notes, and @Shen, Brian (NIH/NCI) [C] could you confirm that the underscores in the filenames won’t create any issues for your program?

Also, the attached document contains the suggested change for the question text for SIB2, highlighted in orange (row 998). This change is a result of the overlapping concept IDs between SIB2 & SIBNAME. @Natarajan, Madhuri (NIH/NCI) [C] could you please make this change when you get a chance?

@Gerlanc, Nicole (NIH/NCI) [E] in this case, I think we will want to correct the concept ID for SIBNAME in the CSV and ultimately the data dictionary, but I’m including the concept IDs that are assigned in the JSON/converted markup so you can review (the CSV/DD currently have 579563781 for both questions):

  "SIBNAME": {
    "isTextBox": true,
    "questionText": "Sibling 1-For your [oldest/next oldest] sibling, please create a nickname or share initials that we can use to refer to this sibling again in future surveys.",
    "conceptId": "**406098499**"

  "SIB2": {
    "questIds": {
      "0": {
        "conceptId": "536341288",
        "concept": "Female"
      },
      "1": {
        "conceptId": "654207589",
        "concept": "Male"
      },
      "2": {
        "conceptId": "576796184",
        "concept": "Intersex or other"
      },
      "77": {
        "conceptId": "178420302",
        "concept": "Unavailable/Unknown"
      }
    },
    **"questionText": "Sibling 1-For your [oldest/next oldest] sibling, please create a nickname or share initials that we can use to refer to this sibling again in future surveys.",
    "conceptId": "579563781"**
  }, 

Please let us know if you have any questions.

Thanks,
Jen

**Comment by cusackjm** [comment]
can we close this issue?

**Comment by boyd-mj** [comment]
Yep!
