### ISSUE TITLE
Added new response to MENSHIS7

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#281]
MENSHIS7= 7 (added after initial edits to MENSHIS section (https://github.com/episphere/questionnaire/issues/239)
![image](https://github.com/episphere/questionnaire/assets/85582895/b099b31f-04b0-41bd-ac36-6755cf459b84)

**Comment by woodruffr** [comment]
Hi Julie, the data dictionary edits for this are missing the Keep values for the non-updated responses.

**Comment by cusackjm** [comment]
confirmed edit in dev testing on 11/3/2023
