### ISSUE TITLE
Survey not loading for participants

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#283]
CS0012073- unable to click start 
- laptop windows 11 
- Chrome
- tried BOH and LAW (unsure if completed BOH, but if they couldn't access it, they shouldn't have been able to access the LAW anyways)

CS0012453
- Edge and Chrome
- no surveys are started in ServiceNow
- tried BOH

CS0012451
- ServiceNow says they started the BOH

CS0012458
- BOH will not load

@anthonypetersen @danielruss is this a QUEST issue?

**8/28 UPDATE**
CS0011523
- participant unable to access SSN survey (issue created for other SSN issue, NORC gave instructions for entering response, participant now unable to access SSN survey)

**Comment by cusackjm** [comment]
Survey was not loading, it took me multiple right clicks to inspect, but once the inspect drop down appeared, the page loaded. This is the error message in Stage. 
![image](https://github.com/episphere/questionnaire/assets/85582895/3feac89c-1a4d-4f2f-9567-80ea6c46bf2c)

**Comment by danielruss** [comment]
checking....

**Comment by danielruss** [comment]
@cusackjm When I run [module one in the quest dev application using the following production URL ](https://episphere.github.io/quest/#https://raw.githubusercontent.com/episphere/questionnaire/main/prod/module1.txt)  `https://raw.githubusercontent.com/episphere/questionnaire/main/prod/module1.txt`
I am able to immediately get the module.  The same is true when I run [module four in the quest dev app](https://episphere.github.io/quest/#https://raw.githubusercontent.com/episphere/questionnaire/main/prod/module4.txt)

@anthonypetersen  can you see if there is a problem with the PWA.

**Comment by danielruss** [comment]
Not sure where to go with this issue.  I don't think it is a quest error.

**Comment by cusackjm** [comment]
@anthonypetersen could it be a PWA problem?

**Comment by anthonypetersen** [comment]
it's possible, I'll be looking into this more today

**Comment by anthonypetersen** [comment]
Not sure how many of these tickets this will affect, but putting in changes today for upcoming prod release:

https://github.com/episphere/connect/issues/702

@cusackjm  this should prevent the issue you showed me this morning.
