### ISSUE TITLE
Make all range checks with "age", have 1 added

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#284]
The following document includes the range checks that just involve "age" and need to be revised to the "age+1" range check: https://nih.app.box.com/file/1294189386644

Qx Subcommittee made decision on 8/30/2023 to make age-based range checks consistent (currently some are based on age and some based on age+1 year)

**Comment by cusackjm** [comment]
Need to update the DD, will update this issue once the "Notes" range check and variable suffix (_v1r0 to _v1r1) are updated

**Comment by joshid-ims** [comment]
Only few Year ranges are updated? Is that intentional?

**Comment by cusackjm** [comment]
yes, not all of the year ranges were missing the 1 year buffer from the range check. we want to be consistent and have all range checks include the 1 year buffer

**Comment by joshid-ims** [comment]
Ok, thanks.

**Comment by joshid-ims** [comment]
For First blood transfusion year, the max is Current year. That cannot be changed. Is that right?

**Comment by cusackjm** [comment]
yes

**Comment by joshid-ims** [comment]
Then that needs to be removed from the file please.

**Comment by cusackjm** [comment]
confirmed fix in dev testing on 11/15/2023
