### ISSUE TITLE
SSN added introduction statement, revised question text, response text, response options, error messages, skip logic, and end messages

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#287]
Content changes under review **I will update this issue when they are ready for programming**
https://nih.app.box.com/file/772342375528?s=4ih3qinmaio8r4x5wt81doe32mncsv0n

**Comment by cusackjm** [comment]
DCEG Doc: https://nih.app.box.com/file/1348654605060
IMS Doc: https://nih.app.box.com/file/1348664783360

I will update this issue once the DD is updated

**Comment by danielruss** [comment]
@joshid-ims   There was no way to handle this in the current version.  So I had to update quest to allow the user to inform quest that another element was a confirmation element.  If you correct either of the elements, they have to validate.

Here is a SSCE that shows the new feature.


```
[H1] 
SSN Please: |SSN|id=lala confirm=lili|

SSN again: |SSN|id=lili|

[END]
Thats all folks
```

**Comment by danielruss** [comment]
The wiki is also updated.   https://github.com/episphere/quest/wiki#confirming-social-security-numbers

**Comment by joshid-ims** [comment]
Thanks Daniel!

**Comment by joshid-ims** [comment]
@cusackjm, do you want me to use any particular IDs for these? For whole SSN and also for last 4 digits.

**Comment by cusackjm** [comment]
No, we don't want the 2nd response to save. The 2nd response is just being used to confirm the participant entered the correct SSN

**Comment by joshid-ims** [comment]
Yes, but Daniel's code show it needs an ID.

**Comment by cusackjm** [comment]
@joshid-ims by id, do you mean cid or variable name (similar to intro text)?

**Comment by joshid-ims** [comment]
Like lala and lili in Daniel's code. 

[H1] 
SSN Please: |SSN|id=lala confirm=lili|

SSN again: |SSN|id=lili|

[END]
Thats all folks

**Comment by cusackjm** [comment]
so just changing lala and lili to something else in the markdown?

**Comment by joshid-ims** [comment]
Yes.

**Comment by danielruss** [comment]
@cusackjm Quest does not allow you to not save an input.  So if you want to confirm, you MUST have an id for it and it WILL make it into the final data.  The downstream analysis need to ignore it.  Although they may want to confirm that the two are equal.  Client side validation can be bypassed by sophisticated users trying to break the system.

**Comment by danielruss** [comment]
No not now, I'll look not saving anything that is used for confirmation.  It may change the markdown for IMS. @joshid-ims  We may have to change to something like

```
[H1]
SSN Please: |SSN|id=lala|

SSN again: |SSN|confirmFor=lala|

[END]
Thats all folks
```

Then I need some way to delete confirmFor from the data.   This may not work.

**Comment by joshid-ims** [comment]
ok, Please let me know when this is done/added.

**Comment by cusackjm** [comment]
@danielruss any update on this?

**Comment by danielruss** [comment]
@cusackjm  This fix will take longer to implement.

**Comment by cusackjm** [comment]
@danielruss that is ok, this survey can be separate from the batched 1/2024 prod push

**Comment by Davinkjohnson** [comment]
All of these comments are captured in the tracked document on Box. Closing this as a duplicate.
