### ISSUE TITLE
Add new response (77 Don't know) to RACEETH

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#289]
Added response 77 "Don't know" to RACEETH. 

DCEG: https://nih.app.box.com/file/1110365640829?s=tx97ibzzl02wyd90vhbq6i2lquk6j03u
IMS: https://nih.app.box.com/file/923659410218?s=aw8cjazz6dnoh2kdbkno0rcyso3fije2
DD: harmonized response added to DD
**Edit for January Prod Push**

**Comment by joshid-ims** [comment]
You would like 77 or 77*?

**Comment by cusackjm** [comment]
@joshid-ims is there a difference? We would like the harmonized Don't know response

**Comment by joshid-ims** [comment]
77* will remove all other selections.

**Comment by joshid-ims** [comment]
Ok thanks

**Comment by cusackjm** [comment]
confirmed fix in dev testing on 11/15/2023
