### ISSUE TITLE
Questions on Module 4 – COVID-related contents changes

### ISSUE THREAD

**Issue by huip-ims** [episphere/questionnaire#29]
> From: Cusack, Julie (NIH/NCI) [C] julie.cusack@nih.gov
Sent: Monday, November 15, 2021 6:55 PM
To: Gaudet, Mia (NIH/NCI) [E] mia.gaudet@nih.gov; Jones, Rena (NIH/NCI) [E] rena.jones@nih.gov; Gerlanc, Nicole (NIH/NCI) [E] nicole.gerlanc@nih.gov; Boyd-Morin, Jennifer (IMS) Boyd-MorinJ@imsweb.com
Cc: Freedman, Neal (NIH/NCI) [E] freedmanne@mail.nih.gov; Brotzman, Michelle (NIH/NCI) [E] michelle.brotzman@nih.gov; DePietro, Deanna (NIH/NCI) [C] deanna.depietro@nih.gov
Subject: RE: Module 4 content changes

Neal and I have been working to update module 4 to incorporate these changes.

We propose the following updates (in order of how they appear):
1. Delete A269 DAYSWORK from Module 1. This question is currently only answered by former pay workers and current workers for whom their current job was not their longest.
2. Add sentence to COMINTRO (commuting section introduction) in Module 4 to preface that we are asking about your commute prior to the pandemic.
3. Add 2 questions between COMINTRO and WORKRES
a. WORK19 “Did you work for pay in 2019, prior to the start of the COVID-19 Pandemic?” (Ask everyone). If Yes, participant is asked DAYSWORK. If no or no response (people that are not considered currently working for pay), skip to PREWORKRES.
b. DAYSWORK. Same question as was in Module 1, except that we removed “none” response and added “If you cannot remember, please give your best estimate” after the question.
4. Changed “Current Work Commute” heading to “Pre-Pandemic Work Commute”
5. Changed jargon to past tense in all questions under “Pre-Pandemic Work Commute”, i.e. Changed “do” and “does” to “did” and “commute” to “commuted”
6. Changed CURWORKMOS from “Of the past 12 months” to “How many months of the year”

See Module 4 (DCEG Draft) for the tracked changes.

Best,
Julie

Hi Julie,

IMS is in the process of updating the markdown code using the proposed changes listed in your email above and also in the Module 4 (DCEG Draft) Quex Word document on Box. However, I have a few questions.

You mentioned to change ‘jargon to past tense’. In the DCEG Draft, I noticed [INTROCURWORK] has ‘The next questions ask about the place where you work and your commute between work and home.’ and [CURWORKT1] has ‘What type(s) of transportation do you use to get to’. Should these be changed to ‘where you worked’ and ‘did you used to get to’?

At the beginning of Section 2 in the DCEG Draft, there a condition ‘IF WORK = 00 and WORK6 = 01 -> GO TO PREWORKRES AND ASK PREWORKRES – PREWORKT8’. This condition is now crossed out after the COVID-related content changes were added. Should we check for some type conditions before asking the previous job questions (PREWORKRES – PREWORKT8)?   FYI - [WORK] represents ‘currently work for pay’ and [WORK6} represents ‘ever worked for pay’.

Please let me know if anything is unclear.

Thanks,
Pete

**Comment by cusackjm** [comment]
1. Yes, these should be changed to ‘where you worked’ and ‘did you used to get to’
2. No, I dont think we need to check for conditions before asking the previous job questions as everyone will be asked at least the first question PREWORKRES. WORK2019 responses determine if someone is going to get the current work commute or skip to the previous work commute (PREWORKRES) (which everyone should see) 
![image](https://user-images.githubusercontent.com/85582895/148235874-3c8e663d-7fcd-43be-add9-9874c5aea29d.png)

**Comment by boyd-mj** [comment]
@huip-ims can this issue be closed?

**Comment by huip-ims** [comment]
@boyd-mj  Yes, I'll close the issue now.
