### ISSUE TITLE
trademark symbol ™ is listed as "TM"

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#293]
Include the trademark symbol ™, instead of TM in MWUSE= 2
![image](https://github.com/episphere/questionnaire/assets/85582895/2d1a7cc8-f9e6-4baa-8fb2-51f92b1865af)
It looks like one word in the PWA

**Comment by cusackjm** [comment]
this is same as bUM

**Comment by cusackjm** [comment]
Thanks @danielruss.

@boyd-mj @joshid-ims please see the above.

**Comment by woodruffr** [comment]
@cusackjm, Is this issue just for Mouthwash or is it also for the Clinical Research Blood/Urine/Mouthwash survey?

**Comment by joshid-ims** [comment]
@cusackjm, I suppose we need to make this change in Biospecimens (Blood/Urine/Mouthwash) survey too.

**Comment by cusackjm** [comment]
confirmed fix in Dev blood/urine/mouthwash Survey testing on 11/15/2023
