### ISSUE TITLE
Skip logic error, went to MWALCFREE after DENTURES

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#294]
I entered the following responses:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/cusackjm/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/cusackjm/AppData/Local/Temp/1/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/cusackjm/AppData/Local/Temp/1/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

ORALHLTH | 0 = Excellent
-- | --
MWBEFORE | 0 = No
RINSEBEFORE | 0 = No
GUMBEFORE | 0 = No
TOBACCOBEFORE | 0 = No
HYGIENE | Toothbrush   Floss   Water-based floss   Tongue Cleaner    Teeth-whiteners    Mouthwash
BRUSH2 | 44 = Never
FLOSS2 | 0 = Less than once per   week
WTRPICK2 | 1 = Once or twice per   week
TONGUE2 | 2 = Three to five times   per week
WHITE2 | 3 = Once per day
MWUSE | Alcohol-based Alcohol-free    Chlorhexidine    Fluoride mout   Peroxide mout   Cetylpyridinium   Mw for sensitive    Mw for dry mouth
MWALC | NO-RESPONSE
MWALCFREE | NO-RESPONSE
MWCHLOR | NO-RESPONSE
MWFLOURIDE | NO-RESPONSE
MWPEROX | NO-RESPONSE
MWCETYL | NO-RESPONSE
MWSENSITIVE | NO-RESPONSE
MWDRY | NO-RESPONSE
PERMTTHLOST | Accident   decay disease   other reason
TEETHLOSTAI | 0 = 1
TEETHLOSTD | 1 = 2 to 4
TEETHLOSTOTH | 2 = 5 to 9
DENTURES | Dental Bridge   Partial Denture   Full Denture   Dental Implants   Other

</body>

</html>

I should have gone to DENTALCLEAN after DENTURES, but went back to MWALCFREE.
Console screenshot:
![image](https://github.com/episphere/questionnaire/assets/85582895/51d61169-1eeb-4f0d-9650-58b2e97fdd82)

**Comment by cusackjm** [comment]
I clicked through MWALCFREE-MYDRY (still did not respond), then PERMTTHLOST-DENTURES and all of the subsequent responses were saved. after DENTURES it took me back to MWCHLOR (instead of MWALCFREE)

**Comment by cusackjm** [comment]
@danielruss is this a quest issue? tony is seeing the responses and doesn't think it is a pwa issue?

**Comment by Davinkjohnson** [comment]
@cusackjm @danielruss i just repeated the steps Julie mentioned above in the Quest renderer and experienced the same issue. So this is an issue within Quest, not the markup.

**Comment by danielruss** [comment]
@Davinkjohnson  If there is a problem with the markup, it will also appear in the quest dev tool.  Let me take a look.  One sec

**Comment by danielruss** [comment]
What module is this?

**Comment by cusackjm** [comment]
https://github.com/episphere/questionnaire/blob/main/moduleMouthwash.txt

**Comment by Davinkjohnson** [comment]
> @Davinkjohnson If there is a problem with the markup, it will also appear in the quest dev tool. Let me take a look. One sec

Maybe I used the wrong terminology? "the renderer" is what I said but what I meant was I loaded the entire module into the tool/app found here: https://episphere.github.io/quest

When testing with this tool and using the module, which Julie linked, I received the same results Julie mentioned. I updated my comment because I see that I mistyped my thought as "markup" but meant the issue isn't within the PWA. (since I replicated it in the dev tool.)

**Comment by danielruss** [comment]
Hi All,
This is a markup error:
https://github.com/episphere/questionnaire/blob/main/moduleMouthwash.txt#L112C1-L193C1

You want this to be:
```
[D_406270109?] In the last <b>month</b>, which of these mouthwash products have you used? Select all that apply. 


[950773275]     Alcohol-based mouthwash (such as Scope® or LISTERINE®) -> D_349659426
[762727133]     Alcohol-free mouthwash (such as LISTERINE® Zero) -> D_766370065
[877842367]     Chlorhexidine mouthwash (such as PeridexTM, PerioGard®, or Paroex®) -> D_520416570
[886771318]     Fluoride mouthwash (such as ACT®) -> D_921972241
[404389800]     Peroxide mouthwash (such as Colgate® Peroxyl® Mouth Sore Rinse) -> D_526973271
[463302301]     Cetylpyridinium chloride mouthwash (such as Crest® Pro-Health) -> D_460873842
[259744087]     Mouthwash for sensitive teeth (such as Sensodyne®) -> D_430060900
[523660949]     Mouthwash for dry mouth (such as biotène®) -> D_800752981


[D_349659426?] In the last <b>month</b>, how often did you use alcohol-based mouthwash (such as Scope® or LISTERINE®)?
(648960871)     Never
(693256778)     Less than once per week
(735330419)     Once or twice per week
(138332277)     Three to five times per week
(858624942)     Once per day
(850675416)     Two or more times per day

[D_766370065?] In the last <b>month</b>, how often did you use alcohol-free mouthwash (such as LISTERINE® Zero)?
(648960871)     Never
(693256778)     Less than once per week
(735330419)     Once or twice per week
(138332277)     Three to five times per week
(858624942)     Once per day
(850675416)     Two or more times per day

[D_520416570?] In the last <b>month</b>, how often did you use chlorhexidine mouthwash (such as PeridexTM, PerioGard®, or Paroex®)?
(648960871)     Never
(693256778)     Less than once per week
(735330419)     Once or twice per week
(138332277)     Three to five times per week
(858624942)     Once per day
(850675416)     Two or more times per day

[D_921972241?] In the last <b>month</b>, how often did you use fluoride mouthwash (such as ACT®)?
(648960871)     Never
(693256778)     Less than once per week
(735330419)     Once or twice per week
(138332277)     Three to five times per week
(858624942)     Once per day
(850675416)     Two or more times per day

[D_526973271?] In the last <b>month</b>, how often did you use peroxide mouthwash (such as Colgate® Peroxyl® Mouth Sore Rinse)?
(648960871)     Never
(693256778) Less than once per week
(735330419)     Once or twice per week
(138332277)     Three to five times per week
(858624942)     Once per day
(850675416)     Two or more times per day

[D_460873842?] In the last <b>month</b>, how often did you use cetylpyridinium chloride mouthwash (such as Crest® Pro- Health)?
(648960871)     Never
(693256778)     Less than once per week
(735330419)     Once or twice per week
(138332277)     Three to five times per week
(858624942)     Once per day
(850675416)     Two or more times per day

[D_430060900?] In the last <b>month</b>, how often did you use mouthwash for sensitive teeth (such as Sensodyne®)?
(648960871)     Never
(693256778)     Less than once per week
(735330419)     Once or twice per week
(138332277)     Three to five times per week
(858624942)     Once per day
(850675416)     Two or more times per day

[D_800752981?] In the last <b>month</b>, how often did you use mouthwash for dry mouth (such as biotène®)?
(648960871)     Never
(693256778)     Less than once per week
(735330419)     Once or twice per week
(138332277)     Three to five times per week
(858624942)     Once per day
(850675416)     Two or more times per day
```

**Comment by danielruss** [comment]
This issue is that No Response is adding questions to the question queue that are already present in the queue. So the questions are added twice.  The queue gets lost because it points to two place in the queue.
<img width="471" alt="image" src="https://github.com/episphere/questionnaire/assets/3767675/5776fc20-53e1-4084-b9c1-db9516919053">
This leads to unpredictable results.  I removed the #NR -> XXXX and also the unnecessary displayifs's.

**Comment by cusackjm** [comment]
@joshid-ims @boyd-mj please see the above markdown issue

**Comment by cusackjm** [comment]
confirmed fix in Dev testing on 10/26/23

**Comment by cusackjm** [comment]
This issue exists in Blood, Urine, Mouthwash survey

**Comment by cusackjm** [comment]
confirmed fix in blood/urine/Mtw Survey during Dev testing on 11/15/2023
