### ISSUE TITLE
Response text wrong for DENTURES= 0

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#295]
![image](https://github.com/episphere/questionnaire/assets/85582895/b395d092-ee47-48e4-ae94-71d9f6ecf6da)

On 4/10/2023, DENTURES= 0 was unharmonized in the DD from "No" to "No, I have no dentures or dental appliances". The DD notes that "no" (cid 104430631) is deprecated and "No, I have no dentures or dental appliances" (cid 371726159) is new, and both do not have prod push dates documented.

The Markdown currently has cid and response text that do not match (i.e. CID 371726159, but response text is "no). This the case for both the Mouthwash survey and Blood, Urine, Mouthwash survey markdowns.

The questionnaire documentation and markdowns need to be updated to have the correct response text.

**Comment by joshid-ims** [comment]
@cusackjm can you please update the document on Box.

**Comment by cusackjm** [comment]
@joshid-ims qx documents are updated

**Comment by cusackjm** [comment]
confirmed fix in dev testing on 10/26/2023

**Comment by woodruffr** [comment]
Hi Julie, I assume that this is also an issue for the Blood/Urine/Mouthwash Clinical survey?

**Comment by cusackjm** [comment]
no the clinical survey is only blood and urine

**Comment by cusackjm** [comment]
Response is still "No" in Blood/Urine/MtW testing in Dev on 11/15/2023

**Comment by cusackjm** [comment]
Issue identified in markdown: 
1. Response text was not updated to "No, I have no dentures or dental appliances."
2. CID= 371726159 corresponds to "No, I have no dentures or dental appliances." in "Mouthwash" Secondary Source. 
3. The CID= 167336253 corresponds to "No, I have no dentures or dental appliances." in the "Blood/Urine/Mouthwash" Secondary Source. **Should the response text for the same response be harmonized?**
![image](https://github.com/episphere/questionnaire/assets/85582895/06cc491c-2931-4fc7-a300-fa9e20379d93)

**Comment by woodruffr** [comment]
Hi Julie, The new response Variable Name is missing on the Questionnaire response for "No, I have no dentures or dental appliances." Please update it in the questionnaire so that Deepti can update it in the mark-up.
SrvMtW_DENTURES2_v1r0

![image](https://github.com/episphere/questionnaire/assets/81166095/5aefe1a5-a2b6-4558-adbc-96d025d33f9b)

**Comment by cusackjm** [comment]
@woodruffr hi I updated the questionnaire documents

**Comment by cusackjm** [comment]
@woodruffr The Blood/Urine/Mouthwash survey has this in Prod: 
![image](https://github.com/episphere/questionnaire/assets/85582895/f689beb9-cbb0-4276-971e-73d2b8bb79f0)

2 problems with The Blood/Urine/Mouthwash survey that is in Prod: the text is not updated and the CID corresponds to the CID for "No, I have no dentures or dental appliances" in the Mouthwash Secondary Source. 

I think we should update the DD to remove the period in the text i.e., Remove period from SrvMtW_DENTURES2_v1r0 Current Question Text in Blood/Urine/Mouthwash. Is this okay given the mismatch in the text and CIDs that are currently in prod? 

I also want to preface that I have no documentation on this edit being made, so I don't know which CID is the correct one, but conceptually think we should make whatever edit that allows us to have the text "No, I have no dentures or dental appliances" (without the period). I noticed the change when I was pulling CIDs from the DD and entering them in my testing template while testing the Mock Mouthwash Survey. I believe it was a change made when we unharmonized certain select all that apply responses and I must've missed the update.

**Comment by woodruffr** [comment]
Has the Mouthwash survey been released to Production with this? It is the Blood/Urine/Mouthwash that has the period. If we have data back with that but not with the CID in Mouthwash, then it might make sense to keep Bl/U/M with the period and CID and change MW. You are correct about it being one of the changes made to unharmonize the Question Text and Source Question. I believe it is your call on which response to keep. We will update the surveys to whatever you put into the Questionnaire documents and in the data dictionary.

**Comment by cusackjm** [comment]
@woodruffr the mouthwash survey is not in production yet, but they are aiming to push it on 11/29. I will keep the period instead and add that to the questionnaire documents, as it sounds like that impact the backend data structure the least

**Comment by cusackjm** [comment]
Gene is working on the new JSON

**Comment by cusackjm** [comment]
Confirmed fix in dev blood/urine/mouthwash survey testing on 11/24/2023
