### ISSUE TITLE
New Intro statement (SEXORIENTINTRO) and new responses added to SEXORIENT

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#296]
New Intro statement (SEXORIENTINTRO) added, updated skip logic from STYLE, and new responses added to SEXORIENT
![image](https://github.com/episphere/questionnaire/assets/85582895/10097d5f-5376-4d75-a55a-1f270e843c56)

questionnaire documents are updated. 
I will update this issue once the new responses are added to the DD

**Comment by cusackjm** [comment]
DD is updated

**Comment by woodruffr** [comment]
Some rows in the dd need to have Keep added. See attached.
[MasterSurveyComb_20220317 SEXORIENT(2).xlsx](https://github.com/episphere/questionnaire/files/13218633/MasterSurveyComb_20220317.SEXORIENT.2.xlsx)

**Comment by cusackjm** [comment]
hi I added them to the dd

**Comment by cusackjm** [comment]
confirmed fix in dev testing on 11/15/2023

**Comment by woodruffr** [comment]
Hi Julie the Keep was left off one Variable for this. The 99 = Declined. It did not affect the JSON, but should be fixed as it might affect future automated processes.
