### ISSUE TITLE
Revise MENSTPRD, MENST60, MENSTART question text

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#297]
Revise MENSTPRD, MENST60, MENSTART question text in Blood, Urine, Mtw and Blood Urine Surveys
![image](https://github.com/episphere/questionnaire/assets/85582895/3ac0ed92-4a38-41d5-a649-e902e63e70d6)

questionnaire documents are updated.
I will update this issue once the DD is updated

**Comment by cusackjm** [comment]
DD is updated

**Comment by woodruffr** [comment]
Hi Julie, The data dictionary and new JSON have V2, but the documents and this issue show V1.

**Comment by cusackjm** [comment]
Thanks Rose. I just updated the questionnaire documents

**Comment by cusackjm** [comment]
Blood, Urine passed dev testing on 11/15/2023, removing label

**Comment by cusackjm** [comment]
Blood, Urine, Mtw passed dev testing on 11/15/2023
