### ISSUE TITLE
Update CURWORKYR1 Text Box Values

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#30]
@cusackjm ,

Please update the Baseline Quex for Module 4 so that the text boxes are named CURWORKYR1_Month and CURWORKYR1_Year. 

> From: Gerlanc, Nicole (NIH/NCI) [E] <nicole.gerlanc@nih.gov> 
Sent: Tuesday, December 21, 2021 11:03 AM
To: Gaudet, Mia (NIH/NCI) [E] <mia.gaudet@nih.gov>; Woodruff, Rose (IMS) <WoodruffR@imsweb.com>; Cusack, Julie (NIH/NCI) [C] <julie.cusack@nih.gov>
Cc: Freedman, Neal (NIH/NCI) [E] <freedmanne@mail.nih.gov>; Brotzman, Michelle (NIH/NCI) [E] <michelle.brotzman@nih.gov>; Boyd-Morin, Jennifer (IMS) <Boyd-MorinJ@imsweb.com>
Subject: Re: Concept IDs in Biospecimen Questionnaires

Hi Rose,

Let’s keep the version that is in the data dictionary.

Thank you,
Nicole

From: "Gaudet, Mia (NIH/NCI) [E]" <mia.gaudet@nih.gov>
Date: Tuesday, December 21, 2021 at 10:32 AM
To: "Woodruff, Rose (IMS)" <WoodruffR@imsweb.com>, "Cusack, Julie (NIH/NCI) [C]" <julie.cusack@nih.gov>, "Gerlanc, Nicole (NIH/NCI) [E]" <nicole.gerlanc@nih.gov>
Cc: "Freedman, Neal (NIH/NCI) [E]" <freedmanne@mail.nih.gov>, "Brotzman, Michelle (NIH/NCI) [E]" <michelle.brotzman@nih.gov>, "Boyd-Morin, Jennifer (IMS)" <Boyd-MorinJ@imsweb.com>
Subject: RE: Concept IDs in Biospecimen Questionnaires

Rose – Julie is out until the new year.

@Gerlanc, Nicole (NIH/NCI) [E] – can you quickly respond to this question? It seems straightforward.

![image](https://user-images.githubusercontent.com/81166095/147147783-875ed129-85a9-4ddd-a4b6-cb1feefd78fc.png)

**Comment by cusackjm** [comment]
changes have been made to markdown

**Comment by woodruffr** [comment]
@cusackjm  The Quest ID  for year should be CURWORKYR1_Year. I note you left the "2" after the "CURWORKYR".

R50.R51.[CURWORKYR1] In what month and year did you startcommuting to [insert address from CURWORK1 –CURWORK3/this address]?(IOr, if it easier to remember your age, enter that here.)[CURWORKYR1_Month] |__|__| Month [CURWORKYR2_Year]

**Comment by woodruffr** [comment]
Hi @cusackjm,

Thank you for making that correction!
