### ISSUE TITLE
Punctuation is missing or has extra space before when text is not piped in

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#300]
(1) The question mark is missing for SITTING, if WORK= 0. Can you add the question mark at end?

![image](https://github.com/episphere/questionnaire/assets/85582895/1f68aa83-a76d-406f-8667-27214a696d57)
![image](https://github.com/episphere/questionnaire/assets/85582895/0b8c4cc3-46f4-4200-9750-80e5c1176e82)

(2) There is an extra space before the question mark in HOUSE1, if WORK= 0. Can you remove the extra space before the question mark?

![image](https://github.com/episphere/questionnaire/assets/85582895/9d7b71d3-df5a-4ab2-8b1c-735e13ada9a0)

![image](https://github.com/episphere/questionnaire/assets/85582895/afe5ac24-8e40-4be0-bcf4-b22e7ae1ffc6)

(EXAMPLE) LAWN1 is an example of how the punctuation should look if text is not piped in because WORK=1

![image](https://github.com/episphere/questionnaire/assets/85582895/2f767cfe-16a7-42b0-81aa-836015f87668)

**Comment by cusackjm** [comment]
(3) The question mark is also missing in SITTING if WORK= 1
![image](https://github.com/episphere/questionnaire/assets/85582895/16e861f1-c79a-4f03-81f3-83c9a19ece22)

**Comment by cusackjm** [comment]
do you have an eta for this? 

(I will be OOO 12/4-12/15 and Aileen is taking over testing)

**Comment by cusackjm** [comment]
Spacing issue still exists for LAWN4C if WORK=0

**Comment by joshid-ims** [comment]
Ok, will remove that.

**Comment by cusackjm** [comment]
confirmed fix in dev testing on 1/22/24
