### ISSUE TITLE
INTROSLESC1 Heading update, if SLEEPSCHA= 0 or Non-response

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#301]
If SLEEPSCHA= 1, the heading looks correct. But, if SLEEPSCHA= 0 or No-response, the heading is "Workdays/Usual Sleep Schedule" does not make sense:
![image](https://github.com/episphere/questionnaire/assets/85582895/1fb9fb52-9289-4adc-bb01-e95cf568c563)

I don't think this is a markdown error/typo, the questionnaire directions are not clear. So I updated the questionnaire document to clarify that if SLEEPSCHA= 0 or No-response, the heading is "Usual Sleep Schedule" 
![image](https://github.com/episphere/questionnaire/assets/85582895/7dfebffa-5deb-44d2-9445-c5fca71522ad)

**Comment by cusackjm** [comment]
do you have an eta for this? 

(I will be OOO 12/4-12/15 and Aileen is taking over testing)

**Comment by joshid-ims** [comment]
It is ready to be delivered with other Module 2 issues waiting for testing on updated quest.

**Comment by cusackjm** [comment]
confirmed fix in dev testing (laptop, chrome) on 1/4/2024 (https://nih.app.box.com/integrations/officeonline/openOfficeOnline?fileId=1405598519478&sharedAccessCode=)
