### ISSUE TITLE
Grid display in Dev - No boxes around responses and text in center, not left orientation

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#302]
Testing Blood/Urine Survey (clinical collection) in Dev and am seeing this:
![image](https://github.com/episphere/questionnaire/assets/85582895/f60e5d81-fbfa-4955-9dc1-57679aa93803)

@danielruss assuming this is related to the grid fixes (#299)? Going to test in stage to see if the display changes.

**Comment by joshid-ims** [comment]
I am not sure if it is related to https://github.com/episphere/questionnaire/issues/299.

**Comment by danielruss** [comment]
@cusackjm   fix pushed please check.

**Comment by cusackjm** [comment]
The multiple choice responses are centered too (Module 1, Dev) @danielruss 
![image](https://github.com/episphere/questionnaire/assets/85582895/9043a4a5-bff1-464a-a3a4-895a19f25015)

**Comment by danielruss** [comment]
Sorry, I don;t understand.  They are not centered. Also, where they always that big?

**Comment by danielruss** [comment]
<img width="662" alt="image" src="https://github.com/episphere/questionnaire/assets/3767675/02abce06-54a8-494d-87fd-ad69e8ecb203">

**Comment by danielruss** [comment]
OH WAIT are the suppose to be on the left????

**Comment by danielruss** [comment]
@cusackjm  now left justified.

**Comment by cusackjm** [comment]
@danielruss theyre on the left, but is it possible to have them indented slightly like before? :)
![image](https://github.com/episphere/questionnaire/assets/85582895/9c5371c1-a62a-4601-b28f-1ef755063560)
![image](https://github.com/episphere/questionnaire/assets/85582895/94f6a259-1b19-4ee1-83cc-9eaab6b526fd)

**Comment by danielruss** [comment]
Can you do a quick test.  I think you may have beat me to all my changes.

<img width="501" alt="image" src="https://github.com/episphere/questionnaire/assets/3767675/a7d000e7-63bd-4531-ac6b-414c4e14a9bc">

**Comment by cusackjm** [comment]
it still looks the same in dev

**Comment by danielruss** [comment]
are you looking at the pwa?

**Comment by cusackjm** [comment]
yes, should i look in the renderer instead?

**Comment by cusackjm** [comment]
@danielruss @anthonypetersen do you have an eta on this?

**Comment by danielruss** [comment]
@cusackjm The dev tool is no longer centered and has a border (admittedly the same color as the background).  I assume you mean the PWA.  I'll release the latest version of quest and you should see the updates.

**Comment by cusackjm** [comment]
@danielruss Testing BUM in Stage, using Safari and iPad: the MED1 questions are formatted as a Grid.
![image](https://github.com/episphere/questionnaire/assets/85582895/c6e4b0c0-130b-4407-a111-304aec9b0eb1)

 On a laptop, they are formatted as multiple choice questions. Is this related to this issue?

**Comment by danielruss** [comment]
No, this has to do with the size of the screen.  A small screen uses the multiple choice, a larger screen uses the grid.  This is a feature, not a bug.

**Comment by cusackjm** [comment]
@danielruss can you go back to the previous feature, where all grid questions are forced to the sub-question type? I.e., force to multiple choice or select all that apply?

**Comment by cusackjm** [comment]
@danielruss since reverting quest yesterday, the grid questions are back to being forced to the sub-question type (tested in Covid Survey, Stage, Safari, iPad), but the response text is still formatted to the center

**Comment by cunnaneaq** [comment]
B/U survey - Dev, Macbook, Chrome and Dev, iPad, Safari

Seeing the grid, I think we want the forced sub-question type

![Screenshot 2023-12-15 at 5 11 09 PM](https://github.com/episphere/questionnaire/assets/83971268/a84f6aea-d755-4378-9eef-5179cddc126f)

![image](https://github.com/episphere/questionnaire/assets/83971268/fdff46e6-8212-44a1-b93c-a71e2974df85)

**Comment by cusackjm** [comment]
![image](https://github.com/episphere/questionnaire/assets/85582895/087c0447-7d7c-4073-baec-ec1009e8fdf2)
@danielruss grids don't have the radio buttons anymore, but are back to missing grid lines and text is centered 
Tested in Dev, Chrome, PC

**Comment by cusackjm** [comment]
@danielruss should I create a separate issue to track the response text orientation? Not sure if the response orientation fix was pushed
![image](https://github.com/episphere/questionnaire/assets/85582895/2d80d7e0-ef6a-48ec-93cc-5b1bdad72020)

**Comment by danielruss** [comment]
Is this still a problem?

**Comment by cusackjm** [comment]
> @danielruss should I create a separate issue to track the response text orientation? Not sure if the response orientation fix was pushed ![image](https://private-user-images.githubusercontent.com/85582895/293250680-2d80d7e0-ef6a-48ec-93cc-5b1bdad72020.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMDA0ODAsIm5iZiI6MTcwNDMwMDE4MCwicGF0aCI6Ii84NTU4Mjg5NS8yOTMyNTA2ODAtMmQ4MGQ3ZTAtZWY2YS00OGVjLTkzY2MtNWIxYmRhZDcyMDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDE2NDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZDhhMDIzNGVhMTBjM2E0OTU5ODY2NjFkODQ3MWRhZTQ2OTY0ODE3NmFjNThiMjE3NTgxNjg3ZjQ5NTFiMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dakZJP1ijhe0ZrUCMf6iudny2NL4JKFYME289yWcPSM)

@danielruss the response text in the check box was fixed. Closing this and re-opening a new one to address the response text for radio buttons to avoid confusion
