### ISSUE TITLE
Skip logic incorrect after BRSTFD

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#303]
Tested in Dev, chrome browser on PC. Entered BRSTFD= 1 and went to end of survey (should have gone to CONTRACEPT)

I entered the following info:
![image](https://github.com/episphere/questionnaire/assets/85582895/c55ed821-37cc-4e42-937a-0ce328b0441f)

**Comment by joshid-ims** [comment]
@cusackjm, as per document, 

![image](https://github.com/episphere/questionnaire/assets/64986739/ea862352-4689-4fb9-94c5-8b1abe095571)

And in your test case, you have PREGNANT = 1. So I think what you see is correct, isn't it? 

Or do you need to update the document?

**Comment by cusackjm** [comment]
@joshid-ims thank you! It somehow got deleted on the dceg questionnaire document I was referencing. I will update the doc
