### ISSUE TITLE
Skip logic issue if hygiene= 0

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#304]
![image](https://github.com/episphere/questionnaire/assets/85582895/8ee361d2-9a0a-44b6-aa42-ed257b08d833)

after HYGIENE=0, I still saw FLOSS2, WTRPICK2, TONGUE2, WHITE2, MWUSE (which I shouldn't have seen)

**Comment by cusackjm** [comment]
Same thing happened after selecting HYGIENE= 1 (Floss), I didn't see BRUSH2, saw FLOSS2, but then I saw WTRPICK2, TONGUE2, WHITE2, MWUSE (which I shouldn't have seen)

**Comment by cusackjm** [comment]
If HYGIENE=2, I don't see BRUSH2 or FLOSS2, see WTRPCK2, but still see WHITE2 and MWUSE. Basically, if a response is selected at HYGIENE, then the logic works until the response's corresponding follow up question, after that, the non-selected follow up questions are incorrectly shown.

**Comment by cusackjm** [comment]
@boyd-mj @woodruffr @joshid-ims @guinevere83 do you have an eta for this fix? We are hoping to test this by Monday

**Comment by boyd-mj** [comment]
@cusackjm I am working on getting an estimate for you.

**Comment by cusackjm** [comment]
Confirmed fix in dev testing on 11/24/2023

**Comment by cusackjm** [comment]
Confirmed fix in Dev Blood/Urine/Mouthwash survey testing on 11/24/2023
