### ISSUE TITLE
CHILDCANC3X display is not working

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#305]
*Not sure if this is a Quest, markdown, or Quest/markdown issue*

Testing Module 1/Stage/Chrome/PC 

If I click on **just the textbox** in CHILDCANC3 [D_812370563?]= 55 [807835037 Another type of cancer] and enter "TEETH" in the textbox [933110091], I do not see CHILDCANC3X [D_278159347?]. If I click **outside of the textbox** in CHILDCANC3 [D_812370563?]= 55 [807835037 Another type of cancer] and enter "TEETH" in the textbox [933110091], I do see CHILDCANC3X [D_278159347?]. 

@danielruss is this a Quest issue that was fixed but lost after yesterday's revert back to old Quest code? See: https://github.com/episphere/quest/issues/423 & https://github.com/episphere/questionnaire/issues/242
@boyd-mj could we avoid this issue by changing the display logic for CHILDCANC3X [D_278159347?], so that it's displayed if [D_278159347?,displayif=equals(D_812370563,807835037)] or [933110091] has text? (idk if that's possible to code or even useful to do).

This also occurred for Sibling section

**Comment by joshid-ims** [comment]
@cusackjm can you please mention question ID instead of concept ID here:

could we avoid this issue by changing the display logic for CHILDCANC3X [D_278159347?], so that it's displayed if **[D_278159347?,displayif=equals(D_812370563,807835037)] or [933110091]** has text? (idk if that's possible to code or even useful to do).

**Comment by cusackjm** [comment]
could we avoid this issue by changing the display logic for CHILDCANC3X, so that it's displayed if: 
CHILDCANC3= Another type of cancer: Please describe
or
Please describe |__| textbox, has text entered 
![image](https://github.com/episphere/questionnaire/assets/85582895/a0c4f93c-5ac8-4ba3-957c-34a1805aa197)

**Comment by joshid-ims** [comment]
Yes, I guess we can do that. Will make the change and test.

**Comment by joshid-ims** [comment]
The new logic is working for us. Should we keep it or wait for Quest changes to be pushed to Prod to see if that was the issue?

**Comment by cusackjm** [comment]
@joshid-ims wait for now, I want to see what Tony says about the other issue being quest related. I'll update you when I hear from him

**Comment by joshid-ims** [comment]
Thanks!

**Comment by boyd-mj** [comment]
@cusackjm any updates on this? I believe this is our only outstanding issue for Module 1.

**Comment by cusackjm** [comment]
@danielruss we think this is an issue with Quest. If I select the **textbox**, enter text, I do not see CHILDCANC3X or the summary. If I select the response (outside of the textbox), enter text, I do see CHILDCANC3X and the summary. 
Can you take a look at this? IMS can program around this issue, but I am also concerned that the data is not saving and there are also many other 55 Other [textbox] responses throughout the modules

**Comment by danielruss** [comment]
looking into it..

**Comment by danielruss** [comment]
@cusackjm   I ran through module one and my 14-year old daughter had hair cancer.  Notice how D_812370563_1_1 has two values: 

1) D_812370563_1_1: which is an array containing one value: 807835037, which is the code for "Another type of cancer".  Had my daughter had a second type of cancer, it would be in the array.  BTW, don't worry about my daughter, she went to the stylist and her hair cancer is in complete remission.

2) D_933110091: which is the input to the type of cancer entered by the user.

If this is the problem, I don't think this is a quest issue.

<img width="778" alt="image" src="https://github.com/episphere/questionnaire/assets/3767675/65de1b38-0f97-4299-9abe-643ee8ac1594">

**Comment by cusackjm** [comment]
@danielruss could it be PWA? I believe IMS is testing the same renderer, so they would not be able to see it either

Not sure if this is helpful: 
![image](https://github.com/episphere/questionnaire/assets/85582895/f35c024b-1d5a-4d10-b961-9599498ba8b1)

**Comment by danielruss** [comment]
@cusackjm The "duplicate ID error" is because the age of cancer onset  has the same ID for all forms of cancer.  The year of cancer onset also has the same id for all cancers.  I told you guys not to do it.  Not sure about the next error.  It is actually wrong.  From w3schools:

> The for attribute of <label> must be equal to the id attribute of the related element to bind them together.

I am concerned about the 'response was block by CORB'.  Not sure what's up with that.

**Comment by cusackjm** [comment]
@danielruss by _"The "duplicate ID error" is because the age of cancer onset has the same ID for all forms of cancer. The year of cancer onset also has the same id for all cancers. I told you guys not to do it. Not sure about the next error. It is actually wrong_., do you mean that Age at diagnosis (CID: 206625031) and Year at diagnosis (CID: 261863326) should not be harmonized? Otherwise I am not following

**Comment by danielruss** [comment]
The way HTML was designed, all elements (html tags like <p> <br>) should have unique ids (or no ids).  We chose to use concept id's as the ID for the question because that is the questionnaires look on paper

`[QUESTNM] This is a question` is what the word doc looks like and is transformed to `<form id='QUESTNM>'` The responses also do this map `|__|id=CONCEPT_ID` to `<input type="text" id='CONCEPT_ID'` This is nice because you can get the results simpler.  When you harmonize the Concept ID's, there are 20ish elements with the same id.

How should we go forward.  I think the element ID should not be the concept id.  The id should be auto generated, and the id should be in html data element.  This would be a major rewrite, think blow out and redo.  Also, we want backwards compatibility. Edge is right to complain, but it's more of a warning and continues to display correctly. Since nothing is "broken", let's not fix it yet.

**Comment by cusackjm** [comment]
Would we have to unharmonize them in all of the modules? Just double checked in the DD and Year of Dx is used 146 times across modules

**Comment by danielruss** [comment]
I don't think you need to do it.  I think it is safe to ignore that error.

**Comment by cusackjm** [comment]
Is there any way to fix the issue? Otherwise we will not collect Age/year of Dx for children with "other type" of cancer, if the participant clicks inside textbox

**Comment by danielruss** [comment]
**BUG FOUND AND FIXED**.   When the user only clicked in the text box and not anywhere else, the 'clicked' radio button was never placed in the results.

**Comment by joshid-ims** [comment]
@danielruss Do I still need to remove those displayifs?

**Comment by danielruss** [comment]
You can 
1) remove them all
2) remove the last
3) fix the last

**Comment by joshid-ims** [comment]
We use https://episphere.github.io/quest/. Not sure it is dev or prod.

**Comment by danielruss** [comment]
if you use that or https://episphere.github.io/connectApp  you are using the dev version

**Comment by joshid-ims** [comment]
Should I remove the last one means from 3Y question (in bold)? 

[CHILDCANC3X?,displayif=valueIsOneOf("CHILDCANC2",55) or valueLength("CHILDCANC2_TB")>0] How old was |displayif=equals(isNotDefined(CHILDNAME,false),false)|{$CHILDNAME}||displayif=doesNotEqual(isNotDefined(CHILDNAME,false),false)|your child| when they were <b>first</b> told by a doctor or other health professional that they have or had |displayif=valueLength("CHILDCANC2_TB")>0|<b>{$CHILDCANC2_TB}</b>||displayif=doesNotExist("CHILDCANC2_TB")|<b>another type of cancer</b>|?<br/>
|__|__|__|__|xor=CHILDCANC3X id=CHILDCANC3X_AGE min=0 max=valueOrDefault("CHILDAGE_AGE","CHILDDEATH_NUM",125)| Age at diagnosis

Or, if it is easier to remember the year, enter that here: <br/>
|__|__|__|__| xor=CHILDCANC3X id=CHILDCANC3X_YEAR min=1800 max=#currentYear| Year of diagnosis


[CHILDCANC3Y?**,displayif=equals(CHILDCANC2,77)**] How old was |displayif=equals(isNotDefined(CHILDNAME,false),false)|{$CHILDNAME}||displayif=doesNotEqual(isNotDefined(CHILDNAME,false),false)|your child| when they were <b>first</b> told by a doctor or other health professional that they have or had <b>cancer</b>?<br/>
|__|__|__|__|xor=CHILDCANC3Y id=CHILDCANC3Y_AGE min=0 max=valueOrDefault("CHILDAGE_AGE","CHILDDEATH_NUM",125)| Age at diagnosis

Or, if it is easier to remember the year, enter that here:<br/> 
|__|__|__|__| xor=CHILDCANC3Y id=CHILDCANC3Y_YEAR min=1800 max=#currentYear| Year of diagnosis

**Comment by danielruss** [comment]
Sorry, CHILDCANC3X not CHILDCANC3Y.    You could also remove CHILDCANC3Y but CHILDCANC3X **must** go

**Comment by joshid-ims** [comment]
@danielruss I made changes as below and now these questions are showing irrespective of the selection made. Maybe I misunderstood what you suggested. 

[CHILDCANC3W?,displayif=equals(CHILDCANC2,22)] How old was |displayif=equals(isNotDefined(CHILDNAME,false),false)|{$CHILDNAME}||displayif=doesNotEqual(isNotDefined(CHILDNAME,false),false)|your child| when they were <b>first</b> told by a doctor or other health professional that they have or had <b>uterine cancer</b>?<br/>
|__|__|__|__|xor=CHILDCANC3W id=CHILDCANC3W_AGE min=0 max=valueOrDefault("CHILDAGE_AGE","CHILDDEATH_NUM",125)| Age at diagnosis

Or, if it is easier to remember the year, enter that here: <br/> 
|__|__|__|__| xor=CHILDCANC3W id=CHILDCANC3W_YEAR min=1800 max=#currentYear| Year of diagnosis


[CHILDCANC3X?] How old was |displayif=equals(isNotDefined(CHILDNAME,false),false)|{$CHILDNAME}||displayif=doesNotEqual(isNotDefined(CHILDNAME,false),false)|your child| when they were <b>first</b> told by a doctor or other health professional that they have or had |displayif=valueLength("CHILDCANC2_TB")>0|<b>{$CHILDCANC2_TB}</b>||displayif=doesNotExist("CHILDCANC2_TB")|<b>another type of cancer</b>|?<br/>
|__|__|__|__|xor=CHILDCANC3X id=CHILDCANC3X_AGE min=0 max=valueOrDefault("CHILDAGE_AGE","CHILDDEATH_NUM",125)| Age at diagnosis

Or, if it is easier to remember the year, enter that here: <br/>
|__|__|__|__| xor=CHILDCANC3X id=CHILDCANC3X_YEAR min=1800 max=#currentYear| Year of diagnosis


[CHILDCANC3Y?] How old was |displayif=equals(isNotDefined(CHILDNAME,false),false)|{$CHILDNAME}||displayif=doesNotEqual(isNotDefined(CHILDNAME,false),false)|your child| when they were <b>first</b> told by a doctor or other health professional that they have or had <b>cancer</b>?<br/>
|__|__|__|__|xor=CHILDCANC3Y id=CHILDCANC3Y_AGE min=0 max=valueOrDefault("CHILDAGE_AGE","CHILDDEATH_NUM",125)| Age at diagnosis

Or, if it is easier to remember the year, enter that here:<br/> 
|__|__|__|__| xor=CHILDCANC3Y id=CHILDCANC3Y_YEAR min=1800 max=#currentYear| Year of diagnosis

**Comment by danielruss** [comment]
are your edits in github?

**Comment by danielruss** [comment]
The version in github looks good to me?  If I select uterine cancer, I dont see the "OTHER" type of cancer.  If I select "OTHER" and uterine they both appear in the summary.  -- LGTM

**Comment by guinevere83** [comment]
Here's what I'm seeing when I do that:

![image](https://github.com/episphere/questionnaire/assets/75336502/3cee7166-a906-4d77-91af-9423df8381da)

**Comment by joshid-ims** [comment]
Let me check MOM and DAD sections

**Comment by cusackjm** [comment]
confirmed fixed in dev testing on 1/1/2024 in chrome/laptop
