### ISSUE TITLE
Address conditional question

### ISSUE THREAD

**Issue by boyd-mj** [episphere/questionnaire#31]
Hi @cusackjm  & @freedmanne, question for you concerning the home address section in Module 4. As you know the section presents a series of questions where the user can enter multiple addresses. They are first asked if they have lived anywhere else in the past 20 years and if they say yes, they are presented with the fields to enter the address:

[HOMEADDOTH2?] Within the <b>past 20 years</b>, have you lived anywhere else for <b>at least two years</b>?
(1) Yes -> HOMEADD1_3
(0) No -> HOMEADDSUM
< #NR-> HOMEADDSUM >

[HOMEADD1_3?] What is the full street address of the place you lived before you moved to the place you live now? Please only include addresses where you have lived for <b>at least two years</b>.

Street number |__|__|id=STNUM2 min=0 max=999999|
Full Street name |__|id=FULLST2|
Apartment, suite, unit, building, etc. |__|__|id=APT2|
City |__|id=CITY2|
State/Province |__|id=ST2|
Zip code |__|__|id=ZIP2 min=0|
Country |__|id=COUNTRY2|

[HOMEADD2_3?,displayif=or(or(isNotDefined(CITY2,false),isNotDefined(ST2,false)),or(isNotDefined(ZIP2,false),isNotDefined(COUNTRY2,false)))] Please provide the following information:
City: |displayif=exists("CITY2")|{$CITY2}|
|__|id=CITY2_FOLLOWUP displayif=doesNotExist("CITY2")|

State/Province: |displayif=exists("ST2")| {$ST2}|
|__|id=ST2_FOLLOWUP displayif=doesNotExist("ST2")|

Zip code: |displayif=exists("ZIP2") | {$ZIP2}|
|__|id=ZIP2_FOLLOWUP min=0 displayif=doesNotExist("ZIP2")|

Country: |displayif=exists("COUNTRY2")| {$COUNTRY2}|
|__|id=COUNTRY2_FOLLOWUP displayif=doesNotExist("COUNTRY2")|
[77*] Don't know

Once they select no to one of the HOMEADDOTHx questions, they are presented with the address summary and are then asked if the list is complete, or if they would like to enter another address. If they select "No, I would like to enter another address", they are taken to the first set of questions in the series where they haven't already said yes to entering an address, but they are taken to the address field section instead. For instance, if after entering two addresses, they say they have no more addresses, then in response to the summary say they would like to enter another address, they are taken to HOMEADD1_3 (shown above). 

If they don't enter any data and instead skip through and select yes, the list is complete when the summary is presented again, there won't be a record of this address. For later follow up questions like year move in/out or water type questions, they wouldn't be presented with the questions for a third address. We had previously asked what should happen if they say yes to adding another address in HOMEADDOTHx, but then don't complete address fields. In that case, we were instructed to still present the follow-up questions and simply prompt them with "when you lived at your 3rd address...". Should we do the same in this case, or should we ignore the missing address?

The scenario seems unlikely to happen often imo and more likely to be a mistake on the participant's part (where they realize once reprompted with the address fields that they didn't mean to go back), but it's a scenario that isn't currently addressed in the code so we wanted to check. 

I hope this is clear. Let me know if not, or if you have questions. We are currently wrapping up the work on Module 4 with these address modifications and can't move forward until we hear back.

Thanks,
Jen

**Comment by cusackjm** [comment]
We think the participant should not see the follow-up questions, as we are unsure how useful it is to gather that information if we don't know where the participant was living at the time.
