### ISSUE TITLE
Grid text display

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#314]
@danielruss is it possible to spread out the response text (red in picture), so that is not smooshed and easier to read? In doing so, can you move the text over to the left so it is closer to the question text (blue). 

GRID_SECSMLF2, Module 3, Dev, Chrome, Laptop
![image](https://github.com/episphere/questionnaire/assets/85582895/6995a11d-d599-48e1-9871-e012a5ee1e56)

**Comment by danielruss** [comment]
How does this look.  Notice the question gets pushed to the next line.

<img width="778" alt="image" src="https://github.com/episphere/questionnaire/assets/3767675/805f8063-767f-4c67-9308-106d4ff46802">

**Comment by cusackjm** [comment]
@danielruss that looks better

**Comment by danielruss** [comment]
pushed to dev...
