### ISSUE TITLE
piped text shouldn't be displayed in LAWN3A if WORK= NR

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#317]
I will update the questionnaire document because it is not clear, but if WORK= nr, the functionality should be the same as WORK= 0 for LAWN section (LAWN3A, LAWN4A, LAWN3B, LAWN4B, LAWN3C, LAWN4C,). The piped text worked as intended for HOUSE1/SITTING/WORKACT sections

**Comment by joshid-ims** [comment]
Is the document updated?

**Comment by cusackjm** [comment]
yes @joshid-ims

**Comment by cusackjm** [comment]
confirmed fix in dev testing on 1/22/24
