### ISSUE TITLE
Update Max range check for COV14B, COV15B, COV16B, COV17B if COV13= NR

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#318]
If No-response is entered at COV13, the range check for COV14B, COV15B, COV16B, COV17B is set to 0. Can you change that from 0 to 180? @joshid-ims

**Comment by cusackjm** [comment]
Failed dev testing on 1/24/2024 on chrome, pc. 
I entered the following information:
![image](https://github.com/episphere/questionnaire/assets/85582895/6eedd606-73d4-4b40-8ca8-1672cc478c7c)

**Comment by cusackjm** [comment]
passed dev testing on 1/24/24 in chrome pc

**Comment by guinevere83** [comment]
Checked a few loops to make sure 180 is the max range when COV13 = NR, looked good to me:

![image](https://github.com/episphere/questionnaire/assets/75336502/687ee52a-d192-42e6-bf25-e45be243a38f)

**Comment by cusackjm** [comment]
@guinevere83 - I updated and closed the issue. It passed testing
