### ISSUE TITLE
revise question text for COV13

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#321]
![image](https://github.com/episphere/questionnaire/assets/85582895/686d0b2b-74d2-46ab-990a-c3c22a0acebd)

**Comment by cusackjm** [comment]
@FrogGirl1123 would this edit require the question text to be versioned? Just realized that the question text does not sound right and it's not a typo

**Comment by woodruffr** [comment]
Mark-up delivered 8/15/2024.

**Comment by woodruffr** [comment]
This was tested on both Dev and Stage testing and passed.
