### ISSUE TITLE
Calendar display on iPads and iPhones

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#323]
@danielruss Do you know when the calendar picker question type went from being displayed as a calendar to a scroll response, for iPhones and Tablets (iPad)? And is this change reversable?

On a **laptop**: COV3 and COV27 are currently displayed as:
![image](https://github.com/episphere/questionnaire/assets/85582895/b51d9354-0e38-4f86-8138-7eff941b2507)
![image](https://github.com/episphere/questionnaire/assets/85582895/209d1115-c55f-4958-98b3-61d5b5464c5b)

On an **iPhone/iPad**: COV3 and COV27 are currently displayed as:
![image](https://github.com/episphere/questionnaire/assets/85582895/5807b0f1-2cc7-473b-bc9e-f2e7d04b7e49)
![image](https://github.com/episphere/questionnaire/assets/85582895/2f6135e8-fbd8-4e5b-b3cf-8dd51cf01f2a)

In the past, calendar pickers were displayed as they currently are on laptops. It is not an issue that they are displayed as the scroll response, but I was wondering if they could be reverted to the calendar format, as they are first displayed as a grey box and grey boxes require additional question text. For time responses, we had to add question text to each question instructing participants to click on the grey box to enter a response, because they were reporting issues with not being able to enter a response. If we are going to keep the current display, we will have to revise the question text for all calendar pickers (impacting COVID-19 and Menstrual Cycle Survey)

**Comment by danielruss** [comment]
@cusackjm  This is the browser not quest.   The quest rendering engine takes the markup and converts html.

The questions you are referring to use the markup `|month| ... |` which is converted to  `<input type="month">`  in HTML.
How the HTML is rendered on the browser is brower-specific (although the mostly do the same thing).  As you see in all the pictures, the goal is to select a month-year.  

I cannot 'roll back' the browser.  If you tell me what the issue with the scrolly calendar, we can talk about workarounds.  If you just don't like the way it looks, I would warn you that apple is particularly good at UI elements.  If there is a different issue, I could try to create a new element via javascript, but it would take take.

**Comment by cusackjm** [comment]
@danielruss thanks!

No issue with the format, I'll just add the question text so participants are aware to click on the grey box if they are using a tablet or phone

**Comment by woodruffr** [comment]
Mark-up delivered 8/15/2024.

**Comment by woodruffr** [comment]
This was tested and passed in both Dev and Stage testing.
