### ISSUE TITLE
QoL Fatigue page formatting change

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#326]
The current alignment of items to the attachment you sent:
•	The Questionnaire word document matches. No change needed.
•	The Data Dictionary will still have both “In the past 7 days / During the past 7 days” because it must apply to all four questions. No change needed.
•	The JSON will have the same as the dd. No change needed.
•	The mark-up will need to have the text modified slightly. This text does not impact any data storage. We will make this change.

**Comment by huip-ims** [comment]
This issue has been completed/fixed and will be included in the next delivery.

**Comment by woodruffr** [comment]
The QoL updated files for this have been delivered to https://app.box.com/folder/249033368741.

**Comment by cusackjm** [comment]
confirmed fix in dev testing on 2/20/2024
