### ISSUE TITLE
Remove punctuation at end of question text for SATISFYSOCIAL2, SATISFYSOCIAL3, SATISFYSOCIAL4

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#327]
Question text for SATISFYSOCIAL2, SATISFYSOCIAL3, SATISFYSOCIAL4 has a period at the end of the statement. Please remove to be consistent with the qx document. 

![image](https://github.com/episphere/questionnaire/assets/85582895/cdc01a84-dcd9-47a5-a578-c0e8a483ffe4)

**Comment by huip-ims** [comment]
This issue has been completed/fixed and will be included in the next delivery.
