### ISSUE TITLE
Removing PAINRANK from QoL Survey

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#329]
Removing PAINRANK (SINGLE ITEM QUESTION) from QoL Survey

**Rationale:**
- There is no option to report no pain. In the previous domain (pain interference) there are options to report "not at all" in regards to feeling pain 
- PAINRANK is not part of the t-score 
- Roxanne Jenson (promis developer) originally said that the single item pain question is not useful for most researchers. If we are interested in pain among cancer survivors, there are tailored domains to use.

**Next steps:**
- **Questionnaire documents:** question is deleted, using tracked changes
- **DD:** @FrogGirl1123 should this be denoted as deprecated, or should we delete the variables from the DD (since it is not in prod)
- **Question types doc:** @woodruffr  edit depends on DD edit
- Markdown: @boyd-mj @joshid-ims needs update and re-delivery

**Comment by cusackjm** [comment]
Question was deleted from the DD and question types document

**Comment by huip-ims** [comment]
This issue has been completed/fixed and will be included in the next delivery.

**Comment by cusackjm** [comment]
confirmed fix in dev testing on 2/20/2024
