### ISSUE TITLE
Min values for 

### ISSUE THREAD

**Issue by boyd-mj** [episphere/questionnaire#33]
Hi @cusackjm it looks like we never closed the loop on this issue. Should we update the minimum to year of birth for the three variables mentioned below? If so, could you add them to the range check document on Box please (it's locked for us) and then we will make the changes:
https://app.box.com/file/869524081027

From: Cusack, Julie (NIH/NCI) [C] <julie.cusack@nih.gov> 
Sent: Monday, November 15, 2021 1:58 PM
To: Boyd-Morin, Jennifer (IMS) <Boyd-MorinJ@imsweb.com>
Cc: Freedman, Neal (NIH/NCI) [E] <freedmanne@mail.nih.gov>; Gaudet, Mia (NIH/NCI) [E] <mia.gaudet@nih.gov>; Gerlanc, Nicole (NIH/NCI) [E] <nicole.gerlanc@nih.gov>
Subject: RE: Min/Max values in Module 4

Hi Jen, 

I did not recommend any range checks for PREWORKYR2, CURWORKYR1, or CURSCHYR1 when I reviewed the ranges for Module 4. 

The only commuting question I recommended a range check for was PREWORKYR1 (year start commuting to address). The minimum value was 0, but I recommended the Min should be the year of birth. If we were to change the Min range check for PREWORKYR2, CURWORKYR1, and/or CURSCHYR1, I would recommend they also be set to the year of birth.

Best,
Julie

Julie Cusack [C] • Operational Development Coordinator
Division of Cancer Epidemiology and Genetics
National Cancer Institute, National Institutes of Health
9609 Medical Center Drive, Rockville, MD 20850
[C] N4 Solutions, LLC
E: julie.cusack@nih.gov
P: 240-276-5861

From: Boyd-Morin, Jennifer (IMS) <Boyd-MorinJ@imsweb.com> 
Sent: Friday, November 12, 2021 7:52 PM
To: Gaudet, Mia (NIH/NCI) [E] <mia.gaudet@nih.gov>; Gerlanc, Nicole (NIH/NCI) [E] <nicole.gerlanc@nih.gov>
Cc: Brotzman, Michelle (NIH/NCI) [E] <michelle.brotzman@nih.gov>; Cusack, Julie (NIH/NCI) [C] <julie.cusack@nih.gov>; Johnson, Davin (NIH/NCI) [C] <davin.johnson@nih.gov>
Subject: FW: Min/Max values in Module 4

Hi Nicole & Mia,

I don’t recall receiving a response to the email below. Could you please resend if I overlooked it, or otherwise let us know your thoughts?

Thanks,
Jen

From: Boyd-Morin, Jennifer (IMS) 
Sent: Wednesday, October 20, 2021 4:30 PM
To: Gerlanc, Nicole (NIH/NCI) [E] <nicole.gerlanc@nih.gov>
Cc: Gaudet, Mia (NIH/NCI) [E] <mia.gaudet@nih.gov>; Brotzman, Michelle (NIH/NCI) [E] <michelle.brotzman@nih.gov>; Johnson, Davin (NIH/NCI) [C] <davin.johnson@nih.gov>
Subject: Min/Max values in Module 4

Hi Nicole,

We have made the min/max changes for Modules 3 & 4. For module 4, a question arose about whether you would like to assign minimum values for the following 3 variables as well since changes were provided for PREWORKYR1:

PREWORKYR2
CURWORKYR1
CURSCHYR1

The minimum values are currently all set to zero. 

Thanks,
Jen

**Comment by cusackjm** [comment]
Hi Jen- we did not end up deeming an update to those range checks necessary, so they can remain set to 0.

**Comment by boyd-mj** [comment]
Thanks!
