### ISSUE TITLE
ZIP Code Character Length 

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [episphere/questionnaire#330]
It looks like we have a character length limit of 8 for all ZIP code related variables in the DD (listed below), however, that should be 9 

MODULE 1
-Alternative ZIP Code
D_857915436_D_379899229 

MODULE 4
-House ZIP Codes
D_121490150_D_202784871
D_574985342_D_467947502
D_828086036_D_335435992
D_680046149_D_455968200
D_274189667_D_554901696
D_113930886_D_127963610
D_809728747_D_256790385
D_539057792_D_673034401
D_537011756_D_453691095
D_171937884_D_674024553
D_828766803_D_795253129
D_716117817_D_256790385

-House Follow up ZIP Codes
D_920576363_D_970000442
D_444145120_D_936129960
D_752101258_D_649864362
D_879180101_D_267027102
D_212343294_D_684217044
D_255474241_D_803526907
D_201906316_D_814644814
D_864213677_D_865310914
D_787064287_D_659122266
D_920576363_D_972332937
D_878688378_D_814137809

-Seasonal House ZIP Codes
D_376408004_D_812433386
D_279093430_D_494380686
D_143927994_D_938180781
D_935378391_D_716343828
D_320166033_D_970217879
D_383535171_D_687407917
D_133566757_D_248996395
D_509553290_D_949478044
D_239279719_D_737885885
D_778711683_D_624226136

-Seasonal House Follow up ZIP Codes
D_173413183_D_354833686
D_657986901_D_845446624
D_564684946_D_245044197
D_558981691_D_701056236
D_194944818_D_787391994
D_508587741_D_103689435
D_293954660_D_230376384
D_268612977_D_421779583
D_216096388_D_855530921
D_757983656_D_158186064

Childhood Address ZIP Code and Follow up ZIP Codes
D_632533534_D_286781627
D_264797252_D_984908796

Current Workplace ZIP Code and Follow up ZIP Code
D_596318751_D_182144476
D_263588196_D_101341673

Previous Workplace ZIP Code and Follow Up ZIP Code
D_992180692_D_110852652
D_350394531_D_168091937

School commute zip code and follow up
D_914696832_D_884494489
D_668887646_D_997041632

**Comment by KELSEYDOWLING7** [comment]
We also have 8 participants that gave only 3 or 4 digits. Do we want to also implement a markdown change to require at least 5 digits?

**Comment by m-j-horner** [comment]
> https://nih.app.box.com/file/1468120180045

@KELSEYDOWLING7  I can't open this file. Are these current address zipcode or historical addresses zipcode?

**Comment by KELSEYDOWLING7** [comment]
![image](https://github.com/episphere/questionnaire/assets/101136647/a2258809-9488-4764-901d-d889c1a15b42)
These are alternative address zip codes in Module 1. We haven't gotten to the Module 4 QC rules for ZIP codes just yet but the same logic would apply

**Comment by cusackjm** [comment]
rena wants 5 digits to be required

**Comment by cusackjm** [comment]
tracking here: https://github.com/episphere/questionnaire/issues/345
