### ISSUE TITLE
Menstrual Cycle (Spanish version) - Embedded English text

### ISSUE THREAD

**Issue by huip-ims** [episphere/questionnaire#331]
Hi Julie - I'm seeing some English text embedded in the Spanish version of the questionnaire. Could you please confirm if these English text should be displayed along with the Spanish text?  See examples below.

> Cuando donó muestras para el Estudio de conexión para la prevención del cáncer [Connect for Cancer Prevention Study]

> Respondió a todas las preguntas de este cuestionario. Para enviar sus respuestas, seleccione el botón “Enviar cuestionario” [“Submit Survey”].

**Comment by huip-ims** [comment]
@cusackjm @danielruss @boyd-mj Julie & Daniel - In addition to my question above, if a participant answers 'No' to MENS1, the skip logic goes to END message “Thank you. When your next menstrual period starts, please return to complete this survey.” [EXIT AND CLEAR CACHE]. However, in the renderer, the END message is displayed and to move forward, the participant has to select the "Submit Survey" button. Is this acceptable or is there a way in the markdown to "EXIT AND CLEAR CACHE"?

![image](https://github.com/episphere/questionnaire/assets/82978291/1fd50552-e70e-4fcc-ac5f-747b30cee67a)

**Comment by danielruss** [comment]
This is not and should not be a quest feature.   The PWA should coordinate the this.

PWA (here is the survey) -> QUEST (NO) -> PWA (Oh... the answer was no, don't mark as complete, clear localforage...)

**Comment by depietrodeanna** [comment]
@anthonypetersen looping in you from DevOps in case there is anything we need to consider. We got a question about embedded English within the Spanish text version of the Menst Survey. There is English in the translated quex document from NIH Lib so I think we can include it, but I'm not concerned about leaving it out either.

**Comment by anthonypetersen** [comment]
> This is not and should not be a quest feature. The PWA should coordinate the this.
> 
> PWA (here is the survey) -> QUEST (NO) -> PWA (Oh... the answer was no, don't mark as complete, clear localforage...)

What @danielruss is describing is exactly how the survey has worked since it went live. The PWA is listening for an answer to that question and if it is `NO` the PWA intercepts Quest and renders the text telling them to come back later with only an OK button displayed. When that button is clicked, we reset the status of the survey for the participant.

**Comment by huip-ims** [comment]
Menstrual Cycle markdown (Spanish version) has been delivered.
