### ISSUE TITLE
Blood Urine Mouthwash (Spanish Version)

### ISSUE THREAD

**Issue by huip-ims** [episphere/questionnaire#332]
@cusackjm Hi Julie - I'm seeing the following differences between English vs. Spanish. Could you please confirm if these changes were done on purpose?

1. MENSTPRD - English has bold "12 months", whereas Spanish has bold "últimos 12 meses".
2. MENST60 - English has bold "60 days", whereas Spanish has bold "últimos 60 días".
3. MENSTPRD, MENST60, and MENSTART - English has additional text "Please do not consider breakthrough bleeding (also known as spotting) as part of the menstrual period.", but Spanish version does not include this.

**Comment by cusackjm** [comment]
@huip-ims hi I just sent an email clarifying which surveys are ready for programming (this survey is not ready yet) because of 3. mentioned above

**Comment by huip-ims** [comment]
@cusackjm Thanks Julie. I will move over to the Spanish Module 4 then.
