### ISSUE TITLE
Version numbers in variable names different

### ISSUE THREAD

**Issue by joshid-ims** [episphere/questionnaire#336]
3 variables have different versions in English and Spanish copies.

![image](https://github.com/episphere/questionnaire/assets/64986739/60a48cc6-c9f6-4aa4-8eb2-e2a85fa1bc45)

![image](https://github.com/episphere/questionnaire/assets/64986739/18b85243-0651-4f3b-a8a2-8a9a106c93bc)

**Comment by cusackjm** [comment]
@joshid-ims Spanish Blood, urine, Mouthwash Survey and Blood and Urine Surveys are updated

**Comment by joshid-ims** [comment]
Thanks!
