### ISSUE TITLE
Discrepancies in Module 1 Spanish

### ISSUE THREAD

**Issue by joshid-ims** [episphere/questionnaire#338]
STYLE is missing option 99 -  Prefer not to answer which is present in English version.

**Comment by cusackjm** [comment]
STYLE should not have that option. It is not in the English Questionnaire documents, is it in the markdown? @joshid-ims

**Comment by joshid-ims** [comment]
Yes:
[STYLE?] A person’s appearance, style, dress, or mannerisms (the way they walk or talk) may affect the way people think of them. On average, how do you think people would describe your appearance, style, dress, or mannerisms?
(0) Very feminine
(1) Mostly feminine
(2) Somewhat feminine
(3) Equally feminine and masculine
(4) Somewhat masculine
(5) Mostly masculine
(6) Very masculine
(99) Prefer not to answer

**Comment by cusackjm** [comment]
@joshid-ims all of our questionnaire documentation (including previous versions) does not have this response, but it is in the DD, so I am going to talk to the QX Subcommittee to determine what needs to be updated

**Comment by joshid-ims** [comment]
Ok, sounds good. Thanks!

**Comment by joshid-ims** [comment]
There is some inconsistency in making the text bold. Is that intentional? For e.g.,

97. [BREASTSUR6] ¿A qué edad tuvo la **extirpación quirúrgica de ambas mamas (mastectomía bilateral o doble)**? 

and

98. [BREASTSUR7] ¿A qué edad tuvo la **cirugía para un absceso mamario** (como incisión y drenaje)? 

It is in most of BREASTSUR questions. Most of other questions have the whole surgery type, including text in parenthesis in bold.

**Comment by cusackjm** [comment]
@joshid-ims "99	Prefiero no responder" was added to STYLE in the Spanish Qx Document. Going to add "prefer not to answer" to the english documents next. This will sync up the questionnaire documents with the DD and markdown

**Comment by joshid-ims** [comment]
Thanks!

**Comment by joshid-ims** [comment]
![image](https://github.com/episphere/questionnaire/assets/64986739/4d3426ad-30d9-4a65-9e1c-71f757f48d7f)

Highlighted text not translated.

**Comment by cusackjm** [comment]
@joshid-ims this has to go back to the translator

**Comment by joshid-ims** [comment]
Ok.

**Comment by joshid-ims** [comment]
In English document we have:

How many years have you worked in that job [JOB FROM WORK3]?

But the way it is in code is:

How many years have you worked in that job?

What should we do about Spanish coding? Should we insert WORK3 response or not?

¿Cuántos años lleva trabajando en ese empleo []?

**Comment by cusackjm** [comment]
@joshid-ims don't insert the WORK3 response to reflect the markdown. I have that as a questionnaire doc edit, but have not applied it to the IMS qx doc yet

**Comment by joshid-ims** [comment]
Ok, thanks!

**Comment by cusackjm** [comment]
@joshid-ims ok, don't think they will be needed, as the text should be: 
How many years have you worked in that job?

**Comment by joshid-ims** [comment]
Oh not for this question. In different places like:

[MHGROUP2] Problemas respiratorios
33. ¿Le ha dicho alguna vez un médico u otro profesional de la salud que tiene o tenía alguna de estas afecciones? Seleccione todas las opciones que correspondan. 
0	Enfermedad pulmonar crónica (enfisema, bronquitis crónica o enfermedad pulmonar obstructiva crónica **[EPOC]**)

**Comment by cusackjm** [comment]
@joshid-ims follow however it is programmed in the english version

**Comment by woodruffr** [comment]
@cusackjm, Aminat made the SIB2 and CHLD2 changes in the Questionnaire, adding the commas. Please review them.

Adding this for documentation purposes:
_From: Cusack, Julie (NIH/NCI) [C] <julie.cusack@nih.gov> 
Sent: Friday, May 17, 2024 4:30 PM
To: Woodruff, Rose (IMS) <WoodruffR@imsweb.com>; Boyd-Morin, Jennifer (IMS) <Boyd-MorinJ@imsweb.com>; Petersen, Tony (NIH/NCI) [C] <tony.petersen@nih.gov>; Gerlanc, Nicole (NIH/NCI) [E] <nicole.gerlanc@nih.gov>; Gaudet, Mia (NIH/NCI) [E] <mia.gaudet@nih.gov>; Horner, Marie Josephe (NIH/NCI) [E] <mariejosephe.horner@nih.gov>; Cunnane, Aileen (NIH/NCI) [C] <aileen.cunnane@nih.gov>; Dowling, Kelsey (NIH/NCI) [C] <kelsey.dowling@nih.gov>
Cc: Johnson, Davin (NIH/NCI) [C] <davin.johnson@nih.gov>; Barra, Gene (NIH/NCI) [C] <gene.barra@nih.gov>; Brotzman, Michelle (NIH/NCI) [E] <michelle.brotzman@nih.gov>; Mazzilli, Kaitlyn (NIH/NCI) [C] <kaitlyn.mazzilli@nih.gov>; Roberts, Amelia (NIH/NCI) [C] <amelia.roberts@nih.gov>
Subject: RE: Spanish Module 4

Hi Rose,

Please apply the comma to the questionnaire document and markdown for the June release. Thanks!

Best,
Julie

Julie Cusack [C] • Questionnaire Development Coordinator
Division of Cancer Epidemiology and Genetics
National Cancer Institute, National Institutes of Health
9609 Medical Center Drive, Rockville, MD 20850
[C] N4 Solutions, LLC
E: [julie.cusack@nih.gov](mailto:julie.cusack@nih.gov)
P: 240-276-5861
 

From: Woodruff, Rose (IMS) <[WoodruffR@imsweb.com](mailto:WoodruffR@imsweb.com)> 
Sent: Friday, May 17, 2024 1:21 PM
To: Cusack, Julie (NIH/NCI) [C] <[julie.cusack@nih.gov](mailto:julie.cusack@nih.gov)>; Boyd-Morin, Jennifer (IMS) <[Boyd-MorinJ@imsweb.com](mailto:Boyd-MorinJ@imsweb.com)>; Petersen, Tony (NIH/NCI) [C] <[tony.petersen@nih.gov](mailto:tony.petersen@nih.gov)>; Gerlanc, Nicole (NIH/NCI) [E] <[nicole.gerlanc@nih.gov](mailto:nicole.gerlanc@nih.gov)>; Gaudet, Mia (NIH/NCI) [E] <[mia.gaudet@nih.gov](mailto:mia.gaudet@nih.gov)>; Horner, Marie Josephe (NIH/NCI) [E] <[mariejosephe.horner@nih.gov](mailto:mariejosephe.horner@nih.gov)>; Cunnane, Aileen (NIH/NCI) [C] <[aileen.cunnane@nih.gov](mailto:aileen.cunnane@nih.gov)>; Dowling, Kelsey (NIH/NCI) [C] <[kelsey.dowling@nih.gov](mailto:kelsey.dowling@nih.gov)>
Cc: Johnson, Davin (NIH/NCI) [C] <[davin.johnson@nih.gov](mailto:davin.johnson@nih.gov)>; Barra, Gene (NIH/NCI) [C] <[gene.barra@nih.gov](mailto:gene.barra@nih.gov)>; Brotzman, Michelle (NIH/NCI) [E] <[michelle.brotzman@nih.gov](mailto:michelle.brotzman@nih.gov)>; Mazzilli, Kaitlyn (NIH/NCI) [C] <[kaitlyn.mazzilli@nih.gov](mailto:kaitlyn.mazzilli@nih.gov)>; Roberts, Amelia (NIH/NCI) [C] <[amelia.roberts@nih.gov](mailto:amelia.roberts@nih.gov)>
Subject: [EXTERNAL] RE: Spanish Module 4

Hi Julie,

This was noted by our Spanish language reviewer for SIB2. We have asked if this also applies to CHILD2, but have not get gotten her response.

When you write "En cuanto a su hermano el que le sigue a ese, ¿qué sexo biológico se le asignó a este hermano al nacer?" you're referring to the brother that follows the older brother (the second child). 
I would add a comma between " su hermano" and "el que le sigue a ese". So it should read "En cuanto a su hermano, el que le sigue a ese, ¿qué sexo biológico se le asignó a este hermano al nacer?"

The comma makes all the difference as it should be used for interruption and clarifications (Appositives).

In this instance you are throwing in an explanatory phrase or clarification into the sentence stating that even though it is the person's older brother, he is still not the oldest (therefore he is the 2nd child).

With the comma it would read like this in English: "As for his brother, the one after him, what biological sex was this brother assigned at birth?"

If they simply want the English statement to read as: "As for his next brother, what biological sex was this brother assigned at birth?", then the translation should be: "En cuanto a su próximo hermano, ¿qué sexo biológico se le asignó a este hermano al nacer?". This translation shows no emphasis or explanation.

Regards,
Rose_

**Comment by cusackjm** [comment]
spanish mod 1 tracked changes were accepted

**Comment by cusackjm** [comment]
can i close this? The qx documents were updated to reflect markdown- so re-testing is not needed

**Comment by guinevere83** [comment]
Yep we can go ahead and close this.
