### ISSUE TITLE
Questions on Biospecimen Questionnaire

### ISSUE THREAD

**Issue by huip-ims** [episphere/questionnaire#34]
Hi Julie,

For several questions, you asked for numeric drop down lists for month, year, or # of times.  Currently, numeric drop downs are not supported.  I can work around these by using numeric text boxes, or did you want to discuss this with Daniel to see if he can add these features?

For grids, you listed variables names with underscores, but I believe this is currently not permitted.  Do you want to confirm this with Daniel and see if underscores can be used or would you like to remove them from the grid variable names?

In the blood & urine section, special missing 77 is listed as ‘Do not know’.  However, in the mouthwash section, 77 is listed as ‘Don’t know’.  Would you like us to make them consistent, and if so, which one do you prefer?  Or, should we leave them as-is?

Thanks,
Pete

**Comment by cusackjm** [comment]
Hi Pete,
1. I will get back to you soon on using the numeric text boxes, or if we want to ask Daniel if he could add the drop down feature.
2. For the variable names, to my understanding I was following this naming convention: 
![image](https://user-images.githubusercontent.com/85582895/152180545-51b2269a-7b65-4d50-a99b-064de1352ab3.png)
Is this different for Grids? 
3. I will change the 77 responses to the harmonized response "Don't know".

**Comment by cusackjm** [comment]
1. (UPDATE) We are ok with using the numeric text boxes

**Comment by danielruss** [comment]
First, drop down boxes are not supported.  I believe the rationale was that it was not 508 compliant.  

Underscore SHOULD be allowed in question id's.  I just checked the code again Yes it accepts underscores.  It wont however take lowercase letters, so I'm shocked that SrvBlUCOV19A1v1r0 works for you (It does not for me).

Try the following in [quest](https://episphere.github.io/quest/)
```
|grid|id="grid_test1"|This is the text on the top like... During the past year, how many times do you the following activities|[ [SRVBLUCOV19A1V1R0] Tie your shoes; [SRVBLU_COV19A_V1R0] Chew Gum; [SrvBlUCOV19A1v1r0] Hop on one foot;]|(1:Never) (2:less than Once per week) (3:less than once per day) (4: more than once per day)|

|grid|id="grid_test2"|This is the text on the top like... During the past year, how many times do you the following activities|[ [SRVBLUCOV19A1V1R0] Tie your shoes; [SRVBLU_COV19A_V1R0] Chew Gum; [XX] Hop on one foot;]|(1:Never) (2:less than Once per week) (3:less than once per day) (4: more than once per day)|

[END] End of Module
```

**Comment by huip-ims** [comment]
Hi Daniel - My apologies for the confusion. I did upcase all the letters prior to testing.

From your example, this is error I'm getting in the renderer whenever I select a response for 'Chew gum' that has the underscores in the variable name.

![image](https://user-images.githubusercontent.com/82978291/152212240-98a8cdc3-b322-48f6-a0b5-2d66bbdc6258.png)

**Comment by danielruss** [comment]
@huip-ims  you have found out a bug in the code that is only exposed if the question id has an underscore.

**Comment by danielruss** [comment]
Fix bug and the error no longer appears.

**Comment by huip-ims** [comment]
@danielruss Thanks Daniel, the grid is working now after your bug fix.
@cusackjm Julie - For question 21 ([SrvBlU_COV6_v1r0] The [first/2nd/3rd/etc.] time you had COVID-19, did you have any symptoms?), the 'No' response is skipping to [SrvBlU_COV23_v1r0], which is question 44 and outside of the # times you had COVID-19 loop. Should it instead skip to question 24 ([SrvBlU_COV9_v1r0], septic shock) or at most to the end the loop at question 39 [SrvBlU_COVSUMMARY_v1r0]? This way, we can loop back to question 18 [SrvBlU_COV3_v1r0] to ask Month/Year for any subsequent times had COVID-19.

**Comment by cusackjm** [comment]
Hi @huip-ims, for question 21 ([SrvBlU_COV6_v1r0], if someone selects "no" they should be done with the loop. If you cant have them skip to [SrvBlU_COV23_v1r0], then they should skip to question 39 [SrvBlU_COVSUMMARY_v1r0].

**Comment by huip-ims** [comment]
@cusackjm Hi Julie - For question 21 [SrvBlU_COV6_v1r0], I set the ‘no’ response to skip to question 39 [SrvBlU_COVSUMMARY_v1r0]. This will allow the loop the continue for the number of passes based on “# of times you had COVID-19”.  Below, I have some additional questions.

Should we set a value limit for the following numeric text boxes: # times you had COVID-19, # nights stay in hospital when you had COVID-19, # months take to recover from COVID-19, and # of shots of vaccine did you get?  If so, please let me know the limit for each.

For # of days with oxygen (by mask or nose), # of days with a breathing tube or ventilator, # of days with ICU monitoring, and # of days received dialysis treatment, should we cap these at the response value for ‘# nights stay in hospital when you had COVID-19?

For grids involving Symptoms (SrvBlU_COV19A_v1r0, SrvBlU_COV19B_v1r0, SrvBlU_COV19C_v1r0, SrvBlU_COV20A_v1r0) and Health Problems (SrvBlU_COV23A_v1r0, SrvBlU_COV23B_v1r0, SrvBlU_COV24A_v1r0), the column headers are currently in bold. Please confirm if these should be bolded in the grid.

For question #44, the display if condition is “IF ((SrvBlU_COV5_v1r0 =0) OR (SrvBlU_COV6_v1r0= 0)) then display [SrvBlU_COV23_v1r0]”.  SrvBlU_COV5_v1r0 and SrvBlU_COV6_v1r0 are within the “# times you had COVID-19” loop.  Therefore, there could be multiple sets of responses for SrvBlU_COV5_v1r0 and SrvBlU_COV6_v1r0, depending of the number of loops involved. For example, if a subject had COVID-19 5 times, this subject will have 5 sets of SrvBlU_COV5_v1r0 and SrvBlU_COV6_v1r0 responses (i.e., SRVBLU_COV5_V1R0_1_1, SRVBLU_COV6_V1R0_1_1, …, SRVBLU_COV5_V1R0_5_5, SRVBLU_COV6_V1R0_5_5). Should [SrvBlU_COV23_v1r0] be displayed if any of these 10 variables have a response value of 0?

**Comment by cusackjm** [comment]
Hi!

We do not want a value limit for # times you had COVID-19 and # nights stay in hospital when you had COVID-19. We do want the value limit for the # of shots of vaccine did you get to be 10. Is it possible to set the value limit for # months take to recover from COVID-19 to be based on the response from question 18 COV3?

Yes, For # of days with oxygen (by mask or nose), # of days with a breathing tube or ventilator, # of days with ICU monitoring, and # of days received dialysis treatment, please cap these at the response value for ‘# nights stay in hospital when you had COVID-19.

For grids involving Symptoms (SrvBlU_COV19A_v1r0, SrvBlU_COV19B_v1r0, SrvBlU_COV19C_v1r0, SrvBlU_COV20A_v1r0) and Health Problems (SrvBlU_COV23A_v1r0, SrvBlU_COV23B_v1r0, SrvBlU_COV24A_v1r0), the column headers are currently in bold, which is an error. I will go back into the Questionnaire Word Documents and un-bold them.

[SrvBlU_COV23_v1r0] is displayed for participants who have no had COVID-19 or have had COVID-19 but without symptoms. This question is not in the Loop and intended to be only asked once, regardless of the number of times the person had COVID-19.

**Comment by huip-ims** [comment]
@cusackjm @woodruffr  Hi Julie – For question #50 “[SrvBlU_COV29_v1r0] Here’s a summary of the information you shared about your COVID-19 vaccinations. If any of the information is incorrect, please select the “Back” button to update your responses. If all the information is correct, please select the “Next” button to move forward.”, currently this summary is outside of the loop for COVID-19 vaccine shots. This may be problematic for the end-user since it will require the participant to click the “Back” button numerous times if a response has to be changed from the earlier vaccine shots. Basically, the end user will have to unwind all of the loops to change the earlier vaccine shot responses. However, if the summary is placed within the loop, the end user can change the responses for each vaccine shot prior to moving on to the questions and summary for the next vaccine shot(s). Do you agree to move the vaccine summary to within the loop so a summary is displayed after each vaccine shot questions before moving on to the questions/summary for each subsequent vaccine shot?

**Comment by cusackjm** [comment]
Hi, Yes I agree. I can update the questionnaire word documents in box
