### ISSUE TITLE
Revise COV3 and COV27 range check min

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#343]
Revise COV3 and COV27 range check min from 3/2020 to 1/2020 

(participant feedback)

**Comment by woodruffr** [comment]
Mark-up delivered 8/15/2024.

**Comment by cunnaneaq** [comment]
@woodruffr can you confirm that this passed dev and stage?

**Comment by woodruffr** [comment]
Yes, this was listed as an issue to check and both COV3 and COV27 range checks on Dev and Stage testing.

**Comment by cunnaneaq** [comment]
Thank you!
