### ISSUE TITLE
Order of questions in mouthwash questionnaire

### ISSUE THREAD

**Issue by boyd-mj** [episphere/questionnaire#35]
Hi @cusackjm the mouthwash questionnaire is not ordered the way that we would expect based on the logic/skip patterns in previous modules, specifically in the section that ascertains oral hygiene product use. With the current order, it requires us to code some additional skip patterns that wouldn't otherwise be necessary. Would it be possible to make two changes so that the code flows a bit better? 

1. Maintain the order of the responses in the initial select all that apply question (#56) except to list mouthwash last:

0 [SrvMw_BRUSH1_v1r0] Toothbrush
1 [SrvMw_FLOSS1_v1r0] Floss
2 [SrvMw_WTRPICK1_v1r0] Water-based flosser or pick/jet
3 [SrvMw_TONGUE1_v1r0] Tongue Cleaner or Scraper
4 [SrvMw_WHITE1_v1r0] Teeth-whiteners (strips, etc.)
5 [SrvMw_MW1_v1r0] Mouthwash

2. Move the select all that apply type of mouthwashes question (#57) to after the teeth whitening question (#62) and before the set of mouthwash frequency questions (questions #63-70)

If you want to maintain the current order, we can accommodate that  as well. Thanks for considering. 
Jen

**Comment by boyd-mj** [comment]
@cusackjm yes, that's correct

**Comment by cusackjm** [comment]
@boyd-mj those changes are ok I will update the questionnaire word documents

**Comment by boyd-mj** [comment]
IMS confirmed these changes were made and will update the markup accordingly.
