### ISSUE TITLE
Spanish M3: HOOKAH9C has option 5 which should not be present

### ISSUE THREAD

**Issue by okisahia** [episphere/questionnaire#354]
Hi Julie,

Similar to ELMAR9A and ECIG9A, HOOKAH9C in the Spanish questionnaire has an option 5 (did not use xyz) which is not present in the English Questionnaire or DD. Please remove for Spanish questionnaire if it is indeed an error.

**Comment by cusackjm** [comment]
That's not an error.. Its in the english qx documents and DD. Are you looking at the latest versions?

**Comment by okisahia** [comment]
Hi Julie,

You might be looing at HOOKAHLIFE?

HOOKAH9C does not have an option 5 in the English questionnaire or DD. See screenshots below. 

![image](https://github.com/episphere/questionnaire/assets/111081733/90247f7a-953c-4fbb-8fb8-d91f9cfb6e6c)

![image](https://github.com/episphere/questionnaire/assets/111081733/fff1eab6-8d7b-4197-96e4-2ee2c4a18711)

![image](https://github.com/episphere/questionnaire/assets/111081733/facb8106-86cd-49fc-8ad9-f6ee8c08573d)

**Comment by cusackjm** [comment]
sorry, yes you are correct. Please remove that response from ELMAR9A and ECIG9A, HOOKAH9C

**Comment by okisahia** [comment]
Done please accept changes.

**Comment by okisahia** [comment]
I also removed option 0 because it is not present in the English version. Please accept changes if you have no objections.

**Comment by cusackjm** [comment]
> Hi Julie,
> 
> You might be looing at HOOKAHLIFE?
> 
> HOOKAH9C does not have an option 5 in the English questionnaire or DD. See screenshots below.
> 
> ![image](https://private-user-images.githubusercontent.com/111081733/331649173-90247f7a-953c-4fbb-8fb8-d91f9cfb6e6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NzczNzQsIm5iZiI6MTcxNTk3NzA3NCwicGF0aCI6Ii8xMTEwODE3MzMvMzMxNjQ5MTczLTkwMjQ3ZjdhLTk1M2MtNGZiYi04ZmI4LWQ5MWY5Y2ZiNmU2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QyMDE3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmU0ODM5MmFlMjk2YWMyNDk5MTYzYjRkNjAzNzQyNTQ5ZDU1N2U2NTIxZmIxMjQ5NTE1MjMwYTVhZWY5MzNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GZe1TrI-FOyJJurPqkdatXaC-36-HSsnxc7nrO-ksPs)
> 
> ![image](https://private-user-images.githubusercontent.com/111081733/331651516-fff1eab6-8d7b-4197-96e4-2ee2c4a18711.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NzczNzQsIm5iZiI6MTcxNTk3NzA3NCwicGF0aCI6Ii8xMTEwODE3MzMvMzMxNjUxNTE2LWZmZjFlYWI2LThkN2ItNDE5Ny05NmU0LTJlZTJjNGExODcxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QyMDE3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNThlM2QwZjUzN2UzMDNhNmRjZDRlNWY5ODhiYzU1YjM4YTJjOWVkYzdhZjhiZDIzZjQ3ZGJhNWM0Yzk2NjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OJ7pwKhAL6Af7eRymBmwiu5W3hc6EwZ5MOe0RLWFQqI)
> 
> ![image](https://private-user-images.githubusercontent.com/111081733/331648957-facb8106-86cd-49fc-8ad9-f6ee8c08573d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NzczNzQsIm5iZiI6MTcxNTk3NzA3NCwicGF0aCI6Ii8xMTEwODE3MzMvMzMxNjQ4OTU3LWZhY2I4MTA2LTg2Y2QtNDlmYy04YWQ5LWY2ZWU4YzA4NTczZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QyMDE3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDI3YTNlZTk0Mjg4NjFmMWI3NTcwMzFhYjMyMzQ0ZTViMmM4ZTZhYjI1MTRlODc4MTlhNTQ0ZDg2MDI5NDljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HfenoI2zqLR4YM5MP2OUPEh-bTy0-BipawohPd-f76Q)

Tracked changes accepted

**Comment by cusackjm** [comment]
> I also removed option 0 because it is not present in the English version. See screenshots below. Please accept changes if you have no objections.
> 
> ![image](https://private-user-images.githubusercontent.com/111081733/331686004-76f91b1a-c637-4f04-9144-e2d69965c942.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NzczNzQsIm5iZiI6MTcxNTk3NzA3NCwicGF0aCI6Ii8xMTEwODE3MzMvMzMxNjg2MDA0LTc2ZjkxYjFhLWM2MzctNGYwNC05MTQ0LWUyZDY5OTY1Yzk0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QyMDE3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2JmZWNkNTAzNTU5NTk1YzJiZDE1ZTI0N2E1ZDNhNzc3Yjc1MzdkNzcxOGFkZDhlZTlhMmU1YTAwNDhhZDc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a194Hi_9NT-KchN4byhSte4D5f8M32bfomoGgh-fRSc)

The response should NOT be deleted. The responses are the same, but the Connect Values in the English and Spanish qx documents (44, 0-8) do not match the DD (44, 1-9). Are Connect Values incorporated in the markdown? If so, either the DD or Qx documents should be updated to reflect the markdown. 

![image](https://github.com/episphere/questionnaire/assets/85582895/3b234f52-d64c-4d3b-9d03-57e1a5eb180f)
![image](https://github.com/episphere/questionnaire/assets/85582895/552a2e97-9c48-479c-a370-99e1028ee0af)
![image](https://github.com/episphere/questionnaire/assets/85582895/9e9bad22-bcc4-4870-b1a3-c698497a4e49)

**Comment by woodruffr** [comment]
The Connect Values are incorporated in the mark-up and link it to the Concept ID. We thought it would be easier to update the Questionnaire for them then change the data dictionary. (The English Mark-up was using the 1-9 plus 44, which matches the dd.)

**Comment by cusackjm** [comment]
@woodruffr qx documents were updated to reflect markdown

**Comment by woodruffr** [comment]
Thanks.

**Comment by woodruffr** [comment]
Spanish M3 has been delivered, but since it is an initial delivery, I would expect this issue to be a part of the regular testing.

**Comment by cusackjm** [comment]
HOOKAHLIFE= 5 response was removed accidentally (I think because of 9A discrepancy above). I added it back in tracked changes- please update markdown. 

I found the ELMARLIFE= 5 in ELMAR9A (which was inaccurate, but meant to be in ELMARLIFE). I added it to ELMARLIFE in tracked changes- please update markdown

I cannot find the response=5 for ECIG in either ECIGLIFE and ECIG9A. @m-j-horner what are the next steps? (This was an issue on the translators part- should we be concerned of their copying and pasting?)

**Comment by joshid-ims** [comment]
This is for June or August release?

I will wait for Marie-Josephe's response too.

**Comment by m-j-horner** [comment]
June, please.

thanks Julie for raising the copy/paste issue from translators. please revise the markdown so it is consistent with English version.

**Comment by woodruffr** [comment]
I have confirmed that all these changes were made.

**Comment by boyd-mj** [comment]
@cusackjm this issue can be closed
