### ISSUE TITLE
Spanish BlU has typo in GRID_SRVBLU_MED1_V1R0

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#355]
Found in Dev testing. 

The mark-up doesn't match the Questionnaire for GRID_SRVBLU_MED1_V1R0. IMS will update the mark-up to match the Questionnaire for Spanish Blood/Urine survey. 

![image](https://github.com/episphere/questionnaire/assets/81166095/a36593d8-f432-40bc-8efb-30b664007c79)

From the Questionnaire:

![image](https://github.com/episphere/questionnaire/assets/81166095/058171ad-ab24-4f37-9828-1bd186175a73)

**Comment by woodruffr** [comment]
Updated issue as this is only in Blood/Urine survey.

**Comment by woodruffr** [comment]
This issue has been fixed and is included in tonight's delivery.

**Comment by huip-ims** [comment]
Can confirm "aspirina" & "omeprazol" typos have been corrected during Dev retest.
