### ISSUE TITLE
End message of Menstrual Cycle survey appearing in English

### ISSUE THREAD

**Issue by boyd-mj** [episphere/questionnaire#358]
Hi Julie,

When testing the Menstrual Cycle survey in dev using Scenario 1, the end message is appearing in English. However, I checked the converted markup (https://app.box.com/file/1459508486122) and it's in Spanish there. Can you maybe confirm the version on dev is the same as the one I'm looking at. It should have this as the version at the top: 
Thu Feb 29 15:38:23 2024 -0500 (short timestamp = 2024-02-29-20-38-23)

Otherwise, not sure why this would be happening? FYI, testing was done on 5/23 on a PC using Chrome. 

Thanks,
Jen

**Comment by m-j-horner** [comment]
@cusackjm  can you replicate this ?

**Comment by cusackjm** [comment]
I believe this end message is not programmed in the markdown. 
![image](https://github.com/episphere/questionnaire/assets/85582895/86381b7c-8e8d-4fc9-9f75-2e1218784bb6)

@Davinkjohnson can you confirm?

**Comment by boyd-mj** [comment]
@Davinkjohnson any thoughts on this?

**Comment by boyd-mj** [comment]
End message being overwritten by what's in the PWA. IMS will keep the code in the survey as a backup.
