### ISSUE TITLE
SRVBLU_MENS2_V1R0 Range Check Doesn't Work on iPhone

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#359]
The min (no more than 60 days ago) and max (no later than today) ranges don't work on an iPhone with Safari.

This is from a PC:

![image](https://github.com/episphere/questionnaire/assets/81166095/c67cf3f5-b877-45eb-98bd-4fbee4a90158)

This is from the iPhone:

![image](https://github.com/episphere/questionnaire/assets/81166095/56850f56-4e24-4e57-bbea-75f2d6b24158)
_After clicking next, it took me to the next page while keeping the out-of-range date._
![image](https://github.com/episphere/questionnaire/assets/81166095/f0846492-bd5f-4eec-ad75-0b606439c862)

![image](https://github.com/episphere/questionnaire/assets/81166095/429f4160-ff13-4179-8efd-0f2174c65778)

**Comment by boyd-mj** [comment]
Flagging this so we can test in stage

**Comment by boyd-mj** [comment]
@cusackjm can you please make sure your team checks this when they test menstrual cycle in stage?

**Comment by cusackjm** [comment]
@boyd-mj yes- will update this issue after we test

**Comment by boyd-mj** [comment]
We are encountering this issue again when testing Menstrual Cycle in stage using Safari.

**Comment by boyd-mj** [comment]
@cunnaneaq @m-j-horner Sorry, to add more information, last time we believed this had to do with overriding the normal time-lapse in triggering the survey. Since Gene had to manually trigger the surveys we tested, we suspect that's the case here again. Can you confirm that we do not need to be concerned about this? Thanks!

**Comment by woodruffr** [comment]
This has been tested for Menstrual Cycle Stage Testing Scenario 2 by waiting for the natural trigger. The account was retested with a Mac and Safari, and the survey passed all testing for that scenario/browser combination.

![image](https://github.com/user-attachments/assets/37475850-ca1e-4321-ae93-b361de6fa3c5)
