### ISSUE TITLE
Change "questionnaire" to "survey" in thank you

### ISSUE THREAD

**Issue by boyd-mj** [episphere/questionnaire#36]
[From:]() Boyd-Morin, Jennifer (IMS) 
Sent: Friday, February 25, 2022 11:57 AM
To: Cusack, Julie (NIH/NCI) [C] <[julie.cusack@nih.gov](mailto:julie.cusack@nih.gov)>
Cc: Brotzman, Michelle (NIH/NCI) [E] <michelle.brotzman@nih.gov>; DePietro, Deanna (NIH/NCI) [C] <deanna.depietro@nih.gov>; Roberts, Amelia (NIH/NCI) [C] <amelia.roberts@nih.gov>
Subject: RE: Edit to 'Thank you' Message at end of Surveys

Hi Julie,

Yes, we can make this change. Would you mind updating the questionnaires on Box and then we will proceed?

Thank you,
Jen

From: Cusack, Julie (NIH/NCI) [C] <julie.cusack@nih.gov> 
Sent: Friday, February 25, 2022 11:22 AM
To: Boyd-Morin, Jennifer (IMS) <[Boyd-MorinJ@imsweb.com](mailto:Boyd-MorinJ@imsweb.com)>
Cc: Brotzman, Michelle (NIH/NCI) [E] <[michelle.brotzman@nih.gov](mailto:michelle.brotzman@nih.gov)>; DePietro, Deanna (NIH/NCI) [C] <[deanna.depietro@nih.gov](mailto:deanna.depietro@nih.gov)>; Roberts, Amelia (NIH/NCI) [C] <[amelia.roberts@nih.gov](mailto:amelia.roberts@nih.gov)>
Subject: Edit to 'Thank you' Message at end of Surveys

Hi Jen,

Is it possible to change a word in the ‘thank you’ message at the end of the surveys? Currently the screen looks like this:  
We would like the message to say “Thank you for completing the survey.” (instead of questionnaire). This is to maintain consistency on the screen, as the submit button states ‘survey’ and we also refer to ‘surveys’ for all participant facing materials. Please let me know if this is possible.

Thanks!

Best,
Julie

Julie Cusack [C] • Operational Development Coordinator
Division of Cancer Epidemiology and Genetics
National Cancer Institute, National Institutes of Health
9609 Medical Center Drive, Rockville, MD 20850
[C] N4 Solutions, LLC
E: [julie.cusack@nih.gov](mailto:julie.cusack@nih.gov)
P: 240-276-5861

**Comment by cusackjm** [comment]
Closing remark "Thank you for completing this section of the survey" has been added to the Module 1, 2, 3, 4 Box documents.

Closing remark "Thank you for completing the survey" has been added to the biospecimen Box documents in DCEG and IMS folders and the SSN Box document in the DCEG folder. I have not found an IMS version of the SSN Box Document.
