### ISSUE TITLE
WEIGHTHIS textbox displayed for age not displayed

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#360]
WEIGHTHIS textbox displayed for age not displayed

Stage testing- participant is 48 and doesn't see the question for weight at 55, but the textbox is displayed

![image](https://github.com/episphere/questionnaire/assets/85582895/a7d7d2e8-bcf9-4d50-b7e1-c4efd4b280a6)

**Comment by cusackjm** [comment]
![image](https://github.com/episphere/questionnaire/assets/85582895/b4621a90-a679-4f41-8fba-04ab04572e1a)

**Comment by boyd-mj** [comment]
This issue has been fixed and is being retested

**Comment by boyd-mj** [comment]
@cunnaneaq This issue has been confirmed fixed
