### ISSUE TITLE
Incorrect skip pattern in Module 1, MHGROUP6 to MHGROUP7

### ISSUE THREAD

**Issue by boyd-mj** [episphere/questionnaire#361]
Hi Julie & Aileen,

While testing the Spanish Module 1 survey in dev, we encountered a skip pattern issue due to the antiquated "NR" coding (this coding was removed from Modules 3 & 4, but set as low priority for Modules 1 & 2 due to other deadlines) that causes you to be rerouted to the MHGROUP6 gout question rather than moving forward to MHGROUP7 after the MHGROUP7 intro text. This came up when testing scenario 3 from the template you provided:

![image](https://github.com/episphere/questionnaire/assets/80920570/ba403f7c-b3a6-48b6-8752-d19f5c59279a)

We checked and found this same issue exists when we test the English version of Module 1 in the renderer. We're wondering if you know whether this scenario was tested when your team did testing of the English surveys in dev/stage and passed or whether it perhaps wasn't tested? The former would point to a possible change in Quest that is affecting these NR codes and we want to make sure we don't miss this issue in other places if that's the case.

I hope that makes sense. Please let me know if you need more information.
Thanks!
Jen

**Comment by boyd-mj** [comment]
@Davinkjohnson we removed unnecessary 'NR' skips. We've already discussed with Anthony & Daniel and they are looking into this. The outstanding question for Julie/Aileen is whether this scenario was tested in the English back in Dec.

**Comment by cusackjm** [comment]
@boyd-mj can you provide the scenario and what happened? (Similar to what rose provided in this issue: https://github.com/episphere/questionnaire/issues/366) Aileen and I are not following.

**Comment by woodruffr** [comment]
This is from Scenario 3. Mulitple testers could not finish Scenario 3 because of these skip pattern issues. The unneccessary NRs were removed from the Spanish M1 survey, but are still in the English version. These unnecessary NRs were removed from some other surveys, but not M1. @joshid-ims  is most familiar with this issue.

![image](https://github.com/episphere/questionnaire/assets/81166095/0c5ad464-736d-46e0-95f7-e368c5a1359e)

**Comment by cusackjm** [comment]
We understand the issue and replicated it in English too

**Comment by cusackjm** [comment]
Can we discuss this documentation during the call today? I recommend keeping _some_ NR directions (for the sake of testers and researchers who will need explicit directions when reading the surveys) and determining how we can indicate that these directions are not to programmed. 

E.g., putting symbols (+) around any directions that should not get programmed.
+NON-RESPONSE --> GO TO INTROSTD+

**Comment by cusackjm** [comment]
@boyd-mj does Tony need to attend the call today? My understanding is that the issues are identified and fixed in Spanish, and will also (eventually) get applied to English.
