### ISSUE TITLE
Spanish Baseline Module 1 Mark-up Language and Grammer Changes To Be Made

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#363]
These issues were found in Dev Testing. The Questionnaire is correct for these so NCI need do nothing with this. This issue is just to track that these issues were found and when they are tested to be confirmed as resolved.

This language is correct in the current Questionnaire. Please update the coding.

1. [INTROM1] is missing an "¡" before "Bienvenido". It also shows "Este es Example" when it should read: "Este es un ejemplo."
2. MHGROUP7 Response 3. Markup has English "Gonoorrhea" but should be Spanish "Gonorrea"
3. GONORR also has the English spelling when it should be "Gonorrea"
4. SIBNAME is missing a comma that is shown in the mark-up.
![image](https://github.com/episphere/questionnaire/assets/81166095/469c6493-d804-4f07-afda-d7fad3ebff3a)
5. CHILDNAME  is missing a comma.
![image](https://github.com/episphere/questionnaire/assets/81166095/425ec71b-0c37-4a0f-8be7-1dd26d7df492)

**Comment by woodruffr** [comment]
The mark-up for this issue was delivered this morning.

**Comment by cusackjm** [comment]
can i close this issue?

**Comment by guinevere83** [comment]
These are resolved.
