### ISSUE TITLE
Cancer Types Show Up in English and Spanish in SIBSUM

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#364]
This was found in Dev Testing and is only a mark-up change. The cancer type(s) show up in English and Spanish in each SIBSUM occurrence. There is nothing NCI needs to do regarding this. This issue is to document what was found so it can be confirmed as fixed in testing.

**Comment by woodruffr** [comment]
The mark-up for this issue was delivered this morning.

**Comment by cusackjm** [comment]
can you provide context to the issue? Similar to what was provided for this: https://github.com/episphere/questionnaire/issues/366

**Comment by woodruffr** [comment]
From Scenario 5:

![image](https://github.com/episphere/questionnaire/assets/81166095/6a5099e9-0a42-495f-a35a-7cb8a6d8441b)

**Comment by woodruffr** [comment]
This is confirmed fixed in Dev testing.
