### ISSUE TITLE
All Job Positions are listed in English OCCUPTN2

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#365]
Found in Dev testing. For Scenario 5, all Job Positions are listed in English. These get piped in from outside. @cusackjm Is this expected behavior? Is there an option to draw from a Spanish version?

**Comment by m-j-horner** [comment]
Thanks, Rose. 
I believe @Davinkjohnson  is aware of this and is working on it.

**Comment by boyd-mj** [comment]
We have confirmed this has been fixed.

**Comment by boyd-mj** [comment]
@cusackjm this can be closed
