### ISSUE TITLE
PROMIS- Spanish APIs

### ISSUE THREAD

**Issue by m-j-horner** [episphere/questionnaire#367]
Spanish APIs:
PROMIS SF v1.0 - Agotamiento 4a 
PROMIS SF v1.0 - Ansiedad 4a 
PROMIS SF v1.0 - Depresión 4a 
PROMIS SF v1.0 - Efectos del dolor  4a 
PROMIS SF v1.0 - Trastornos del sueño 4a 
PROMIS SF v2.0 - Capacidad de funcionamiento físico 4a 
PROMIS SF v2.0 - Capacidad para participar en roles y actividades sociales 4a 
PROMIS SF v2.0 - Función cognitiva 4a 

Notes: 
(Recall, we are not using the pain scale question in either language)

**Comment by m-j-horner** [comment]
@anthonypetersen 

I did not see the Spanish equivalent API for PROMIS SF v2.0 - Social Isolation 4

The Spanish name of the form is:  PROMIS SF v2.0 - Aislamiento social 4a

**Comment by anthonypetersen** [comment]
@m-j-horner I believe there should be 10 total forms? I believe the Social Satisfaction form is missing still.

**Comment by anthonypetersen** [comment]
@m-j-horner any updates on this?

**Comment by anthonypetersen** [comment]
@m-j-horner because we store answers as Concept IDs, I don't think it is necessary to reference the Spanish forms for getting scoring data. We can just use the logic we already have for translating Concept ID responses into scoring data.
