### ISSUE TITLE
Issues in Module 1 Scenario #5 Spanish

### ISSUE THREAD

**Issue by joshid-ims** [episphere/questionnaire#370]
If all options are selected along with 55 text box, they are not getting stored in the memory. The text value gets stored in question ID as well, not 55. 

![image](https://github.com/episphere/questionnaire/assets/64986739/dc4b6e4a-c9e3-4eae-ac0c-4a7833168973)

If I enter the text value first and then select the radio button,, it saves. 

![image](https://github.com/episphere/questionnaire/assets/64986739/39a33e7e-208c-4322-83a0-2d135acd0e0e)

Is it a Quest issue?

**Comment by cusackjm** [comment]
@joshid-ims can you provide the full scenario of what was entered

**Comment by joshid-ims** [comment]
It shows in the second screenshot all the entered values.

**Comment by cusackjm** [comment]
I can't read code can you send the testing template

**Comment by guinevere83** [comment]
[dev_testing_MOD 1_Spanish_Scenario5_202401612.xlsx](https://github.com/user-attachments/files/15838743/dev_testing_MOD.1_Spanish_Scenario5_202401612.xlsx)

Scenario 5 would work for this.

**Comment by cusackjm** [comment]
Ok so: If MHGROUP9= 5, BREASTSUR= 1-8 and 55 (and text is entered in textbox), BREASTSUR0-BREASTSUR9 are not displayed.

Did you test: MHGROUP9= 5, BREASTSUR= 1-8 and 55 (but no text is entered), if BREASTSUR0-BREASTSUR9 displayed?

**Comment by guinevere83** [comment]
Yes, that's correct. Interestingly, if you check the box for 55 and enter text, nothing will display, but if you enter the text first, then follow-ups will display.

**Comment by anthonypetersen** [comment]
This should be resolved now

**Comment by joshid-ims** [comment]
Thanks!

**Comment by woodruffr** [comment]
**These are IMS-only mark-up changes. Documenting them here to confirm changes in the delivered mark-up.**

Additional issues found…
HYSTER: This Q looked to appear 2X, but on the 2nd iteration, the textbox was already populated with the previous answer

The rest are small typos
MOMCANC3M and N, DADCANC3L and M: "Linfoma" should start in lowercase

MOMCANC3V and DADCANC3U: There is a space before "?"

**Comment by guinevere83** [comment]
These issues were tested in the PWA and they appear resolved.
