### ISSUE TITLE
comenzar missing underline in FATIGUE7D2

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#374]
![image](https://github.com/episphere/questionnaire/assets/85582895/d6f48b98-4bbf-41e5-8eb5-39dbf0befd8c)
![image](https://github.com/episphere/questionnaire/assets/85582895/36913a4b-7c41-4a9b-8407-2f1f54de6069)

**Comment by joshid-ims** [comment]
Is it for August? And which survey?

**Comment by cusackjm** [comment]
july prod push and quality of life survey (see labels)

**Comment by huip-ims** [comment]
The updated markdown has passed IMS internal testing and is ready to deliver.

**Comment by woodruffr** [comment]
This has been fixed. Screenshots from Dev testing today with laptop/Mozilla Firefox.
![image](https://github.com/episphere/questionnaire/assets/81166095/1ca29e8b-8dfd-408e-adb8-298617beb998)
