### ISSUE TITLE
Make "A" lower case in COGFUNCT7D1, COGFUNCT7D2, COGFUNCT7D3, COGFUNCT7D4

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#375]
![image](https://github.com/episphere/questionnaire/assets/85582895/12121de4-28a7-4d4e-97fe-e34e13e00bbc)
![image](https://github.com/episphere/questionnaire/assets/85582895/ebf79ce1-873a-4bcc-9ad1-358dfbf03daf)

**Comment by joshid-ims** [comment]
Is it for August? And which survey?

**Comment by cusackjm** [comment]
July and Quality of Life

**Comment by huip-ims** [comment]
The updated markdown has passed IMS internal testing and is ready to deliver.

**Comment by woodruffr** [comment]
This has been fixed. These screenshots are from Dev testing today with laptop/Firefox:
![image](https://github.com/episphere/questionnaire/assets/81166095/fb62f2c1-485a-4d92-950d-294ef6b8fbc8)

![image](https://github.com/episphere/questionnaire/assets/81166095/3b44fceb-dc2b-4cda-9dcc-7046434a82ea)
