### ISSUE TITLE
{##} function does not show spanish superscript

### ISSUE THREAD

**Issue by joshid-ims** [episphere/questionnaire#377]
It shows 1st. Should be 1er.

**Comment by anthonypetersen** [comment]
@joshid-ims decision was made to always use "o" [1.o, 2.o, etc.]

@cusackjm do you know what word doc is being referenced?

**Comment by cusackjm** [comment]
Spanish Module 2: https://nih.app.box.com/file/1482403616622
![image](https://github.com/episphere/questionnaire/assets/85582895/2523ebed-8011-4c64-a9f8-2914e75f973e)

The discrepancy may be because of different translators? E.g., Covid Spanish uses "a". 
![image](https://github.com/episphere/questionnaire/assets/85582895/ca9784ea-7ca3-4bb6-82a9-141129ec3b9f)

**Comment by joshid-ims** [comment]
Also in Module 2, is this a PWA issue?

![image](https://github.com/episphere/questionnaire/assets/64986739/7cccb6f1-ae03-4464-88ae-c273c1f6f817)

**Comment by cusackjm** [comment]
> Also in Module 2, is this a PWA issue?
> 
> ![image](https://private-user-images.githubusercontent.com/64986739/347023399-7cccb6f1-ae03-4464-88ae-c273c1f6f817.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1Mzk5MzQsIm5iZiI6MTcyMDUzOTYzNCwicGF0aCI6Ii82NDk4NjczOS8zNDcwMjMzOTktN2NjY2I2ZjEtYWUwMy00NDY0LTg4YWUtYzI3M2MxZjZmODE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDE1NDAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NzlhYWUwMTY3MGY1MzU5ZTJmM2NkMjc2NmEwZjdkNTMzNWI5Y2M5NzlkNGY3YjFmNGJiZTY2N2FmOGExMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Y7iyuQUrl0Lsx-M2xRaGSlvT89fkcrhmf7AB-mjlJw)

can you create a separate issue and provide more context @joshid-ims

**Comment by boyd-mj** [comment]
> > Also in Module 2, is this a PWA issue?
> > ![image](https://private-user-images.githubusercontent.com/64986739/347023399-7cccb6f1-ae03-4464-88ae-c273c1f6f817.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1Mzk5MzQsIm5iZiI6MTcyMDUzOTYzNCwicGF0aCI6Ii82NDk4NjczOS8zNDcwMjMzOTktN2NjY2I2ZjEtYWUwMy00NDY0LTg4YWUtYzI3M2MxZjZmODE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDE1NDAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NzlhYWUwMTY3MGY1MzU5ZTJmM2NkMjc2NmEwZjdkNTMzNWI5Y2M5NzlkNGY3YjFmNGJiZTY2N2FmOGExMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Y7iyuQUrl0Lsx-M2xRaGSlvT89fkcrhmf7AB-mjlJw)
> 
> can you create a separate issue and provide more context @joshid-ims

This was addressed in a separate issue and the 'o' changes have been made. This issue can be closed.
