### ISSUE TITLE
Text edits to Spanish Module 1: BREASTSUR=8 and BREASTSUR8

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#378]
See tracked changes: https://nih.app.box.com/file/1482398132570

**Comment by cusackjm** [comment]
was this tested?

**Comment by huip-ims** [comment]
@cusackjm Julie - The text "microdiscectomía" was removed from BREASTSUR and BREASTSUR8, tested at IMS, and the updated markdown was delivered on 07/11/2024.
