### ISSUE TITLE
Button and instruction texts different

### ISSUE THREAD

**Issue by joshid-ims** [episphere/questionnaire#379]
The Word doc has this Spanish instruction “Ha respondido a todas las preguntas de este cuestionario. Para enviar sus respuestas, seleccione el botón “Enviar cuestionario”, but the submit button is labeled as "Enviar Encuesta"

**Comment by cusackjm** [comment]
can you provide the variable fir that text?

**Comment by joshid-ims** [comment]
It is the Submit button.

**Comment by cusackjm** [comment]
do you mean the end message?

**Comment by joshid-ims** [comment]
Yes

**Comment by cusackjm** [comment]
I will look into it. Is this only in Module 2? If not, please list the other surveys

**Comment by cusackjm** [comment]
Module 2 is updated to reflect button

**Comment by joshid-ims** [comment]
Thanks. We will check other modules.

**Comment by joshid-ims** [comment]
Pete found: the closing remark at the end of surveys M1-M4 are the same in the Word docs, so the Submit button issue is in other modules too.

**Comment by cusackjm** [comment]
End messages for baseline modules are updated

**Comment by joshid-ims** [comment]
Thanks

**Comment by joshid-ims** [comment]
I have removed "Submit Survey" in all Spanish surveys. Hope that is ok. Also, we will need to update the documents too.

**Comment by woodruffr** [comment]
This was found in Menstrual Cycle.

**Comment by woodruffr** [comment]
I note that since the mark-up matches the July Prod Push Questionnaire, we will not be making that change at this time.
