### ISSUE TITLE
Piped Text in Grids

### ISSUE THREAD

**Issue by huip-ims** [episphere/questionnaire#38]
@boyd-mj @FrogGirl1123 Hi Julie - For the COVID-19 Symptoms grid [SrvBlU_COV20A_v1r0] and the Health Problems grid [SrvBlU_COV24A_v1r0], these are asking for piped text from previous "Other [Free text box]" .  Quest currently does not have this functionality in grids.  Would NCI like to make Questionnaire changes or implement Quest changes?

**Comment by cusackjm** [comment]
We can implement questionnaire changes. Waiting to finalize the question language/format. I will comment here when the Questionnaire Box document is updated

**Comment by cusackjm** [comment]
Questionnaire box document has been updated
