### ISSUE TITLE
Spanish Module 1, stuck at CHILD2

### ISSUE THREAD

**Issue by huip-ims** [episphere/questionnaire#381]
@anthonypetersen Hi Tony, during DEV testing, I was getting stuck at CHILD2 (what biological sex was this child assigned at birth?). For each child in the loop, I could not move forward to the next question after I selected a response. I was stuck on this screen. The "Seguiente" (next) button did not work, but clicking the "Atrás" (back) button did move to the next question. Several of us have experienced this on different devices and browsers in DEV testing.

**Comment by anthonypetersen** [comment]
@huip-ims can you please provide the response setup to duplicate the bug?

**Comment by huip-ims** [comment]
@anthonypetersen Tony, Scenarios 1-3 were being tested when this occurred.  Please see attached Excel file for the response set up.

[yyyy.mm.dd_Tier Testing_MOD 1_Spanish (All Text tested).xlsx](https://github.com/user-attachments/files/16167882/yyyy.mm.dd_Tier.Testing_MOD.1_Spanish.All.Text.tested.xlsx)

**Comment by cusackjm** [comment]
Issue replicated- There's a typo in the markdown:
![image](https://github.com/episphere/questionnaire/assets/85582895/6cbc81e2-e381-40d7-bc7e-112b0597d7b5)
![image](https://github.com/episphere/questionnaire/assets/85582895/724ff49a-fd72-45ae-9364-9adf91252bac)

**Comment by joshid-ims** [comment]
Thanks!

**Comment by woodruffr** [comment]
This was confirmed fixed in Dev testing.
