### ISSUE TITLE
Example text is different in BLDTRANS3 year textbox

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#382]
BLDTRANS3 shows:
![image](https://github.com/episphere/questionnaire/assets/85582895/92514d24-0c19-4f49-92bd-1b923f24a315)

All previous "Or(xor)" questions (e.g., MHGROUP follow up questions) look like this:
![image](https://github.com/episphere/questionnaire/assets/85582895/9f762341-418f-45f1-8a0b-55aa0d6d9ca2)

Would prefer to see this example format, rather than what is at BLDTRANS3 (it looks like something's broken)

**Comment by anthonypetersen** [comment]
`O, si le es más fácil recordar en qué año, anótelo aquí:<br/>
|__|__|__|__|xor=BLDTRANS3 id=D_197994844 min=#currentYear-valueOrDefault("D_150344905","age",100)-1 max=#currentYear| Año de la primera transfusión`
 
I think `min` is supposed to be `minvalue` like other instances where there is `|__|__|__|__|`

**Comment by joshid-ims** [comment]
We also see gray text in English in text boxes in renderer. Is that fixed in PWA?

**Comment by cusackjm** [comment]
@joshid-ims we are ok with the gray text existing, just not the additional text that is shown in BLDTRANS3

**Comment by joshid-ims** [comment]
Yes, that part is fixed. We were wondering if gray text should be in Spanish.

**Comment by cusackjm** [comment]
It is in spanish (see the above screenshot)

**Comment by joshid-ims** [comment]
But we see it in English in renderer. Is that expected?

**Comment by anthonypetersen** [comment]
The part that Julie has underlined in red shouldn't be displaying to begin with, if that's the text you are referencing @joshid-ims

**Comment by joshid-ims** [comment]
No, I am not referencing that. I have fixed code for that extra text. This issue we see only in renderer. In OWA, the gray text is in Spanish.

**Comment by anthonypetersen** [comment]
Please send a picture @joshid-ims

**Comment by guinevere83** [comment]
Here you go:

![image](https://github.com/user-attachments/assets/7e463f31-a9a1-4b0a-8251-fce1e53b0fd8)

**Comment by anthonypetersen** [comment]
Ah I see... So that text isn't controlled by the language of the markdown you are testing, it is controlled by Quest itself. It appears you have the language mode in English since the buttons are also in English, so the grey text being in English as well makes sense.

**Comment by anthonypetersen** [comment]
@woodruffr there isn't anything that needs to be fixed - the grey text being in English vs Spanish isn't dependent on the markdown if you're using the development tool, it's controlled by a setting within the tool itself

**Comment by woodruffr** [comment]
OK. I was just checking because we changed the dd/JSON values that aren't used by the Mark-down but are used by NCI to determine which language is being used. We are working on reverting them. I wasn't sure if that mattered, but if they are being set manually that wouldn't matter.

**Comment by huip-ims** [comment]
The grey text is in Spanish in our Dev testing, so I think this issue can be closed.
