### ISSUE TITLE
SIBSUM format and text edits

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#383]
Revisions to SIBSUM in Module 1

![image](https://github.com/episphere/questionnaire/assets/85582895/2b96d25a-d539-4258-8a59-80dabef3b198)

1. Can we format each part of the summary to be on its own line?
2. Remove space before semicolon "múltiple : No"
3. Remove ["Back"] and ["Next"] _I will update Qx documents if this is there_

**Comment by cusackjm** [comment]
Remove ["Back"] and ["Next"] in the following places:
_(Denoted in tracked changes in qx docs)_
Module 1: SIBCONFIRM, SIBSUM, CHILDCONFIRM, CHILDSUM
Module 2: PREGSUMMARY
Module 4: HOMEADD4, SEASADD4, CHILDADD4, CURWORKCONFIRM, PREWORKCONFIRM, CURSCHCONFIRM
Covid: COVSUMMARY, COV29

**Comment by joshid-ims** [comment]
There were line break characters after each line. I added one extra there. It is being tested now. 

Not sure why they were not showing up. We have seen issue with line breaks in the past too. It may depend also on the browser or devices from what I remember.

**Comment by cusackjm** [comment]
did this pass testing?

**Comment by huip-ims** [comment]
@cusackjm Julie - Deepti mentioned there was a line break already after each line in SIBSUM, but she went ahead and added a 2nd one.  Depending on device/browser and whether or not back button was used, there may be 1 or 2 line breaks displayed between each summary line in SUBSUM. The updated markdown was delivered on 07/11/2024.
