### ISSUE TITLE
Survey language switched to Spanish

### ISSUE THREAD

**Issue by okisahia** [episphere/questionnaire#387]
While testing M4 on android + chrome, I started the survey in Spanish but it auto-switched to English while within the survey and I can't switch back to Spanish.

![image](https://github.com/user-attachments/assets/58b892ca-445c-4e37-a244-a6203bf2f03b)

**Comment by anthonypetersen** [comment]
@okisahia what is the Connect ID of the participant?

**Comment by okisahia** [comment]
9662705526

**Comment by anthonypetersen** [comment]
@okisahia can you please try logging in and starting the survey using an incognito window?

**Comment by okisahia** [comment]
Back in Spanish now. Thank you
