### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#39]
@cusackjm We noticed two minor issues:

_47.	[SrvBlU_COV26_v1r0] How many shots of vaccine did you get?
__ [please have drop down (numeric)]
For each vaccination based on [SrvBlU_COV26_v1r0], [can we include an indicator of which shot?] i.e. for your first shot, for your second shot, for your third shot..._ 
As a matter of grammar, there should be a comma after the "i.e."

_56.	[SrvMw_HYGEINE_v1r0] Next, we have a few questions about your oral health and routine that will help us better understand your mouthwash (saliva) sample._
The "I" and "E" have been transposed on Hygiene.

**Comment by cusackjm** [comment]
I will update this in the same update for issue #37 and #38

**Comment by woodruffr** [comment]
Hi Julie,

Another very minor change is the Connect Value for _[SrvBlU_MENSTARTDATE_v1r0] MM/DD/[YYYY]() 
1 	This does not apply to [me]()_ should be a zero (0), not a 1. We are recommending that change in the data dictionary as well.

**Comment by cusackjm** [comment]
added to update

**Comment by cusackjm** [comment]
Questionnaire box document has been updated
