### ISSUE TITLE
Module 3 Spanish - piped response not chosen in response section

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#391]
[Module 3 Scenario 13 - Spanish](https://nih.app.box.com/file/1593010288380)
MacBook, Chrome, Account: qolsptest3@mailinator.com (8786700366)

Instructions in questionnaire document say to fill either fuma/fumaba and llena/llenaba.  Based on my response to PIPE 5 I should see fumaba and llenaba.  In the bolded response section, I am still seeing [llena/llenaba] in MyConnect.  I believe I should only see llenaba.  @cusackjm is that correct or is the slash ok in the response section?

[IF PIPE5 = 0 or NO RESPONSE, fill “fuma” and “llena” 
IF PIPE5 = 1 or 2, fill “fumaba” and “llenaba”]
[PIPE9A] Los días que [fuma/fumaba], ¿cuántas veces [llena/llenaba] la pipa de tabaco para fumar al día?  

**|__|__| Número de veces que [llena/llenaba] la pipa de tabaco para fumar al día** 

![Screenshot 2024-07-17 at 9 11 33 PM](https://github.com/user-attachments/assets/703ab2d7-7f7c-4055-8e9f-aa5c4551aa0d)

**Comment by cusackjm** [comment]
@cunnaneaq both shouldn't get piped in

@joshid-ims is this a markdown issue?

**Comment by huip-ims** [comment]
Yes, we found this during Dev testing and made the fix. It's going through internal testing now before delivery.

**Comment by huip-ims** [comment]
This has passed IMS internal testing and is ready to deliver.

**Comment by boyd-mj** [comment]
@cusackjm this issue can be closed
