### ISSUE TITLE
Module 3 Spanish - typo in question in ELMAR9A

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#392]
Module 3 Spanish
Macbook, Chrome, Account (qolsptest3@mailinator.com)

Pipe filled question text should read "los usaba" instead reads "losba"

![Screenshot 2024-07-18 at 9 55 00 AM](https://github.com/user-attachments/assets/1b67b9f0-7298-4ab4-9f7f-0f56763acd66)

![Screenshot 2024-07-18 at 9 55 47 AM](https://github.com/user-attachments/assets/ce6e4591-aef4-45cc-914f-cc7f2080cc11)

**Comment by huip-ims** [comment]
We also found this during Dev testing and made the fix. It's going through internal testing now before delivery.

**Comment by huip-ims** [comment]
This has passed IMS internal testing and is ready to deliver.
