### ISSUE TITLE
Spanish M4 Dev Testing Scenario 9 Issues - Mostly Mark-up Only

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#393]
I'm documenting this here so we know what changed in the mark-up delivery and we know what needs to be retested. I note that bolding on the Home Address section is an issue that will need to be revisited in English and Spanish. It is obviously not a priority since the bolding was published in English that way. Also, there is one testing template change, but that will be addressed elsewhere.

[dev_testing_MOD 4_Spanish_Scenario9_20240712.PTH_Comments.xlsx](https://github.com/user-attachments/files/16285494/dev_testing_MOD.4_Spanish_Scenario9_20240712.PTH_Comments.xlsx)

**Comment by cusackjm** [comment]
I think bolding can be addressed in August release. We should focus on non-aesthetic issues to meet the July dev testing deadline

**Comment by boyd-mj** [comment]
@woodruffr should the prod push label be changed to Aug for this issue? Or can you split out the bolding into a new issue if there were others implemented for this release? Thanks.

**Comment by cusackjm** [comment]
@boyd-mj I have separate issues for the mod 4 bolding issues already created, so closing this
