### ISSUE TITLE
Module 4 Spanish - remove period in HOMEADD1_2

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#397]
Spanish Module 4 Scenario 10
Macbook, Chrome, Account email (spanishtesting1@mailinator.com)

HOMEADD1_2  Remove 2nd period in question text

![Screenshot 2024-07-19 at 2 19 32 PM](https://github.com/user-attachments/assets/e991be04-e041-4fb3-bbaa-0a0de67c0363)

**Comment by huip-ims** [comment]
We've made this correction, passed internal testing, and it's ready to deliver.

**Comment by guinevere83** [comment]
This looks good on the PWA:

![image](https://github.com/user-attachments/assets/38945777-a7a9-456a-957e-833a5db7b4c3)
