### ISSUE TITLE
Extra Period in Spanish M2 INTROMENSHIS was removed in mark-up but not Questionnaire.

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#403]
This was included in https://github.com/episphere/questionnaire/issues/389#issue-2413855638, and corrected in the Mark-up but not addressed in the Questionnaire:
![image](https://github.com/user-attachments/assets/98659895-271b-4c4f-be45-66fc99d5ea68)

**Comment by cusackjm** [comment]
qx docs updated
