### ISSUE TITLE
Superscript for Spanish Module 2 PREG4 

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#404]
Although some attention was given to the PREG4 superscript in https://github.com/episphere/questionnaire/issues/377, the updated value does not appear as a superscript; it is in normal text. Both the English and Spanish documents have the st or o as a superscript. In Dev testing we noticed it is not raised. If it should be a superscript, then Tony will have to make this change. We can't do it in the markdown, since {##} is a function that NCI implemented. I'm assuming that this issue also appeared the last time the English M2 was tested, but we do not have those records to compare.

**Comment by cusackjm** [comment]
@anthonypetersen are you able to make the values superscript

**Comment by anthonypetersen** [comment]
@m-j-horner was superscript a requirement?

**Comment by m-j-horner** [comment]
@anthonypetersen Correct, we did not superscript the English ordinals in the past. 

If you have bandwidth and time to do superscripting of ordinals in English and Spanish, then great. 
Otherwise, let's move this to low priority in the bucket of "nice things to have" for user experience.

**Comment by anthonypetersen** [comment]
This has been added as an enhancement in another issue (https://github.com/episphere/connect/issues/926), closing.
