### ISSUE TITLE
Spanish Module 4 - CHILDADD1 has suite text in bold instead of italics

### ISSUE THREAD

**Issue by boyd-mj** [episphere/questionnaire#408]
Suite is in bold, should be in italics:
![image](https://github.com/user-attachments/assets/c0a382a8-464b-4e12-8f61-10d683b57bff)

IMS is updating the markup

**Comment by woodruffr** [comment]
The updated mark-up has been delivered for this change.

**Comment by boyd-mj** [comment]
This issue has been confirmed fixed
