### ISSUE TITLE
Module 2 (Medications, Eng & Spa): NR skip logic for "When was the last time you took [MED]?

### ISSUE THREAD

**Issue by huip-ims** [episphere/questionnaire#410]
@cunnaneaq @m-j-horner @cusackjm In the Medications section, I noticed the skip logic for NR is different for the same question. For PAINREL1, CHOLHTN, ACIDSUP, a NR response is directed to the next question in series (highlighted in yellow below).  However, for METFOR and INSULIN, a NR response is skipped to the next set of medication questions (highlighted in green below). Can you confirm if this was intentional or not?

![image](https://github.com/user-attachments/assets/0dfbe1ac-e98a-43cd-bb19-d02d5ed7f031)

![image](https://github.com/user-attachments/assets/2592197d-99bc-419c-a8b8-f01479cdb4d0)

![image](https://github.com/user-attachments/assets/d5e7d10e-9fce-41dd-9c4b-7297b154206a)

**Comment by cusackjm** [comment]
That's intentional

**Comment by huip-ims** [comment]
OK, thanks. This issue can be closed then.
