### ISSUE TITLE
Allowing and Limiting number of responses to 3 in Select all that applies question

### ISSUE THREAD

**Issue by joshid-ims** [episphere/questionnaire#411]
For requirement for question below, we need a functionality to allow users to select and limit to 3 responses for a Select all that applies type of question. Currently it allows as many. 

![image](https://github.com/user-attachments/assets/cbd4add7-780d-4eb2-9fff-2d48dd8eb11f)

**Comment by danielruss** [comment]
You can:
```
[A1|max-count=2] What are the top 2 reasons for joining Connect?
[1] Why not?
[2] I hear Martin gives doughnuts if you visit him in Mass.
[3] The $2.50 I get for giving out all my personal data.
[4] I like questionnaires?
[5] My boss required me.

[END] Thats all folks 
```

**Comment by joshid-ims** [comment]
Thanks, we will try that.

**Comment by woodruffr** [comment]
This survey passed Dev and Stage testing.
