### ISSUE TITLE
Spanish survey appears in English on Android

### ISSUE THREAD

**Issue by okisahia** [episphere/questionnaire#413]
Even though the selected language is Spanish the survey appears in English using Android + chrome. Survey appears as expected using PC+chrome on the same account. See attached screenshot.

![image](https://github.com/user-attachments/assets/e6c22c22-df50-4f5d-8b30-60ae0a0cbafa)

**Comment by m-j-horner** [comment]
@okisahia is this using a test account or was this reported from a real participant account?

**Comment by anthonypetersen** [comment]
@okisahia please provide details about the account

**Comment by okisahia** [comment]
Sorry for the delay. Yes, I was using QuestTest75.

I checked my browser and it does look like it was automatically translating the survey.

It looks good now. Thanks for the help

**Comment by cunnaneaq** [comment]
Awesome!
