### ISSUE TITLE
Race/ethnicity updates to Module 1 (Census)

### ISSUE THREAD

**Issue by m-j-horner** [episphere/questionnaire#417]
@huip-ims @joshid-ims 

Please see minor revisions to the race ethnicity intro text and question stem. These changes reflect the most recent OMB/census guidelines.

Updated English word document is here: https://app.box.com/s/at8aq42ia5xyeldkwk998lwabq5wk24l

Deepti- Please revise the Module 1 markdown. Thanks.  

I am working on Spanish.

**Comment by m-j-horner** [comment]
@joshid-ims @huip-ims Module 1 Spanish is posted : https://app.box.com/s/7q0i08ddh866grm2tp9x661dncoabthk

updates include: age range checks, revision to race/ethnicity question stem, and a minor correction to spanish translation of breast cancer response

**Comment by joshid-ims** [comment]
Thanks!

**Comment by joshid-ims** [comment]
Is the underline here is intentional? Also, is the period in the right place? 

![image](https://github.com/user-attachments/assets/f2ce3dbb-b242-4a04-9b38-87964916ddb0)

**Comment by m-j-horner** [comment]
It looks like the track changes just looked wonky. I cleaned up the punctuation. the phrase should not be underlined.

**Comment by woodruffr** [comment]
The English Questionnaire is not Italicized and the Spanish one is. Marie Joseph made changes to the English question in September, so I went back and checked the August 15 word doc, last edited by Julie. The English question did not have italics then:

![image](https://github.com/user-attachments/assets/fb88e221-e5c3-45b5-ad6c-506f2dfb8156)

The English Word document does not have italics now:

![image](https://github.com/user-attachments/assets/14004cc5-cb41-49d2-85ab-df95bd32f206)

We beleive the italics should be removed from the Spanich RACEETHINTRO.

![image](https://github.com/user-attachments/assets/56d03743-2bfd-45bf-a241-2624e61d80ee)

@m-j-horner, do you agree with that or is there some other reason it would be Italicized in Spanish?

**Comment by cunnaneaq** [comment]
@woodruffr updates look good in the Spanish mod 1 qx doc
