### ISSUE TITLE
[TESTTHER3] [TESTTHER5] [PRESHOR3] Age Range Checks

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#42]
Upper limit for age range is 55.  The age I entered when I signed up is 54.

**Comment by cunnaneaq** [comment]
When testing on 3/15 - My age is 52 (from mod 1) and the upper limit check says 54.  Need to clarify where this is pulling from.  Screenshot below is from [PRESHOR3]

<img width="347" alt="Screen Shot 2022-03-15 at 11 52 08 AM" src="https://user-images.githubusercontent.com/83971268/158417967-48a17acf-1ad9-4a35-a9ca-820bbd8edcf9.png">

**Comment by guinevere83** [comment]
Haven't been able to reproduce this on our end. Might be related to renderer differences.

**Comment by cusackjm** [comment]
Issue fixed 4/29/22 for account: 609-576-3460 and Connect ID: 9393372061.
