### ISSUE TITLE
Coding Cancer screening history survey- Spanish

### ISSUE THREAD

**Issue by joshid-ims** [episphere/questionnaire#428]
One question - Is the MHGROUP9 section in Module1 and Cancer screening history survey supposed to be exactly the same? WHen I compared them, the text in questions and answers is different. 

From Module 1 Spanish:

![image](https://github.com/user-attachments/assets/8ddf4bb1-e2a7-481b-9b09-4977b219295b)

From Cancer screening history survey:

![image](https://github.com/user-attachments/assets/8901dd84-2613-4cfa-9b97-6adeccb70a89)

**Comment by joshid-ims** [comment]
I have not checked other questions in detail yet if they are common with other surveys.

**Comment by woodruffr** [comment]
Having the same question is different modules caused issues before with PROMIS so the question was worded slightly differently. I believe this may be on purpose to avoid concept ID collisions. The one place we have that is Biospecimens and the questions have the same variable prefix, which makes sense since they are just the survey duplicated and broken into two surveys. It would make less sense here.

**Comment by woodruffr** [comment]
The wording of the questions should be slightly different because this survey uses full variable names and SrvScr_MHGROUP9_v1r1 is a different question than M1 MHGROUP9.

**Comment by joshid-ims** [comment]
Are the age limits for questions like:

![image](https://github.com/user-attachments/assets/d5352e8a-f035-4b9e-922b-06cab915a29d)

same as Module 1 questions? 

![image](https://github.com/user-attachments/assets/27fd9cb2-38fb-4457-a1fc-18bc43caa523)

**Comment by joshid-ims** [comment]
![image](https://github.com/user-attachments/assets/599df3b6-b126-42d6-a866-79b04ae99202)

The text to be filled in is not translated. 

Also, we will need a variable name for text box when BREASTSUR= 55. 

![image](https://github.com/user-attachments/assets/1d886e5f-a780-4310-beb6-e1ca6a13a557)

**Comment by cunnaneaq** [comment]
@joshid-ims Thanks for pointing these out! 

I reached out to our communications coordinator to facilitate the translation of the FILL text for SrvScr_BREASTSUR_v1r0.  I will post the new document when it is available.

The variable updates that are tracked are not in the data dictionary.  I will add these in tomorrow and include a variable name for the text box when BREASTSUR=55

**Comment by joshid-ims** [comment]
I do not see this question in Spanish and English latest version but it is in Clean version. No track changes showing it is deleted. What should we do? 

![image](https://github.com/user-attachments/assets/b67ce68c-66bd-4f57-972e-27213ff88c22)

**Comment by cunnaneaq** [comment]
@joshid-ims  you're all set?  I am seeing this tracked in the [v18 tracked document](https://nih.app.box.com/file/1674734626847)

**Comment by joshid-ims** [comment]
Oh yes, saw that later. Thanks!

**Comment by woodruffr** [comment]
@cunnaneaq, I'm starting our Documentation issue for this survey. Would you please clarify which Questionnaire has all the changes for English? I'm not as concerned about the tracked changes since I can compare the current one to the last published version. I just want to be sure to not miss any of the changes. Thanks.

**Comment by joshid-ims** [comment]
The bolding in many places is inconsistent ( for e.g., some questions have bolding in "¿Alguna vez "  and some do not). What should we do? 

Also, some bolding is not same as bolding in English survey. Is that ok?

**Comment by cunnaneaq** [comment]
@huip-ims Please bold "ever" in the English survey and "alguna vez" in the Spanish survey.  I updated the questionnaire documents to reflect this.  Thank you!

**Comment by huip-ims** [comment]
@cunnaneaq Hi Aileen - Could you please provide the links to the updated English and Spanish documents? On Box, in the 'Screening Version 1.0_NOV Prod Push' folder, The English document 'V19' was last updated on 10/22, and the Spanish document was last updated on 10/16. Thanks.

**Comment by cunnaneaq** [comment]
@huip-ims sorry I know what I did! I just made the update in the v19 Tracked English document and the Spanish document

**Comment by huip-ims** [comment]
I've updated the "ever" and "alguna vez" bolding in the English and Spanish markdown files.

**Comment by cunnaneaq** [comment]
@huip-ims closing the loop on 2 of Deepti's comments above:
1. I added the age range checks into the v19 and untracked English documents and the Spanish document and added a table at the top of the documents for programming notes.  For all surgeries the **age** range check is min=0, max=age and the **year** range check is min=yob, max=Current Year.  To Deepti's comment - this is the same range check as in Baseline M1.

2. SrvScr_BREASTSUR9_v1r0 text fill has been translated and added into the Spanish document with tracked changes
![Screenshot 2024-11-05 at 4 02 32 PM](https://github.com/user-attachments/assets/6623ac65-fecc-4323-b726-cfb663254450)

**Comment by cunnaneaq** [comment]
@huip-ims - This survey has been a bit harder to track with the different tracked changes document, but wanted to make sure that the final English coding matches this document which has been approved by the IRB - https://nih.app.box.com/file/1673745039838?s=e7xhpn3l8pm8y7bwx1ywncba6pybz53i

I thought of this specifically in regard to the changes made to the responses in SrvScr_SEX2_v2r1 question, which match the v19 tracked document but are different from the v18 tracked document.
