### ISSUE TITLE
Cancer Screening Hx Survey - Updates to code needed for Quest

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#446]
These are coded properly in Module 1, so that's a good reference. Here are two examples so far of markdown coding updates that are needed for Quest to take specific actions.

The second example applies to all instances of the 'enter age or year' type inputs.
 
Example:
[535003378]	I have <b>not</b> had any of these surgeries
 
Should be:
[535003378*]	I have <b>not</b> had any of these surgeries
 
Where the asterisk is used to tell Quest to deselect all other selected options.
 
Example:
[D_675055475?] How old were you when you had your <b>tonsils removed (tonsillectomy)?</b>
|__|__|id=D_623218391 min=0 max=_value("age")| Age at surgery
Or, if it is easier to remember the year, enter that here:
|__|__|__|__|id=D_802622485 min=_value("yob") max=#currentYear| Year of surgery
 
Should have the xor property like this example from module1:
 
[D_965917116?,displayif=equals(D_167101091,698944820)] How old were you when a doctor or other health professional <b>first</b> told you that you have or had <b>vitamin B-12 deficiency (pernicious anemia)</b>?<br/>
|__|__|xor=ANEMIA id=D_206625031 min=0 max=sum(isDefined(D_150344905,age),1)| Age at diagnosis
 
Or, if it is easier to remember the year, enter that here:<br/>
|__|__|__|__|xor=ANEMIA id=D_261863326 minval=difference(difference(#currentYear,isDefined(D_150344905,age)),1) max=#currentYear| Year of diagnosis
< #NR -> D_929240175 >
 
Where that xor property tells quest to clear the other input.

**Comment by woodruffr** [comment]
The mark-up update for this was delivered on 12/12/2024.
