### ISSUE TITLE
Inconsistent bolding of 'ever' in Cancer Screening

### ISSUE THREAD

**Issue by boyd-mj** [episphere/questionnaire#447]
Hi Aileen,

There seems to be inconsistent bolding of the word 'ever' in the questions in cancer screening. For these questions, ever is not bolded:

SrvScr_MHGROUP9_v1r1
SrvScr_ANALSCREEN_v1r0
SrvScr_BRSTSCREEN_v1r0 
SrvScr_OVSCREEN_v1r0
SrvScr_CERVSCREEN_v1r0
SrvScr_ENDOSCREEN_v1r0
SrvScr_MULTISCREEN_v1r0 

Everywhere else it is. Should these also have 'ever' bolded?

Thanks,
Jen

**Comment by boyd-mj** [comment]
@cunnaneaq yes, that would be great. We can start making the changes in the meantime. I did go through Spanish just now and confirmed those are all bolded as expected.

**Comment by cunnaneaq** [comment]
great!  Just made the bolding changes to the linked doc above

**Comment by woodruffr** [comment]
The updated mark-up changes for this were delivered on 12/13/2024.

**Comment by cunnaneaq** [comment]
bolding looks good/consistent in Spanish survey
