### ISSUE TITLE
Cancer Screening Survey - Submit Screen in Spanish

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#449]
Update the submit screen to remove the programming instructions and the quotation marks before "Ha

Update also made in Spanish qx doc.  Please see screenshots below 

<img width="975" alt="Screenshot 2024-12-16 at 11 29 11 AM" src="https://github.com/user-attachments/assets/c5a5fafc-7761-4d47-bd4a-7e720ce162c7" />

![Screenshot 2024-12-16 at 11 29 31 AM](https://github.com/user-attachments/assets/0ccb5f00-d3ed-4530-b744-28c8615fad75)

**Comment by woodruffr** [comment]
The mark-up changes for this have been delivered.

**Comment by cunnaneaq** [comment]
looks good in Spanish dev testing
