### ISSUE TITLE
[INTROSITTING] "Outside of work" excluded if [WORK] = 0?

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#45]
Should we exclude the phrasing "outside of work" in [INTROSITTING] like it is excluded from [SITTING] when [WORK] = 0?

<img width="610" alt="Screen Shot 2022-03-16 at 10 09 26 AM" src="https://user-images.githubusercontent.com/83971268/158608797-85d7a0a9-41ee-4551-a3b1-8e1d81bc0a6f.png">

<img width="1124" alt="Screen Shot 2022-03-16 at 10 11 26 AM" src="https://user-images.githubusercontent.com/83971268/158609206-89088a80-7d5f-4871-b91b-2d719a5a0c54.png">

**Comment by boyd-mj** [comment]
@cusackjm is this a content change that NCI would like us to make? If so, has the questionnaire been updated?

**Comment by cusackjm** [comment]
leaving as is
