### ISSUE TITLE
Cancer Screening Skip Logic - BREASTSUR7

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#450]
Please see my responses below - I saw SrvScr_BREASTSUR7_v1r0 when I shouldn't have

SrvScr_BREASTSUR_v1r0
6 = Extirpacion de ambas mamas (mastectomia doble o bilateral)

SrvScr_BREASTSUR6A_v1r0
No response

I saw question SrvScr_BREASTSUR7_v1r0 Cuantos anos tenia cuando se sometio a circugia de absceso mamario (por ejemplo, incision y drenaje)?

I entered a response of 54 in the age text box.

This is documented in the tab "Testing Scenario 9 AC-Spanish" in the [testing spreadsheet](https://nih.app.box.com/file/1724777619927)

**Comment by joshid-ims** [comment]
I think this error should be in English one also.

**Comment by woodruffr** [comment]
The fix for this was just delivered.
