### ISSUE TITLE
Cancer Screening History - Kidney surgery type going to wrong next question

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#451]
[SrvScr_KidneySurgType_v1r0]
If participant responds 88 or NR instructions say --> GO TO SrvScr_VASEC_v1r0
but this doesn't make sense

Updated English and Spanish questionnaire documents to say --> GO TO SrvScr_LIPOSUCT_v1r0

I then saw SrvScr_VASEC_v1r0 again following SrvScr_FallTubeSurg_v1r0, but did I did not select 10 = Vasectomy in SrvScr_MHGROUP9_v1r1 so should definitely not be seeing SrvScr_VASEC_v1r0

I tested this in [Spanish scenario 8](https://nih.app.box.com/file/1724777619927), but based on the questionnaire documents, I imagine this is also an issue in the English mark down.

**Comment by woodruffr** [comment]
The fix for this was just delivered.

**Comment by cunnaneaq** [comment]
In Spanish survey - Selecting NR or 88 at SrvScr_KidneySurgType_v1r0 correctly goes to LIPOSUCT
