### ISSUE TITLE
Cancer Screening History - MAMMO2 to MAMMO3B skip logic issue

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#452]
Testing [scenario 8](https://nih.app.box.com/file/1724777619927) in Spanish (Connect ID: 6827054620)

For [SrvScr_MAMMO2_v1r0], I responded:
0 = Una vez

Next question should be [SrvScr_MAMMO3B_v1r0]

I didn't see SrvScr_MAMMO3B_v1r0, I was brought directly to [SrvScr_BRSTBIOP_v1r0]

**Comment by woodruffr** [comment]
This was fixed in English and delivered 12/13/2024. We are working on fixing it in Spanish now.

**Comment by woodruffr** [comment]
The Spanish fix for this was just delivered.

**Comment by cunnaneaq** [comment]
iPad, Safari, Spanish scenario 5 ([test spreadsheet](https://nih.app.box.com/file/1724777619927))
I just tested this and it is corrected for when 0 is selected at SrvScr_MAMMO2_v1r0
But for this scenario now MAMMO3B is not being shown:

SrvScr_MAMMO2_v1r0 = 1 (506053626)
SrvScr_MAMMO3_v1r0 = 1 (729845236)

I should then be brought to SrvScr_MAMMO3B_v1r0, but instead I am being brought to MRI (the next screening test that I chose)

**Comment by joshid-ims** [comment]
Should everyone see MAMMO3B? No matter what the values of MAMMO2 and 3?

**Comment by cunnaneaq** [comment]
@joshid-ims that's right, everyone is seeing MAMMO3B, but not everyone is seeing MAMMO3
