### ISSUE TITLE
Mark-up Issues Found in 12/16/2024 Dev Testing for Cancer Screening

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#453]
Note that this is for documentation only. These issues were fixed with mark-up changes.

From scenario 4:
SrvScr_FTREM_V1r0 and SrvScr_FTREM2_v1r0 not displayed.

From scenario 6:
For SrvScr_MHGROUP9_v1r1, I answered 5 8 9 and 16. SrvScr_VASEC_v1r0 displayed immediately which shouldn't have and it was out of order even if it should. SrvScr_FTREM_v1r0 did not display.

**Comment by woodruffr** [comment]
The fix for this was just delivered.

**Comment by cunnaneaq** [comment]
confirmed saw FTREM and FTREM2 in the Spanish survey
