### ISSUE TITLE
Cancer Screening History - did not see [STOOL3]

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#454]
Testing scenario 7 in Spanish using Connect ID: 6792847852 in Safari on an iPhone

Responses recorded [here](https://nih.app.box.com/file/1724777619927)

(960218176) SrvScr_STOOL2_v1r0: responded (282580702) 3 = Entre 6 y 10 veces
Next question I should see is (806961194) SrvScr_STOOL3_v1r0

Instead I was brought to the next section: (129025755) SrvScr_ANALSCREEN_v1r0

I'm not sure if this issue is also occurring in the English scenarios.

**Comment by woodruffr** [comment]
The fix for this was delivered on 12/17/2024.

**Comment by cunnaneaq** [comment]
Confirmed fixed in Spanish dev
