### ISSUE TITLE
SrvScr_CERVSCREEN_v1r0 option 2 issue

### ISSUE THREAD

**Issue by joshid-ims** [episphere/questionnaire#455]
When option 2 is selected in SrvScr_CERVSCREEN_v1r0, all other options should be deselected.

**Comment by woodruffr** [comment]
The fix for this was just delivered.

**Comment by cunnaneaq** [comment]
I am able to select options 0, 1, and 2 in dev (Spanish survey).  88 de-selects other responses

<img width="1284" alt="Screenshot 2024-12-18 at 12 04 48 PM" src="https://github.com/user-attachments/assets/2be3e872-c0df-4917-bc2d-f3abd973707d" />

**Comment by cunnaneaq** [comment]
Issue was present in stage testing

**Comment by boyd-mj** [comment]
@joshid-ims can you please look into this.

**Comment by woodruffr** [comment]
The fix for this in the Spanish survey was just delivered.

**Comment by cunnaneaq** [comment]
confirmed fixed
