### ISSUE TITLE
Cancer Screening Survey - typo in BREASTSUR3 (Spanish)

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#456]
iPad, Safari, Scenario 5, Spanish, Connect ID: 2987887066

Phrase in parentheses should read as (mamoplastia reductora): 
![Screenshot 2024-12-17 at 7 18 46 PM](https://github.com/user-attachments/assets/7923f985-cec8-4ece-aee0-a4a1594c2d8f)

But showing in the PWA as (mamopúltimaia reductora)

![Screenshot 2024-12-17 at 7 16 22 PM](https://github.com/user-attachments/assets/d2ac27bf-e189-4b43-be77-cd7840021d97)

**Comment by woodruffr** [comment]
The fix for this was just delivered.

**Comment by cunnaneaq** [comment]
looks good in dev
