### ISSUE TITLE
Cancer Screening - BREASTSUR9 seeing concept IDs in question (Spanish)

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#458]
SrvScr_BREASTSUR_v1r0 - I selected all breast surgeries.  For "another type of breast surgery" I did not enter any information into the text box in order to test "otro tipo de cirguia de mamas" being filled in.

Please see screen shot below for how this appeared in the PWA - I don't remember seeing this issue in other dev testing
<img width="1271" alt="Screenshot 2024-12-18 at 11 32 02 AM" src="https://github.com/user-attachments/assets/7edce97b-df13-41f2-bc06-eac084bfd12b" />

**Comment by joshid-ims** [comment]
we are not able to reproduce this issue in the renderer, converted and unconverted. Could this be PWA issue?

**Comment by cunnaneaq** [comment]
maybe?  @anthonypetersen @JoeArmani any thoughts on this?  I just tested again in dev to try and replicate and only selected 

807835037 | Other \|__\|

and I am seeing the concept ID displayed in the follow-up question: 

907385951 | How old were   you when you had other breast surgery? - CSH
<img width="1258" alt="Screenshot 2024-12-18 at 1 35 52 PM" src="https://github.com/user-attachments/assets/5db543ec-a2be-4f3d-964d-c6643298ff2f" />

**Comment by boyd-mj** [comment]
@anthonypetersen is Quest 2.0 pushed to the dev testing site: https://episphere.github.io/quest-dev/

We've been testing on https://episphere.github.io/quest/, which I assume is the old quest. I've asked our team to test again on the above.

**Comment by boyd-mj** [comment]
> @boyd-mj For the renderer: https://episphere.github.io/quest-dev/ has the Quest 2.0 version https://episphere.github.io/quest/ has the original version

Sorry, our messages crossed paths. See my edited comment above.

**Comment by JoeArmani** [comment]
> ETA: Our team is reporting they are unable to use the dev renderer at all, they are just getting a blank field in the renderer. So the reported issue may be something with Quest 2.0 since we can't reproduce it on the other testing site, which is presumably still using the other version of Quest. I hope that's helpful @anthonypetersen @JoeArmani .

Thanks for reporting this @boyd-mj. Found and resolved the issue with the blank screen. The renderer at https://episphere.github.io/quest-dev/ should be working now.

<img width="971" alt="Screenshot 2024-12-18 at 2 09 56 PM" src="https://github.com/user-attachments/assets/e74e7ef2-2178-45ed-a8c7-5a43dd7160fd" />


@cunnaneaq looking into the issue with the 'other' concept ID displaying in the Spanish survey.

**Comment by joshid-ims** [comment]
![image](https://github.com/user-attachments/assets/c7b4d03e-2c6d-428c-9fe1-c9e4018e8fbf)

Could reproduce in 2.0 renderer.

**Comment by boyd-mj** [comment]
@JoeArmani I think this indicates an issue with Quest 2.0 then since we can only reproduce it in that renderer?

**Comment by JoeArmani** [comment]
@boyd-mj agreed, thanks. I will look into this.

**Comment by cunnaneaq** [comment]
@JoeArmani I don't know if this is helpful, but I am NOT seeing this in stage testing right now.

**Comment by cunnaneaq** [comment]
hate to be the bearer of bad news, but I saw this in stage this morning when I did a quick test 
<img width="747" alt="Screenshot 2024-12-19 at 10 13 44 AM" src="https://github.com/user-attachments/assets/a63a30c6-3fab-47e0-a3e9-119e522c7404" />

**Comment by JoeArmani** [comment]
@cunnaneaq Thanks. This PR is in, and I'll let you know when it's ready for testing.

**Comment by JoeArmani** [comment]
@cunnaneaq This is active and ready to test in dev or stage. I verified it in dev.

**Comment by boyd-mj** [comment]
@cunnaneaq is your team going to test this or would you like us to?

**Comment by cunnaneaq** [comment]
@boyd-mj I'll test it, thanks for asking!

**Comment by cunnaneaq** [comment]
@JoeArmani in stage, I was at the "another type of breast surgery" age/year question, I logged out and logged back in, the survey was still on that question, but there were no concept IDs - I think this means it's ready for production

**Comment by JoeArmani** [comment]
@cunnaneaq Just to confirm - did you see either the text you originally entered in that input or, if you left that field selected and empty, the fallback text 'another type of breast surgery'?

**Comment by cunnaneaq** [comment]
I saw the text that I entered previously

**Comment by JoeArmani** [comment]
Perfect. Thanks for confirming. I tested both ways, and both produced the expected results.

**Comment by cunnaneaq** [comment]
Great!  I just tested again with the fallback text and also worked as expected in stage

**Comment by JoeArmani** [comment]
Excellent, thanks for testing that case too. Agreed, it looks like we're all set.
