### ISSUE TITLE
PAINREL8 response "no" should be "never"

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#46]
PAINREL8 responses in the PWA are no, sometimes, often, and prefer not to answer. the "no" response should be "never" (reflected in the box document)

**Comment by woodruffr** [comment]
Hi Julie, did you mean to assign this to someone?

**Comment by cusackjm** [comment]
Hi- sorry for the confusion. That is correct. The documentation in Box indicates I changed it to "never" 44 following that email, which is a mistake. 

Related to that question, Neal and I are wondering if we could change PAINREL8 from 
"Did you ever use prescription pain relievers that contain opioids in any way not directed by a doctor?" to 
"Have you ever used prescription pain relievers that contain opioids in any way not directed by a doctor?"
For the purpose of sounding less accusatory to the participant
