### ISSUE TITLE
biospecimen content changes (menstrual history section)

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#48]
Made content changes to box questionnaire documents.

Ready for markup changes

**Comment by woodruffr** [comment]
@cusackjm 

These changes have been made in the Mark-up. They are ready to be made in the DD. Would you like to make them and I can confirm they are made:
Adding MENST60
Changing the question type and formatting for MENSTART, including deleting the removed row for "This does not apply to me."

**Comment by woodruffr** [comment]
Note that MENSTART response is a Date function so the Variable Type should be Date.

![image](https://user-images.githubusercontent.com/81166095/160669570-6b7354da-2e3e-486d-a259-635280dc7b29.png)

**Comment by cusackjm** [comment]
Changes have been made and are uploaded in box

**Comment by woodruffr** [comment]
Hi Julie,

MENSTARTDATE still has a Source Question on the Box DD. (Also, the row is too small to see all of the Source Question.) The Question text should be what is in the Source Question currently. The Variable Name should be MENSTART (based on the Questionnaire and Mark-up. Also, the format MM/DD/YYYY should be in the Column Q Connect Value, and it is currently in the Required column. 

As for the Questionnaire, the MENSTARTDATE variable should be completely removed. The Date data will be stored under the same Variable as the Question Text: MENSTART.

**Comment by cusackjm** [comment]
Changes have been made to DD and questionnaire documents and are in box

**Comment by woodruffr** [comment]
I have reviewed the changed and confirm that they are as expected.
