### ISSUE TITLE
Variable name prefixes

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#51]
updated in DD and biospecimen qx

**Comment by woodruffr** [comment]
Hi Julie,

These changes were noted in the February 3 Questionnaire change log as "Updating variable name prefixes (mouthwash from “BioMwQ” to “SrvMw” and non-specific subsection questions (from “SrvBlU” to “SrvBio). To help us identify them, what is meant by "non-specific subsection questions"?

Thanks,
Rose

**Comment by cusackjm** [comment]
hi rose,
the non-specific subsection questions are Q1 (SEX)- Q6 (WAKETIME)

**Comment by woodruffr** [comment]
Hi Julie,

While reviewing our Mark-up changes we noticed that the prefixes were not changed in the SYMPTDAY responses. Also, EATDRINKBEFORE (2) has a Go to statement that needs to have the prefix changed.

**Comment by cusackjm** [comment]
changes have been made

**Comment by woodruffr** [comment]
These changes were made in the Mark-up and in the Questionnaire as expected.
