### ISSUE TITLE
Possible Biospecimen Questionnaire Changes

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#53]
Hi Julie,

I was just comparing the Mark-up to the Questionnaire in search of anything that might conflict with the current DD. We are still working on the DD part, but have these questions for the Questionnaire:
1. SYMPTDAY has a number 5 in the Questionnaire and an 88 in our Mark-up. I believe it should be the harmonized 88 = none of the above in the DD, which could still be "88 [SrvBlU_NOSYMPTDAY_v1r0] No, I had none of these symptoms" in the Mark-up.
2. SEX, CONTRACEPT, and HORMONE do not have any numbers for their responses. Please revise the questionnaire accordingly.
3. Should the DENTURES "0 No" be an "88 No" which harmonized in the DD translates to "None of the above"?
4. Also, in DENTURES, I just want to confirm that it is intentional that for the second word in each response, "denture" is not capitalized, but "Bridge" and "Implants" are capitalized.

The harmonization document can be found on the Special Missing tab here: https://app.box.com/file/872367647533?s=ah2fyje4hgjvn1dynm2bqkdb7nsaztug

Thanks,
Rose

**Comment by woodruffr** [comment]
Hi Julie,

1. Do you want to change that in the DD now or wait until you get the next set of DD updates from us?
2. That must have been a glitch in the comparison software versus the file formats. Please ignore that one.

**Comment by cusackjm** [comment]
Wait for the next set of DD udpates

**Comment by woodruffr** [comment]
The change for SrvBio_NoSymptDay_v1r0 has been changed to 88.
