### ISSUE TITLE
Changing question type for MENSTPRD, MENST60, MENSTART from option to required 

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#54]
- Removing No response option from MENSTPRD, MENST60, MENSTART 
- changing question types from optional to required

These changes support the triggering for the Menstrual Cycle Survey

**Comment by woodruffr** [comment]
LOL...We don't currently have a question type for Required Multiple Choice...I've thought for a while we really need to just Remove the Optional from that one. I guess now we will. The DD formatting is all the same but a Y instead of N in the Required column which we really hadn't filled out. The big difference is in the mark-up. A ? is for optional and a ! for required. I'll pass this to a coder.

**Comment by woodruffr** [comment]
Oops, I assumed these were made in the Questionnaire doc. Please let me know when the changes have been made on the Questionnaire on Box, then I'll pass this to a coder.

**Comment by cusackjm** [comment]
sorry still in a meeting, I will make the changes soon

**Comment by cusackjm** [comment]
changes have been made

**Comment by huip-ims** [comment]
Changes for MENSTPRD, MENST60, MENSTART have been made in the markup and will be passed on to internal testing.

**Comment by cusackjm** [comment]
@woodruffr can I make updates to the question type/dd now?

**Comment by woodruffr** [comment]
Yes, the changes have been added to the dd copy we are working with for recommended changes, but if you make them now, you won't need to make them later. I had an internal question here that I was waiting on, but it shouldn't keep you from changing the DD.

**Comment by woodruffr** [comment]
You can certainly change the Question Types document.

**Comment by cusackjm** [comment]
sounds good. I will udpate the question types document and make the changes to the DD when the other ones are ready

**Comment by cusackjm** [comment]
(qx type document has been updated)

**Comment by woodruffr** [comment]
Hi Julie, I wanted to check since for MENSTART the DD says "mentrual period" but the Questionnaire just says "period". I believe all the other references (Module 2) say "menstrual period". Shall we change the data dictionary or was that a Questionnaire oversight?

**Comment by cusackjm** [comment]
Hi- we think update the qx, I will do that now

**Comment by FrogGirl1123** [comment]
@cusackjm Please be sure to update the "Required" column in the Biospecimen DD for the responses that are now required as well as populating that column with No's where appropriate.  

All the same columns should be populated for the questionnaire dictionaries as are populated for the master, including Required, PII, Dictionary (i.e. Biospecimen Survey), State (which will be "No" for all the questionnaires), Default, etc.

**Comment by cusackjm** [comment]
Biospecimen DD updated
