### ISSUE TITLE
Testing Scenario 3 AC: Wrong choices selected and/or displayed

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [episphere/questionnaire#55]
(Flattened Module 2 in dev)

Update: with retest these errors were solved

**Comment by zly2021** [comment]
I just checked. As of current moment, I didn't see 798889867 in current Connect.participants table.

**Comment by FrogGirl1123** [comment]
@cusackjm Could you and Aileen double check how you recorded what you selected during your Module 2 testing.  Multiple choice answers are coded starting with 0 in the data dictionary, but if you were just counting in the list presented in the Survey, you probably started counting at 1.  I want to make sure we are comparing apples to apples so to speak.
