### ISSUE TITLE
Testing Scenario 4 JC (2): Responses showing as null and answer doesn't match data dictionary

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [episphere/questionnaire#56]
Dev Environment, flattened Module 2 and recruitment

Have you ever taken any of these types of progestin-only prescription hormones? Select all that apply.(PROGHOR==1,55,other)(D_800943768_687050279, D_800943768_807835037, D_800943768_235516216 , D_800943768_535003378)  :  1 selected but not an option, answers are 0, 55, and 88; 2 options for other( _ ) in data dictionary, only one other option given on survey.

How many days per cycle did you use this other type of combined estrogen plus progestin prescription hormones? (SEPHOR2==2) (D_290126991): Variable in participants table and flattened M2, but populates as NA instead of 2

**Comment by cusackjm** [comment]
Not sure how this happened as this was a while ago, but I think this could be because of how I was testing certain issues. 

For some questions I was submitting an answer, going forward, and then going back and changing my answers to see if/how the skip pattern changed. I don't know for sure if that was the case for these questions, as I didn't make records of when I changed a response, and to my understanding we never had an issue of the wrong data being saved on the backend, so I never thought to record the responses that were first entered and then the final responses entered when the survey was submitted. 
@FrogGirl1123  Could that be why the data is not matching the records?

**Comment by zly2021** [comment]
D_496539718 actually doesn't have data by itself, it only includes D_969451837 nested under it. For D_290126991, it seems that the queries were scheduled in the afternoon. I've adjusted them to run in the morning before 8:00 AM.

**Comment by KELSEYDOWLING7** [comment]
So for age at first Mensural period I reran the query with the nested ID only and found it. Is there a reason that it was nested as D_496539718_969451837  in the participants but not in the flattened? Should I be looking out for that with other nested variables, appearing alone?

For combined estrogen plus progestin prescription hormones I'm seeing it in the flattened and participants but it's not populating yet. Should I wait until tomorrow to try rerunning? @zly2021  Also in the table, 1 is selected instead of 2 @cusackjm

**Comment by zly2021** [comment]
If the ID is a harmonized ID, it would require nesting (otherwise it will raise confusion), while if it is not a harmonized ID, either nesting or non-nesting would work. @FrogGirl1123 can explain the concept of harmonization better than me I guess. 

I've scheduled the queries to run before 8:00 AM every day yesterday, and double check it later in the day would help too.

**Comment by KELSEYDOWLING7** [comment]
Oh ok I think I see what you mean when I look at the Data Dictionary

**Comment by KELSEYDOWLING7** [comment]
Confirmed D_290126991 is showing as null in the participants table after today's morning run

**Comment by FrogGirl1123** [comment]
@KELSEYDOWLING7 and @cusackjm Just to make sure I understand the current status.  The variable  D_290126991 exists in the participants table and in the flattened Module 2 data but isn't populated at all?  And for the other variables listed in this issue, they are populated with the wrong data relative to this scenario? If this is the case @cusackjm, I agree it could be from going back and changing answers and that's something we should definitely test in the next round of testing.

**Comment by FrogGirl1123** [comment]
@zly2021 I think the NAs in this issue may have the same cause as in issue #62 . Could you please check to see if these are "select all that apply" variables and adjust the flattening code as needed?

**Comment by cusackjm** [comment]
@FrogGirl1123 I can test that in the next testing round. 

Only other theory @cunnaneaq and I have is that this could be part of the issue we had in submitting the qx. In the last round of testing, Aileen submitted the module, but when the page refreshed, it appeared as if the module was not submitted. When going back into that module and trying to submit the module, she was taken to the end of the module to submit again, but in clicking backwards in the pwa it appears that some responses were not saved. This happened a couple times to her, but did not for me. Not sure why (the only difference in our testing is that I test on a PC and she tests on a Mac)

**Comment by KELSEYDOWLING7** [comment]
@FrogGirl1123  The variable D_290126991 is in both the participants table and flattened Mod2 table. But when I search the variable's answer for this participant (email d_869588347="bernardblank6@gmail.com") in the participants table, it shows a "null" response instead of a response of 2

**Comment by zly2021** [comment]
Similarly to #62, I did see flat_M2 table has values. It seems that it can update successfully once the original connect.participant table has values.

**Comment by Davinkjohnson** [comment]
@KELSEYDOWLING7 can you check these as well? (similar to the other issues)

**Comment by KELSEYDOWLING7** [comment]
@Davinkjohnson  Responses for nearly every variable are now populating as NA/null, including the two variables listed above

**Comment by FrogGirl1123** [comment]
@Davinkjohnson We'll need to keep this issue open until we retest and see if the fixes for the data saving issues remedy this issue.

**Comment by KELSEYDOWLING7** [comment]
With retesting, SEPHOR2 / D_290126991 no longer shows in either flattened mod2 or participants table
