### ISSUE TITLE
Testing Scenario 5 AC: Responses populating only as NA, and some not matching Test Scenario

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [episphere/questionnaire#57]
(DEV Environment, Mod 2 Flattened Data)

Variable in participants table and flattened Mod2 table, but populating "NA" results instead of submitted responses:
-Age first menstrual period (MENSHIS==44) (D_969451837 -nested concept only, full concept not in flattened)

**Comment by FrogGirl1123** [comment]
@cunnaneaq and @cusackjm Do either of you remember any issues with this scenario?

**Comment by FrogGirl1123** [comment]
@zly2021 Again could you check if any of the variables that are NA are "select all that apply" and adjust the flattening code as described in issue #62?

**Comment by cusackjm** [comment]
Aileen tested this scenario. I copied below from another issue vvv

Only other theory @cunnaneaq and I have is that this could be part of the issue we had in submitting the qx. In the last round of testing, Aileen submitted the module, but when the page refreshed, it appeared as if the module was not submitted. When going back into that module and trying to submit the module, she was taken to the end of the module to submit again, but in clicking backwards in the pwa it appears that some responses were not saved. This happened a couple times to her, but did not for me. Not sure why (the only difference in our testing is that I test on a PC and she tests on a Mac)

**Comment by cunnaneaq** [comment]
Yes @cusackjm is correct, this happened to me a few times during testing.  I have a note in my testing spreadsheet in this scenario's tab, that this submission issue happened to me at the end of Module 2.

**Comment by FrogGirl1123** [comment]
@Davinkjohnson We'll need to keep this issue open until we retest and see if the fixes for the data saving issues remedy this issue.

**Comment by KELSEYDOWLING7** [comment]
closed issue #57 5/27
