### ISSUE TITLE
Testing Scenario ACJC 6: Responses showing as NA and answers selected not matching test scenario

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [episphere/questionnaire#58]
DEV Environment, Module 2 flattened

How many days per week is your sleep schedule determined by your job, school, or other activities? (SLEEPSCHB==6) (D_168431681) : 4 chosen (5 days) instead of option 2 (3 days)

On non-workdays, do you wake up before the alarm rings? (SLEEP2L==0) (D_820694957): In participants data and flattened data, but populating as NA

Has a doctor or other health professional ever told you that you have any of these conditions? Select all that apply. (SLPROB1==1) (D_479628567):      0 and 1 chosen instead of 2

Which of these treatments do you use or once used for your sleep apnea? Select all that apply (SLPROB2==0,55-herb)(D_629010195) : Herb not specified, only 0 and 55 selected

**Comment by KELSEYDOWLING7** [comment]
@FrogGirl1123  Confirmed showing as NA after this morning's run of participants table

**Comment by FrogGirl1123** [comment]
@cunnaneaq and @cusackjm Do you remember any issue with this scenario?

**Comment by FrogGirl1123** [comment]
@zly2021 I think the NAs in this issue may have the same cause as in issue https://github.com/episphere/questionnaire/issues/62 . Could you please check to see if these are "select all that apply" variables and adjust the flattening code as needed?
