### ISSUE TITLE
COV2 No Response Directions

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#59]
Hi Julie,

The Questionnaire has no instructions for what to do if someone answers COV1 "Have you ever had COVID-19?" with 1 Yes and has no response to COV2 "How many times have you had COVID-19?". I imagine if they are not sure how many times they've had it they might skip that. COV2 is what sets the number of loops. With no instructions, the questionnaire just stops. What should be the NR directions for COV2?

**Comment by cusackjm** [comment]
If someone selects COV1= 1 and no response at COV2 the person should be sent to COV3 and put through 1 loop. 
I will add the following statement to the qx after COV2 "_NO RESPONSE --> GO TO COV3 AND SET LOOP TO 1 ITERATION_" 
Does that make sense?

**Comment by woodruffr** [comment]
Yes, It makes sense to me. Please let me know when you update the Questionnaire and I'll assign the Mark-up changes to Pete.

**Comment by cusackjm** [comment]
Changes made

**Comment by huip-ims** [comment]
@cusackjm Julie, I addressed this previously when coding the markup. You agreed to use a 'min=1' check, so the participant will have to enter a value and not leave COV2 as NR.

**Comment by woodruffr** [comment]
Pete, I brought this up.

**Comment by woodruffr** [comment]
Julie,

Sorry about this. We can close this. When I saw there were no instructions in the Questionnaire, I looked at the Mark-up and put it in the renderer, but did not grab the code all the way to the end of the loop. Now that I've included the code all the way to the end of the loop, I see that it is putting a 1 loop minimum there.
