### ISSUE TITLE
Incorrect skip pattern for EMPLYERSRVCE1= No response

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#6]
When EMPLYERSRVCE1= No response I should be brought to WORK8, but instead I was taken to WORK7.

**Comment by cusackjm** [comment]
When going through the rest of the qx with Non-responses, I realized that this skip pattern DOES work properly (which was not expected). The following is what I saw:
EMPLRYSRVCE1= NR 
WORK7= NR _(I should've gone to WORK8)_
OCCUPTN2= NR
EMPLYR2= NR
BSNSSTYP2= NR
EMPLYRSRVCE2= NR
WORK8= NR _**(this is what should happen at EMPLRSRVCE= NR)**_

**Comment by boyd-mj** [comment]
Delivered

**Comment by KELSEYDOWLING7** [comment]
Still seeing error on 5/24 testing, connect ID 4242162341

**Comment by boyd-mj** [comment]
Hi @KELSEYDOWLING7 I just want to confirm that this issue IS still occurring? I got an earlier message that it wasn't present during testing:

**Comment by KELSEYDOWLING7** [comment]
@boyd-mj  Yes, I apologize. I hadn't realized it was an NR response for EMPLYERSRVCE1 that was causing the incorrect skip logic when I tested on 5/23.  So when we retested on 5/24 I skipped the question and was brought to Work7 instead of Work8

**Comment by cusackjm** [comment]
confirmed fix in testing 5/26
