### ISSUE TITLE
Large amounts of extra space in address displays

### ISSUE THREAD

**Issue by boyd-mj** [episphere/questionnaire#66]
Hi @cusackjm are you able to view this issue in the Quest Github:
https://github.com/episphere/quest/issues/374

We reported an issue a while back with large amounts of space that appear in the address sections due to the length of the code. It's just an aesthetics issue, but I'd like to determine if it's something your team wants fixed with this initial release. I've also posted a follow up in that issue asking Daniel to respond. If you can't view it, I can have someone repaste the screenshots here as well. 

Thanks,
Jen

**Comment by cusackjm** [comment]
I think if its just an aesthetics issue it is fine to leave as is for the initial release

**Comment by danielruss** [comment]
@cusackjm I thought we (and by we I mean @naiyume ) addressed this awhile ago.
