### ISSUE TITLE
[HOUSE2] grid - showing incorrect choices

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#67]
[HOUSE2] grid is only supposed to include answer choices that don't = never in HOUSE1.  I answered 44='never' to "caring for pets" and "caring for children and adults" and these options were present in [HOUSE2].  See screenshots below

[HOUSE1]
![Screen Shot 2022-04-13 at 1 14 41 PM](https://user-images.githubusercontent.com/83971268/163234620-953ed402-8adb-4aeb-8bb1-4d1080321a7d.png)

[HOUSE2]
![Screen Shot 2022-04-13 at 1 15 09 PM](https://user-images.githubusercontent.com/83971268/163234683-a7801b5f-da74-40d1-9f0d-a448270eecc6.png)

**Comment by boyd-mj** [comment]
Looking into this

**Comment by boyd-mj** [comment]
@cunnaneaq could this be an issue with the PWA timing out like we discussed on our call today? We aren't able to recreate this issue:
![image](https://user-images.githubusercontent.com/80920570/163269905-90bc60eb-84e8-480d-98ed-c4a25e29713b.png)
![image2](https://user-images.githubusercontent.com/80920570/163269903-339e3047-12f2-4394-929f-9e34002810c4.png)

**Comment by cunnaneaq** [comment]
I think it is possible.  I will make sure to check this when I go through module 2 tomorrow

**Comment by cunnaneaq** [comment]
@boyd-mj We were able to resolve the timing out issue!  I re-tested module 2 today and was unfortunately still seeing the [HOUSE2] grid issue noted here.

**Comment by guinevere83** [comment]
Can we see your full path through the module to the grid? I want to see if perhaps something unanticipated is affecting what displays in HOUSE2.

**Comment by boyd-mj** [comment]
@cunnaneaq following up to make sure you saw Gwen's question above so that we can continue to investigate this issue. Thanks.

**Comment by cusackjm** [comment]
@guinevere83 Aileen is on PTO but our testing document has record of this issue when Aileen tested under irinainstitute@gmail.com Connect ID: 1654043404. 

Is this the information you need? Do you want to see the testing document to see the previous responses that were selected?

**Comment by cunnaneaq** [comment]
@guinevere83 @boyd-mj I attached the excel sheet where I recorded my answers here.  I saw this issue in both scenarios/tabs (Testing Scenario 4_AC = cell 552) and (Testing Scenario 5_AC = cell 622)

[Module 2 Testing 04.12.22_HOUSE2 issue.xlsx](https://github.com/episphere/questionnaire/files/8513007/Module.2.Testing.04.12.22_HOUSE2.issue.xlsx)

**Comment by cunnaneaq** [comment]
@guinevere83 Please see the attached spreadsheet with all of the answer choices recorded for modules 1-3 for participant aqcunnane@aol.com (Connect ID: 1217779307).  This information is to help work through the [HOUSE2] grid issue here in module 2 and issue #71 that presents in module 3.  Cells with the issues are highlighted in yellow.  Thank you!

[Connect_Baseline Module Testing_IMS.xlsx](https://github.com/episphere/questionnaire/files/8535007/Connect_Baseline.Module.Testing_IMS.xlsx)

**Comment by guinevere83** [comment]
Here's HOUSE1
![image](https://user-images.githubusercontent.com/75336502/164724753-f60b941b-855a-44c9-9835-d0b8e59a38bf.png)
and HOUSE2
![image](https://user-images.githubusercontent.com/75336502/164724849-8174b5f0-2b0a-4cd7-a302-d0e2e57ebdde.png)

At this point, I'm pretty sure it has to be something to do with a difference in the renderers. 

Here's my path and variables for reference:

![image](https://user-images.githubusercontent.com/75336502/164724959-dbcc77a2-5ba1-41ad-a5bc-ad3e03afc003.png)
![image](https://user-images.githubusercontent.com/75336502/164725037-b7f5df66-c5e7-40e0-b7ac-268a5913732e.png)
![image](https://user-images.githubusercontent.com/75336502/164725142-1c660022-e155-4e44-9531-8bc846e2bfcb.png)
![image](https://user-images.githubusercontent.com/75336502/164725218-c34b4428-917a-4dfd-81ed-4ac603d755a6.png)
![image](https://user-images.githubusercontent.com/75336502/164725303-e67722d3-b5c8-43ac-9d91-f1f5795519ca.png)
![image](https://user-images.githubusercontent.com/75336502/164725357-819d9cd2-6354-4035-8e53-711604da8d03.png)
![image](https://user-images.githubusercontent.com/75336502/164725419-d8d23058-f813-491a-8491-f8e64a419030.png)
![image](https://user-images.githubusercontent.com/75336502/164725483-af7f784d-849d-454a-9692-ae9310abb1b4.png)
![image](https://user-images.githubusercontent.com/75336502/164725555-16764d6a-609c-4b35-8ec6-844b9d88c7c7.png)
![image](https://user-images.githubusercontent.com/75336502/164725608-b6c4ab4f-026d-4e00-8b07-48300e973523.png)
![image](https://user-images.githubusercontent.com/75336502/164725653-23dc45ea-8da0-4c7f-9e97-82673904abd3.png)

**Comment by FrogGirl1123** [comment]
@Davinkjohnson, @danielruss, @anthonypetersen 

It looks like there is something different in our rendering than in the renderer IMS is using.  If I am correct in that IMS @guinevere83 is using the most current version of the Quest renderer, then this might be an issue with the PWA

**Comment by boyd-mj** [comment]
This is the renderer we are using: https://episphere.github.io/quest/

**Comment by danielruss** [comment]
what module is this?

**Comment by cusackjm** [comment]
module 2

**Comment by naiyume** [comment]
@cusackjm, @cunnaneaq  This should be resolved now. Please check this in the next batch of testing

**Comment by cusackjm** [comment]
confirmed fix during testing 5/16/22
taratdrp@gmail.com CONNECT ID: 2252696519
