### ISSUE TITLE
update to PREG5 skip logic

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#68]
updated PREG5 skip logic in box questionnaire documents

**"[IF PREG1 = 1, DO NOT DISPLAY PREG 5 FOR THE MOST RECENT PREGNANCY, GO TO PREG10]_(I.e., IF PREG4 = 1, GO TO PREG 10. IF PREG4 = 2, DISPLAY PREG5 FOR “FIRST” PREGNANCY, BUT SKIP TO PREG10 FOR “2ND” PREGNANCY)_"**

Let me know if they are unclear and need re-wording

**Comment by huip-ims** [comment]
@cusackjm @boyd-mj Hi Julie - For PREG5 skip logic:
You referenced PREG4, which is age at each pregnancy. This should be PREG3 (# of pregnancies), correct? If so, please update the Word doc.
Also, for this skip logic, you just want the last iteration of the pregnancy loop to skip PREG5-PREG9, correct?  We're assuming the way the questions are phrased, the participants are providing their pregnancies from earliest (1st) to most recent (nth). If so, this should be a small change to the conditional display statements in the markup code. Let me know if this is not how you want to implement this skip logic change.

**Comment by cusackjm** [comment]
@huip-ims yes sorry that was a typo. I will update it now. 
Yes that is how we would like to implement the skip logic change.

**Comment by huip-ims** [comment]
@cusackjm @boyd-mj Julie - For PREG10, there's a condition to only display this question if PREG5 = 0,1,2,3. For the last iteration of the pregnancy loop, you want now to skip to PREG10 without answering PREG5. Should PREG10 & PREG11 be asked on the last iteration, even though we don't have the pregnancy outcome response from PREG5?

**Comment by cusackjm** [comment]
@huip-ims I am consulting with Mia on this and will get back to you

**Comment by cusackjm** [comment]
@huip-ims we decided to change the skip logic to "[IF PREG1 = 1, DO NOT DISPLAY PREG 5 FOR THE MOST RECENT PREGNANCY, GO TO **PREGSUMMARY**]_(I.e., IF PREG3 = 1, GO TO PREG 10. IF PREG3 = 2, DISPLAY PREG5FOR “FIRST” PREGNANCY, BUT SKIP TO PREG10 FOR “2ND” PREGNANCY)_"

**Comment by cusackjm** [comment]
I am updating this in the questionnaire documents now

**Comment by huip-ims** [comment]
@cusackjm @boyd-mj Julie - You have [IF **_PREG1_** = 1, DO NOT DISPLAY PREG 5 FOR THE MOST RECENT PREGNANCY, GO TO PREGSUMMARY]. I don't see PREG1 in the Word doc. Could you please clarify which "PREG" it should be?

**Comment by cusackjm** [comment]
sorry PREG. I will update that now

**Comment by huip-ims** [comment]
@cusackjm @boyd-mj Julie - Just to confirm, based on your current skip logic:
If a participant is currently pregnant (PREG=1), the last iteration of the pregnancy loop will skip PREG5-PREG11 and go straight to PRESUMMARY. However, if a participant is not currently pregnant (PREG=0), PREG5-PREG11 will be asked for all pregnancies, including the most recent. Is this correct?

**Comment by cusackjm** [comment]
@huip-ims Yes

**Comment by huip-ims** [comment]
@cusackjm @boyd-mj Hi Julie - I've made these skip logic changes and sent the markup for our internal testing. However, I just noticed in the Word doc there are 2 [PREG] quest IDs. Could you please update the 2nd one (Are you currently pregnant?) to [PREG1]?  FYI- You then also need to update the PREG5 skip logic condition to 'IF **_PREG1_** = 1, DO NOT DISPLAY ....'. Once you've updated the Word doc, this issue can be closed. Thanks!

[PREG] Next, we will ask you some questions about pregnancies that you may have had.
[PREG] Are you currently pregnant?

**Comment by cusackjm** [comment]
Ok I will update that in the questionnaire document now.

This error appears in the qx document (not the master DD), but does it occur anywhere else that needs the update?

**Comment by woodruffr** [comment]
I have checked Question Types document and PREG is correctly not in there as it is text only with no backend storage, but PREG1 seems to be correctly listed. I believe everything is now synchronized: The DD, the Mark-up, the Questionnaire, and the Question Types document so the Quest ID issue is fixed. Julie, you can Accept the change in the Questionnaire document as the change/correct value is in the Mark-up.

**Comment by cusackjm** [comment]
@woodruffr The baseline module questionnaire documents have always had the tracked changes in the IMS document, do you want me to accept all tracked changes? or leave as is?

**Comment by woodruffr** [comment]
@cusackjm That is a question for @boyd-mj .

**Comment by boyd-mj** [comment]
@cusackjm once @huip-ims confirms these changes, I think we can go ahead and accept all of the tracked changes so that we have a clean copy moving forward.

**Comment by huip-ims** [comment]
@cusackjm @boyd-mj Julie - These skip logic changes have been made in the markup.

**Comment by cusackjm** [comment]
@huip-ims @boyd-mj sounds good, i will accept all tracked changes now
