### ISSUE TITLE
Biospecimens Questionnaire DESC Variable Names

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#69]
Although this was mentioned in an email related to Question Types, I'm creating a Github issue because it will involve a Questionnaire change. Questions with text boxes, other than Text Box Only, will need a Variable Name for the text box. In the Mark-up we call it the ID= value. In the DD, it is the Variable Name. In order to connect the text box with the Source Question, it is preferable to have the Source Question Variable Name as a part of the text box Variable Name. To that end, these will be changed in The Questionnaire, Mark-up, and DD:

COV196CDesc to COV196CADesc
COV23B8Desc to COV23B8ADesc

**Comment by cusackjm** [comment]
changes have been made to DD and Questionnaire

**Comment by woodruffr** [comment]
Hi Pete,
Please make these changes on the Mark-up when you have a chance. Work on all previous modules takes precedence.

**Comment by huip-ims** [comment]
@woodruffr Hi Rose - These variable name changes have been made in the markup.

**Comment by woodruffr** [comment]
Hi Julie,
These Mark-up changes have been made. You can remove the highlighting from the Questionnaire when you have time.
Thanks,
Rose
