### ISSUE TITLE
Stuck in SIB/CHILD loop when not providing a response to SIB/CHILD

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#7]
I did not answer SIB (no response) and SIBCONFIRM said I have "0 undefined" siblings and then brought me through the sibling loop. I clicked back to see if this happened when I entered "0" at SIB and the loop did not happen (which is correct, so I think the loop issue only happens when the participant does not respond to SIB). 
I tried duplicating this issue at CHILD and the same thing happened at CHILDCONFIRM (picture)
 
![image](https://user-images.githubusercontent.com/85582895/142486100-7f414895-02cd-4275-8fe2-76c94d9148b3.png)

Instead of clicking back and entering "0" at CHILD like I did for the SIB loop, I clicked next, and then got stuck in the Child Loop. I went through 5 loops before clicking back to CHILD and entering 0, so that I could get out of the loop.

**Comment by cusackjm** [comment]
box questionnaire documents updated (from SIB and CHILD to SIB1 and CHILD1)

Master DD Updated (https://nih.app.box.com/file/932437849865?s=s58tyrx38k9xn1yn55vlfb47jaxjx91r) required column

**Comment by boyd-mj** [comment]
@cusackjm we've made these changes, but the master DD on Github still shows these as not required. Could you please update?

**Comment by cusackjm** [comment]
Yes just updated CHILD1. SIB1 was listed as required.

**Comment by cusackjm** [comment]
participant reported being stuck in sibling loop after reporting 0 sib

**Comment by boyd-mj** [comment]
Hi @cusackjm do you have any more details? Do you know where exactly they got stuck? If it was in sibconfirm, do we know what number displayed instead of zero?

**Comment by cusackjm** [comment]
they entered SIB1= 0 and got stuck in an infinite sibling loop. I am going to work on replicating this issue based on their responses in the participant table @boyd-mj
