### ISSUE TITLE
Seeing SECSMLF questions for ages older than my participant

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#71]
testing 4/15 participant is 55, but I am seeing SECSMLFG (ages 60-69) and SECSMLFH (ages 70 and older)

**Comment by boyd-mj** [comment]
@cusackjm & @FrogGirl1123 we'll look into this, but I didn't think testing for M3 was supposed to start until the beginning of next week? FYI, there is an issue currently with the ALCLIFE grids in the transformed markup. I sent an email to Nicole and we'll be following up with a suggested DD change to address it. Once we have the updated JSON we will need to redeliver.

**Comment by guinevere83** [comment]
Hmm, I'm not seeing that in my own testing:

![image](https://user-images.githubusercontent.com/75336502/163601468-e045d7db-aef5-4f5e-9a26-87c3a8349c0f.png)

Do you have a list of your response to previous questions in the module? I'll see if I can reproduce it if I know your testing path.

**Comment by cusackjm** [comment]
@boyd-mj I saw it in Dev on 4/15 around 2:45 has any change been made since then?

**Comment by boyd-mj** [comment]
No

**Comment by KELSEYDOWLING7** [comment]
I also saw it here: ivaniteb5@gmail.com
Connect ID: 4061436541

**Comment by guinevere83** [comment]
Could I see the values that were being entered for this testing? There was a document in this issue that was helpful in at least seeing the testing path: https://github.com/episphere/questionnaire/issues/67

Might help me see if there are unexpected variables affecting this grid.

**Comment by cunnaneaq** [comment]
I'm not sure if this helps, but when testing as a 44 year old, I noticed that the age ranges that aren't supposed to be showing are showing up as "50-**44**" and "60-**44**."  The "70 and older" is present too, but doesn't have a range.  (email: aqcunnane@aol.com, Connect ID: 1217779307)

![Screen Shot 2022-04-21 at 4 21 14 PM](https://user-images.githubusercontent.com/83971268/164551082-0649d4f4-17c6-4dc6-bf1b-ccad80675bcb.png)

**Comment by KELSEYDOWLING7** [comment]
That is similar to what I was seeing as well. For one scenario Age 45 (as put in enrollment) was confirmed, and I saw age 45-60 for the second to last, and "70 and older for the last". The second scenario I answered no to age verification and entered "55". The third to last question said "50-54", the second to last said 54-60, and the last said "70 and older".

**Comment by cusackjm** [comment]
issue still present in testing 4/29/22
account: 609-576-3460
Connect ID: 9393372061

**Comment by boyd-mj** [comment]
After additional review, we could not identify the issue or recreate the error. We are wondering if it has something to do with the way the valueordefault function is performing:

|grid?|id="GRID_SECSMLF2"|Thinking about your usual adult life, about how often were you around the tobacco smoke of others, for example in your home, work, or school?|[ 

[SECSMLF2A] Age 0 to {$e:min(17,valueOrDefault("AGE","age",100)) };
[SECSMLF2B,displayif=greaterThan(difference(isDefined(AGE,age),2),18)] Age 18 to {$e:min(24,valueOrDefault("AGE","age",100)) };
[SECSMLF2C,displayif=greaterThan(difference(isDefined(AGE,age),2),25)] Age 25 to age {$e:min(29,valueOrDefault("AGE","age",100)) };
[SECSMLF2D,displayif=greaterThan(difference(isDefined(AGE,age),2),30)] Age 30 to age {$e:min(39,valueOrDefault("AGE","age",100)) };
[SECSMLF2E,displayif=greaterThan(difference(isDefined(AGE,age),2),40)] Age 40 to age {$e:min(49,valueOrDefault("AGE","age",100)) };
[SECSMLF2F,displayif=greaterThan(difference(isDefined(AGE,age),2),50)] Age 50 to age {$e:min(59,valueOrDefault("AGE","age",100)) };
[SECSMLF2G,displayif=greaterThan(difference(isDefined(AGE,age),2),60)] Age 60 to age {$e:min(69,valueOrDefault("AGE","age",100)) };
[SECSMLF2H,displayif=greaterThanOrEqual(isDefined(AGE,age),70)] Age 70 and older;]|

(0:Every day, at least 2 hours each day)
(1:Every day, less than 2 hours each day)
(2:Most days of the week)
(3:A few days per week)
(4:One day per week)
(5: A few days per month)
(6: One day per month)
(7: few days per year)
(44: Never)|

@danielruss & @naiyume when age and AGE are both defined, the displayifs don't seem to function as expected. Could you please take a look? This is the only outstanding high priority issue for Module 3.

**Comment by danielruss** [comment]
![image](https://user-images.githubusercontent.com/3767675/167959237-3102392c-a412-4fbe-8664-d4ee64fddb3c.png)

**Comment by danielruss** [comment]
![image](https://user-images.githubusercontent.com/3767675/167959640-e6331032-31e9-48be-8591-87b52e4b8141.png)

QUEST is working exactly as expected when you give it both age and AGE.
From the markdown `{$e:min(17,valueOrDefault("AGE","age",100)) }`. <- valueOrDefault picks AGE, if AGE doesnt exist, it choose age, if that doesn't exist  then return 100.

**Comment by boyd-mj** [comment]
This issue is being addressed here: https://github.com/episphere/quest/issues/403

**Comment by cunnaneaq** [comment]
Looks good to me in testing 5/23 - @cusackjm @KELSEYDOWLING7 can you confirm before closing?

**Comment by cusackjm** [comment]
confirmed testing 5/23/22

**Comment by woodruffr** [comment]
Julie,

Has the spacing issue in Quest Github 403 been resolved? Is the "Loos good" just refer to the age ranges themselves or the age ranges and spacing of the age ranges?

Thanks,
Rose

**Comment by cusackjm** [comment]
the spacing issue looked resolved to me and aileen

**Comment by KELSEYDOWLING7** [comment]
Looks good for me as well
