### ISSUE TITLE
Quest ID SEX and Variable Name SrvBio_SEX_v1r0 Have Same Question Text

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#72]
Both Quest ID SEX (line 1039 in DD M1 and SrvBio_SEX_v1r0 (line 6086 in DD Biospecimens) share the exact same text: "What was your biological sex assigned at birth?" Although the Questionnaire could keep both of these, the only other time we had this issue was with AGE (DD line 814 M1). Age was asked in a questionnaire before Module 1. That was handled by having the original age they presented piped in to AGECORE (line 812 M1) and asking them to confirm it. If they say no, they get AGE (DD line 814) "How old are you today?"

![image](https://user-images.githubusercontent.com/81166095/164463904-7ed6d923-f910-448f-96c6-4b0fea0c0ba1.png)

Again, we could handle the transformer collision by simply adding anything to the text in the DD, but I think this is more of a content decision.

**Comment by cusackjm** [comment]
We would like extra text added in the DD. (we can't do the piping since it is possible that someone could complete the biospecimens before doing the baseline modules)
