### ISSUE TITLE
[HOMEADD3] Skipped Incorrectly

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#73]
Account Email: irinainstitute@gmail.com
Connect ID: 1654043404

Please see the cells in yellow for the situations in which [HOMEADD3] was skipped when I should have seen it

![Screen Shot 2022-04-21 at 11 08 15 AM](https://user-images.githubusercontent.com/83971268/164488653-a3cc64d9-c693-4e12-8240-659dbc7adf25.png)

Instructions for [HOMEADD3] from specs document:

![Screen Shot 2022-04-21 at 11 09 25 AM](https://user-images.githubusercontent.com/83971268/164489002-d5834afa-9065-4414-9ad1-7820a95d5ded.png)

**Comment by cusackjm** [comment]
issue still present in testing 4/29/22
account: 609-576-3460
Connect ID: 9393372061

**Comment by joshid-ims** [comment]
We need this logic to correct this HOMEADD3 being skipped:

displayif=(noneExist("STNUM","FULLST") and someExist("CITY_FOLLOWUP","ST_FOLLOWUP","ZIP_FOLLOWUP","COUNTRY_FOLLOWUP","CITY","ST","ZIP"COUNTRY"))

Not working as is.

**Comment by danielruss** [comment]
When I run it I see HOMEADD3_1 as expected. However i dont see HOMEADD3_3.  This is because the logic that @joshid-ims  uses in only on HOMEADD3_1.

Notice you see HOMEADD3_1 in the tree, but not HOMEADD3_3.  Of course there is no HOMEADD_2_2 or 3_2 because HOMEADD2_1 contains all the info.


```
INTRORH 
HOMEADD1_1 
HOMEADD2_1 
HOMEADD3_1 
HOMEADD4_1 
HOMEADDOTH1 
HOMEADD1_2 
HOMEADD4_2 
HOMEADDOTH2 
HOMEADD1_3
HOMEADD2_3 
HOMEADD4_3  <=== currentNode
 ============================= 
```

**Comment by boyd-mj** [comment]
@joshid-ims

**Comment by joshid-ims** [comment]
To be specific, I see in developers screen that someExist does not get evaluated. 

![image](https://user-images.githubusercontent.com/64986739/168140138-a3bac0ad-59b0-47de-89ba-3b4df900d173.png)

In this code:

[HOMEADD3_1?,displayif=noneExist("STNUM","FULLST") and someExist("CITY_FOLLOWUP","ST_FOLLOWUP","ZIP_FOLLOWUP","COUNTRY_FOLLOWUP","CITY","ST","ZIP","COUNTRY")] Please provide the cross streets of the intersection closest to this address:

**Comment by danielruss** [comment]
@joshid-ims  This is a problem that has been popping up often.  I am going in the middle of fixing it, but we may need to talk the team the runs converts the question id to concept ids.  This may take a while.

**Comment by danielruss** [comment]
I don't think it should.  The problem I fixed related to quotes and space.
(this is made up, it may not actually work) `|displayif=valueIsOneOf("name", "Daniel", "Dan") | Oh, it's you Daniel |` 

When this is rendered into html the quotes would end the html attribute.
`<span `**displayif='valueIsOneOf('**`  name","Daniel,Dan)>Oh, it's you Daniel`

I change the style to emphasize the displayif attribute.  There was also an issue with spaces.  That was a little more complicated, but it was causing the noneExist() or someExist() to be chopped off at the space.

Both of these problems have be addressed.

**Comment by joshid-ims** [comment]
@FrogGirl1123 I will still need to make markup changes in Module 4 in many other places similar to HOMEADD3_1.

**Comment by cusackjm** [comment]
@joshid-ims was this in the latest delivery/is this ready for testing?

**Comment by joshid-ims** [comment]
@cusackjm yes.
