### ISSUE TITLE
Incorrect answer choice (5) for [DRINKSWTR2C/D/E]

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#78]
Currently they all say:
"I drink tap water in coffee but don't know how often"

The last answer choice should match the question.  

[DRINKSWTR2C]:
"I drink tap water in hot tea but don't know how often"

![Screen Shot 2022-04-22 at 11 59 22 AM](https://user-images.githubusercontent.com/83971268/164751534-f443475b-f47a-4f90-a17f-a8cdfaf4d5d5.png)

[DRINKSWTR2D]:
"I drink tap water in iced tea but don't know how often"

![Screen Shot 2022-04-22 at 11 59 53 AM](https://user-images.githubusercontent.com/83971268/164751622-e1434351-509b-4ec5-a441-536c8ecea6b1.png)

[DRINKSWTR2E]:
"I drink tap water in other beverages or soup but don't know how often"

![Screen Shot 2022-04-22 at 12 00 08 PM](https://user-images.githubusercontent.com/83971268/164751665-0a8706f9-2aed-48fa-a95d-198d8591d4a8.png)

**Comment by boyd-mj** [comment]
This issue has been fixed and will be included in the next delivery

**Comment by cunnaneaq** [comment]
Issue fixed in 5/25 testing for all answer choices: hot tea, iced tea, and other beverages (example below)

<img width="587" alt="Screen Shot 2022-05-25 at 3 15 39 PM" src="https://user-images.githubusercontent.com/83971268/170350138-acc9f993-f26d-46c1-9756-447f7dd70ab8.png">
