### ISSUE TITLE
Switching order of PREWORKRES and PREWORK

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#79]
For Module 4, we would like to switch the order of PREWORK and PREWORKRES so that PREWORK is asked first.

Participants who have never had a job _for pay_ are displayed "work commutes in the past" (the PREWORK section) because they may have had a "job" that is not for pay, such as volunteer work. Given that potential scenario, people that have never worked for pay still need to see that section, but we think it would make most sense if such participants see PREWORK first, so that if they are the individuals that never worked at all, they don't see a question about an occupation (which is what PREWORKRES does).

I will switch the order in the qx so that it is (#R65) PREWORK and then (#R66) PREWORKRES, and update the skip logic in previous sections so that the skip logic is based on PREWORK, and not PREWORKRES anymore. 

Once the updates have been made I will notify you in a comment below.

**Comment by cusackjm** [comment]
Updates to qx document made using tracked changes

**Comment by joshid-ims** [comment]
Ok, Thanks!

**Comment by joshid-ims** [comment]
This is done.
