### ISSUE TITLE
No & DK for Select all that apply in Biospecimen Survey

### ISSUE THREAD

**Issue by huip-ims** [episphere/questionnaire#80]
@cusackjm @boyd-mj @guinevere83  Hi Julie - For PERMTTHLOST and DENTURES, can you please confirm if selecting "No" or "Don't Know" should clear all other answers?

**Comment by cusackjm** [comment]
@huip-ims yes, selecting "no" or "don't know" should clear all other answers

**Comment by huip-ims** [comment]
Markup has been updated and sent for internal testing.
