### ISSUE TITLE
Biospecimen Survey: Should COV3 be required?

### ISSUE THREAD

**Issue by huip-ims** [episphere/questionnaire#81]
@cusackjm @boyd-mj Hi Julie - During testing, we're finding that when no month/year are provided for COV3 (i.e., 1st/2nd/3rd/etc. time you had COVID-19), this causes display and logic issues in later follow-up questions. For example, COVSUMMARY and COV21 involve piped dates. Should COV3 be required so we have dates to fill in?

**Comment by huip-ims** [comment]
@cusackjm @boyd-mj @woodruffr Julie - I'll proceed with making COV3 required in the markup. Please make any necessary changes in the Word doc and/or DD.

**Comment by cusackjm** [comment]
@huip-ims @boyd-mj Updates have been made to the DD and Question Types Doc

**Comment by cusackjm** [comment]
no worries, i will accept the tracked changes
