### ISSUE TITLE
Biospecimen Survey: Missing symptoms for COV19C6A & COV23B8A

### ISSUE THREAD

**Issue by huip-ims** [episphere/questionnaire#82]
@cusackjm @boyd-mj Hi Julie - For COV19C6A & COV23B8A, if a participant answers 'Yes' but doesn't provide any symptoms in the text box, we can't pipe the response into the follow-up questions. This results in an incomplete question for COV19C6B & COV23B8B (i.e., "Are you still experiencing ?"). When the text box is left as null, should we phrase the follow-up question as "Are you still experiencing _**these other symptoms**_"? And, we'll replace "these other symptoms" with piped symptoms if the text box is filled in. Or, let us know how you would like to handle a 'Yes' response with a null text box.

**Comment by cusackjm** [comment]
@huip-ims I like this suggestion: 
When the text box is left as null, should we phrase the follow-up question as "Are you still experiencing these other symptoms"? And, we'll replace "these other symptoms" with piped symptoms if the text box is filled in.

Unless it is possible to make it a requirement to enter text in the text box (i.e., making the text box required if "yes" is selected), without making the question type required?

**Comment by huip-ims** [comment]
@cusackjm @boyd-mj Julie - We cannot make the text box within a response required but leave the question itself optional. We can make a content change by adding a new question to check if 'Yes' was selected with text box left null, and if so, require the participant to enter symptoms into a new text box. Or, use my original suggestion to phrase the question with added generic text if the text box was left null, otherwise, pipe in the symptoms if the text box was filled in. Let me know which of the 2 options you prefer.

**Comment by cusackjm** [comment]
@huip-ims @boyd-mj We can go with your original suggestion and phrase the question with added generic text if the text box was left null, otherwise, pipe in the symptoms if the text box was filled in. I will make updates to the Qx document and DD now.

**Comment by huip-ims** [comment]
@cusackjm @boyd-mj Julie - FYI these other symptoms are also piped into COV20A17 & COV24A14. Could you please also update the Qx document for these 2 questions? I've updated the markup for COV19C6B, COV23B8B, COV20A17, and COV24A14.

**Comment by cusackjm** [comment]
@huip-ims updates made in box qx documents and DD
