### ISSUE TITLE
SrvBlU_COV22_DAYS_v1r0 Variable Length

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#84]
Noticing that Biospecimens COV22 has a Variable Length of 2, it seems that the intent is to have the respondent use both the months and days text boxes. I just want to confirm that you don't expect your respondents to put a days response bigger than 99. For example, not fill out the months, but put 365 in the Days text box. Do you need to add min max or clarifying instructions?

**Comment by woodruffr** [comment]
There is no min max in the Questionnaire. The Mark-up currently has a max of 30. If the max is 30, the Variable Length of 2 works. If the max should be changed to 365, that would need to be changed in the mark-up and the DD would need a Variable Length of 3.

**Comment by cusackjm** [comment]
Ok I can update the DD to change the variable length to 3

**Comment by woodruffr** [comment]
If you want the Max to be 365 please add it to the Questionnaire as we will need to change it in the Mark-up.

**Comment by woodruffr** [comment]
The default is they are not mutually exclusive unless the question or the directions say they are to be. That note is sufficient for the coder.

**Comment by cusackjm** [comment]
Ok I will update the rest of the questionnaire documents

**Comment by huip-ims** [comment]
@woodruffr @cusackjm Rose and Julie - I've updated the markup and sent it along for internal testing.
