### ISSUE TITLE
Message when required question is not answered

### ISSUE THREAD

**Issue by joshid-ims** [episphere/questionnaire#85]
The default message that shows up when any required question is not answered by user is:

![image](https://user-images.githubusercontent.com/64986739/166977288-48cd22e5-2a41-47b3-bcf1-c0bdd568ce8c.png)

But the document for Menstrual Cycle Survey says:

[error message if someone clicks NEXT without entering a date]: Please use the calendar to select the date that your next menstrual period started. 
 
This is not something I can do or I do not know how to do it if it is possible to do. 
Is the default text or or can you please coordinate with Daniel and Brian on whether this feature is available?

**Comment by danielruss** [comment]
What module is this in?

**Comment by joshid-ims** [comment]
This is the new Menstrual Cycle Survey.

**Comment by boyd-mj** [comment]
Hi @danielruss any updates on this?

**Comment by danielruss** [comment]
looking

**Comment by danielruss** [comment]
So you want to change the message?   This might create ugly(ier) markup. 

[Q1!]  Question with default message

Would something like this work?
[Q2] |date|min=x max=y required| 
where a red box appears under the calendar and says "please fill out this field?"

**Comment by joshid-ims** [comment]
@huip-ims is that acceptable?

**Comment by joshid-ims** [comment]
Actually, this question is for @cusackjm. Is Daniel's suggestion acceptable? If so, do we need to update the Word document?

**Comment by cusackjm** [comment]
@joshid-ims just to clarify, this is the suggestion:

[SrvBlU_MENS2_v1r0] Please provide the first day that your next menstrual period started. This information helps researchers figure out where your body was in the menstrual cycle on the day you donated samples. If you do not remember the exact day, please make your best guess.

and on the next screen is:
"<Calendar to indicate date __/___/___>"
and this is required?

**Comment by joshid-ims** [comment]
@danielruss is that what you meant?

**Comment by danielruss** [comment]
![image](https://user-images.githubusercontent.com/3767675/167722989-a8642d82-5449-4796-8a88-fc05f4954635.png)

**Comment by danielruss** [comment]
If this is ok, Just want to let you know you can use.  Fix not pushed yet.  Waiting to hear if this is ok.

```
|date| required min="5/9/2022" max="5/10/2022"|
```

**Comment by cusackjm** [comment]
@danielruss yes that option looks good

**Comment by danielruss** [comment]
Pushed.  Please Test.

**Comment by boyd-mj** [comment]
@danielruss thanks! Just a heads up that since this is for the menstrual cycle we likely won't test for a bit given other priorities. We will make sure to update/close the issue once we do.

**Comment by joshid-ims** [comment]
The date widget is allowing invalid dates. 

![image](https://user-images.githubusercontent.com/64986739/168877255-f0dadcce-ca2c-4d04-9899-b723e1c19e42.png)

**Comment by naiyume** [comment]
@joshid-ims I have opened a new issue for this
https://github.com/episphere/questionnaire/issues/107
