### ISSUE TITLE
Spacing Between Paragraphs and responses

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#86]
*aesthetic issue to be addressed later on

Need larger space between first 2 paragraphs - should be same size as the space between paragraph 2 and 3 
![image](https://user-images.githubusercontent.com/85582895/167177340-ef4d46f6-725c-4f1e-9e22-cbf5b0c99c79.png)

Qx document for reference:
![image](https://user-images.githubusercontent.com/85582895/167177416-920a1127-7688-4bc3-b267-8a100a36dbbd.png)

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/167435342-7bcafe0b-3613-4067-bdba-8d524baeded2.png)

**Comment by cunnaneaq** [comment]
[PREGSUMMARY] spacing off when number of infants, method of delivery, and breastfeeding questions are not shown to the participant

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/83971268/167901815-37e47cfb-1372-4546-a64c-17a7c99f755f.png)

**Comment by naiyume** [comment]
@danielruss Didn't we add a basic fix for this?
https://github.com/episphere/quest/commit/899046a45ac017c0f6aff7b8a0ff7ae5da26a8e0
Still might need to recursively remove brs after the display:none questions.

**Comment by danielruss** [comment]
I thought we did.  Can you take a look at this?

**Comment by cunnaneaq** [comment]
"Urinary and Reproductive System" section looks great!

![Screen Shot 2022-06-09 at 10 58 46 AM](https://user-images.githubusercontent.com/83971268/172878511-8f27cfb4-4696-44ff-b80e-1e19e97d8d7e.png)

**Comment by cusackjm** [comment]
@naiyume what is the status on this
