### ISSUE TITLE
remove display logic for HRMED2= 1, so that all participants see this response

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#89]

**Comment by joshid-ims** [comment]
@cusackjm I do not see these changes in the Word document on Box.

**Comment by cusackjm** [comment]
@joshid-ims I had power outage problems and it must've not saved! Will make the updates now

**Comment by joshid-ims** [comment]
Thanks!

**Comment by cusackjm** [comment]
change was made

**Comment by joshid-ims** [comment]
Thanks

**Comment by boyd-mj** [comment]
Delivered

**Comment by cusackjm** [comment]
want to reopen for retest to confirm fix
