### ISSUE TITLE
Able to enter age of Dx that is greater than family member's age

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#90]
Ex) said dad died at 20, but can say he was diagnosed with cancer at 31

Age range check does not work, but the year range check does work

**Comment by cusackjm** [comment]
markup issue. Max should be AGE

**Comment by FrogGirl1123** [comment]
@danielruss I seem to recall you were working on this, but there was a syntax issue.

**Comment by danielruss** [comment]
You would need to calculate age at death.  What if dad is not dead?

**Comment by danielruss** [comment]
@FrogGirl1123   You are pushing a lot of QA on the question.  Can you assure that quest knows the age?  You would need to specify  ageCancer < age and ageCancer< ageDeath

**Comment by cusackjm** [comment]
@danielruss the participant answers either DADAGE or DADDEATH

**Comment by danielruss** [comment]
The markdown for DADCANCE3e (as an example) has `|__|__|__|xor=DADCANC3E id=DADCANC3E_AGE min=0 max=125`.   This should be changed to  `|__|__|__|xor=DADCANC3E id=DADCANC3E_AGE min=0 max=valueOrDefault("DAD_AGE","DADDEATH_NUM",125)| `. 

There is a small bug that pops up when the user goes forwards and backwards (If you go back and change the AGE/DEATHAGE, the validation doesn't change).   I am looking into that but this is in IMS' hands now.

**Comment by danielruss** [comment]
Here is a SSCE

```
[DAD?] Is your biological father still living?
(0) No -> DADDEATH
(1) Yes -> DADAGE
(77) Don’t know -> DADCANC
< #NR -> DADCANC >

[DADAGE?] How old is your father today?
|__|__|__|id=DAD_AGE minval=max(isDefined(AGE,age),5) max=125| Father’s age
[77*] Don’t know
< -> DADCANC >

[DADDEATH?] At what age did your father die?
|__|__|__|id=DADDEATH_NUM min=5 max=125| Father’s age
[77*] Don’t know


[DADCANC] How old was your father when they were <b>first</b> told by a doctor or other health professional that they have or had <b>colon/rectal cancer</b>?
|__|__|__|xor=DADCANC3E id=DADCANC3E_AGE min=0 max=valueOrDefault("DAD_AGE","DADDEATH_NUM",125)| Age at diagnosis

[END] Thank you 
Dad age: {$DAD_AGE}
Dad death: {$DADDEATH_NUM}
Dad cancer: {$DADCANC3E_AGE}

```

**Comment by boyd-mj** [comment]
@FrogGirl1123 the changes to the age at diagnosis code have been made (we're currently testing the changes). Please let us know if we can consider this issue complete barring any testing issues, or whether you are still investigating options for the year of diagnosis fields. Thanks!

**Comment by boyd-mj** [comment]
Delivered

**Comment by cusackjm** [comment]
want to retest to confirm fix

**Comment by KELSEYDOWLING7** [comment]
Error still presenting in 5/23 testing for Connect ID 4164883179. Was able to enter both age and year out of range for mom's cancer diagnosis (marked not living, death at 50, year of diagnosis 2022 and age at diagnosis of 57, both worked)

**Comment by cusackjm** [comment]
confirmed fix in 5/26 testing
