### ISSUE TITLE
Heading not on same page as the intro text

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#91]
MED "Medications" heading should be on same page as MED1 grid text

![image](https://user-images.githubusercontent.com/85582895/167706838-d43902dc-e02b-48b1-a46d-b02fdf005a4c.png)

**Comment by cunnaneaq** [comment]
Issue still present in 5/20 dev testing

**Comment by cusackjm** [comment]
@cunnaneaq this hasn't been fixed yet and is low priority

**Comment by joshid-ims** [comment]
For this to happen, we will need to remove ID [SRVBLU_MED_V1R0] from the code. Is that ok?

**Comment by cusackjm** [comment]
@FrogGirl1123 is removing ID [SRVBLU_MED_V1R0] ok to do?

**Comment by cusackjm** [comment]
"MARIJUANA" [SECTION2] on different page from [INTROMAR]

**Comment by FrogGirl1123** [comment]
@cusackjm @boyd-mj Yes, removing ID [SRVBLU_MED_V1R0]  is OK, as well as any other markup/content edits needed to resolve the heading issues

**Comment by boyd-mj** [comment]
This issue has been fixed and will be included in the next delivery

**Comment by cusackjm** [comment]
@boyd-mj was this also fixed in module 3? for Marijuana and Alcohol

**Comment by cunnaneaq** [comment]
Fixed for med in Biospec Questionnaire in 7/11 stage testing

![Screen Shot 2022-07-11 at 1 24 40 PM](https://user-images.githubusercontent.com/83971268/178322218-fc1b6b2f-845b-49f6-9c55-58a7059868b2.png)

**Comment by cusackjm** [comment]
fixed in testing on 7/25
