### ISSUE TITLE
incorrect skip pattern for follow-up questions from HYGIENE

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#93]
selected HYGIENE= 0 (BRUSH1),1 (FLOSS1), 2 (WTRPICK1) and correctly saw BRUSH2, FLOSS2, WTRPICK2, but I still saw TONGUE2, WHITE2, and MWUSE, which i should not have seen because i didnt select 3 (TONGUE1), 4 (WHITE1) or 5 (MW1) in HYGIENE

**Comment by boyd-mj** [comment]
This issue has been fixed and will be included in the next delivery

**Comment by cunnaneaq** [comment]
Selected HYGIENE = 0(BRUSH1), 1(FLOSS1), AND 3(TONGUE1) and only saw BRUSH2, FLOSS2, AND TONGUE2.  Looks good, but will leave open until we're done with testing to try other responses.

**Comment by cusackjm** [comment]
testing 5/20 confirmed fix
