### ISSUE TITLE
Need to base MIN range check for subsequent COV27 responses based off previous COV27 responses

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#95]
able to report a date at the 2nd COV27 (2nd covid shot) that is before the date of the 1st covid shot

**Comment by joshid-ims** [comment]
<loop max=25>

[SRVBLU_COV27_V1R0?,displayif=greaterThanOrEqual(SRVBLU_COV26_V1R0,#loop)] When did you get vaccinated with your {##} shot? 

Month |__|__|id=SRVBLU_COV27_MONTH_V1R0 min=1 max=12|
Year |__|__|__|__|id=SRVBLU_COV27_YEAR_V1R0 min=2020 max=#currentYear|

These variables are inside a loop. So I do not know how to use month/year entered in the previous iteration for min/max values, if at all it is possible inside the loop. 

Also, months cannot be compared on their own as the years could be different for two shots. 

This will be a question for Daniel. Could not tag him here. @cusackjm will you be able to talk with Daniel about possibility of this?

**Comment by cusackjm** [comment]
@danielruss is this possible?

**Comment by danielruss** [comment]
yes,

```
|Date|min=date max=date|
```

**Comment by danielruss** [comment]
I think so, let me check.

**Comment by danielruss** [comment]
Sorry,  This is not currently a feature.  However, it seems like a really good idea.  I'll look into fixing it with @naiyume.

**Comment by danielruss** [comment]
@joshid-ims  @cusackjm  I wrote a function dateCompare that looks like this:

dateCompare(month1,year1,month2,year2) 

This will return -1 if the month1/year1 is less than month2/year2, +1  greater than if month2/year2, 0 if equal.

does this address your needs for this feature?

dateCompare(_value("SRVBLU_COV3_MONTH_V1R0_1\"),_value("SRVBLU_COV3_YEAR_V1R0_1"),_value("SRVBLU_COV3_MONTH_V1R0_1"),_value("SRVBLU_COV3_YEAR_V1R0_1"))

**Comment by joshid-ims** [comment]
@huip-ims Are you looking into this?

**Comment by huip-ims** [comment]
@cusackjm Julie - This COVID-19 vaccine loop allows up to 25 vaccination dates (Month & Year). Did you want this feature to compare the Month/Year of the current iteration to the Months & Years of all previous iteration responses? I think Daniel's feature currently can only compare 2 dates.

@danielruss Daniel - The comparison of dates needs to be done while actively within the loop. Do we have access to the underscore Month/Year variables ( _1, _2, ,,,. _25) while within the loop?

**Comment by danielruss** [comment]
@huip-ims Peter,  If you are within the loop, the names get mangled by default.  Not sure that is a good thing in this case, if you want the value from the last iteration.  Comparing dates is more complicated than I first thought because the validation requires BOTH month/date field.  The date picker was initially disallowed for sec. 508 disability reasons, I'm not sure this is an issue anymore.  Can we change to a month/year picker (or date picker on firefox?)

**Comment by huip-ims** [comment]
@cusackjm Julie - Per Daniel, he indicated we may need to try something different to compare the dates between each iteration while within the loop. Could you look at Daniel's suggestion and respond whether or not it's feasible?

**Comment by cusackjm** [comment]
@danielruss @huip-ims Yes, that response type works for us

**Comment by boyd-mj** [comment]
@danielruss are you working on updating to a month/year picker? Pete will be out of the office through the end of next week so please assign back to me and @joshid-ims when it's ready for testing.

**Comment by danielruss** [comment]
@boyd-mj  @cusackjm   the only problem with a month picker is that it does not work in firefox.  Can we use a date picker instead?

**Comment by cusackjm** [comment]
@danielruss asking neal what he thinks. Only concern with the date picker is participant recall, given that some sites have already had difficulty recalling the month and don't readily carry their vax card or a picture of the vax card on hand

**Comment by danielruss** [comment]
@cusackjm  and @boyd-mj  I just pushed the  month picker to quest.  It is only in dev.  
Format...  `|month| id=myid min=2015-01 max=2025-12 value=2013-01|`

`|month|min="2020-01" value="#currentYear-#currentMonth"|` also should work (there may be some errors if the month is one digit.  I'll fix that.

**Comment by danielruss** [comment]
forgot to mention.  I had to make changes to the quest to make it work with firefox, which lacks an input type="month".

**Comment by cusackjm** [comment]
@danielruss is the month picker the calendar, but just showing months and not days? 

If it is just months and year calendar that is ok, but if it requires the participant pick a day, we would like to just proceed as is (no range check).

**Comment by danielruss** [comment]
@cusackjm There is a month picker and a date picker.  I was talking about a month picker.  It picks month and year.  If you want the day, then you need the date picker, which is month-day-year.

**Comment by cusackjm** [comment]
@danielruss month picker is great. I will look at it in dev

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/186439495-5d16ed2a-5d36-4742-aaa9-d01c3afc5d84.png)
 this is in dev

**Comment by cusackjm** [comment]
@danielruss what is the status on this

**Comment by danielruss** [comment]
```
[I] Hi
[Q1] When did you get your 1st shot
|month|id=CVD_SHOT min=2020-2 max=#currentYear-#currentMonth|
[END] All done.
```

How does this look?

<img width="761" alt="image" src="https://user-images.githubusercontent.com/3767675/187951467-e900c13e-1b45-4024-92e6-56053e611f20.png">

<img width="788" alt="image" src="https://user-images.githubusercontent.com/3767675/187951331-55a7dc07-bc25-4bee-b118-b8675a645523.png">

**Comment by danielruss** [comment]
Forgot to mention that Firefox on computer is a problem child...  But I dealt with that..

<img width="721" alt="image" src="https://user-images.githubusercontent.com/3767675/187952096-0e7b6eaa-f033-4e3d-b562-021110502180.png">

<img width="717" alt="image" src="https://user-images.githubusercontent.com/3767675/187952565-b2bb38c0-1718-4499-9682-887e4ba540fc.png">


<img width="730" alt="image" src="https://user-images.githubusercontent.com/3767675/187952234-21de5333-8aaf-44b5-b8f4-044d4d3d593b.png">

<img width="716" alt="image" src="https://user-images.githubusercontent.com/3767675/187952351-aafef94e-9864-4930-aee9-46f7eae0a465.png">


if you enter 1-2022, it will auto correct to 2022-1.

**Comment by danielruss** [comment]
does this work?

**Comment by cusackjm** [comment]
@danielruss yes

**Comment by joshid-ims** [comment]
@danielruss so we will not be comparing last shot's date with the date user enters here? Just with current date?

**Comment by danielruss** [comment]
@joshid-ims   you can now do this:
```
[Q1] When did you get your 1st shot
|month|id=CVD_SHOT_1 min=2020-2 max=#currentYear-#currentMonth|
[Q2] When did you get your 2nd shot?
|month|id=CVD_SHOT_2 min=valueOrDefault("CVD_SHOT_1","2020-2") max=#currentYear-#currentMonth|
[END] All done.
```
What you cannot do is `valueOrDefault("CVD_SHOT_1","2020-2")+6)` to get 6 months after.
Why?  because I have to recognize that "2020-2" is a  month-year.  Right now it is text.  I don't have a good solution yet.

**Comment by joshid-ims** [comment]
The question is in the loop. So not sure how this can be done. 

<loop max=25>

[SRVBLU_COV27_V1R0?,displayif=greaterThanOrEqual(SRVBLU_COV26_V1R0,#loop)] When did you get vaccinated with your {##} shot? 

Month |__|__|id=SRVBLU_COV27_MONTH_V1R0 min=1 max=12|
Year |__|__|__|__|id=SRVBLU_COV27_YEAR_V1R0 min=2020 max=#currentYear|
// Month and Year drop down lists are not currently supported

**Comment by danielruss** [comment]
This is not as easy as it sounds.  How do you handle the first time the question is asked?

Something like this?
min=prev(Id1,Id2,Value)

From: joshid-ims ***@***.***>
Reply-To: episphere/questionnaire ***@***.***>
Date: Friday, September 2, 2022 at 3:54 PM
To: episphere/questionnaire ***@***.***>
Cc: "Russ, Daniel (NIH/NCI) [E]" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [episphere/questionnaire] Need to base MIN range check for subsequent COV27 responses based off previous COV27 responses (Issue #95)


The question is in the loop. So not sure how this can be done.

[SRVBLU_COV27_V1R0?,displayif=greaterThanOrEqual(SRVBLU_COV26_V1R0,#loop)] When did you get vaccinated with your {##} shot?

Month |||id=SRVBLU_COV27_MONTH_V1R0 min=1 max=12|
Year |||||id=SRVBLU_COV27_YEAR_V1R0 min=2020 max=#currentYear|
// Month and Year drop down lists are not currently supported

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fepisphere%2Fquestionnaire%2Fissues%2F95%23issuecomment-1235846176&data=05%7C01%7Cdruss%40mail.nih.gov%7C5ed8d0cb061149e5855d08da8d1cf7e8%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637977452799374288%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NQ8p9%2BpirWUM4vH9G%2FLT%2FfucxphECSSX5FYWGNRAnog%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA4X2624JBJ4PZOUPYMPONDV4JLAZANCNFSM5VVF2SKQ&data=05%7C01%7Cdruss%40mail.nih.gov%7C5ed8d0cb061149e5855d08da8d1cf7e8%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637977452799374288%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7F9M8oWZtStT2oS0LnlmCnTu%2FUGQWcVn0P5qTRMEahg%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by joshid-ims** [comment]
In prev function, there can be only 2 arguments or many?

**Comment by danielruss** [comment]
There is no prev function yet.  I am

**Comment by cusackjm** [comment]
we would just like to compared the date with the date that was listed previously. If there are more than 2 vaccinations, comparing the entered date with the date entered in the previous question will still ensure people do not list dates out of order. Is that possible?

**Comment by danielruss** [comment]
Right now, what I have is a month picker so you dont need to worry about handling month/year as two variables.  you can set the min/max.  The only issue is handling the "previous value of a loop".  

I'm looking into it now.  The markdown syntax is difficult because you cant have  |__|id=shotdate min=shotdate#prev| (what happens on the first iteration).   you may have to have min=valueOrDefault(shotdate#prev,"2022-03")

**Comment by danielruss** [comment]
@joshid-ims @cusackjm   ok, sorry it took so long to get back.  This was a difficult bug fix/feature request.

I made some MAJOR changes to quest looping.  I have not yet added them to episphere/quest, but [danielruss/quest](https://danielruss.github.io/quest)  has my changes.  You should be able to use the month picker in the loop. The code below was pulled out of the module and contains updates to use the month picker.  IF you want the date to be 3 months after the last shot, we can now handle it, but it is a little more difficult.
  
```
[SRVBLU_COV26_V1R0?] How many shots of the COVID-19 vaccine did you get? Please include your initial vaccination and any booster shots.

|__|__| min=1 max=10| Shot(s)
// Numeric drop down list is not currently supported

<loop max=25>

[SRVBLU_COV27_V1R0?,displayif=greaterThanOrEqual(SRVBLU_COV26_V1R0,#loop)] When did you get vaccinated with your {##} shot? 

|month|id=SRVBLU_COV27_V1R0_MY min=valueOrDefault("SRVBLU_COV27_V1R0_MY#prev","2020-03") max=#currentYear-#currentMonth|

[SRVBLU_COV28_V1R0?,displayif=greaterThanOrEqual(SRVBLU_COV26_V1R0,#loop)] Which COVID-19 vaccine shot did you get?

(0) Moderna
(1) Pfizer
(2) Johnson & Johnson
(3) AstraZeneca
(55) Other |__|id=SRVBLU_COV28DESC_V1R0|
(77) Don't know

[SRVBLU_COV29_V1R0,displayif=greaterThanOrEqual(SRVBLU_COV26_V1R0,#loop)] Here's a summary of the information you shared about your COVID-19 vaccinations. If any of the information is incorrect, please select the "Back" button to update your responses. If all the information is correct, please select the "Next" button to move forward.

Vaccination number: #loop
Vaccination date: {$SRVBLU_COV27_V1R0}
COVID-19 vaccine shot: |displayif=equals(SRVBLU_COV28_V1R0,0)| Moderna||displayif=equals(SRVBLU_COV28_V1R0,1)| Pfizer||displayif=equals(SRVBLU_COV28_V1R0,2)| Johnson & Johnson||displayif=equals(SRVBLU_COV28_V1R0,3)| AstraZeneca||displayif=equals(SRVBLU_COV28_V1R0,55)| Other ( {$SRVBLU_COV28DESC_V1R0} )||displayif=equals(SRVBLU_COV28_V1R0,77)| Don't know|

</loop>

[END] The end.
```  

BTW: this may fix episphere/quest#411

**Comment by danielruss** [comment]
If I don't hear from anyone by tomorrow I'll assume everyone is happy an check the version into episphere/quest.

**Comment by joshid-ims** [comment]
We can test this on our end if you want @cusackjm @danielruss where can it be tested?

**Comment by cusackjm** [comment]
@joshid-ims @danielruss I can test this in dev

**Comment by joshid-ims** [comment]
Thanks!

**Comment by danielruss** [comment]
[https://danielruss.github.io/quest](https://danielruss.github.io/quest)

**Comment by cusackjm** [comment]
@danielruss will this affect other loops in the modules too

**Comment by danielruss** [comment]
It only adds functionality.  Nothing *should* break.  ¯\_(ツ)_/¯ You might want to double check.

**Comment by cusackjm** [comment]
@danielruss i dont see any changes in dev

**Comment by danielruss** [comment]
Just pushed to episphere.  I wanted to wait and test against my repo, but you are working of epishere. try now

**Comment by cusackjm** [comment]
@danielruss its still not in there

**Comment by danielruss** [comment]
How are you testing?  

If you are testing with the PWA, it won't be picked up.  We have not tagged it for deployment.

No questionnaire modules have been changed yet, so using the quest development tool (https://episphere.github.io/quest) they should not look different.  However, loops should not have been broken by my fix.  That is my concern.

**Comment by cusackjm** [comment]
@danielruss Ooo gotcha I was testing in the PWA in dev

**Comment by cusackjm** [comment]
@danielruss loops don't appear broken in testing in the quest dev tool. 

@joshid-ims do you have a status update on your testing

**Comment by danielruss** [comment]
@cusackjm  Thank you.  The loops are complex and easy to break.

**Comment by joshid-ims** [comment]
@cusackjm we did not test it as you said you were. Were we supposed to?

**Comment by cusackjm** [comment]
@joshid-ims I thought you were testing the date/month edit

**Comment by joshid-ims** [comment]
No, as Daniel said it was in dev instance.

**Comment by joshid-ims** [comment]
@cusackjm Ok, we tested quickly. Seems to work. Same month can be entered though. I guess that is ok.

**Comment by cusackjm** [comment]
@joshid-ims that is ok. Will this be ready for delivery soon?

**Comment by joshid-ims** [comment]
Yes, it can be delivered soon. @boyd-mj

**Comment by cusackjm** [comment]
The date range checks dont work. I entered
COV26= 3 (shots)
COV27_1= 2/2021
COV27_2= 1/2020
COV27_3= 1/2021

**Comment by joshid-ims** [comment]
@cusackjm as per Rose this needs changes to the Questionnaire - Research Appointment - on Box. You would have the correct variables there and it will need a data dictionary update. As the ID SRVBLU_COV27_V1R0_MY in COV27 is not getting converted.

**Comment by cusackjm** [comment]
@woodruffr what changes need to be made?

**Comment by woodruffr** [comment]
Hi Julie,

We rely on the Questionnaire to know what Variable Name to use. I just talked to Deepti who talked to Daniel. It seems that since this function is in a loop, the response needs a separate Variable Name/concept ID from the Question Variable Name/Concept ID. Deepti also said you were fine with calling it month. So, my recommendation would be to remove the COV_27_YEAR Variable Name and Leave the SrvBlU_COV27_MONTH_v1r0 as the response storage Variable Name/Concept ID. Obviously, we will need data dictionary updates and we will need to document the format and any data dictionary rules for the new function.

**Comment by joshid-ims** [comment]
Can we have ID that Daniel used? SRVBLU_COV27_V1R0_MY

**Comment by danielruss** [comment]
what am i fixing?

**Comment by joshid-ims** [comment]
Currently nothing as Rose and I spoke about using a separate ID for response.

**Comment by cusackjm** [comment]
@woodruffr variable name updates are denoted in tracked changes in the qx documents

**Comment by woodruffr** [comment]
Thanks, Julie. I'll look at the data dictionary updates and make recommendations.

**Comment by joshid-ims** [comment]
@cusackjm Our tester found this:

 if we put a date for COV27 in the first loop and then NR for COV27 in the 2nd loop, we can input a date before the first COV27's value in subsequent loops.

The default used in code is:

|month|id=SRVBlU_COV27_MY_V1R0 min=valueOrDefault("SRVBlU_COV27_MY_V1R0#prev","**2020-03**") max=#currentYear-#currentMonth|

Is this acceptable?

**Comment by cusackjm** [comment]
Neal and I think that's ok, as it will affect a very small number of people @joshid-ims

**Comment by woodruffr** [comment]
@danielruss COV27 isn't using the new MY Variable Name for storage. Can you confirm that the 2nd variable name is necessary for Quest to work with the function?

![image](https://user-images.githubusercontent.com/81166095/194385174-5c0203bb-b742-4014-8336-0bcebf5c7882.png)

**Comment by danielruss** [comment]
looking at the COV27 loop in the [privatequest repository](https://github.com/cyrjeant/privatequest).  I cut out the important part of the module

```
[SRVBLU_COV26_V1R0?] How many shots of the COVID-19 vaccine did you get? Please include your initial vaccination and any booster shots.

|__|__| min=1 max=10| Shot(s)
// Numeric drop down list is not currently supported


<loop max=25>

[SRVBLU_COV27_V1R0?,displayif=greaterThanOrEqual(SRVBLU_COV26_V1R0,#loop)] When did you get vaccinated with your {##} shot? 

|month|id=SRVBLU_COV27_MY_V1R0 min=valueOrDefault("SRVBLU_COV27_MY_V1R0#prev","2020-03") max=#currentYear-#currentMonth|

[SRVBLU_COV28_V1R0?,displayif=greaterThanOrEqual(SRVBLU_COV26_V1R0,#loop)] Which COVID-19 vaccine shot did you get?

(0) Moderna
(1) Pfizer
(2) Johnson & Johnson
(3) AstraZeneca
(55) Other |__|id=SRVBLU_COV28DESC_V1R0|
(77) Don't know

[SRVBLU_COV29_V1R0,displayif=greaterThanOrEqual(SRVBLU_COV26_V1R0,#loop)] Here's a summary of the information you shared about your COVID-19 vaccinations. If any of the information is incorrect, please select the "Back" button to update your responses. If all the information is correct, please select the "Next" button to move forward.

Vaccination number: #loop
Vaccination date: {$SRVBlU_COV27_MY_V1R0}
COVID-19 vaccine shot: |displayif=equals(SRVBLU_COV28_V1R0,0)| Moderna||displayif=equals(SRVBLU_COV28_V1R0,1)| Pfizer||displayif=equals(SRVBLU_COV28_V1R0,2)| Johnson & Johnson||displayif=equals(SRVBLU_COV28_V1R0,3)| AstraZeneca||displayif=equals(SRVBLU_COV28_V1R0,55)| Other ( {$SRVBLU_COV28DESC_V1R0} )||displayif=equals(SRVBLU_COV28_V1R0,77)| Don't know|

</loop>

[SRVMW_ORALHLTH_V1R0?] <b>Mouthwash Data Collection </b> 

```

It works with out a problem.  I will try with the version on stage.

**Comment by danielruss** [comment]
The [version in stage](https://github.com/cyrjeant/privatequest/blob/master/biospecimen.txt#L435-L458) does not use the month picker.

**Comment by boyd-mj** [comment]
Per our call today, @cusackjm is updating the DD. Once changes are confirmed, Gene will generate an updated JSON.

**Comment by Gbarra9** [comment]
> Per our call today, @cusackjm is updating the DD. Once changes are confirmed, Gene will generate an updated JSON.

@boyd-mj "SrvBlU_COV27_MY_v1r0" was recently added to the most recent JSON.

**Comment by cusackjm** [comment]
range checks work in 11/2 dev testing on a PC

Aileen is testing on a tablet to check calendar display on a smaller screen and will comment her test results

**Comment by cunnaneaq** [comment]
Range checks work on iPad testing 11/2 in dev.  The image below is of the date picker for the vaccine questions on an iPad

<img width="524" alt="Screen Shot 2022-11-02 at 3 18 15 PM" src="https://user-images.githubusercontent.com/83971268/199581487-8dad6563-9682-46ef-b1a1-889ba96b8e22.png">

**Comment by cusackjm** [comment]
(forgot to post this passed stage testing too)
