### ISSUE TITLE
Incorrect skip pattern following COV19A-C and COV19C6A= 0

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#96]
Selected 0 for all responses in COV19A, COV19B, COV19C grids and COV19C6A. Should have gone to 20A, which has DISPLAY directions that would route the participant to not see COV20A and go to COV25, but instead I was incorrectly routed to COV21 and COV22

**Comment by joshid-ims** [comment]
@cusackjm The display condition for 20A in the document is:

[DISPLAY GRID_SRVBLU_COV20A_V1R0 IF (SrvBlU_COV19A_v1r0=1, 2), (SrvBlU_COV19B_v1r0=1, 2), (SrvBlU_COV19C_v1r0=1, 2)   

ELSE, GO TO SrvBlU_COV25_v1r0] 

It is not to be displayed when the responses are 0. Do we need to change the document? Am I missing something?

**Comment by cusackjm** [comment]
@joshid-ims  No the document is right, just not sure if I was clear enough in it. For my test I did the following:

COV19A, COV19B, COV19C= 0

COV19C6A= 0 **--> GO TO COV20A**

COV20A's DISPLAY directions are "[DISPLAY GRID_SRVBLU_COV20A_V1R0 IF (SrvBlU_COV19A_v1r0=1, 2), (SrvBlU_COV19B_v1r0=1, 2), (SrvBlU_COV19C_v1r0=1, 2) ELSE, GO TO SrvBlU_COV25_v1r0]"

So I should've gone straight to COV25, but in the PWA I was taken to COV21 and COV22 before I was taken to COV25. This to me appears to be a skip logic issue

**Comment by joshid-ims** [comment]
Oh ok, I thought you said it should have gone to 20A. I will look into this. Thanks!

**Comment by boyd-mj** [comment]
@cusackjm this should have been fixed with the latest delivery. Could your team please retest? Thanks.
