### ISSUE TITLE
[COV27] - update wording of question

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#98]
Question states, "When were you vaccinated?" and text fills 1st/2nd/3rd shot in the loop based on response to COV26.  Altogether in the PWA it reads, "When were you vaccinated for your 1st shot?"  

Suggested edit - "When did you get vaccinated [with your 1st shot]?"  And subsequently, "...with your 2nd shot?" and "...with your 3rd shot?"

![Screen Shot 2022-05-11 at 10 42 53 AM](https://user-images.githubusercontent.com/83971268/167893596-8e25284d-f7d3-4c50-846c-4e9053e9b356.png)

**Comment by cusackjm** [comment]
waiting for Neal's opinion on the potential change

**Comment by cusackjm** [comment]
Edit made in the questionnaire documents and are denoted in tracked changes

**Comment by boyd-mj** [comment]
This issue has been fixed and will be included in the next delivery

**Comment by cunnaneaq** [comment]
Looks good!

![Screen Shot 2022-05-20 at 12 31 35 PM](https://user-images.githubusercontent.com/83971268/169572288-afafd14d-39f2-464d-8121-4774f4081ea2.png)
