### ISSUE TITLE
[COVSUMMARY]  ; placement for symptoms list

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#99]
[COV8] = 7,10,12,15

[COVSUMMARY] Symptoms: list begins with a colon when the first choice in [COV8] is not selected 

![Screen Shot 2022-05-10 at 5 09 38 PM](https://user-images.githubusercontent.com/83971268/167896998-4703613b-ad1f-4e1e-9cb1-2ea4b567323a.png)

**Comment by boyd-mj** [comment]
This issue has been fixed and will be included in the next delivery

**Comment by KELSEYDOWLING7** [comment]
Not seeing this issue in 6/8 testing

**Comment by cusackjm** [comment]
Unnecessary semi colon at the end of the symptoms list 
![image](https://user-images.githubusercontent.com/85582895/178329282-b9001c36-703c-457a-8e8d-a0f9ce90d186.png)

**Comment by boyd-mj** [comment]
Thanks Julie. @joshid-ims please create an issue for this so we can make this fix

**Comment by joshid-ims** [comment]
@danielruss Please take a look as it will always show either in the front or in the end.

**Comment by cusackjm** [comment]
@danielruss do you have a status update on this?

**Comment by danielruss** [comment]
not right now.  Will get on this.

**Comment by danielruss** [comment]
@joshid-ims @cusackjm   Ok, I think I can do this...

|displayList(ID1,VALUE1,ID2,VALUE2,...,sep=; )|

If ID1 exists print VALUE1
If ID1 and ID2 exist print VALUE1; VALUE2.

Is that ok?

**Comment by joshid-ims** [comment]
Yes, that should work.

**Comment by joshid-ims** [comment]
@danielruss the code using this displayList function does not work. 

[SRVBLU_COVSUMMARY_V1R0,displayif=greaterThanOrEqual(SRVBLU_COV2_V1R0,#loop)] Here is a summary of the information you shared about when you had COVID-19 for the {##} time. If any of the information is incorrect, please select the "Back" button to update your response. If all of the information is correct, please select the "Next" button to move forward.

Date: |displayif=exists("SRVBLU_COV3_YEAR_V1R0")|{$SRVBLU_COV3_MONTH_V1R0}/{$SRVBLU_COV3_YEAR_V1R0}|<br/>
Positive Test: |displayif=equals(SRVBLU_COV4_V1R0,1)| Yes||displayif=equals(SRVBLU_COV4_V1R0,0)| No|<br/>|displayif=equals(SRVBLU_COV4_V1R0,77)| Unsure| 
<br/>

Symptoms present:|displayif=equals(SRVBLU_COV6_V1R0,1)| Yes||displayif=equals(SRVBLU_COV6_V1R0,0)| No| <br/>

|displayif=doesNotEqual(SRVBLU_COV6_V1R0,0)|Symptoms: |
|displayList(valueEquals('SRVBLU_COV8_V1R0',0),"Fever",valueEquals('SRVBLU_COV8_V1R0',1),"Body chills (feeling cold, shivering)",valueEquals('SRVBLU_COV8_V1R0',2),"Body or muscle aches",valueEquals('SRVBLU_COV8_V1R0',3),"Weakness or fatigue (tiredness)",valueEquals('SRVBLU_COV8_V1R0',4),"Confusion",valueEquals('SRVBLU_COV8_V1R0',5),"Trouble sleeping",valueEquals('SRVBLU_COV8_V1R0',6),"New loss of taste or smell",valueEquals('SRVBLU_COV8_V1R0',7),"Stuffy nose (nasal congestion)",valueEquals('SRVBLU_COV8_V1R0',8),"Sore throat",valueEquals('SRVBLU_COV8_V1R0',9),"Cough",valueEquals('SRVBLU_COV8_V1R0',10),"Shortness of breath (trouble breathing)",valueEquals('SRVBLU_COV8_V1R0',11),"Chest tightness",valueEquals('SRVBLU_COV8_V1R0',12),"Stomach pain",valueEquals('SRVBLU_COV8_V1R0',13),"Diarrhea or watery stool (poop)",valueEquals('SRVBLU_COV8_V1R0',14),"Nausea (being sick to your stomach)",valueEquals('SRVBLU_COV8_V1R0',15),"Vomiting (throwing up)",valueEquals('SRVBLU_COV8_V1R0',16),"Rashes or other skin changes",valueEquals('SRVBLU_COV8_V1R0',17),"Conjunctivitis (pink eye)",valueEquals('SRVBLU_COV8_V1R0',55),"Other",sep="; ")|<br/>


|displayif=doesNotEqual(SRVBLU_COV6_V1R0,0)|Overnight Hospitalization: ||displayif=equals(SRVBLU_COV12_V1R0,1)| Yes||displayif=equals(SRVBLU_COV12_V1R0,0)| No||displayif=equals(SRVBLU_COV12_V1R0,77)| Unsure|<br/>

No error. After Symptoms: it just does not display anything. Is it an issue of double and single quotes around question IDs?

**Comment by danielruss** [comment]
<img width="795" alt="image" src="https://user-images.githubusercontent.com/3767675/191839924-dcf9bcb2-855c-4a7d-bcf5-a2a8a2739f61.png">

**Comment by danielruss** [comment]
using: https://episphere.github.io/quest 
cyrjeant blood_urine.txt

**Comment by joshid-ims** [comment]
@danielruss It is not blood_urine it is biospecimen survey. As you can see there is extra ; at the end.

**Comment by danielruss** [comment]
@joshid-ims  Clearly the writer of this module are trying to put my in an early grave. 

Overview of the issue:  The list you are checking against is a question with a combobox and an "other".  The results are stored like as an object { ID: [ values ] }.    Whenever you use an array (a combobox), you want to use valueIsOneOf not value equals.  In addition, the valueIsOneOf did not handle the combobox + other case appropriately.  I just fixed and pushed.

please change the code to:

```
|displayList(valueIsOneOf('SRVBLU_COV8_V1R0',0),"Fever",valueIsOneOf('SRVBLU_COV8_V1R0',1),"Body chills (feeling cold, shivering)",valueIsOneOf('SRVBLU_COV8_V1R0',2),"Body or muscle aches",valueIsOneOf('SRVBLU_COV8_V1R0',3),"Weakness or fatigue (tiredness)",valueIsOneOf('SRVBLU_COV8_V1R0',4),"Confusion",valueIsOneOf('SRVBLU_COV8_V1R0',5),"Trouble sleeping",valueEquals('SRVBLU_COV8_V1R0',6),"New loss of taste or smell",valueIsOneOf('SRVBLU_COV8_V1R0',7),"Stuffy nose (nasal congestion)",valueIsOneOf('SRVBLU_COV8_V1R0',8),"Sore throat",valueIsOneOf('SRVBLU_COV8_V1R0',9),"Cough",valueIsOneOf('SRVBLU_COV8_V1R0',10),"Shortness of breath (trouble breathing)",valueIsOneOf('SRVBLU_COV8_V1R0',11),"Chest tightness",valueIsOneOf('SRVBLU_COV8_V1R0',12),"Stomach pain",valueIsOneOf('SRVBLU_COV8_V1R0',13),"Diarrhea or watery stool (poop)",valueIsOneOf('SRVBLU_COV8_V1R0',14),"Nausea (being sick to your stomach)",valueIsOneOf('SRVBLU_COV8_V1R0',15),"Vomiting (throwing up)",valueIsOneOf('SRVBLU_COV8_V1R0',16),"Rashes or other skin changes",valueIsOneOf('SRVBLU_COV8_V1R0',17),"Conjunctivitis (pink eye)",valueIsOneOf('SRVBLU_COV8_V1R0',55),"Other",sep="; ")|<br/>
```

**Comment by danielruss** [comment]
![image](https://user-images.githubusercontent.com/3767675/192591835-47de59af-eeed-4a49-a2ee-b48b571b45e0.png)

**Comment by joshid-ims** [comment]
Thanks! Will make the change and test.

**Comment by cusackjm** [comment]
fixed in 9/30 stage testing
